### ISSUE TITLE
Update author details page (wf002) to match wireframes v3

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#100]
Just a case of changing the button to a checkbox and adding a text field.

<img width="911" alt="screenshot 2018-04-25 15 03 15" src="https://user-images.githubusercontent.com/115310/39251203-a0edc3b8-489a-11e8-909d-e1449c511a41.png">

<img width="978" alt="screenshot 2018-04-25 15 13 10" src="https://user-images.githubusercontent.com/115310/39251439-34afa800-489b-11e8-9cba-a611d0ee88d6.png">

**Comment by diversemix** [comment]
https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/38
