### ISSUE TITLE
Dashboard list items incorrectly sized between smallest and mid breakpoint

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1000]
🎖 1000th ticket! 🎖 

**Describe the bug**
Between 480px and 768px the dashboard list item component is displaying incorrectly. The vertical spacing between the status and last updated date is too large.

**To Reproduce**
1. Go to 'https://staging--xpub.elifesciences.org/'
2. Resize window to betwen 480px and 768px
3. Observe incorrectly sized dashboard list item

**Expected behavior**
The dashboard list item should behave in the same way between 480px and 768px as below 468px.

**Screenshots**

![screen shot 2018-11-07 at 14 18 38](https://user-images.githubusercontent.com/17023702/48137056-1b423e80-e299-11e8-8820-b398d1824788.png)

Designs:

<img width="360" alt="screen shot 2018-11-07 at 14 28 01" src="https://user-images.githubusercontent.com/17023702/48137171-5ba1bc80-e299-11e8-9da4-1eaa0705bdd7.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Firefox

**Comment by jsms90** [comment]
I don't believe we've ever had responsive designs for the dashboard (the list items or the rest). So I think this is new information:
> The dashboard list item should behave in the same way between 480px and 768px as below 468px.

Right now, the way the dashboard items look on tablet is basically a squished version of the desktop. Until now, I think we were assuming that "mobile" (in Zeplin) meant < 480px & "desktop" meant >= 480px

Should we be interpreting "mobile" in Zeplin to mean > 768px & "desktop" in Zeplin to mean >= 768px?
Does this apply to everything on the dashboard? Or just the `DashboardListItem` component?
