### ISSUE TITLE
Failing to handle expired sessions gracefully in app

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1002]
**Describe the bug**

When a users session has expired but they still have access to the apps `<AuthenticatedComponent>` wrapped route pages, the app behaves in an undesirable way displaying unfriendly graphql error messages when performing actions that run graphql queries / mutations.

**To Reproduce**
1. Signed in, go to the dashboard page.
2. Open another tab in your browser and go to the app in this new tab.
3. Sign out in the new tab using the profile menu found in right of the `AppBar`.
4. Go back to the first tab which should still be displaying the dashboard, select the Archived tab.
5. Select the submissions tab to return to the original view.

**Expected behavior**
TBD

We should probably be redirecting the user back to the sign in page if their session is expired whenever a query is ran that requires them to be logged in, possibly with some notification that they haven't lost any progress and they need to sign in again to continue.

**Screenshots**

<img width="428" alt="screenshot 2018-11-08 at 09 29 12" src="https://user-images.githubusercontent.com/22455561/48190924-cefc0a80-e33b-11e8-93ee-6dd0a9545f2e.png">

**Comment by diversemix** [comment]
I would expect the graphql query to return a HTTP status of something like 401 ... in this case we should redirect to `/login`

/cc @hdrury1 @chugginselifesciences
