### ISSUE TITLE
Populate staging with live people data

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1003]
@hdrury1 Has updated the live site with the necessary data for "People" (more specifically Editors)

We would like to migrate this data from the live site to `continuumtest` (staging) so we can use it to test the People Picker for xPub in staging.

linked to #958

**Comment by diversemix** [comment]
Because CI depends on the data in staging (`continuumtest`) then we have tests failing for #991 
This ticket needs to be completed before #991 

/cc @hdrury1

**Comment by giorgiosironi** [comment]
Yes, the other one will cover the automation.
