### ISSUE TITLE
Prevent user from suggesting and excluding the same editor (using inactive PersonPod)

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1011]
A user should not be able to suggest and exclude the same person using the people picker.

I would welcome @chugginselifesciences and @diversemix thoughts on this. The easiest way of implementing the behaviour may be to add validation to the excluded editor field(s) and flag to the user if they have duplicated their choice. 

A more elegant solution may be to make those pods inactive within the people picker itself, but I suspect this would be much more work from a technical point of view since we don't have an 'inactive' state for this component currently in the codebase.

========

**UPDATED REQUIREMENTS**

_As a staff member I want to ensure that authors cannot exclude and suggest the same editor(s) so that I can be sure I do not invite editors with a conflict of interest to assess the submission_

- If a Pod has already been selected (either suggested or excluded) that Pod should be rendered inactive in all other instances, e.g. if a user has already suggested an editor, their Pod should be inactive when the user accesses the People Picker to choose editors to exclude.

**Designs**

![48363360-a22e5700-e69d-11e8-9455-346fda770f8a](https://user-images.githubusercontent.com/17023702/48398843-d7788a80-e719-11e8-8b3c-8612bd6e1fc9.png)

**Comment by diversemix** [comment]
We could filter out those users that have already been selected. The issue we have is that we need to feedback this error ASAP to the user.

**Comment by hdrury1** [comment]
I'm not suggested we just don't show the pods. I'm suggesting we show them in an inactive state (greyed out, with 'Already suggested' or similar in the status line).

I think the quickest solution would be a validation error, but this would only be fed back to the user after they had made a duplicate choice- i.e. it wouldn't prevent them from making that choice in the first place.

**Comment by hdrury1** [comment]
@chugginselifesciences some mockups would be great at some point.

**Comment by chugginselifesciences** [comment]
@hdrury1 
![picker-author-exclude 1x](https://user-images.githubusercontent.com/41907215/48363360-a22e5700-e69d-11e8-9455-346fda770f8a.png)

I've added the above state to the style guide.  It's essentially everything at 50% opacity, except for status text which is 100% error colour (#cf0c4e)

**Comment by hdrury1** [comment]
I've updated the top description and opened a new issue (#1022) for creating the inactive state.
