### ISSUE TITLE
Continue submissions from last used step of the wizard

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1032]
**Describe the bug**
Returning to continue a submission currently always navigates to the first step of the initial submission wizard. This causes users to have to press next one or more times to get to last worked on step of the wizard

**Steps To Reproduce**
Partially create a submission, return to the dashboard and click on it

**Expected behavior**
You should return to the last "active" step 

**Device, Operating System and Browser**
Feedback from susanna from editorial team

**Comment by hdrury1** [comment]
Closing as this has been fixed.
