### ISSUE TITLE
Title overlapping app bar

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1033]
I think this is what we fixed for the static pages ... now it also appears on the Login screen....

![screenshot from 2018-11-14 09-12-46](https://user-images.githubusercontent.com/8524685/48472202-a4073000-e7ed-11e8-82e4-85fbf0d60fc4.png)

**Comment by chugginselifesciences** [comment]
@diversemix I was having the same issue at below 768px on the login screen, but it's been fixed. Is the browser height quite small when you have this problem? But width above 768px?

**Comment by chugginselifesciences** [comment]
I managed to recreate it by reducing the browser height so assuming that's the problem

![image](https://user-images.githubusercontent.com/41907215/48475184-25fa5780-e7f4-11e8-8dff-ef5284183146.png)

**Comment by diversemix** [comment]
@chugginselifesciences ... we'll leave investigation for who ever picks up this issue.
