### ISSUE TITLE
Clicking Next button, the next page doesn't start at the top

### ISSUE THREAD

**Issue by weimunchan** [elifesciences/elife-xpub#1036]
**Describe the bug**

When I click the Next button at the bottom of the submission form to proceed to the next part of the form, the subsequent page of the form doesn’t start from the top of the submission form. It would make sense for the next page of the form to appear near the top of the page when i click next. Likewise when clicking back, perhaps it would make most sense for the page to start at the top of the form again.

This appears to affect all sections of the submission form.

**Steps To Reproduce**
**Expected behavior**
...

**Screenshots**

![screen shot 2018-11-13 at 18 09 22](https://user-images.githubusercontent.com/44775077/48478317-db7cd900-e7fb-11e8-8464-f8aa699d050e.png)

**Device, Operating System and Browser**

MacBook Air, Mac OS, Chrome

**Comment by diversemix** [comment]
I think this an artefact of it being a SPA... how difficult is this to do @damnhipster / @Cooryd

**Comment by hem-brahmbhatt** [comment]
It shouldn't be difficult. It's something we can add within `react-router` to do on each page. 

See [docs](https://reacttraining.com/react-router/web/guides/scroll-restoration)

**Comment by hdrury1** [comment]
Closed in #2189
