### ISSUE TITLE
Progress indicator mis-alligned in IE11

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1037]
**Describe the bug**
The progress indicator and its step labels are not alligned in IE 11.

**Steps to Reproduce**
Access https://staging--xpub.elifesciences.org on IE11 using BrowserStack.

**Screenshots**
<img width="591" alt="screen shot 2018-11-14 at 11 22 14" src="https://user-images.githubusercontent.com/17023702/48479588-affbed80-e7ff-11e8-9b64-48c8eb97e690.png">

**Device, Operating System and Browser**
Windows, IE11 (using BrowserStack)

**Comment by jyenes** [comment]
It's an Issue on pubsweet, I managed to fix it adding a mediaQuery to see if the browser is IE11 and then play with the `left` property still not very happy with the fix

the code looks like this:
```
  @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    left:-50px;
  }
```

and its applied on 

```
const StepTitle = styled.span`
  font-size: 0.9em;
  position: absolute;
  text-align: center;
  top: 25px;
  white-space: normal;
  width: 120px;

  ${override('ui.Steps.StepTitle')};
`

```
On `Step.js` file 

@Cooryd and @damnhipster can you provide feedback before launching a MR on pubsweet side?

**Comment by jyenes** [comment]
MR created on pubsweet

see https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/485

**Comment by hem-brahmbhatt** [comment]
Is the CSS not something that can be added to [our override](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/elements/ui/Steps.js#L40-L45)? It should get applied to Pubsweet's StepTitle molecule [here](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/ui/src/molecules/Steps.js#L56)

**Comment by jyenes** [comment]
> Is the CSS not something that can be added to [our override](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/elements/ui/Steps.js#L40-L45)? It should get applied to Pubsweet's StepTitle molecule [here](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/ui/src/molecules/Steps.js#L56)

is what I tried to do, but I didn't find a solution that worked out, as step has more component inside, so what we want to overwrite is `StepTitle`

**Comment by hem-brahmbhatt** [comment]
@jyenes I think the bug we're facing is [this](https://github.com/philipwalton/flexbugs/issues/154).

Unfortunately, there's not really a fix for it, so your fix of using `left: -50px` is the way to go.

The other fix would be to change the DOM structure to include a wrapping element to remove the need for absolute positioning.

**Comment by diversemix** [comment]
@jyenes ... Having caught up with this ... can we remove the blocked and go with the fix? ... Agreeing with @damnhipster as I don't want to have to wait for Pubsweet even if they could fix it. If they did we can always apply it after doing this fix temporarily.

/cc @hdrury1
