### ISSUE TITLE
Pressing "Login with ORCID" not redirecting to ORCID login page

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1039]
**Describe the bug**
When logged out of XPUB, pressing "Login with ORCID" should take the user to the ORCID login page, but instead either immediately logs in (with details stored somewhere?) and shows the "continue to XPub" page, which it should not show.

This means users cannot log out and login with different credentials. It also takes users to the blue button/continue page, which it shouldn't. 

Users should maybe logged out if they press "back" to return to the login page? 

**Steps To Reproduce**
Go to staging, log out and press "Login with ORCID". This currently takes the user to the (blue button) continue page, but instead should go to dashboard. 

**Expected behavior**
User should be directed to the ORCID login screen, where they can either login with existing account or enter different account details. When pressing Sign in the user should be taken to their dashboard.

This also seems to cause a bug where users are on the XPub login page (green button) while also logged in, because refreshing the page or navigating back is automatically logging them in.

**Screenshots**
![image](https://user-images.githubusercontent.com/41907215/48481267-ce181c80-e804-11e8-9e4b-d7e870076920.png)

**Device, Operating System and Browser**

**Comment by thewilkybarkid** [comment]
This is working as expected: you're still logged in to ORCID.

ORCID appear not to have a way to force re-authentication. The nearest is forcing a log out (http://members.orcid.org/api/resources/customize#logout), which requires JavaScript.

**Comment by chugginselifesciences** [comment]
Ok. So do we intentionally have the same situation on the journal site? i.e. you can't log out and then log in as a different user? It seems to be the case for me after some testing.

Or is it just a limitation of ORCID that we're tolerating?

**Comment by thewilkybarkid** [comment]
Yes, it's expected. (Seems like an unlikely use case, you need to sign out of ORCID manually.)

Other authentication services I used before allow forced re-authentication (often needed when doing a sensitive action). It looks like [ORCID have recently added support for OpenID](https://orcid.org/blog/2018/08/30/orcid-openid-connect-and-implicit-authentication), which does have a mechanism for this. Re-authenticating after a sign out is tricky though, since we have to remember that the user was logged in.

**Comment by hdrury1** [comment]
As far as I can tell, what this effectively means is that 'logging out' of xPub doesn't actually log you out (i.e. you would not be required to re-enter your ORCiD credentials to log back in again), would that be a fair assessment? @chugginselifesciences are we happy to leave this as-is? It may have arisen as an issue purely during testing because we've asked testers to submit multiple manuscripts... I'd be tempted to park this pending further real-world feedback.

**Comment by chugginselifesciences** [comment]
> 'logging out' of xPub doesn't actually log you out

Yes that seems correct

It seems to me that we have the same issue in Xpub as we do on the journal site. In both, logging out doesn't actually log you out of your ORCID, so attempting to log back in doesn't allow you to use another ORCID - it just logs you in again as the same user. This is not ideal, but I expect it's an edge case, like Chris said, that would take time to allow for.
<br/>
Based on what I would consider a typical web experience, I think it _should_ work like this...

**Journal site**
To logout: press profile dropdown > select Log out > reload current page in logged out state

To login again: press login/register > ORCID login page > return to current page but logged in.  

This does actually happen sometimes, maybe once. But then pressing login simply reloads the page, automatically logging in to the previously used profile. Therefore you cannot change profile without manually logging out of the ORCID, which is not at all obvious.

**XPub**
To logout: press profile dropdown > select Log out > go to "green button" ORCID login page

To login again: press "Login with ORCID" from same page > go to ORCID login page & press Log in > go to dashboard. 

If they left XPub after logging out they would see the same login page when selecting "submit my research" so same process.
<br/>
This is what I think should happen for a consistent and typical login/out experience. The question is, based on @thewilkybarkid's points around ORCID, how much works is involved and is it even possible for all users? How does that effort match up against the likelihood that it affects users?

My gut feeling is that this will cause issues for very few people, but for those it affects it will be very annoying. For example for people using both personal and work/institution accounts. Therefore we should aim to 'fix' logging out, but would be low priority.

**Comment by hdrury1** [comment]
Okay. I'm going to de-prioritise this for now, with a view to resurrecting it if further user testing reveals this to be a bigger problem than we currently anticipate.
