### ISSUE TITLE
Create e2e test for navigation

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#104]
- Using URL bar to navigate to different pages
- Navbar e.g. "Dashboard"
- Checking that user can't skip steps when filling out the form

**Comment by giorgiosironi** [comment]
Close as superseded? Both `test:browser` and `elife-spectrum` in `end2end` cover this now.

**Comment by chugginselifesciences** [comment]
@hdrury is there anything I should be looking at here? It's in awaiting design review.

I created a new submission and entered "editors" at the end of the URL, and it jumped to the Editors step of the submission wizard even though earlier steps were not complete. So I assume this isn't working correctly?

I see it was moved by automation so are there other tickets for this? Can it be ignored and moved to Done?

**Comment by hdrury1** [comment]
Hi @chugginselifesciences apologies for the confusion. By default all closed tickets move to the awaiting design review column and from there I should manually move into done if your eyes aren’t needed. I missed this one- it can go into done!

**Comment by chugginselifesciences** [comment]
No problem at all. Just thought I'd better check that if something's not right we've got it covered in a ticket somewhere else before I moved it to done?

In a quick test I managed to jump ahead in the submission process via the URL when I think it should redirect to the last active or completed step?
