### ISSUE TITLE
separate 'success' subfolder of http-mocks, to clarify which tests are creating which fixtures

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#1040]
Some of the fixtures (aka "http mocks") that are being generated inside the `/success` folder are generated by the server side tests & some are generated by the browser tests.

In general, it would be quite helpful to be able to figure out which `test.js` file is generating and using which set of fixtures.

## Suggested subtasks
Change path for replay test fixtures, so they're not all pointing to 'success'?
- [ ] 'server' sub-folder for tests generated by unit/integration tests
- [ ] 'browser' sub-folder for tests generated by `yarn test:browser

**Comment by diversemix** [comment]
@jsms90 / @Cooryd Will we need to modify say `webpack` to ensure that these are not included in the docker container? :thinking: Maybe this is only when we tidy up the containers? .... I'll leave this here just in case it is an issue or inspires some other thoughts about how we do this testing :)
