### ISSUE TITLE
Show the version of the app somewhere on the pages.

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#105]
To avoid the almost inevitable confusion that can ensue by not realising you are looking at an old version - Let's pop the version / revision / date somewhere on the site. I suggest header/footer but let's discuss.

Originally raised here: https://elifesciences.atlassian.net/browse/ELPP-3604

**Comment by g-sam** [comment]
Is it sufficient to embed it in the html or does it need to be visible?

**Comment by diversemix** [comment]
Yeah I was thinking the same ... let's embed it for now... if that becomes a pain we can make it visible later

**Comment by diversemix** [comment]
Why was this closed @g-sam

**Comment by tamlyn** [comment]
1. Visit a production deployment such as https://xpub-elife-staging.gateway.xpub.semioticsquares.com
2. View source

You should see something like this 
```
<!--
  | Package version: 1.0.0
  | Git hash: 3ac68bab5bb8fe17530d499d2e934fe181d8dd46
  | Build time: Wed Jun 20 2018 16:17:23 GMT+0000 (UTC)
  | -->
```

Does this not satisfy the requirements of this ticket?

**Comment by diversemix** [comment]
@tamlyn ... That looks good ... 

But I don't see it here: view-source:https://demo--xpub.elifesciences.org/

All I see is ```

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <meta charset="utf-8">
  | </head>
  | <body>
  | <div id="root"></div>
  | <script src="/assets/app.js"></script>
  | </body>
  | </html>
 


```

**Comment by tamlyn** [comment]
Are you running a production build? It doesn't appear in development for a couple of reasons: in development the HTML index file is used as-is, not built; and all that information should already be available to you in a local dev environment.

**Comment by hdrury1** [comment]
Happy if you're happy... close at will!
