### ISSUE TITLE
Submission freezing on editors' recommendation page

### ISSUE THREAD

**Issue by mariajoaoguerreiro** [elifesciences/elife-xpub#1052]
**Describe the bug**

Submission froze at the Senior editor and Reviewing Editor picker page. User was able to hit "Cancel" and go back to the main editor picker screen (without any editors selected), but every time an attempt to select an editor was made the submission froze again, with the user being unable to carry on their submission. This was experienced using Android on a Wiko U Feel Lite (mobile).

**Steps To Reproduce**

User tried this various times with a Wiko U Feel Lite, always experiencing the same behaviour.

**Expected behavior**

Select editors and complete submission.

...

**Screenshots**
![screenshot_20181114-193837](https://user-images.githubusercontent.com/43955186/48568633-ba99ae00-e8f7-11e8-81a3-fe9eb2470114.png)

**Device, Operating System and Browser**
Wiko U Feel Lite (mobile; Android)

**Comment by diversemix** [comment]
@damnhipster ... do you think this could be related to the scroll-lock issue?

**Comment by hem-brahmbhatt** [comment]
> @damnhipster ... do you think this could be related to the scroll-lock issue?

Yes, will move this into todo.
