### ISSUE TITLE
Diacritical character omitted in author's name

### ISSUE THREAD

**Issue by mariajoaoguerreiro** [elifesciences/elife-xpub#1056]
**Describe the bug**
Submitted manuscript with eJP tracking # 15-11-2018-ISRA-eLife-02000 omitted a character in the name. In the surname, where it reads "Simes" it should have read "Simões".

**Steps To Reproduce**
Insert a diacritical character in a users' name.

**Expected behavior**
The diacritical character should be transferred, with no omissions.

**Device, Operating System and Browser**
macOS High Sierra, version 10.13.6

**Comment by diversemix** [comment]
Looks like an eJP issue. 

## article.xml
```
            <surname>Simões</surname>
            <given-names>Maria</given-names>
```

**Comment by diversemix** [comment]
Clara [6:59 PM]
I believe I've got the missing character issue fixed for the next code update (it was indeed an encoding problem).

**Comment by diversemix** [comment]
Checked by re-exporting
