### ISSUE TITLE
Metadata and files not transferred to eJP

### ISSUE THREAD

**Issue by mariajoaoguerreiro** [elifesciences/elife-xpub#1057]
**Describe the bug**
Submitted manuscript with eJP's tracking # 14-11-2018-ISRA-eLife-01996 did not carried over any of the metadata or files submitted in xPub. Author's name showing up as "Staff eJP press".

**Steps To Reproduce**
Not sure how this can be reproduced.

**Expected behavior**
All metadata and files should have been transferred.

**Device, Operating System and Browser**
macOS High Sierra
Version 10.13.6

----
We should check the logs to see what the POST was and what we did. 
Do we have any tests for this?
Put in state change in ChangeLog
Have better logging for the /meca-result POST

**Comment by diversemix** [comment]
Two things:
1. Send email to editorial team on EXPORT_SUCCESS - in the short term so they can check. Longer term we need a job queue and to poll for a timeout for 24 hours to go to failure state.
2. We need to test eJP sends us a failure when they fail.

**Comment by diversemix** [comment]
Closed as reimported fine
