### ISSUE TITLE
Dashboard submissions not ordered chronologically

### ISSUE THREAD

**Issue by weimunchan** [elifesciences/elife-xpub#1060]
**Describe the bug**

"Submissions Dashboard" submissions are not ordered chronologically or alphabetically.

**Steps To Reproduce**

**Expected behavior**

When viewing the xPUb submissions made from the xPub submissions dashboard one would expect them to be ordered chronologically or alphabetically perhaps with the option to sort by date / name.
...

**Screenshots**
![screen shot 2018-11-16 at 11 27 07](https://user-images.githubusercontent.com/44775077/48619416-5547ca80-e994-11e8-92ff-631e78a960be.png)
![screen shot 2018-11-16 at 11 26 55](https://user-images.githubusercontent.com/44775077/48619417-5547ca80-e994-11e8-893c-5b200607cb74.png)

**Device, Operating System and Browser**
Macbook air, MacOS High Sierra, Chrome

**Comment by hdrury1** [comment]
To be clear, expected behaviour is that the list should be ordered chronologically, with latest submission at the top. 

There is currently no functionality to allow the user to sort their submissions.

**Comment by chugginselifesciences** [comment]
@hdrury1 - I'm moving this into To Do as Cory mentioned it should be an easy fix. I think it's worth doing before launch.
