### ISSUE TITLE
Investigate People Picker performance (#419)

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1073]
Investigate People Picker performance (#419) - Timebox to half a day please

**Comment by damnhipster** [comment]
Good overview of performance optimisations: https://reactjs.org/docs/optimizing-performance.html

**Comment by damnhipster** [comment]
My findings match the results of the investigation performed [here](https://github.com/elifesciences/elife-xpub/issues/419#issuecomment-409583197).

When we remove the limit for PersonPods, the people picker takes up to **2 seconds** to appear. I tried using `React.Pure` components, and manually changing `shouldComponentUpdate` but the performance gains were negligible. This would also be the case if using immutable data structures.

The options I've come across to fix this issue are:
- Use windowing, such as [react-window](https://github.com/bvaughn/react-window) or [react-virtualized](https://github.com/bvaughn/react-virtualized)
- Further separate out components within PersonPod to allow React to apply more granular optimisations

**Comment by hdrury1** [comment]
Great, thanks @damnhipster. I'll take a look at the options with @chugginselifesciences and see what he thinks.

**Comment by hdrury1** [comment]
React-window looks like a smaller package... would I be right in assuming it is likely less work to implement this than to refactor the current PersonPod as per Option 2? Is there any downside to implementing react-window?

**Comment by damnhipster** [comment]
@Cooryd and @SemraSh are looking into another option; there may be a bug where PersonPods are being rendered eagerly, since even closing the people picker has a delay.

> React-window looks like a smaller package... would I be right in assuming it is likely less work to implement this than to refactor the current PersonPod as per Option 2? Is there any downside to implementing react-window?

This would be less work and I'm more confident it would give a better performance boost. There doesn't seem to be a downside other than the fact that the height of all PersonPods need to be the same, and we need to know how many PersonPods to show. The reviewers/editors are fetched before the people picker is opened, so this won't be a problem, and there won't be a visible delay.

**Comment by diversemix** [comment]
@chrishuggins you ok with PPods being the same height... please say yes... :pistol:

/cc @hdrury1

**Comment by hdrury1** [comment]
They are the same height by design so I think react-window is a suitable solution.

**Comment by SemraSh** [comment]
This branch `419-people-picker-performance` fixes [this](https://github.com/elifesciences/elife-xpub/issues/419#issuecomment-409583197)

**Comment by diversemix** [comment]
Investigation complete - implementation #419
