### ISSUE TITLE
Add Google Analytics tracking to application

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1077]
## Problem / Motivation
- WHO Product Manager
- WHEN in preparation for public release WHERE in all header tags of the application.
- WHAT Google analytics tracking
- WHY to record accurate user data which will be used to surmise KPIs. For MVP, we would like to measure the following:

1) Length of time taken to complete a submission
2) Drop offs - are users giving up? If so, where?
3) Is there a particular step that is taking users a long time?
4) What Browser are people using?
5) Viewport sizes
6) Which devices are people using?

## Proposed solution
- Add Google Analytics tags to all client-facing pieces of the application

## Clarification needed and assumptions
- Code can be easily generated from the Google Analytics application

**Comment by hdrury1** [comment]
I now have a tracking code that will need adding before the close of every `<Head>` tag on every page of the application. Not sure how this will work technically with, for example, the People Picker which doesn't have its own URL.

**Comment by hem-brahmbhatt** [comment]
We'll want to implement Google Analytics to track pageviews using [this guide](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications). 
It's something we can tie into the router code of the application so the tracking happens automagically.

**Comment by hem-brahmbhatt** [comment]
We can hardcode some of the Google Analytics code as you said, on the `<head>` tag by editing [this file](https://github.com/elifesciences/elife-xpub/blob/develop/app/index-production.html). If there's a better way to dynamically load it, we'll try to use that solution, but this can be a fallback. 

With the fallback, you can get everything except page/event tracking, so that includes:
- Time of initial page visits
- Browser information
- Location information

Using the guide [mentioned above](https://github.com/elifesciences/elife-xpub/issues/1077#issuecomment-454012354), we can have page/event tracking as well.

**Comment by hdrury1** [comment]
Maybe we can chat about this tomorrow. I'll add it to the agenda.

**Comment by giorgiosironi** [comment]
> We can hardcode some of the Google Analytics code as you said

How do we distinguish between environments?

**Comment by hem-brahmbhatt** [comment]
> > We can hardcode some of the Google Analytics code as you said
> 
> How do we distinguish between environments?

:shipit:

**Comment by hdrury1** [comment]
> How do we distinguish between environments?

@giorgiosironi Generate separate tags for Production and Demo?

**Comment by hem-brahmbhatt** [comment]
> > How do we distinguish between environments?
> 
> @giorgiosironi Generate separate tags for Production and Demo?

We have a way to [load config from the server on page load](https://github.com/elifesciences/elife-xpub/blob/develop/app/index-production.html#L10), so we can embed the tag onto the page easily enough.

**Comment by hdrury1** [comment]
Production Environment tag:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132441389-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132441389-1');
</script>
```

**Comment by hdrury1** [comment]
Demo environment tag:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132441389-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132441389-2');
</script>
```

**Comment by giorgiosironi** [comment]
I read `Demo` as `staging` and `end2end` since they are both environments that mimic production. You probably don't want it in review environments as they will just create noise.

**Comment by damnhipster** [comment]
@diversemix Why has this been closed? If this has been implemented, can you link the PR?

**Comment by diversemix** [comment]
Accidentally closed

**Comment by hdrury1** [comment]
I've changed the title of this issue to reflect that Hotjar may also be a possibility (documentation: https://help.hotjar.com/hc/en-us/articles/115011805428-Hotjar-on-Single-Page-Apps)

With Hotjar, you can record individual user journeys, so we would see when they are clicking, when idle etc.

**Comment by diversemix** [comment]
Do we have a need for Google Analytics in any other environment other than production? If so why?
@hdrury1

**Comment by hem-brahmbhatt** [comment]
> Do we have a need for Google Analytics in any other environment other than production? If so why?
> @hdrury1

It would be useful to have in Staging so we can manually test it. We're likely to add more tracking events in the future, so it would be useful to have an environment to test it in other than Production

**Comment by hdrury1** [comment]
Testing purposes only, yes.

**Comment by hem-brahmbhatt** [comment]
@hdrury1 can you put the tracking code for hotjar here?

https://help.hotjar.com/hc/en-us/articles/115009499088-How-to-Find-your-Hotjar-Tracking-Code

**Comment by hdrury1** [comment]
As per Standup discussions I will create a new issue for adding HotJar tracking.
