### ISSUE TITLE
Review ChangeLog

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1079]
## Problem / Motivation

- WHO - Product / Editorial
- WHEN and WHERE - In the product before launch
- WHAT - A ChangeLog to query.
- WHY - Ability to ask questions and retrieve useful information about the product.

## Proposed solution
- [ ] Arrange a meeting to ask what questions they anticipate needing to ask
- [ ] Add `ChangeLog` entries in the code to facilitate answering these questions.

## Clarification needed and assumptions
(TBD after meeting)

/cc @hdrury1 - please reword as you see fit.

**Comment by hdrury1** [comment]
Meeting scheduled for tomorrow- will update issue after this.

**Comment by hdrury1** [comment]
Update, following meeting with Editorial team:

They will be interested in a log of status changes only. In practice, for the initial submission interface, this will be the date/time an author began a new submission and the date/time they completed it.

Product will require more granular details, e.g. each time an author visits a new page of the wizard, how many times they attempted to upload a file. This may more closely resemble a SystemLog.

**Comment by diversemix** [comment]
@hdrury1 Going to open up a new issue for the Editorial Requirements ... can we close this out
