### ISSUE TITLE
Expose elife-api in the package xpub-model

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1084]
**complete #1609 first**

See https://github.com/elifesciences/elife-xpub/pull/1065#discussion_r235074668

**Comment by diversemix** [comment]
@Cooryd / @damnhipster ... will this get done as part of #1587 ?

**Comment by hem-brahmbhatt** [comment]
Yes, will include it in the epic.

**Comment by hem-brahmbhatt** [comment]
Currently the model requires `elife-api`. Moving the file into `xpub-controller` means that the model will require the controller which is a code smell.

We can look at moving the clients into their own package alongside `xpub-controller` and `xpub-model` so both of them can make use of clients.

What does everyone think? @diversemix @Cooryd @jyenes

**Comment by Cooryd** [comment]
I like this idea, makes the controller directory tidier too

**Comment by Cooryd** [comment]
See #1609 which creates the top level `xpub-client` (???) directory. This issue just relates to relocating the `elife-api` to that directory
