### ISSUE TITLE
Dependencies & Architecture

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1086]
At the moment the dependencies and the architecture are too ad-hoc. We need to formalise this into layers that can be simply extended. We don't want Spaghetti !!! 

![20181121_111507](https://user-images.githubusercontent.com/8524685/48900453-51abbc00-ee4a-11e8-9932-3d84e1b3b262.jpg)

/cc @damnhipster Thought I'd move our chat here

**Comment by damnhipster** [comment]
I'd consider putting the logic within server.

But in an ideal world, we could have a package called `xpub-base` which contains the business logic, and `xpub-server` would be responsible for server code, and a separate package called `xpub-api` for the graphql API.

Server and model contain business logic, and it may be easier to move the logic from one to the other to begin with.

I like the idea though.
