### ISSUE TITLE
Disable review environments on Gitlab

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1100]
We have review environments on Gitlab and Jenkins. 

We should remove and disable review environments on Gitlab so we don't have to maintain two sets of environments.

<img width="709" alt="screen shot 2018-11-22 at 16 02 44" src="https://user-images.githubusercontent.com/2573277/48914002-0efdda00-ee72-11e8-846a-b428d8521cd8.png">

**Comment by diversemix** [comment]
Let's talk about this on a call sometime to ensure we are all on the same page. Might fit in well with a demo about end2end tests?

/cc @giorgiosironi  @hdrury1

**Comment by giorgiosironi** [comment]
Right now review environments on Jenkins also have an S3 simulation working so good to remove the Gitlab ones.

**Comment by giorgiosironi** [comment]
I think I'll make a small PR for this.
