### ISSUE TITLE
Run database migrations on deploy

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1102]
At the moment, we have to manually run the migrations on each environment before the pipeline can successfully move onto the next environment, so it's pretty slow.

We store the migration history on the database itself, and our migration command takes care to run new migrations only.

We should execute `npx pubsweet migrate` on the `xpub` application container within environments. Make sure it's executed **after** the application has deployed/updated, so the new migration scripts are picked up.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-xpub-formula/pull/59 is the first attempt.

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/test-elife-xpub/ is green now.

However, https://github.com/elifesciences/elife-xpub-formula/pull/60 is also necessary.

**Comment by damnhipster** [comment]
Can this be closed now? Is this something that has been tested out?

**Comment by giorgiosironi** [comment]
Merged; https://alfred.elifesciences.org/job/test-elife-xpub/502/console is using the leader-node (on `node==1`) version for the first time. We'll also test `prod`.

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/prod-elife-xpub/36/console is a success too, as far as I can tell:
```
10:29:25 [54.210.77.75] out:           ID: elife-xpub-database-migrations
10:29:25 [54.210.77.75] out:     Function: cmd.run
10:29:25 [54.210.77.75] out:         Name: docker-compose -f docker-compose.yml -f docker-compose.formula.yml exec -T app npx pubsweet migrate
10:29:25 [54.210.77.75] out:       Result: True
10:29:25 [54.210.77.75] out:      Comment: Command "docker-compose -f docker-compose.yml -f docker-compose.formula.yml exec -T app npx pubsweet migrate" run
10:29:25 [54.210.77.75] out:      Started: 10:29:16.400291
10:29:25 [54.210.77.75] out:     Duration: 2851.62 ms
10:29:25 [54.210.77.75] out:      Changes:   
10:29:25 [54.210.77.75] out:               ----------
10:29:25 [54.210.77.75] out:               pid:
10:29:25 [54.210.77.75] out:                   21743
10:29:25 [54.210.77.75] out:               retcode:
10:29:25 [54.210.77.75] out:                   0
10:29:25 [54.210.77.75] out:               stderr:
10:29:25 [54.210.77.75] out:               stdout:
```
