### ISSUE TITLE
Manuscript Delete - needs confirmation dialog

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1107]
In the dashboard when you click delete for a manuscript - we need a confirmation dialog.

**Comment by chugginselifesciences** [comment]
Please use the below format to show the submission title to the user in the modal. I will add the warning-button version to the style guide.

![image](https://user-images.githubusercontent.com/41907215/49009219-ed4d6d00-f167-11e8-831c-5722cbead081.png)
