### ISSUE TITLE
Redirect to first incomplete page when user navigates too far ahead in wizard

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#111]
Example: author starts a submission, fills in author details then changes the URL to go straight to editor suggestions (the last step of the form), fills our the fields then clicks submit. Everything on that page is correct but the submission cannot be made because data from previous pages is missing from the manuscript.

Suggested solution: When a user lands on a page of the submission form wizard, check that all previous pages have valid data and if not, redirect the user to the last incomplete page.

**Comment by tamlyn** [comment]
This touches a lot of the form saving logic and will be tricky to implement before #54, #95 and #126.

Proposed approach:
- Move `WithCurrentSubmission` up into `SubmissionPage` component
- Import each page's yup schema into that page and run the saved data through them
- Ensure that every page before the requested one is valid and redirect if not

**Comment by tamlyn** [comment]
Prerequisite issues are now resolved so this is unblocked.

**Comment by diversemix** [comment]
More explanation needed. What is meant by "too far"? Why do we need to redirect? Why is it a problem? If it is why can we do it in the first place?

**Comment by tamlyn** [comment]
Description updated. Let me know if it requires further clarification.

**Comment by hdrury1** [comment]
Hmm. Could we redirect upon hitting the submit button? In the above use case, this would mean:

1) Data entered on the editor suggestion page is saved
2) User is redirected to the last incomplete page
3) Validation errors are displayed on this page to alert the user to why they have been redirected

**Comment by hdrury1** [comment]
Following yesterdays f2f discussion, we will not redirect the user to the last edited field (or the page containing the last edited field) if they navigate too far ahead.

This matches the expected behaviour of clicking to continue an in progress submission from the dashboard (#732)

**Comment by tamlyn** [comment]
Sorry, we changed this again this morning. I think I was wrong to suggest these two issues are related. 

"Return to last viewed page when clicking on a manuscript on the dashboard" is covered by #732 and this issue is just about ensuring the user doesn't get too far ahead in the wizard.
