### ISSUE TITLE
Create model for Audit Log

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1110]
Background see #1079 

When a manuscript (in the `base-model`) has a State change - this should get logged into the database `audit_log` table. This includes manuscript create and delete.

## PR breakdown
- [x] Create an `AuditLog` entity in the `xpub-model` based on the following migration
```
CREATE TABLE audit_log (
    id UUID PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
    user_id UUID REFERENCES "user",
    action TEXT NOT NULL,
    object_id UUID,
    object_type TEXT
);
```
- [x] Add a test to ensure that this this is correctly written to the database.

**Comment by diversemix** [comment]
Needs to be done for tracking issues like #1057

**Comment by damnhipster** [comment]
Created #1243 and #1244 to capture the rest of the requirements.
