### ISSUE TITLE
ModalDialog should close if/when a user clicks on the greyed out background around the white modal itself

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#1121]
This component is currently used in 3 situations:
- Within dashboard - appears when user clicks on delete icon (modal created in issue #1107)
- Within PeoplePicker - appears when user clicks on info icon inside PersonPod (modal created in issue #635)
- At the end of submission wizard - appears when user clicks Submit on last step of wizard (modal created in issue #511)

## Subtasks
Possibly:
- [ ] Add `onClick` functionality to `ModalOverlay`
- [ ] Hook up to `onRequestClose` within `ModalDialog`

## Assumptions and notes
- We could use this technology
- More notes or suggestions

**Comment by hdrury1** [comment]
Closing as unconvinced this is a product requirement.
