### ISSUE TITLE
Write tests for new PersonPod modal - full person info

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#1125]
Write tests for Person Info modal (created in issue #635 via PR #1119)

#### Accessing the info modal via the PeoplePickerControl
Renders correctly:
- [ ] When author clicks on the info icon from the editors page (i.e. inside PeoplePickerControl), the modal should display 'Remove editor'

Functionality:
- [ ] Given that an author has opened the info modal from within the PeoplePickerControl, when an author then clicks 'Remove editor', the relevant person pod should be removed from the control
- [ ] When an author clicks 'Cancel', the modal closes and the PeoplePickerControl is unchanged

#### Accessing the info modal via the PeoplePickerModal
Renders correctly:
- [ ] Given that the author has opened the PeoplePickerModal, when the info button is clicked on a PersonPod that has **not** yet been selected, the modal should have '**Add Editor**' text
- [ ] Given that the author has opened the PeoplePickerModal, when the info button is clicked on a PersonPod that **has** been selected, the modal should have '**Remove Editor**' text
- ~Given that maximum number of editors have already been selected in the PeoplePickerModal **and** person has already been selected, when the info button is clicked, the modal should have '**Remove Editor**' text~ - to be completed as part of issue #1128 

Functionality:
- [ ] Given that ... (see 1st point above) ..., when info is clicked, then Add Editor is clicked, modal should close & person should be selected (i.e. tag should appear and icon type should change to a tick)
- [ ] Given that ... (see 2nd point above) ..., when info is clicked, then Remove Editor is clicked, modal should close & person should be deselected (i.e. tag should disappear and icon type should change to +)
- ~Given that maximum number of editors have already been chosen, Add Editor button in modal should be disabled~ - to be completed as part of issue #1128

**Comment by hdrury1** [comment]
@jsms90 in the instance where a user has already reached the maximum number of selections and opens the info modal, the 'Add Editor' button should be disabled. i.e. unclickable and 50% opacity.
