### ISSUE TITLE
Allow app to be more easily configured with environment variables

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#113]
Currently the only way to pass config through the environment is to use [a blob of JSON](https://gitlab.coko.foundation/yld/xpub-deployment-config-postgres/blob/master/templates/xpub-elife-configmap-nodeconfig.yaml) in `NODE_CONFIG`.

`node-config` [provides a mechanism](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables) for mapping individual environment variables into the config structure. This is easier to understand and makes the app easier to deploy. It should also make the above referenced config map unnecessary.

**Comment by diversemix** [comment]
Is this a point of discussion, or are we going with `NODE_CONFIG`? What I would like to ensure is that we can trace with exactly what configuration an application has been run with at any point in time. This might be as simple as logging out the config but I think we need to have a strategy on this. @g-sam ?

**Comment by tamlyn** [comment]
See https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/48

This should make this config unnecessary https://github.com/elifesciences/elife-xpub/blob/develop/docker-compose.yml#L17
