### ISSUE TITLE
serif fonts appearing in many incorrect places

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1139]
**Screenshots**

Person pods
![image](https://user-images.githubusercontent.com/41907215/49283224-1f710e80-f489-11e8-894d-8e073294e2c9.png)

![image](https://user-images.githubusercontent.com/41907215/49283233-25ff8600-f489-11e8-9db1-12ce702ca3bd.png)

Upload drop target
![image](https://user-images.githubusercontent.com/41907215/49283387-842c6900-f489-11e8-8498-8d458b6e2ce7.png)

Modal:

![image](https://user-images.githubusercontent.com/41907215/49283457-afaf5380-f489-11e8-89e9-7be1b554b3ba.png)

Dashboard:
![image](https://user-images.githubusercontent.com/41907215/49283851-ce621a00-f48a-11e8-9290-6c088066be7c.png)

(Should be noto sans regular 12px)

**Comment by hdrury1** [comment]
Captured in #1122
