### ISSUE TITLE
Create an example MECA archive from xPub manuscript and decision data

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#114]
MECA spec https://docs.google.com/document/d/1Fki78pgOzZCFhFaJVCBd04ZZYZYkDThqg22suZ-q2RQ/edit

**Comment by hdrury1** [comment]
Waiting to hear back from Joel following latest communication.

**Comment by diversemix** [comment]
@tamlyn 's example here: https://docs.google.com/document/d/1PHM3e0WKsK8fnf0Hdt6SvV-SkGlRKfIYUT-5f4VCQh4/edit#heading=h.da5i9ruslolu

**Comment by diversemix** [comment]
Creating... https://github.com/elifesciences/elife-xpub-meca
