### ISSUE TITLE
Option to only exclude 1 Senior Editor

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1140]
**Describe the bug**
A user can currently select two Senior editors to exclude. They should only be able to select one.

**Steps To Reproduce**
Navigate to the Editors step of the wizard
Choose to exclude a Senior editor
Open the People Picker
See that you are able to select two editors

**Expected behavior**
A user should only be able to make one selection

**Comment by diversemix** [comment]
@SemraSh Can you check this again in staging? Doesn't appear to be working :/

**Comment by diversemix** [comment]
My bad! ... looking at the Inclusion not the Exclusion ... sorry :pray:
