### ISSUE TITLE
Change people picker headings from "Choose" to "Suggest" when suggesting and "Exlude" when excluding

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1141]
The term "choose" may be confusing while authors make suggestions for Senior and Reviewing Editors via the people picker. We should continue using the term "Suggest" instead of "Choose" so that users are clear that it is a suggestion, not a definite selection.

![image](https://user-images.githubusercontent.com/41907215/49284315-1e8dac00-f48c-11e8-8b71-0dd12fcee66a.png)

Exclude a Senior Editor (can only exclude 1)

![image](https://user-images.githubusercontent.com/41907215/49285365-2438c100-f48f-11e8-9f7d-c7c8bc32e1f0.png)

Exclude Reviewing Editors (2 allowed - 1 min)

![image](https://user-images.githubusercontent.com/41907215/49285465-619d4e80-f48f-11e8-8281-218db5d52ca7.png)

(please ignore button inactive states above)

**Comment by hdrury1** [comment]
Also worth updating the labelling at this point to 'Senior Editor' and 'Reviewing Editor' (capitalised).
