### ISSUE TITLE
Display of manuscript within the system (Texture)

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#115]

**Comment by tamlyn** [comment]
See https://github.com/elifesciences/sciencebeam-texture, specifically
- [Dummy DAR client](https://github.com/elifesciences/sciencebeam-texture/blob/develop/demo/src/js/Editor.js#L59)
- [Texture editor on which science beam version is based](https://github.com/substance/texture/blob/732664b3fcf8d68bb1583b10d29353f60a0e04c9/web/editor.js)

Thanks @de-code
