### ISSUE TITLE
Add a header to the list of files.

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1161]
Header should appear after one supporting file is uploaded.

//cc @hdrury1 Screenshot

**Comment by hdrury1** [comment]
<img width="942" alt="screen shot 2018-12-04 at 12 53 30" src="https://user-images.githubusercontent.com/17023702/49443463-6e3de180-f7c4-11e8-9f32-7abb69a76d14.png">

**Comment by hdrury1** [comment]
This has been implemented.
