### ISSUE TITLE
Autosave feature broken

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1162]
When uploading a supporting file the autosave does not work. See discussion in agenda 4/12/2018

https://docs.google.com/document/d/1IEYlmkzyBmxEFhn8U0kM8F5cl5OO-2jEpJmVV4VGZus/edit

**Comment by diversemix** [comment]
TODO: Add a `lastUpdated` check against `this` and the return of `this.$query()` in the `save()` of a `Manuscript` and throw an error if the two are not equal (version conflict)

**Comment by diversemix** [comment]
Seems like `objection` does have a `patchAndFetchById` option which is used in the `base_model`

(see https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/base-model/src/index.js#L111)

**Comment by diversemix** [comment]
I have raised 2 MR for pubsweet to handle this:
To ensure `updated` is set on an object when it is created:
- https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/463

To protect the `save()` from overwriting data:
- https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/464

**Comment by giorgiosironi** [comment]
Not sure if related: https://github.com/elifesciences/elife-xpub/issues/1207

**Comment by diversemix** [comment]
This was closed in error - as the issue is now logged - but not actually fixed. When the exception was thrown this caused the browser tests to fail on occasion. Now it just logs the error - we need further investigation to ensure this is properly fixed.
/cc @hdrury1
