### ISSUE TITLE
Subscription to manuscript upload progress maintains when submission deleted

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1175]
**Describe the bug**

Subscription to manuscript upload progress maintains when submission is deleted and a new submission is created.

**Steps To Reproduce**

- Create a new submission
- Get to the manuscript upload step
- Upload a large manuscript 
- While in progress go back to the dashboard
- Delete the submission you have just created
- Create a new submission
-Get to the manuscript upload step
- If the server is still processing the document, the upload section will still display a progress spinner

**Expected behavior**

Progress shouldn't continue to show across different submissions.

**Device, Operating System and Browser**

OSX - Chrome

**Comment by hdrury1** [comment]
This was addressed wasn't it @Cooryd?
