### ISSUE TITLE
Add header to supporting files section

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1197]
We should provide a context header to the supporting files section, which should appear as soon as a user has chosen one or more supporting files to upload.

NotoSans, 14px, colorTextSecondary

<img width="503" alt="screen shot 2018-12-12 at 09 42 29" src="https://user-images.githubusercontent.com/17023702/49887854-57873280-fe35-11e8-9320-5521db1ba87c.png">

**Comment by chugginselifesciences** [comment]
@hdrury1 @jyenes This looks like it is in 16px colorText not 14px colorTextScondary.

![image](https://user-images.githubusercontent.com/41907215/50781868-64653d80-129e-11e9-9718-776e368c4f0e.png)
