### ISSUE TITLE
Investigate: Title extraction working intermitently

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1198]
**Describe the bug**
I am only getting the title extracted around 50% of the time I upload a manuscript. Often, extraction will work if I navigate back to the Files step and re-upload the same manuscript file.

**Steps To Reproduce**
Difficult to reproduce, as the failure is intermitent. Keeping this bug ticket as a placeholder- will test extensively and copy terminal logs.

**Expected behavior**
Title extraction should happen successfully in the majority of cases.

**Comment by hdrury1** [comment]
Uploaded the following file:

[elife-40583-v2.pdf](https://github.com/elifesciences/elife-xpub/files/2685648/elife-40583-v2.pdf)

The application gave me a success message, but navigating to the next page the title had not extracted. I navigated back and re-uploaded the same file. This time the title appeared on the next page of the wizard as expected.

**Comment by hdrury1** [comment]
Uploaded the following file with the same results- title only extracting on second upload attempt:

[elife-39723-v2.pdf](https://github.com/elifesciences/elife-xpub/files/2744872/elife-39723-v2.pdf)

And this file wouldn't extract at all:

[elife-38852-v2.pdf](https://github.com/elifesciences/elife-xpub/files/2744871/elife-38852-v2.pdf)

**Comment by diversemix** [comment]
Adding logging into the app to try and figure out what is going on. Couldn't get things to fail locally - and we probably need some of this logging in when we go live to assess how sciencebeam is doing. see #1286

/cc @hdrury1

**Comment by diversemix** [comment]
We can reproduce the problem locally by doing a `docker restart` on the sciencebeam containers, and then requesting an extraction....

```
$ time python tester.py 
{'_content': b'<article article-type="research-article">\n  <front>\n    <article-meta>\n      <title-group>\n        <article-title/>\n      </title-group>\n      <contrib-group content-type="author">\n        <contrib contrib-type="person">\n          <name>\n            <surname>Pennyworth</surname>\n            <given-names>Alfred</given-names>\n          </name>\n        </contrib>\n      </contrib-group>\n      <abstract>\n\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n\t\t\t</abstract>\n    </article-meta>\n  </front>\n  <body/>\n  <back/>\n</article>\n', '_content_consumed': True, '_next': None, 'status_code': 200, 'headers': {'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '937', 'Access-Control-Allow-Origin': '*', 'Server': 'Werkzeug/0.14.1 Python/2.7.14', 'Date': 'Mon, 14 Jan 2019 14:50:42 GMT'}, 'raw': <urllib3.response.HTTPResponse object at 0x7fb5967d1b38>, 'url': 'http://localhost:8075/api/convert', 'encoding': 'utf-8', 'history': [], 'reason': 'OK', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(0, 15, 862743), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x7fb5967bde48>}

real	0m16.060s
user	0m0.186s
sys	0m0.012s
```


[tester.py.txt](https://github.com/elifesciences/elife-xpub/files/2755631/tester.py.txt)

/cc @de-code @hdrury1

**Comment by diversemix** [comment]
The logs had failures at least 10 mins apart ... checked and discovered that the 10 min interval is not an issue. i.e. sciencebeam still quickly extracted after being left for 10 mins.

**Comment by diversemix** [comment]
Looking within the grobid container... it appears to takes 15.2 seconds to load the models ... can we do this on start up @de ?

```
INFO  [2019-01-14 15:13:36,406] org.eclipse.jetty.server.Server: Started @3336ms
INFO  [2019-01-14 15:17:33,241] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/10
INFO  [2019-01-14 15:17:33,256] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/fulltext/model.wapiti (size: 20462507)
INFO  [2019-01-14 15:17:35,949] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/segmentation/model.wapiti (size: 15807193)
INFO  [2019-01-14 15:17:38,385] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/header/model.wapiti (size: 36094028)
INFO  [2019-01-14 15:17:44,324] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/name/header/model.wapiti (size: 2225578)
INFO  [2019-01-14 15:17:44,487] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/name/citation/model.wapiti (size: 393118)
INFO  [2019-01-14 15:17:44,554] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/affiliation-address/model.wapiti (size: 2646298)
INFO  [2019-01-14 15:17:46,516] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/citation/model.wapiti (size: 16235248)
INFO  [2019-01-14 15:17:48,479] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/reference-segmenter/model.wapiti (size: 4829569)
```

**Comment by diversemix** [comment]
This issue is closed as we have found the source of the issue. What we need to decide upon is how / who will fix this? @hdrury1
