### ISSUE TITLE
Automate rebuilding of the base image

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#1199]
The base image is time saving as every new version of `elifesciences/elife-xpub` only has to rebuild the application-specific stuff rather than starting from scratch from a `node` image. It originally comes from https://gitlab.coko.foundation/yld/xpub-deployment-config-postgres/blob/master/images/xpub-base/Dockerfile but if all the relevant Dockerfiles are committed with special names into the repository, we can automate the rebuilding process and issue generated tags.

Reference also https://hub.docker.com/r/pubsweet/pubsweet-base/tags/ which only has the `latest` tag and no versioning.

**Comment by giorgiosironi** [comment]
Notice also the `base` image is currently huge (858 MB) because it contains a Yarn cache, can take the opportunity to look for ways to both have quick builds and at the same time shrink its size which also results in faster pushes and pulls.

**Comment by damnhipster** [comment]
We can also shave off 300mb if we use `node:8-alpine` rather than `node:8`

**Comment by giorgiosironi** [comment]
> if we use node:8-alpine 

Though it needs to be tested that dependencies like the headless browser or any NPM package work in that environment

**Comment by damnhipster** [comment]
We'll also have to include git and maybe some other basic packages.
