### ISSUE TITLE
Move base docker image to different repository

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1202]
The docker repository for the base image is `xpub/xpub`, hosted by Dockerhub [here](https://hub.docker.com/r/xpub/xpub/)

This repository is also used by https://gitlab.coko.foundation/xpub/xpub. We should host our base image in a separate repository.

**Comment by giorgiosironi** [comment]
We have a [few](https://github.com/elifesciences/elife-base-images) related to different programming languages, it will be something like `elifesciences/*`.

**Comment by damnhipster** [comment]
We should also take this opportunity to change the tagging convention from a timestamp format (`20180101-1200`) to the commit SHA from the repo.

**Comment by diversemix** [comment]
@damnhipster  / @giorgiosironi  .... is this ticket still relevant / is there still outstanding work?

**Comment by giorgiosironi** [comment]
The base image is still on [`xpub/xpub`](https://github.com/elifesciences/elife-xpub/blob/develop/Dockerfile#L2) so this is outstanding.
