### ISSUE TITLE
Update font of text in empty dashboard tabs 

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1211]
Please update the following lines of text in the dashboard to `font-family = "Noto Sans regular"`, `font-size = 12px` and `font-weight = 400`.

In submissions tab:
> You may want to bookmark this page to easily retrieve your in progress submissions.

and in both tabs:

> Can't find a submission? You might find it in our full peer review and submissions system.

**Please also check that the `"You currently have no active/archived submissions"` text is in regular font/400 as it looks semibold/too heavy.**

![image](https://user-images.githubusercontent.com/41907215/50012141-c4c1d180-ffb5-11e8-9233-29db44ef7798.png)

**Comment by diversemix** [comment]
Possibly depending on #1122
