### ISSUE TITLE
Premature validation on editors step

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1218]
**Describe the bug**
Untouched fields are showing up as invalid on the editors step.

**Steps To Reproduce**
1. Navigate to editors step
2. Select Senior editors to include using peple picker
3. Add Senior editors (closing people picker)
4. Observe that untouched fields are invalidated

**Expected behavior**
Untouched fields should not be validated against until they are focussed on for the first time (click on and click off).

Would like a test written for this, as this is an old bug that has been re-introduced.

**Comment by diversemix** [comment]
Confirm its an issue and you've not been hacking around like @hdrury1

**Comment by hdrury1** [comment]
Tested this and can't reproduce with expected user journey, so closing down.
