### ISSUE TITLE
Create loading state for People Picker

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1220]
As a short term fix to the people picker performance issue - put up a loady spinny thing to indicate to the user that it might take some while.

Ideally we just show a centred spinner with “Loading”. If we have to show other elements of the modal we should center it in available space
The numbers show in order of preference 1 being most preferred

![image](https://user-images.githubusercontent.com/8524685/50208091-3019f380-0368-11e9-9948-0290af7ad18c.png)

**Comment by SemraSh** [comment]
### Checklist
[ ] Create a new component which has: 
      [ ] ProgressBar 
      [ ] `Loading... `text
[ ] Add loading state when the app is not ready to show certain results in People Picker

**Comment by SemraSh** [comment]
_Agreed with @chugginselifesciences on the following design_
![image](https://user-images.githubusercontent.com/32770804/50684639-323dac80-100e-11e9-8aaf-ff9422a956d4.png)

**Comment by Cooryd** [comment]
For future reference: https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-q2-2019-the-one-with-concurrent-mode

This would solve the issue of the app freezing up when attempting to render all of the `PersonPod` components at once. Scheduled for release in Q2 2019
