### ISSUE TITLE
Improve performance of people picker

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1225]
## Summary 

The people picker takes a moderate amount of time to display all the people.

- [ ] reduce the amount of time the people picker is in a loading state

### Solutions

The agreed solution for this has been to implement lazy loading on large lists. You can find our reasoning below under **The reason it's slow**.
 
A few solutions have already been attempted:

1. `react-window`
    - Closed PR: https://github.com/elifesciences/elife-xpub/pull/1183
2. `react-virtualized`
    - Closed PR: https://github.com/elifesciences/elife-xpub/pull/1195
3. Building our own infinite scrolling feature
    - Closed PR: https://github.com/elifesciences/elife-xpub/pull/1214

My recommended approach is to use `react-virtualized`. If we're implementing lazy loading, the following features need to be supported, which `react-virtualized` does:
- People picker needs to be responsive. This means running the lazy loading logic again on resize.
- Lazy loading should support two column layout.
- Pass in the scrollable element to bind the lazy loading to.

### Diving into the logic flow

When the user navigates to the Editors page, we render the page, and query for the data we need for the people picker in the background. When the user opens the people picker, we start the rendering process, after the data has been successfully retrieved from the API.

The below diagram represents the above logic.

![mvimg_20181219_124856](https://user-images.githubusercontent.com/2573277/50221523-50a87480-038d-11e9-93f9-368f67182782.jpg)

The step highlighted in red was found to be the major source of delay. 

### The reason it's slow

The application is trying to update the React tree to add a large number of PersonPods and their children. You can see this in the flamegraph below:

![flame](https://user-images.githubusercontent.com/115310/43525597-2e655dcc-959a-11e8-854b-e281de99d7bd.png)

The API calls are also slow, but because this happens in the background when the user first visits the page, there isn't any visible impact on performance.

### History

Initially there was an artificial limit in place so we only showed 30 people. 

This was not feasible to go to production with, [so the limit was removed](https://github.com/elifesciences/elife-xpub/pull/1181). 

To alleviate the performance issues, [a loading state was introduced in the meantime](https://github.com/elifesciences/elife-xpub/issues/1220).

**Comment by hdrury1** [comment]
Closed by mistake
