### ISSUE TITLE
test:browser hanging

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#1228]
e.g. https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1181/6/pipeline hangs apparently forever in the `test:browser` target until the build is killed after a 2 hours timeout.

Situation seems more or less normal:
```
ubuntu@ip-10-0-2-66:~$ docker logs elife-xpub_app_test_browser

> xpub-elife@1.0.0 test:browser /home/xpub
> NODE_CONFIG_ENV=test NODE_ENV=production testcafe "${BROWSER:-chrome}" 'test/**/*.browser.js' "--screenshots" "/tmp/screenshots" "--screenshots-on-fails"

clean-webpack-plugin: /home/xpub/_build/assets has been removed.
 Running tests in:
 - HeadlessChrome 71.0.3578 / Linux 0.0.0

 Submission
Type "TeamMemberMeta" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Object" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.

root@f9bd68cefa51:~# ps faxww
  PID TTY      STAT   TIME COMMAND
  450 pts/0    Ss     0:00 bash
  481 pts/0    R+     0:00  \_ ps faxww
    1 ?        Ssl    0:00 npm
   14 ?        S      0:00 sh -c NODE_CONFIG_ENV=test NODE_ENV=production testcafe "${BROWSER:-chrome}" 'test/**/*.browser.js' "--screenshots" "/tmp/screenshots" "--screenshots-on-fails"
   15 ?        Sl     0:00  \_ node /home/xpub/node_modules/.bin/testcafe chrome:headless --no-sandbox test/**/*.browser.js --screenshots /tmp/screenshots --screenshots-on-fails
   21 ?        Sl     3:16      \_ /usr/local/bin/node /home/xpub/node_modules/testcafe/lib/cli chrome:headless --no-sandbox test/**/*.browser.js --screenshots /tmp/screenshots --screenshots-on-fails
   35 ?        Sl     2:51 /usr/bin/google-chrome --remote-debugging-port=42035 --user-data-dir=/tmp/tmp-21lcy9JbFf41ye --headless --no-sandbox --disable-infobars --disable-session-crashed-bubble --no-first-run --new-window http://172.18.0.4:38831/browser/connect/9QiPhqb
   55 ?        S      0:00  \_ cat
   56 ?        S      0:00  \_ cat
   58 ?        S      0:00  \_ /opt/google/chrome/chrome --type=zygote --no-sandbox --headless --headless --enable-crash-reporter
   74 ?        Sl     8:00  |   \_ /opt/google/chrome/chrome --type=renderer --no-sandbox --use-gl=swiftshader-webgl --field-trial-handle=5163239487003863702,13403338227765113574,131072 --disable-gpu-compositing --service-pipe-token=12500788145309215154 --lang=en-US --headless --enable-crash-reporter --num-raster-threads=1 --service-request-channel-token=12500788145309215154 --renderer-client-id=2 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
   76 ?        Sl     0:00  \_ /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=5163239487003863702,13403338227765113574,131072 --no-sandbox --headless --headless --enable-crash-reporter --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --headless --enable-crash-reporter --service-request-channel-token=12943588458587203487
```

Working on specifying a fixed `remote-debugging-port` to be able to access it from outside the container (requires a browser to navigate).

**Comment by giorgiosironi** [comment]
Related (I think) error:
```
Error: listen EADDRINUSE :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Server.tryCatcher (/home/xpub/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/home/xpub/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at startServer (/home/xpub/node_modules/pubsweet-server/src/start-server.js:28:9)
    at start (/home/xpub/node_modules/pubsweet/src/startup/start.js:14:31)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xpub-elife@1.0.0 test:browser: `NODE_CONFIG_ENV=test NODE_ENV=production testcafe "${BROWSER:-chrome}" 'test/**/*.browser.js' "--screenshots" "/tmp/screenshots" "--screenshots-on-fails"`
```

**Comment by diversemix** [comment]
Would it help if I tested overnight ... by putting the browser tests into an infinite loop of testing to see if they actually hang at some point - just to rule out the code base?

**Comment by giorgiosironi** [comment]
Yes, try it on your laptop, it may help us understand if the conditions that lead to this are only verified on EC2 or also locally.

**Comment by diversemix** [comment]
Test here: #1239

**Comment by damnhipster** [comment]
Test passes, which points us toward the following expectation

> If this PR is successful (run it a number of times) then we know it is a code-infrastructure combination that is causing the current problems

To narrow down the specific commit, I'll start introducing the subsequent changes after the commit to narrow down the problematic change.

### Binary search results:

#1235
#1231 
#1232 
#1223 
#1203 
#1219 
#1217 
#1213 
#1215

**Comment by diversemix** [comment]
#NOTES
- We've agreed that the issue will not get solved in the short term.
- We are raising an PR to remove `test:browser` from the pipeline.
- We are changing the template to remind reviewers to run `test:brower` locally on that branch.
- We are putting a meeting in the calendar to discuss solving this long-term for next week.

**Comment by diversemix** [comment]
Closed by mistake

**Comment by diversemix** [comment]
After putting the replay file for hotjar into the #1229 (at build #15 see link below) it appears to be working with one exception... build #16 hangs even when it is replayed ... so I'm unsure now about whether the 'fix' is really a 'fix'

https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/activity?branch=PR-1229

**Comment by diversemix** [comment]
I seem unable to replay `Commit: 028fdee` which was successfully run as build #15 ... subsequent attempts all fail #16, #19, #22 ... although #17 does work - however that was started via the replay in the old Jenkins interface (not Blue Ocean)

**Comment by diversemix** [comment]
I'm now pretty convinced that "replay" does not work for this pipeline. This is probably an issue in itself as it would be good to be able to rebuild an historic version of the application. Nonetheless I think we can probably re-instate the `test:browser` tests. 

Bear in mind #1246 may cause hanging too as its a third party service we use in test.

**Comment by giorgiosironi** [comment]
Reopening also on the Cambridge Team board.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-xpub/pull/1251 is where the quarantined tests are being re-enabled.

**Comment by diversemix** [comment]
Closing this off - as we have done some work-rounds to put the tests back in... however the underlying problem is that of Testcafe

/cc @hdrury1
