### ISSUE TITLE
Implement validation patterns for submission form

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#124]

**Comment by NickDuf** [comment]
Some note based on validation of form inputs. Visual designs for controls and inputs to follow next week.

[xPub-initial-submission-wires-validation.pdf](https://github.com/elifesciences/elife-xpub/files/1988285/xPub-initial-submission-wires-validation.pdf)

**Comment by jsms90** [comment]
Can this issue be closed @hdrury1? I believe we have all of this validation already, as part of creating these components.
