### ISSUE TITLE
Add manuscript state to AuditLog

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1243]
When a manuscript (in the `base-model`) has a State change - this should get logged into the database `audit_log` table. This includes manuscript create and delete.

- [x] Add a "setter" for `status` onto the `Manuscript` entity in `xpub-model`
- [x] Change everywhere to use the property setter and not directly change the variable.
- [x] Change the setter for `status` to create an `AuditLog`'s log entry with appropriate params.

**Comment by damnhipster** [comment]
Setter will get called when the instance property gets changed. [See the docs.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) 

```
var language = {
  set current(name) {
    this.log.push(name);
  },
  log: []
}

language.current = 'EN';
language.current = 'FA';

console.log(language.log);
// expected output: Array ["EN", "FA"]
```

**Comment by damnhipster** [comment]
> Setter will get called when the instance property gets changed. [See the docs.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set)

Will be using an `updateStatus` function instead, as the `status` keyword is used as a property, which means we can't use `set status` since it's the same keyword.

Raised #1249 to address the issue.

**Comment by hem-brahmbhatt** [comment]
Raised #1391 to store the following details to the AuditLog: *user performing the action on the object*
