### ISSUE TITLE
Change all alerting emails to xpub-alerts@elifesciences.org

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1255]
There are now 2 new groups that you can join called: 
- `xpub-alerts@elifesciences.org` - https://groups.google.com/a/elifesciences.org/forum/?hl=en#!forum/xpub-alerts
- `xpub-tech-alerts@elifesciences.org` - https://groups.google.com/a/elifesciences.org/forum/?hl=en#!forum/xpub-tech-alerts/new

All  alerts from the application should change to the `xpub-alerts` address, so people can (un)subscribe at will (including editors)

Tasks
- Configuration change `meca.notificationEmail` to `xpub-alerts@elifesciences.org` (currently not set in production)
- All alerts from infrastructure, e.g.  NewRelic / AWS should change to `xpub-tech-alerts@elifesciences.org`

**Comment by giorgiosironi** [comment]
The current New Relic Alert policies all go to `techalerts@elifesciences.org` (generic for all services):
https://alerts.newrelic.com/accounts/1451451/channels
Probably some custom policies are needed there that target only the xpub-related services and that notify to this new address.

**Comment by giorgiosironi** [comment]
I have created a test policy for myself targeting the Apdex of `elife-xpub--prod`:
https://alerts.newrelic.com/accounts/1451451/policies/372574
Seems straightforward, but we need to replicate the 5 policies tuning them for `elife-xpub--prod`. Should pair on this to diffuse knowledge of New Relic.

**Comment by diversemix** [comment]
Sounds great - let's catch up f2f ... the main motivation for this ticket is to ensure the right level of alerts go to the right people.

**Comment by giorgiosironi** [comment]
Created two policies:
https://alerts.newrelic.com/accounts/1451451/policies/386586
https://alerts.newrelic.com/accounts/1451451/policies/386589
with notification channel xpub-tech-alerts@elifesciences.org

We need to expand the Infrastructure conditions to cover both elife-xpub--prod--1 and elife-xpub--prod--2, as only the first is covered at the moment.

The mailing list needs to be expanded to reach non-elifesciences.org people.

**Comment by giorgiosironi** [comment]
Sent two New Relic invites to @SemraSh and @jyenes, with `User` permissions.

**Comment by giorgiosironi** [comment]
I have expanded the `xpub-tech-alerts` mailing list so that everyone from YLD is now invited (admin links follows):
https://admin.google.com/u/1/ac/groups/00qsh70q2q609om/members?fc=true
https://admin.google.com/u/1/ac/groups/00qsh70q2q609om/settings?fc=true

**Comment by giorgiosironi** [comment]
We triggered a test alert (before adding people however):
![4d28e404-c77b-4eb6-98ba-7b59756db421](https://user-images.githubusercontent.com/160299/52063011-9306c900-2569-11e9-91a8-23ed8618911f.png)
