### ISSUE TITLE
MECA Failure Modes Specification

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1257]
Write a specification for failure modes in different circumstances for Clara.

/cc @hdrury1

**Comment by hdrury1** [comment]
Import into eJP should fail if any of the following is missing from article.xml. This means there is potentially a problem with xPub exporter, as this information is required in the submission wizard:

- article_type
- keywords
- article-title
- author surname
- author given-names
- author email
- author affiliation

Import should also fail if any of the files listed in manifest.xml are not present in the zip package. This includes the disclosure form.

**Comment by diversemix** [comment]
The only thing to add from a technical point of view is that if the import software fails in anyway then it must do best endeavour to send the failure message (for example handling exceptions to report failure)

**Comment by diversemix** [comment]
We've responded with this to Clara ... and are awaiting a response

**Comment by diversemix** [comment]
Clara has responded - this needs more funding ... so is now a financial issue. Closing off... @hdrury1 should we create another ticket to track the progress and test the implementation of the failure modes? 

/cc @BlueReZZ
