### ISSUE TITLE
Investigate: Not all affiliations are shown on the person pod

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1259]
Where a person's affiliation(s) run over more than one line in Journal CMS, only the first line is being pulled into the Person Pod.

Journal CMS:

![screen shot 2019-01-08 at 11 08 27](https://user-images.githubusercontent.com/17023702/50827217-cde45b00-1335-11e9-8c58-1a646e0fb354.png)

xPub:

![screen shot 2019-01-08 at 11 09 20](https://user-images.githubusercontent.com/17023702/50827250-de94d100-1335-11e9-85a0-8e11d15298a2.png)

Expected behaviour:

Full affiliation should be pulled into the Person Pod, with line separation maintained.

see https://elifesciences.slack.com/archives/C6MJK1RD4/p1546880024000100

**Comment by chugginselifesciences** [comment]
@hdrury1 @acollings Can we confirm the decision here is to show full affiliation in the modal (which may wrap onto more than 2 lines). See 2nd image

But we will only show the affiliation on a single line in the person pod. And in this case we would show the different aspects/lines of the affiliation with a comma separating them if there is room. See 1st image.

**Person pod** 

![image](https://user-images.githubusercontent.com/41907215/50829158-75b05780-133b-11e9-9151-1e31ebdd2f56.png)


**Modal (seen by pressing 'i' button)**

![image](https://user-images.githubusercontent.com/41907215/50829066-2cf89e80-133b-11e9-9d95-0b910c6b1097.png)

**Comment by hdrury1** [comment]
@chugginselifesciences Yes, that seems like a sensible solution.

**Comment by acollings** [comment]
@chugginselifesciences sounds good. However, I wonder if there's something else going on with Howard Hughes Medical Institute, beyond truncation? For Sean Morrison, for example, the affiliation on xPub is Howard Hughes Medical Institute, but on the journal website (which is correct) it's Howard Hughes Medical Institute, University of Texas Southwestern Medical Center. xPub seems to be missing University of Texas Southwestern Medical Center altogether, even on the modal. (NB: on the person pod I would expect this to be truncated with ...)

**Comment by hdrury1** [comment]
@chugginselifesciences My understanding is that xPub is only pulling in the first line of any author's affiliation, so for those funded by HHMI, this is the only affiliation appearing.

Please note that I have now updated Journal CMS so that HHMI is the second affiliation listed- this way, their primary institution will always appear before the ellipsis in the  Person Pod.
