### ISSUE TITLE
Sort Person Picker by last name

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1260]
(see https://elifesciences.slack.com/archives/C6MJK1RD4/p1546880321000500 )

**Comment by diversemix** [comment]
Do we want to do this given we want to be culturally agnostic and just store `name` in the future?

/cc @hdrury1 @acollings

**Comment by acollings** [comment]
I think we should be consistent with the journal site in the short term, https://elifesciences.org/about/people/biochemistry-chemical-biology, https://elifesciences.org/about/people/cancer-biology and so on. I also think we're a long way from being able to support "name" (given the importance of PubMed), so in the meantime, having an order that's recognisable would be very helpful.

**Comment by Cooryd** [comment]
@hdrury1 currently the people api returns a single value of `name` which holds the persons full name. This is easy to order by and appears on the app as though we are sorting by first name but in reality we are just sorting by the whole `name` string. To sort by last name we would need to split this `name` string by empty spacing and use the last value found. An expensive process when fetching 400+ people in one request but may be feasible. Thought I'd check before going through with the work.
