### ISSUE TITLE
Server Hardening

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1267]
Just having a look through the logs in staging ... there seems to be times when we are getting probed by script kiddies. Might be worth installing `fail2ban` or equivalent. See attachment

[requests.txt](https://github.com/elifesciences/elife-xpub/files/2737216/requests.txt)

**Comment by damnhipster** [comment]
> They're onto us, ABORT ABORT

**Comment by giorgiosironi** [comment]
We could probably block incorrect hostnames in nginx (allowing `localhost` and `[*--]xpub.elifesciences.org` only).
