### ISSUE TITLE
Add filename to <title> tag in article.xml

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1268]
In order to populate the file title field in eJP, we will need to modify our export code to pull the filenames of any supporting files into article.xml prior to export.

See https://elifesciences.slack.com/archives/CDAD612MT/p1546969495017900

**Comment by hdrury1** [comment]
From an end user point of view, this will enable staff/editors to see the following in eJP:

![image](https://user-images.githubusercontent.com/17023702/50893397-a7d3bf00-13f8-11e9-8c73-2b7a80115ca9.png)

**Comment by diversemix** [comment]
Depends on #1164

**Comment by diversemix** [comment]
Done as part of #1164 

/cc @hdrury1 - we should probably check this when #1164 gets deployed to staging,
