### ISSUE TITLE
Make static assets work with styleguide

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#127]
Right now static assets (such as icons) are loaded in the app from the assets directory (e.g. `/assets/elife-icon-cross.svg`). This is a runtime thing and it's not actually where they live (they are located in `/static/`). This makes styleguide unable to load them.

One solution to this would be to reference assets without using the extra `assets` directory, but for some reason `app.use(express.static(path.resolve('.', '_build', 'assets')))` doesn't seem to work. If it's possible to do this, then we just need to add `assetsDir: "static"` in `styleguide.config.js`.

Another solution would be to place the static files in the `_build` directory when webpack does its things (not entirely sure how this works).

**Comment by hdrury1** [comment]
Closing this down as obsolete.
