### ISSUE TITLE
Manuscript upload doesn't show new file when replacing existing file

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1284]
**Steps to reproduce:**

*We've only managed to reproduce this on Peter's machine. It seems to cause/be caused by two manuscript sources in the database for that submission*

1. Start a new submission
2. Upload a manuscript file
3. Go back and replace the manuscript file with a different one
4. Go back to the upload page
5. The filename is still the first uploaded file

**Comment by damnhipster** [comment]
We're unable to reproduce this consistently, and as it's only ever occurred on @diversemix local machine so far, this is being left in the backlog.

**Comment by diversemix** [comment]
No longer an issue on my machine ... however it could have been #1310
