### ISSUE TITLE
Change sciencebeam config to not use real endpoint

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1287]
The app is configured to use [the real Sciencebeam API by default](https://github.com/elifesciences/elife-xpub/blob/develop/config/default.js#L121)

This is misleading as we currently host sciencebeam ourselves alongside xpub and use that instance instead of the real one.

- [ ] change default sciencebeam URL within `config/default.js` to refer to a local URL instead.
- [ ] update test config to use appropriate URL, and update replay mocks
- [ ] ensure we can run the application locally
  - [ ] add the sciencebeam image to `docker-compose`
  - [ ] update `yarn start:services` to start the sciencebeam container
- [ ] ensure review environments and staging work correctly
  - [ ] sciencebeam should be added to the [pod definition for review environments](https://github.com/elifesciences/elife-xpub-formula/blob/master/helm/elife-xpub/templates/deployment.yaml#L44),as per [@giorgiosironi's suggestion](https://github.com/elifesciences/elife-xpub/issues/1287#issuecomment-453938846)
  - [ ] test the title extraction within the environments after the change has been made

**Comment by giorgiosironi** [comment]
At this point sciencebeam should be added to the [pod definition for review environments](https://github.com/elifesciences/elife-xpub-formula/blob/master/helm/elife-xpub/templates/deployment.yaml#L44) so that they can continue using it.

**Comment by diversemix** [comment]
Not necessary... as they will be using the mocks recorded by replay

**Comment by hem-brahmbhatt** [comment]
> Not necessary... as they will be using the mocks recorded by replay

Review environments don't use replay, only tests do. Review environments are started with `NODE_ENV_CONFIG=ci`.
