### ISSUE TITLE
Sciencebeam does not keep logs

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1288]
Unlike xPub ... sciencebeam does not have an option to log to a file so they can be stored outside of the container (mounted volume on host)... This means when the container dies the logs die too :(

Talked with Daniel about this and it should be straightforward for him to do at some point.

**Comment by de-code** [comment]
Summoning @giorgiosironi - what is the best practice regarding container logs. I can easily add an option for ScienceBeam to log to a file / directory that is then mounted. Who is then responsible for keeping the logs for 30 days? The ScienceBeam logging config or another process that monitors the logging volume?

Do we need something like Loggly integration? Does ScienceBeam need to output it's logging in a particular format? What about other logs within the ScienceBeam container? (e.g. _syslog_)

WIth Kubernetes & Co, is the logging volume the best practice or are there other ways to do it? Can we just configure it at the Docker level to keep or redirect it's logs? (which could then easily be applied to other containers). (Could discuss in person next week)

**Comment by giorgiosironi** [comment]
> I can easily add an option for ScienceBeam to log to a file / directory that is then mounted. Who is then responsible for keeping the logs for 30 days? The ScienceBeam logging config or another process that monitors the logging volume?

`logrotate` on the host, assuming it's running on EC2 which is the only supported choice at the moment

> Do we need something like Loggly integration?

It's also taken care at the host level by `syslog-ng`, which tails a file and uploads it.

> Does ScienceBeam need to output it's logging in a particular format? 

[JSON Lines](http://jsonlines.org/) (simpler than it sounds) is ideal, because then the log aggregator can parse the lines and offer filters on the fields.

> What about other logs within the ScienceBeam container? (e.g. syslog)

Shouldn't be there or of interest, syslog is usually implemented with a daemon that is not around in the container. Nginx is a different container, etc.

> WIth Kubernetes & Co, is the logging volume the best practice or are there other ways to do it? Can we just configure it at the Docker level to keep or redirect it's logs? (which could then easily be applied to other containers). (Could discuss in person next week)

There are many possible choices but it usually boils down to:

- log on stderr and let Kubernetes nodes be configured to aggregate all of that somewhere
- log on a volume and have a sidecar container asynchronously upload that to an aggregator (exactly what syslog-ng does with the EC2-based implementation)

**Comment by de-code** [comment]
Could we spec a bit what the JSON should look like? e.g. what attributes?

And what logging we expect to see in there at the minimum (which may not currently be logged to the console).

**Comment by giorgiosironi** [comment]
There's no organization-wide logging standard but some fields are common:
- `datetime`: `2019-01-01T00:00:00+0000`
- `level` (`INFO`, `ERROR`, etc)
- `message` (arbitrary string)

**Comment by de-code** [comment]
I guess we also want or consider:

- `app`: `sciencebeam`
- is the module interesting? (e.g. `sciencebeam.utils`)
- what about access log relevant information, like start time or how long it took, status code etc?
- that could also be logged for client requests (e.g. from `sciencebeam` to `GROBID`)

**Comment by giorgiosironi** [comment]
> app: sciencebeam
> is the module interesting? (e.g. sciencebeam.utils)

Yes, these two are generic fields that are interesting

> what about access log relevant information, like start time or how long it took, status code etc?
> that could also be logged for client requests (e.g. from sciencebeam to GROBID)

These are specific to particular logs (receiving or performing requests), but what you describe is reasonable.

> like start time

That should be covered by the generic `datetime` field of the "attempting request" log line.
