### ISSUE TITLE
Investigate how xpub can search EJP data.

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#129]
During the transition from using EJP to xpub it will be necessary to search the data in EJP. The search will need to be done to look for manuscripts that have been considered previously.

See: https://elifesciences.slack.com/archives/C6LKMFK5Z/p1525419788000331

References:
#42 
#50

**Comment by hdrury1** [comment]
Closing as this will likely be superseded by integration with Libero DataHub.
