### ISSUE TITLE
Add persistent volume to deployments for DARs

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#130]
The `dar-server` package stores its data on the filesystem. We will probably implement our own version in future that uses Postgres but for now we need a folder on the deployments in which to store the manuscripts.

**Comment by g-sam** [comment]
Waiting on https://github.com/elifesciences/elife-xpub/issues/115 for testing. See the [comment](https://github.com/elifesciences/elife-xpub/issues/115#issuecomment-388841161) there.

**Comment by tamlyn** [comment]
@g-sam can you remind me how to set this up and test it?

**Comment by diversemix** [comment]
@g-sam @tamlyn Documentation alert! :)

**Comment by diversemix** [comment]
No longer applicable - not using Texture
