### ISSUE TITLE
Supplementary Files with the same name get overwritten in the MECA zip

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1308]
**Describe the bug**

Files are added to the MECA zip as the name they are given when uploaded. This means that files with the same name are overwritten and so the export generates a bad zip file.

**Steps To Reproduce**

Upload supplementary files with the same name

**Expected behavior**

Not sure - should we prevent same name files being uploaded? or uniquely tag them in the zip?

**Comment by diversemix** [comment]
@hdrury1 ... can we get this into todo :pray:

**Comment by hdrury1** [comment]
Now that we're addressing #1383 will this still be a problem? It's expected behaviour that a file with the same name will overwrite an existing file... or is there an actual error with generating the package?

**Comment by diversemix** [comment]
Superceded by #1383
