### ISSUE TITLE
Create production-ready DAR server

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#131]
As a stopgap, we are using the example DAR express app which stores manuscripts on the filesystem, and deploying this app as a plugin to PubSweet.

We should make the DAR server deployable separately and use a database as the storage backend.

**Comment by g-sam** [comment]
As a stopgap, we are using the example DAR express app which stores manuscripts on the filesystem, and deploying this app as a plugin to PubSweet.

We should make the DAR server deployable separately and use a database as the storage backend.

**Comment by hdrury1** [comment]
@damnhipster and @diversemix is this still a to-do?

**Comment by tamlyn** [comment]
Yeah, Texture view has been removed and I'm removing the DAR file generation as part of #520 (since the existing DAR server doesn't work with S3).

**Comment by hdrury1** [comment]
So... close?

**Comment by damnhipster** [comment]
Closed.
