### ISSUE TITLE
Fix error occurring when logged in user not found in DB

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#132]
Client needs to delete token from localStorage and redirect to login if the user is not found.

**Comment by tamlyn** [comment]
I'm not sure whether this is really a bug. If the currently logged in user doesn't exist in the database then, outside of the context of development and testing, something has gone very wrong. Is silently redirecting to the login page the right response?

**Comment by diversemix** [comment]
@tamlyn @g-sam ... I agree with Tam, this is possibly just a testing issue, and redirecting to the login page may just be postponing the error. I'm going to close this and we can always raise another ticket if/when it becomes an issue.
