### ISSUE TITLE
Fix input min height including validation

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1323]
**Describe the bug**
Often when validation errors are shown in a form the height of the component increases, which causes content below to jump. Space needs to allow for validation text by default to avoid this.

![image](https://user-images.githubusercontent.com/41907215/51382019-96cc3180-1b0d-11e9-9ed9-2d71ec528c58.png)

**Comment by hdrury1** [comment]
Closing in favour of #1415
