### ISSUE TITLE
Should we select "Research article" by default?

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1329]
To reduce the likelihood of validation errors from users failing to make a selection/enter data, can we increase the amount that we use default values? This could also reduce effort for users when we have an obvious "most commonly used" option.

Do we have some data to support this?

**Current:** 

![image](https://user-images.githubusercontent.com/41907215/51383638-e876bb00-1b11-11e9-9177-a176a2a29e38.png)

**New default option?**

![image](https://user-images.githubusercontent.com/41907215/51383701-165bff80-1b12-11e9-9a42-dfd9675269c3.png)

**Comment by hdrury1** [comment]
Closing this out until we have clear evidence that it would improve user experience.
