### ISSUE TITLE
Fix intermittent browser test failures in CI

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1337]
Our build on Jenkins seem to be failing intermittently with the following output:

https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1326/8/pipeline#step-68-log-108

We've added some more logs in https://github.com/elifesciences/elife-xpub/pull/1326, where we concluded the following:

- Outbound server-side requests are intercepted and mocked using replay
- The output suggests sciencebeam failed. The logs show that replay successfully mocked the sciencebeam response
- No other outbound network requests were intercepted which hadn't been mocked

**Comment by diversemix** [comment]
Weird deadlock  - https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1478/1/pipeline/

**Comment by diversemix** [comment]
Closing this as everything appears fine now. The references to pipelines are now dead - so I suggest if anything else raises its head we create a new ticket
