### ISSUE TITLE
Remove "corresponding author" checkbox from author details page

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#134]
Wireframes 002-003 to be replaced with.... ![wizard-screen-1](https://user-images.githubusercontent.com/12328191/40120793-fdbe903a-5917-11e8-8e4f-76a2ccf31c59.png)

+ [ ] Remove checkbox from author details page component
+ [ ] Data structure on the graphql scheme needs to be updated to reflect the removal of this item

**Comment by gmaciocci** [comment]
Name, email, institution fields are also now editable.

**Comment by jsms90** [comment]
As I understand it, the removal of this checkbox is an attempt to reduce clutter & streamline the form filling process? Because the original wireframes include entry of 2 sets of information, when we only need to keep one:
![image](https://user-images.githubusercontent.com/15656538/40126504-615d4a02-5925-11e8-9343-31927717afca.png)

But questions have been raised about whether this change to the wireframes is sufficiently catering for the needs of a Secretary (or someone else), who is entering this information on behalf of an author.

The suggestion is that, by pre-populating these fields with the Secretary's data, they may simply see that their details are correct & continue filling out the form, without registering that they were supposed to replace this with the author's details instead.

How about leaving these fields blank by default & introducing a **fill in with orcid** button, which only then populates the fields with the orcid data? This would satisfy the needs of both sets of users, without increasing the likelihood of errors.

**Comment by NickDuf** [comment]
@jsms90 we think your idea makes sense. I am just updating my designs to make sure everyone is onboard.

**Comment by jsms90** [comment]
@NickDuf Ah right. Cool! :+1:

**Comment by g-sam** [comment]
Just to confuse things further, an alternative is something along the lines of an *I am not the corresponding author* checkbox/button that would clear the prepopulated data.

As I understood your thinking, you wanted to reduce the clicks for the majority of users, but presumably the majority will want to use ORCID to populate the data

**Comment by g-sam** [comment]
A third suggestion on Jen's model is a **I am the corresponding author** checkbox that causes the ORCID data to be pulled in.

**Comment by NickDuf** [comment]
Cheers @jsms90 . I shared a similar idea this morning. The preferred approach came out as starting with clear fields and then populating though.

**Comment by jsms90** [comment]
Ah ok. So we are starting out with clear fields, when a user first navigates to that page?

In which case, what will cause the population of those fields?
A button, as I was suggesting? Or a checkbox, as Sam suggests? Or perhaps there's another idea we haven't thought of?

**Comment by diversemix** [comment]
@NickDuf .. will you be updating the wireframes?

**Comment by NickDuf** [comment]
Here is a link to the updated designs including notes. https://docs.google.com/document/d/1cK158VrGlYRVZfA2vJrMNrUY6QYvtdC-jo0-SUvtBN4/edit?usp=sharing

**Comment by hdrury1** [comment]
Following yesterday's discussions on this wireframe what I'd like to do is get it implemented as-is, and get it in front of some users. Any further iteration should be in response to results from said testing.

**Comment by hdrury1** [comment]
@tamlyn Are there any updates on where this is at?

**Comment by diversemix** [comment]
@jsms90 Is the code for this merged yet?

**Comment by hdrury1** [comment]
Moving to 'Blocked' while @tamlyn is away.

**Comment by tamlyn** [comment]
Sorry, I forgot to post a link to the MR https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/69

This was merged week before last.
