### ISSUE TITLE
Add validation state for supporting file that is too large

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1367]
**Describe the bug**
When attempting to upload an invalid file, e.g. one more than 100MB, there is no indication why it cannot be uploaded. The file manager closes with the UI unchanged.

**Steps To Reproduce**
1. Navigate to the file page.
2. Upload a manuscript successfully.
3. Click the link to upload supporting file(s).
4. Observe that file manager closes with no file added.

**Expected behavior**
We should feed back to the user that the file they have attempted to upload is invalid. They should then be able to clear this validation message by deleting the item from the list.

Design:

![screen shot 2019-01-22 at 12 46 23](https://user-images.githubusercontent.com/17023702/51536622-204c6e00-1e44-11e9-8adb-781816a06281.png)

We should cap the number of items displayed to the user at 10, regardless of whether the items are valid or invalid.

The user should be able to continue through the wizard while invalid files are listed.

The user can also re-upload a file with the same name to override the error. (<- How difficult is this techinically? We could potentially drop for launch)

**Comment by diversemix** [comment]
@hdrury1 / @chugginselifesciences ... are we implementing the trash icon as part of this?
> They should then be able to clear this validation message by deleting the item from the list.

**Comment by hdrury1** [comment]
Please note that for MVP we will not be introducing the trash icon. I'll raise a new ticket to add this additional functionality post-release.
