### ISSUE TITLE
Introduce status on to File entity

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1373]
Need to have a status on a file to determine that its being uploaded, and in the future if its been deleted.
This ticket is to add this to a new migration and also to the mode class of `File`. At the moment this should contain three states:
- `CREATED`
- `UPLOADING`
- `UPLOADED` 
- `CANCELLED`

The default should be `CREATED`

Part of #1362

**Comment by hem-brahmbhatt** [comment]
I think `UPLOADED` is clearer than `PRESENT`

**Comment by hem-brahmbhatt** [comment]
It may be better to keep this within a `upload_status` column instead of a `status` column

**Comment by diversemix** [comment]
@damnhipster  
:+1: for `UPLOADED` will change it
:-1: for rename, as we could have a `TRANSFERRED` state if it were to come from a different journal so `uploaded_status` seems to constrain the use of the `status` - what do you think?

**Comment by hem-brahmbhatt** [comment]
I'm not sure about the status of a *File* as a concept. It's something you would have on a *Manuscript* (submission) which would step through multiple statuses on it's journey, but a *File* wouldn't behave in that way except for the upload journey.

I think it would be better to constrain the use of the column to a specific descriptor. This would mean adding a new column to describe attributes such as where the file originated from, and having a separate column for it's uploaded status.

**Comment by diversemix** [comment]
I'm currently working on the status (life-cycle) of a file of being:
`CREATED -> UPLOADED -> STORED or CANCELLED`

I think it's entirely correct that a File has its own status outside that of its containing Submission. This way we can add this to the AuditLog too and monitor the lifecycle of an individual file.

**Comment by diversemix** [comment]
@damnhipster / @Cooryd
