### ISSUE TITLE
Update playbook with how to restore the database from a snapshot

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1375]
Going to be done by @giorgiosironi as the repo might get renamed

**Comment by giorgiosironi** [comment]
Testing out a snapshot on a new server, from https://console.aws.amazon.com/rds/home?region=us-east-1#snapshot:engine=postgres;id=rds:elife-xpub-staging-2019-01-29-03-30

**Comment by giorgiosironi** [comment]
Instance being created at https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=elife-xpub-staging-restore-test;is-cluster=false

**Comment by giorgiosironi** [comment]
Instance ready, trying to generate a `pg_dump` of it.

**Comment by giorgiosironi** [comment]
Either I copied the wrong hostname or there are some visibility problems between subnets:
```
pg_dump: [archiver (db)] connection to database "elife-xpub-staging-restore-test" failed: could not connect to server: Connection timed out
        Is the server running on host "elife-xpub-staging-restore-test.cxyopn44uqbl.us-east-1.rds.amazonaws.com" (10.0.4.4) and accepting
        TCP/IP connections on port 5432?
```

**Comment by giorgiosironi** [comment]
The [security group](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#SecurityGroups:search=sg-e4a1de81;sort=groupId) seems to allow only traffic from inside the security group. It seems an old one so I'll detach it, must be some default.

**Comment by giorgiosironi** [comment]
Changed to `elife-xpub-staging-VPCSecurityGroup-16L6J45AL7U4W`. This needs better automation.

**Comment by giorgiosironi** [comment]
```
#!/bin/bash
set -e

docker run \
    -e PGHOST=elife-xpub-staging-restore-test.cxyopn44uqbl.us-east-1.rds.amazonaws.com \
    -e PGPORT=5432 \
    -e PGUSER=$PGUSER \
    -e PGPASSWORD=$PGPASSWORD \
    -e PGDATABASE=elifexpubstaging \
    postgres:10 \
    pg_dump
```
got me a dump:
```
elife@staging--xpub:~$ ls -l /ext/tmp/dump.log 
-rw-rw-r-- 1 elife elife 697369 Jan 29 13:02 /ext/tmp/dump.log
```

**Comment by giorgiosironi** [comment]
The `directory` format is better as it's compressed by default and can be restored both while dropping or not dropping the existing tables:
```
#!/bin/bash
set -e

docker run \
    -e PGHOST=elife-xpub-staging-restore-test.cxyopn44uqbl.us-east-1.rds.amazonaws.com \
    -e PGPORT=5432 \
    -e PGUSER=$PGUSER \
    -e PGPASSWORD=$PGPASSWORD \
    -e PGDATABASE=elifexpubstaging \
    -v /ext/tmp/:/ext/tmp \
    postgres:10 \
    pg_dump -Fd -f $@
```

**Comment by giorgiosironi** [comment]
Restore command worked for me, destroying my freshly created submissions:
```
#!/bin/bash
set -e

docker run \
    -e PGHOST \
    -e PGPORT \
    -e PGUSER \
    -e PGPASSWORD \
    -v /ext/tmp/:/ext/tmp \
    postgres:10 \
    pg_restore -c -d "$PGDATABASE" -Fd $@
```
Some warning however:
```
elife@staging--xpub:~$ ./restore.sh /ext/tmp/dump/
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3987; 0 0 COMMENT EXTENSION plpgsql 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
pg_restore: [archiver (db)] Error from TOC entry 3988; 0 0 COMMENT EXTENSION pgcrypto 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension pgcrypto
    Command was: COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
WARNING: errors ignored on restore: 2
```
Will now put scripts in the formula for deployment.

**Comment by giorgiosironi** [comment]
What?
```
An error occurred (InsufficientDBInstanceCapacity) when calling the RestoreDBInstanceFromDBSnapshot operation: Cannot create a db.t2.small database instance because there are no availability zones with sufficient capacity for non-VPC and storage type : gp2 for db.t2.small. Please try the request again at a later time.
```
Why non-VPC, since it should be in the default security group. Maybe that security group is out of the VPC then.

**Comment by giorgiosironi** [comment]
Better when specifying the subnet group, which is then mandatory for creation I guess. The security group has to be specified after creation instead.

**Comment by giorgiosironi** [comment]
In review with:

- https://github.com/elifesciences/elife-xpub-formula/pull/69
- https://github.com/elifesciences/elife-xpub/pull/1412
