### ISSUE TITLE
Over-write supporting files with the same name

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1383]
If a user uploads a second file with the same name as the first, the second file should override it in the database (currently we allow for multiple files with the same filename to be stored, but this does not persist through to export).

On the front end, rather than displaying both the first and second file in the list of uploaded files, only the second would be displayed to the user.

subtask:
- [x] return the id on the upload mutation (#1424)
- [ ] multiple supporting file uploads in parallel (#1449)

**Comment by hem-brahmbhatt** [comment]
Moved into backlog until #1449 is done.

**Comment by diversemix** [comment]
@damnhipster ... could you update with the text you put in Slack please?

**Comment by hem-brahmbhatt** [comment]
> @damnhipster ... could you update with the text you put in Slack please?

We've decided to park this issue. Instead, we thought it's better to do the work after we've refactored the code in #1449 to support multiple parallel uploads.

It should be easier to do this after we've refactored, and we won't have to write this feature two times (once now and once after refactor).
