### ISSUE TITLE
Investigate: link in notification email pointing to localhost:3000

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1385]
**Describe the bug**
The link embedded in a user's notification email enabling them to re-access their dashboard was found to point to localhost:3000. We need to check that the email is configured correctly.

![image](https://user-images.githubusercontent.com/17023702/51617375-01bda400-1f24-11e9-9076-1801a54baa46.png)

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-xpub/blob/8fef310dc7b698ba6cc3db7897ac19e801511a01/server/xpub-controller/notification.js#L54-L61 is the reference where this is passed to the email templates.

**Comment by giorgiosironi** [comment]
However:
```
elife@staging--xpub:~$ docker exec -it xpub_app_1 bash
root@44a9e2e7ddff:~# env | grep PUBSWEET_BASEURL
PUBSWEET_BASEURL=https://staging--xpub.elifesciences.org
```

**Comment by giorgiosironi** [comment]
Read in by:
https://github.com/elifesciences/elife-xpub/blob/e93757368b3a72885af8743f22a819e7a0b62d87/config/custom-environment-variables.js#L11
and considering the upstream example:
https://gitlab.coko.foundation/search?utf8=%E2%9C%93&snippets=&scope=&search=baseUrl&project_id=61
I think we should change `base_url` to `baseUrl`, the former is probably null/undefined and then defaults to `localhost:3000`. Null check to be added too?

**Comment by hdrury1** [comment]
Also hard-coded to `base_url: 'http://localhost:3000',` in `default.js` (which may or may not be relevant)...
