### ISSUE TITLE
Use EKS in deployment

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#139]
We can sign up for a preview here: https://pages.awscloud.com/amazon-eks-preview.html

**Comment by giorgiosironi** [comment]
We already signed up, but likely won't get it until it is into General Availability.

**Comment by diversemix** [comment]
@g-sam Is there a question of whether or not we use k8s for now - we can do this later ... What would be good is to actually begin to get this app deployed in a production-like way.

**Comment by diversemix** [comment]
Is it separate ticket to break down the server side components into their own containers?

**Comment by tamlyn** [comment]
K8s makes per-branch deployments possible (or, at least, easier). For persistent deployments like staging and production, you're free to use something else (as I understand it, running production databases in K8s is actively recommended *against*). It probably makes sense to use the Docker images we are building in CI as these have been tested.

**Comment by tamlyn** [comment]
Oh, also I don't think there's any further breaking down to do. The Node app is monolithic at runtime despite being composed of multiple components at build time. 

The current backing services (Postgres and ScienceBeam) are already separate containers. Once we introduce a job queue there will be a need for worker processes and these would run in separate containers in production.

**Comment by hdrury1** [comment]
Can I close this @diversemix ?

**Comment by diversemix** [comment]
Yes, I will close this for now. This is certainly a future (post first release) thing. Now we are become part of the eLife deployement strategy I think this will be dictated by the likes of @giorgiosironi and the wider tech team. This also might be driven when we adopt the current pipelines from YLD onto eLife infrastructure - but that is a different issue.
