### ISSUE TITLE
Investigate Andy's missing article files

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1394]
Point (2) from Andy : https://elifesciences.slack.com/archives/C6MJK1RD4/p1548361250003700

> 24-01-2019-EC-eLife-02129, 24-01-2019-ISRA-eLife-02125, 24-01-2019-ISSR-eLife-02126, and 24-01-2019-ISTR-eLife-02127 were all imported into eJP without the article file I'd uploaded! Not sure why? (The article file for 24-01-2019-ISSC-eLife-02128 did make it across.)

**Comment by diversemix** [comment]
## 24-01-2019-EC-eLife-02129
First missing article file is related to xPub id: `36a712ac-0417-4e70-aa58-ed5bc87a8fff`
The package seems to correctly identify (and contain) the file:

```  
    <item id="xpub-123" type="manuscript" submission-item-id="custom003" version="0">
        <title>Article File</title>
        <description>Article File</description>
        <filename>10-05-2017-RA-eLife-28507R1.docx</filename>
        <file-order>1</file-order>
        <instance media-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" href="10-05-2017-RA-eLife-28507R1.docx"/>
    </item>
```

**Comment by diversemix** [comment]
## 24-01-2019-ISRA-eLife-02125
xPub id: `e40e0293-2132-410c-bead-870ad747e095`
Also is correctly specified in the manifest:
```

    <item id="xpub-123" type="manuscript" submission-item-id="custom003" version="0">
        <title>Article File</title>
        <description>Article File</description>
        <filename>Bray 41637.docx</filename>
        <file-order>1</file-order>
        <instance media-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" href="Bray 41637.docx"/>
    </item>
```
However it has also been uploaded as a supporting file ... this has messed up the import...
```
    <item id="4ea399b3-238b-4a94-9638-8851634d22f7" type="supplemental" submission-item-id="4ea399b3-238b-4a94-9638-8851634d22f7" version="0">
        <title>Bray 41637.docx</title>
        <description>Bray 41637.docx</description>
        <filename>Bray 41637.docx</filename>
        <file-order>1</file-order>
        <instance media-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" href="Bray 41637.docx"/>
    </item>
```

**Comment by diversemix** [comment]
## 24-01-2019-ISSR-eLife-02126
xPub id: `d7fffd0b-e3c4-4ec7-aa79-ce6599dd0cf2`

Again this is correctly specified and contained within the package:
```
    <item id="xpub-123" type="manuscript" submission-item-id="custom003" version="0">
        <title>Article File</title>
        <description>Article File</description>
        <filename>Nowak elife 2018.docx</filename>
        <file-order>1</file-order>
        <instance media-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" href="Nowak elife 2018.docx"/>
    </item>
```

**Comment by diversemix** [comment]
## 24-01-2019-ISTR-eLife-02127
xPub id: `0010e7a3-9150-403f-bf24-4653fa88c782`

Again this is correctly specified and contained within the package:

```
    <item id="xpub-123" type="manuscript" submission-item-id="custom003" version="0">
        <title>Article File</title>
        <description>Article File</description>
        <filename>Gaffield_etal_revision3.docx</filename>
        <file-order>1</file-order>
        <instance media-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" href="Gaffield_etal_revision3.docx"/>
    </item>

```

**Comment by diversemix** [comment]
@acollings / @hdrury1 ... This looks like an issue with eJP - the have been reported as successfully imported (another false positive). There does seem to be at least 2 issues, 
- one being where the same file is uploaded as the manuscript and a supporting file. 
- the second being not importing the article file at all.

**Comment by hdrury1** [comment]
The non-imported article files I will raise with Clara to investigate her end. The same file messing up the import presumably is an issue with our code?
