### ISSUE TITLE
Reinstate vertical centring of login page content

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1398]
**Describe the bug**
In the past the content of the login/continue page was vertically centred. It no longer appears to be, and the spacing below 768px is non-existent.

This is likely the result of the work done to fix #980 where the content was overlapping the app bar on very short and wide browser size.

The vertical centring should be reinstated, without again causing the content to overlap the app bar again.

![image](https://user-images.githubusercontent.com/41907215/51830705-642df000-22e8-11e9-9bf8-5e73b200ccb7.png)

![image](https://user-images.githubusercontent.com/41907215/51830751-7c9e0a80-22e8-11e9-8fa1-76d98ed89f9c.png)

![image](https://user-images.githubusercontent.com/41907215/51830833-ad7e3f80-22e8-11e9-928a-1b53f0ad0496.png)

**Comment by hdrury1** [comment]
Going to close this given new layout requirements in #1575
