### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#141]

**Comment by hdrury1** [comment]
@tamlyn Presumably this component was never made as #132 was closed?

**Comment by tamlyn** [comment]
Correct, this is still to do.

**Comment by hdrury1** [comment]
@NickDuf WOuld it make sense to re-use the assets from the website?

**Comment by diversemix** [comment]
@hdrury1 ... this is still do to before release, and maybe `50x` pages too

**Comment by Cooryd** [comment]
There now seems to be a 404 error page in the router however we could do with a generic error page to redirect to when things go wrong. ie: AppBar fetches the current user, if this query were to return an `Error` it would be useful to redirect to a page with none of the layout components and a suitable error message.
