### ISSUE TITLE
Cover letter/text editor validation styling fixes

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1411]
In addition to the text editor button states described in #462, the text editor validation state should be updated for consistency with other input component validation states.

**Currently validation text appears 18px below the component.**

![image](https://user-images.githubusercontent.com/41907215/51924067-404fd480-23e4-11e9-9bd7-866de5812c3a.png)

The validation text should instead be shown 12px below, and the component 1px border should turn `colorError`when in an error state.

![image](https://user-images.githubusercontent.com/41907215/51924301-accad380-23e4-11e9-966e-3a27ee53c341.png)

**Comment by hdrury1** [comment]
Closing as obsolete.
