### ISSUE TITLE
Update Text Editor/cover letter input to include additional buttons and responsive behaviour

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1413]
In addition to updating the text editor button styles (#462), we should aim to include controls to add bulleted and numbered lists, and to increase/decrease indents.

@hdrury1 this is based on design work before I started. I am assuming the decision was to keep things simpler short term, but include these additional controls later, which is why I'm adding the ticket now. Please let me know if the decision was in fact to never include them.

For smaller screens, an overflow container would be ideal. If not feasible buttons could wrap onto a second row.

![image](https://user-images.githubusercontent.com/41907215/51926774-f669ed00-23e9-11e9-8852-7825d04fe98b.png)

Button styles:

![image](https://user-images.githubusercontent.com/41907215/51926816-0eda0780-23ea-11e9-9ce5-a5a0205bf957.png)

**Comment by chris-huggins** [comment]
Note: related to #251

**Comment by hdrury1** [comment]
Closing as obsolete.

**Comment by chris-huggins** [comment]
@hdrury1 By obsolete do you mean we will never intend to add bullets, numbered lists or indentation?
