### ISSUE TITLE
Review authenticate-fixture.js

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#142]
It appears this tests the `pubsweet-server/src/authentication` mechanism, which is one we do not use in the code. Perhaps we should remove it?

**Comment by g-sam** [comment]
This doesn't test anything, just does setup and teardown. It's badly named and probably needs refactoring though.

**Comment by hdrury1** [comment]
@diversemix is this still in the codebase? Worth looking at as part of the refactor?
