### ISSUE TITLE
Check production configuration for email

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1430]
Check config `baseUrl`

**Comment by giorgiosironi** [comment]
Is this what you are after?
https://github.com/elifesciences/builder-configuration/blob/cef111514bc08fb37a11e33cf23376b260672363/pillar/environment-staging-public.sls#L16
https://github.com/elifesciences/builder-configuration/blob/7527baf30d86e1358ba6ce0584d51acc69808511/pillar/environment-prod-public.sls#L28

**Comment by Cooryd** [comment]
@giorgiosironi  everything is working as it should, however could you clarify that the config links you've sent in the `builder-configuration` are setting the environment variables being accessed in the app. Seems like theres some serialisation between the builders config value and the variable set? or am I miss-understanding

https://github.com/elifesciences/elife-xpub/blob/05d1324777744111598ae6e325eac480ddc45d9a/config/custom-environment-variables.js#L11

**Comment by Cooryd** [comment]
<img width="401" alt="screenshot 2019-02-01 at 11 29 47" src="https://user-images.githubusercontent.com/22455561/52120961-f1898100-2615-11e9-9236-eaabb7cd6571.png">

Staging email link to site seems correct. :heavy_check_mark:

**Comment by giorgiosironi** [comment]
@Cooryd there is an explicit mapping from these `pillars` to environment variables:
https://github.com/elifesciences/elife-xpub-formula/blob/master/salt/elife-xpub/init.sls#L42-L47

**Comment by jyenes** [comment]
checked variables on config files and everything seems to be right

**Comment by diversemix** [comment]
I checked this out to pre-launch so closing
