### ISSUE TITLE
Check production configuration for sftp

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1431]
Also check and create the `MECA_API_KEY`

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder-configuration/blob/cef111514bc08fb37a11e33cf23376b260672363/pillar/environment-staging-public.sls#L18
https://github.com/elifesciences/builder-configuration/blob/7527baf30d86e1358ba6ce0584d51acc69808511/pillar/environment-prod-public.sls#L30
are ok in terms of `host`.
https://github.com/elifesciences/builder-private/blob/master/pillar/environment-staging.sls#L8-L13
has `username`, `password` and `api_key`.
https://github.com/elifesciences/builder-private/blob/master/pillar/environment-prod.sls#L213-L217
has `username` and `password`, missing `api_key`.

**Comment by giorgiosironi** [comment]
Can easily generate one, but the point is we need to get it to EJP; and prove that the `staging` one has also been sent to EJP.

**Comment by hem-brahmbhatt** [comment]
FYI, SFTP uses ssh keys, whereas FTP(s) uses a username password. We’re using the latter, even though the config within our code says SFTP.

**Comment by giorgiosironi** [comment]
SFTP is an extension of the SSH protocol so it can use username and password (as the protocol allows); to the best of my knowledge this is what we are using, not FTPS which is an extension to FTP instead?

**Comment by hem-brahmbhatt** [comment]
> SFTP is an extension of the SSH protocol so it can use username and password (as the protocol allows); to the best of my knowledge this is what we are using, not FTPS which is an extension to FTP instead?

I think this is correct.

**Comment by hem-brahmbhatt** [comment]
@diversemix I'm able to connect to the SFTP endpoint in production using plain old FTP with a username and password, which is a security risk: https://www.beyondsecurity.com/scan_pentest_network_vulnerabilities_ftp_clear_text_authentication

**Comment by hem-brahmbhatt** [comment]
Tested out the API key, and am able to successfully make a request using it.

**Comment by hem-brahmbhatt** [comment]
Test out the SFTP config for production and it's working correctly.

**Comment by hem-brahmbhatt** [comment]
We're only able to test out the API key once #793 is closed, have moved over the testing task there.
