### ISSUE TITLE
Update Kubernetes nginx config to allow large file uploads

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#145]
Currently, uploading a file over ~3MB causes an error and this prevents the ScienceBeam from working.

**Comment by hdrury1** [comment]
@g-sam Where is the nginx config to change?

**Comment by g-sam** [comment]
Config is here: https://gitlab.coko.foundation/pubsweet/infra/blob/master/addons/ingress-nginx.yaml#L229-230

I'd say this is fairly low priority atm: this is only our kubernetes nginx instance which we will stop using -- only matters if we need to test with larger files before then.

**Comment by g-sam** [comment]
This is tested as working with a 4mb file that was failing before. I set the limit to 20mb but confusingly, it is still not working with a 13mb file. It is also frequently timing out so there may be other issues.

**Comment by diversemix** [comment]
This may prove useful for upping the sizes for the eLife AWS deployments: https://github.com/elifesciences/elife-xpub-formula/search?utf8=%E2%9C%93&q=nginx&type=

**Comment by g-sam** [comment]
I am renaming this to refer to Kube deployment only and closing, else it will hang around for ever.
