### ISSUE TITLE
FileStatus: Add virtual attribute for file status

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1469]
**Background & context**

Currently there is a bug that allows the user to submit a manuscript while a supporting file is still in the process of uploading. This causes problems generating the `meca` package as the file exists in the database but the file isn't accessible through S3.

Our intended solution is to prevent the user from clicking 'Next' on the file stage of the wizard when  any associated files do **not** `STORED` or `CANCELLED`  status. 

We aim to achieve this functionality by adding a field to the manuscript of `fileStatus` which will have an enum value of `CHANGING` or `READY`. As this is a derived value, it should exist as a virtual attribute on the `Manuscript` object and not within the database. 

This issue relates only to adding this new virtual attribute and calculating its value. Further work will be raised for the remaining functionality described above.

see: https://vincit.github.io/objection.js/#virtualattributes

**Comment by hem-brahmbhatt** [comment]
Virtual attributes are only included when `.toJSON` is called on the model.

Will look into the following alternatives:
- `manuscript.fileStatus`, implemented as `get fileStatus() {}`
- `manuscript.fileStatus()` implemented as `fileStatus()`

**Comment by Cooryd** [comment]
> * `manuscript.fileStatus`, implemented as `get fileStatus() {}`

This will likely cause schema conflicts when saving

**Comment by hem-brahmbhatt** [comment]
[It seems to work](https://github.com/elifesciences/elife-xpub/blob/1469-file-status-virtual-attribute/server/xpub-model/entities/manuscript/index.test.js#L143-L151)

**Comment by Cooryd** [comment]
Great, do you think this will still be the case once we've fixed the `$$omitFromDatabaseJson` issue and are able to edit and save an entity multiple times without re-fetching?

**Comment by hem-brahmbhatt** [comment]
I'm not sure how to reproduce that issue so I can't confirm.
