### ISSUE TITLE
Taking decisions in the project

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#147]
Please look over https://docs.google.com/document/d/1tCbXFGdYX3CQ02oqtfFTQuxFog3VYsnGRYbuaM2hZ1Y/

Feel free to add pros & cons and comment on what I wrote there. We should select one of those methods (or add something else if you think it's better) and stick to it. We can agree on one of those solutions by commenting here/in the document or at a standup/retro. I'm ok with solutions 1 & 3.

**Comment by diversemix** [comment]
Going to use the Libero Approach as posted by @giorgiosironi in #xpub-tech (10:43 24/5/2018)

Inspired by: http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions

Example (usually they are discussed one at a time) https://github.com/elifesciences/elife-base-images/pull/8
