### ISSUE TITLE
FileStatus: Check before export (error if wrong)

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1471]
Currently we run a process at the point of final submission which generates a meca folder for sending to ejp. The aim of this task is to add a validation check over the files being included in this meca package to ensure all files are all in a `STORED` state. 

This may need to run a query over all files related to the manuscript, however #1469 aims to add a virtual attribute to the Manuscript entity to represent this state so it may be suitable to evaluate this value instead of doing the check manually.

**Comment by jyenes** [comment]
@diversemix can you provide more info about this one?

**Comment by Cooryd** [comment]
@jyenes I've updated the description of this issue. It may be worth putting this in a blocked state awaiting #1469
