### ISSUE TITLE
FileStatus: Add to client validation (error if wrong)

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1472]
### Background
Currently the a user can continue through the submission wizard to the submit stage while there are outstanding uploads in progress. This has caused issues with the meca exports not containing the files listed in the manifest.xml (and thus not being imported into ejp). #1471 aims to add server side validation for this to prevent the user being able to submit while files are still uploading. 

### Task
This issue involves adding a client-side validation check on the upload progress of all files, both manuscript and supporting. This should take place at the point of moving from the 'Files' step to the 'Submission' step. The user should not be able to move forward in the wizard from the 'Files' view until all files have been stored in s3. This should be prevented with validation errors.

- [x] fix for uploading Manuscript See (https://github.com/elifesciences/elife-xpub/pull/1654)
- [ ] fix for supporting files

**Comment by Cooryd** [comment]
Description updated. It may be worth seeing #1469 to see if this issue relies on the new virtual attribute.

**Comment by jyenes** [comment]
I'm going to block this issue till #1669 is finished

**Comment by hdrury1** [comment]
@SemraSh Has this issue actually been done? I'm not sure validation for supporting files has been implemented.
