### ISSUE TITLE
Styleguide is failing on CI

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1476]
The styleguide is failing to build and deploy. This is due to #1452. 

We should update the webpack config for the styleguide, and possible any other webpack configs left to do, to contain the updated resolver.

You can see the failed build here: https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-1474/2/pipeline/39/

**Comment by Cooryd** [comment]
The aliases are defined in the common resolver https://github.com/elifesciences/elife-xpub/blob/edf77a77a096e8377a9b1995465a0c026952f0d8/webpack/common-resolve.js this should be getting imported and applied in the `resolvers` part of all webpack config files. A starting point for the investigation. 

https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#resolver
