### ISSUE TITLE
Copy&Paste rot

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#148]
Below is an example that needs fixing, also search for others.

app/components/submission/AuthorDetails/AuthorDetailsPage.js
12-    {(updateSubmission, initialValues) => (
13-      <Formik
14-        component={AuthorDetails}
15-        initialValues={initialValues}
16-        onSubmit={(values, { setSubmitting, setErrors }) => {
17:          const data = omitDeep(values, ['__typename', 'files'])
18-          return updateSubmission({ variables: { data } })
19-            .then(() => setSubmitting(false))
20-            .then(() => history.push('/submit/upload'))
21-            .catch(errors => {
22-              setErrors(errors)

app/components/submission/ManuscriptMetadata/ManuscriptMetadataPage.js
14-        {(updateSubmission, initialValues) => (
15-          <Formik
16-            component={ManuscriptMetadata}
17-            initialValues={initialValues}
18-            onSubmit={(values, { setSubmitting, setErrors }) => {
19:              const data = omitDeep(values, ['__typename', 'files'])
20-              return updateSubmission({ variables: { data } })
21-                .then(() => setSubmitting(false))
22-                .then(() => history.push('/submit/suggestions'))
23-                .catch(errors => {
24-                  setErrors(errors)

app/components/submission/ReviewerSuggestions/ReviewerSuggestionsPage.js
14-        {(updateSubmission, initialValues) => (
15-          <Formik
16-            component={ReviewerSuggestions}
17-            initialValues={initialValues}
18-            onSubmit={(values, { setSubmitting, setErrors }) => {
19:              const data = omitDeep(values, ['__typename', 'files'])
20-              return updateSubmission({ variables: { data } })
21-                .then(() => setSubmitting(false))
22-                .then(() => history.push('/'))
23-                .catch(errors => {
24-                  setErrors(errors)

app/components/submission/FileUploads/FileUploadsPage.js
26-      <Mutation mutation={UPLOAD_MUTATION}>
27-        {(uploadFile, { data: uploadData, loading, error: uploadError }) => (
28-          <Formik
29-            initialValues={initialValues}
30-            onSubmit={(values, { setSubmitting, setErrors }) => {
31:              const data = omitDeep(values, ['__typename', 'files'])
32-              return updateSubmission({ variables: { data } })
33-                .then(() => setSubmitting(false))
34-                .then(() => history.push('/submit/metadata'))
35-                .catch(errors => {
36-                  setErrors(errors)

**Comment by tamlyn** [comment]
Haha, one step ahead of you! 😛 

https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/64

**Comment by diversemix** [comment]
Out-Manoeuvred!
