### ISSUE TITLE
Whitelist input fields for HotJar recordings

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1484]
Currently, text input fields are suppressed by default on HotJar screen recordings. This behaviour can be overwritten so that we can view users' keystrokes.

The data is not private since we are recording it all in the MECA package.

See https://help.hotjar.com/hc/en-us/articles/115015563287-Whitelisting-input-fields for documentation.

**Comment by jyenes** [comment]
@hdrury1 what are the input field do you want to whitelist?

**Comment by hdrury1** [comment]
@jyenes Everything (I think HotJar doesn't allow us to capture email address, but we should capture everything else). We don't capture anything sensitive and everything is exported in the MECA file anyway.

So:

First name, last name, institution and input into the search bar in the people picker

**Comment by hdrury1** [comment]
Concerns have been raised that this work is going to put us in breech of eLife's privacy policy, given that we are recording this information without explicit consent. I am looking into it, but please hang fire for now. We may need to explore other options for anonymously logging the use of the search box in the People Picker, which is what Product are particularly interested in.

**Comment by jyenes** [comment]
ok closing this then.
