### ISSUE TITLE
Quick fix -  Stuck at 99% uploading

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1487]
Issue came in via user: Date: Fri, 8 Feb 2019, 22:56

Hello Susanna,

... We are trying to submit a manuscript to eLife, and we received an email to use the new interface. However, while we were trying to upload our manuscript, we were stuck on the 99% uploading. Then we tried to delete the submission request and create a new submission, the manuscript uploading text box is stuck on 99% even though we haven't upload anything yet. Please see attached screenshot.

---

As a quick fix for this the progress connection created when a user starts a manuscript should be specific to that manuscript, not the user. This should allow the user to create a new submission without displaying the progress % of the stuck manuscript.

**Comment by diversemix** [comment]
We had a New Relic alert about the same time...

https://alerts.newrelic.com/accounts/1451451/incidents/56409231/violations

**Comment by acollings** [comment]
![image](https://user-images.githubusercontent.com/43173300/52520042-62efb200-2c5c-11e9-8a65-b1bb89cab1cb.png)
This was the screenshot they sent.

**Comment by acollings** [comment]
Description of the experience/issue (I can retrieve the file on Monday if that helps):

We managed to stumbled across the old interface and successfully submitted our paper.

We went on the eLife website, then clicked log in. We then used the Institutional account to log in ORCID. We went back to the eLife website and click Submit My Research. I believe this is when we receive the email if we were selected to use the new interface or not. After our first attempt on uploading the manuscript, it was stuck at 99%. So we deleted the first attempt, signed out, closed the browser and signed back in. The moment we entered the new interface with a new submission, the manuscript box already showed the 99% (as you can see on the screenshot). That's basically the gist of it, except we probably did that 10 more times and we managed to get in the old interface instead.

**Comment by Cooryd** [comment]
Some thoughts I've had regarding this issue over the weekend: 

The subscription thats opened to relay updated progress is only defined as `ON_UPLOAD_PROGRESS.${userId}` in the `uploadManuscript` controller function. This would mean having two or more uploads happening in parallel would be sending the same message key. We should maybe look at appending the `manuscriptId` of the file to the message key?

99% upload progress suggests we are failing and exiting the `uploadManuscript` code before hitting line 177 where the 100% progress message is declared. We should ensure that this is sent and the `setInterval` is canceled before throwing errors so that the conversion on the client knows the process has finished (we'd need to make sure that the error is surfaced even in a 100% conversion scenario).

**Comment by diversemix** [comment]
Notes for phone conversation this morning:

We agreed that this will be broken down into 4 separate issues, the first of this will be fixed on this ticket, the latter three with be raised and xref'ed on here:

- Make the upload progress by keyed on `Manuscript.id` and `File.id` *Ticket* #1487
- Fix the ordering of the client side checks of error and converting (see #1486) *Ticket* #1490"
- Investigate what the cause of the error in Production *Ticket* #1491"
- Breakdown and fix the `upload` function to ensure the final message is sent on error *Ticket* #1492"
- Investigate the use of subscriptions on file upload, including Pubsweet *Ticket* #1493"

**Comment by diversemix** [comment]
@giorgiosironi ... I've noticed you've acknowledge the NewRelic Alert. If you have anymore information on this can you comment / xref on here please :smile:  :+1:

**Comment by hdrury1** [comment]
Please note that I also encountered this bug. @diversemix monitored me starting/deleting several new submisisons and saw the stale manuscript persisting in the database:

Example:
```
elifexpubstaging=> SELECT created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
              created_by              
--------------------------------------
 9ac8a28e-9aa6-4141-b94d-31d303e43b0c
(1 row)

elifexpubstaging=> SELECT created_by FROM manuscript WHERE id='f3459a55-ad38-4384-87ef-3023d130feea';
 created_by 
------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
                  id                  |              created_by              
--------------------------------------+--------------------------------------
 ce0e9c5f-4719-4087-86a6-48a268d6d9c9 | 9ac8a28e-9aa6-4141-b94d-31d303e43b0c
(1 row)

elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 1
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
                  id                  |              created_by              
--------------------------------------+--------------------------------------
 369df88a-6cc8-4c8b-8355-b5d79a7e4523 | 9ac8a28e-9aa6-4141-b94d-31d303e43b0c
(1 row)

elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 1
elifexpubstaging=> DELETE FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c'  ;
DELETE 0
elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
 id | created_by 
----+------------
(0 rows)

elifexpubstaging=> SELECT id, created_by FROM manuscript WHERE created_by = '9ac8a28e-9aa6-4141-b94d-31d303e43b0c';
                  id                  |              created_by              
--------------------------------------+--------------------------------------
 ff079bac-dfd4-4ea3-90f8-612646bba5bd | 9ac8a28e-9aa6-4141-b94d-31d303e43b0c
(1 row)

```
