### ISSUE TITLE
Investigate:  Ordering of the client side checks of error and converting

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1490]
See #1446 & #1487

Currently the client displays the content of the upload area based on a number of different props passed to the `ManuscrioptUpload` component. These props are evaluated to determine what 'state' the upload is in. This can be:

- Converting (an upload is in progress)
- Error (Somethings either gone wrong or the client side validation has kicked in)
- Completed (A file has been successfully uploaded and there is no ongoing upload process happening)
- Empty/Idle (There is no manuscript file and nothing is currently being uploaded)

A cascading set of `if` checks decide which one of these states is displayed and the ordering of these checks is important as one state should take preference over another ie:

Error is thrown but the conversion progress is still not at 100%.  The client should display the error state over the converting state.

#1487 suggests that there may be bug with the app continuing to show a converting state when an error has been returned. This issue will require the investigation of the `ManuscriptUpload` component to see if the logic for displaying the states is inline with what should be expected.

**Comment by Cooryd** [comment]
As a note, currently if the user tries to upload an invalid file type,  then begins uploading a new file, the component still has the previous error message in state. This was the reason for rejecting #1446

**Comment by jyenes** [comment]
this issue is no longer needed, as the work required was moved to the backend side 
see #1492, #1517, #1535, with this work done in the backend we can ensure the client side is no longer hanging when uploading a new manuscript, as we are handling the errors properly in the backend side.
