### ISSUE TITLE
xpub-tech-alerts not working in production

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1496]
We've had an EJP failure in production and no email was sent ...

```
a9fc13af-4c94-44a0-ae51-34ab58b666d5 | 2019-02-09 03:45:41.863+00 | MECA_IMPORT_FAILED
```

**Comment by jyenes** [comment]
I realised the `from` field has not been set, I introduce the field and I got an email on ethereal mail

**Comment by giorgiosironi** [comment]
Isn't this `xpub-alerts`? I receive emails from `xpub-tech-alerts`.
