### ISSUE TITLE
Add Research Advance link to Login screen

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1498]
On their dashboards, we currently direct authors of Research Advances to submit via eJP. We should make this clear to authors who have not yet logged in to the system by displaying the link on the Login screen too.

//cc @chugginselifesciences I didn't know if you wanted to add a mockup for this?

**Comment by chris-huggins** [comment]
See https://invis.io/RHQP0Q42D39#/348810694_login-Updates-EJP-Redirect and milestone for details

**Comment by hdrury1** [comment]
Going to close this as it is superceeded by #1575
