### ISSUE TITLE
Add links to Terms and Conditions and Privacy Notice to footer of dashboard

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1499]
These appear in the dashboard and login screen footer of eJP:

<img width="1234" alt="screen shot 2019-02-11 at 14 18 06" src="https://user-images.githubusercontent.com/17023702/52568948-ffa28300-2e07-11e9-972b-0530b6c3c78d.png">

//cc @chugginselifesciences did you want to add mockup(s) for the placement of these links in xPub? Should they appear at the global nav level?

**Comment by chris-huggins** [comment]
I'm wondering if we can "move" them to the author/reviewer guide type content.

Do they have to be visible on the dashboard?

**Comment by hdrury1** [comment]
@acollings the best person to address that question. My understanding is these are currently hosted on the Journal site, so for a quick fix I'm happy to just link out.

**Comment by acollings** [comment]
Hi @chugginselifesciences and @hdrury1. I asked Paul K and they need to be visible from the point we start collecting personal information, which in this case means https://reviewer.elifesciences.org/login, I think. By global nav level, does that mean"Author guide | Reviewer guide | Contact us? If so, I think that's the most sensible place for the links.

I would also recommend linking out to https://elifesciences.org/terms and https://elifesciences.org/privacy, and not replicating the content on xPub itself.

Questions about these links are probably best directed to Paul K, but let me know if I can help.

**Comment by chris-huggins** [comment]
Will do. Thanks for your help @acollings

**Comment by chris-huggins** [comment]
See links in footer on dashboard

![image](https://user-images.githubusercontent.com/41907215/53359637-5d1bf100-392b-11e9-8d68-0ccbb4f8ff98.png)
