### ISSUE TITLE
Write tests for controller helper functions

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1520]
## Background

As part of #1492 the `manuscript` controllers `upload` function was simplified by splitting out the functionality into smaller steps and placing these in helper functions. One of the aims of this re-factoring task was to make the individual pieces of functionality easier to test as they now sit in the stand alone functions rather than the controller classes function.

This task involves writing the tests for these helper functions that have been pulled out of the `manuscript` controller. 

## Assumptions and notes

It may be worth looking through existing tests for the `manuscript` controller function and `uploadManuscript` resolver function as they may already contain code for testing some of the functionality of these new helper functions and could be reused / moved as appropriate.

**Comment by SemraSh** [comment]
This ticket will be closed after testing part of the functions in xbup-controller helpers

```
validateFileSize
generateFileEntity
publishPredictedProgress // tested in a previous pr
endFileProgress
```

the rest of the functions are tested in these tickets --> #1554 and #1555
