### ISSUE TITLE
Investigate: Adding coveralls for coverage reports

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1524]
We currently manage our own coverage reporting to let us know if our test coverage is below accepted levels. Coveralls is a service which manages this for you.

https://coveralls.io/

- Integrates with Github
- Free on open source repositories
- Means we don't have to manage our own coverage reporting

Investigate the following:
- [ ] what steps are needed to add this to `elife-xpub`?
- [ ] what steps are needed to remove existing test coverage code?
- [ ] what reporting/information do we get from coveralls?

**Comment by SemraSh** [comment]
We have decided to use Codecov instead, to check the reasons please see #1638  
I will close this ticket
