### ISSUE TITLE
Hem to notify people of discontinuation of AWS hosting by YLD

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1533]
## Assumptions and notes
- We currently pay an AWS bill from YLD which will be discontinued by the end of March
- Hem to ensure all those affected are made aware (currently I believe this is just Coko)

/cc @damnhipster , @hdrury1 , @BlueReZZ

**Comment by hem-brahmbhatt** [comment]
The only deployments on the cluster are Pubsweet review environments. I have contacted Jure to inform him about the future of the cluster.

The new cluster is within a private subnet within elife, so it's not something that can be used to host Pubsweet's review environments.

**Comment by hem-brahmbhatt** [comment]
Jure has agreed that we can delete the review environments.

**Comment by hem-brahmbhatt** [comment]
Deleted all of eLife's resources in YLD's AWS account.
