### ISSUE TITLE
Update NewRelic apdex alert threshold to 1 second

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1542]
The threshold is currently set to 0.1 seconds. Our average response time on the /ping endpoint is 118ms, so we keep getting alerts in our emails from New Relic.

Given that our average response time on /graphql is 700-800ms, we should change the alert threshold to 1000ms.

You can change the setting here: https://rpm.newrelic.com/accounts/1451451/applications/162983119/settings-application

**Comment by giorgiosironi** [comment]
Setting changed, the output was that the agents should restart. Monitoring the open alert.

**Comment by giorgiosironi** [comment]
[Apdex has jumped up to 0.85](https://rpm.newrelic.com/accounts/1451451/applications/162983119/) so at least the alert should be closed soon.

**Comment by giorgiosironi** [comment]
https://alerts.newrelic.com/accounts/1451451/incidents/57259336 is now closed.

**Comment by hem-brahmbhatt** [comment]
All incidents and warnings have been closed automatically.

<img width="1280" alt="screen shot 2019-02-19 at 10 11 26" src="https://user-images.githubusercontent.com/2573277/53007252-c765fa80-342e-11e9-9dea-a2464c368e6d.png">
