### ISSUE TITLE
Write tests for controller helper functions PART3

### ISSUE THREAD

**Issue by SemraSh** [elifesciences/elife-xpub#1555]
This ticket is the third part of writing tests for controller helpers, see https://github.com/elifesciences/elife-xpub/issues/1520 for the first part and https://github.com/elifesciences/elife-xpub/issues/1554 for the second part.
This ticket covers the functions below
setManuscriptMetadata
validateManuscriptSource

**Comment by hem-brahmbhatt** [comment]
`setManuscriptMetadata` may need to be broken down further. The function is also responsible for changing the pending file to the source file, which is at odds with the name of the function.

https://github.com/elifesciences/elife-xpub/blob/324cc9c0e1dac14acbdf55735b7a1a153cde68ec/server/xpub-controller/helpers/files.js#L151-L166

**Comment by diversemix** [comment]
No PR - as we are going to stop working on this until we have a conversation. May not be addressed - as the code may be re-written.
