### ISSUE TITLE
Implement email delivery system

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#156]
We need an email delivery system (e.g. SMTP server) to be able to send emails. Not sure if eLife already has something in place for this. If we don't, there are plenty of solutions out there, many companies offer email delivery as a service.

**Comment by tamlyn** [comment]
I believe xPub will SES for this in production since eLife sites are hosted on AWS. In any case I don't think we need to know this at this stage so long as the email sending service is made configurable (as it already is in PubSweet).
