### ISSUE TITLE
Update page titles

### ISSUE THREAD

**Issue by rowenamaskell** [elifesciences/elife-xpub#1586]
## Problem / Motivation
The current page titles for all https://reviewer.elifesciences.org pages are 'xpub'. As this isn't relevant for authors and shows up in various places (Tab labels, Google SERPS etc.) I would like the page titles to be updated.

## Proposed solution
- Update the page titles to conventions that are the same as the main eLife site
- e.g.
"Submit | eLife" for https://reviewer.elifesciences.org/login
"Author guide | eLife" for https://reviewer.elifesciences.org/author-guide/editorial-process

## Clarification needed and assumptions
- Can we also add an icon that appears in the tab?

---

## Tasks

- [ ] A description of a task
- [ ] A description

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes

@hdrury1

**Comment by hdrury1** [comment]
Agreed on the following values:

Author guide -> ‘Author guide | eLife’
Reviewer guide -> ‘Reviewer guide | eLife’
Contact us -> ‘Contact us | eLife’
Dashboard -> ‘Dashboard | eLife’
Login screen(s) -> ‘Login | eLife’
Submission wizard pages -> ‘Submit | eLife’
