### ISSUE TITLE
Create virtual property on Manuscript model to return file of type MANUSCRIPT_SOURCE

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1592]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) it would be beneficial to have a function on the `Manuscript` model to return the file data of the manuscripts source file
 (`{ type: 'MANUSCRIPT_SOURCE }`)

This would make it easier for controller functions to check if the manuscript has a source file and to fetch the data for the source file (ie: `id`) without having to manually iterate over all `manuscript.file` entries.

### Example code
```
class Manuscript {
  ...
  static get virtualAttributes() {
    return ['sourceFile']
  }
  sourceFile() {
    const manuscriptSourceFileIndex = this.files.findIndex(
      element => element.type === 'MANUSCRIPT_SOURCE',
    )
    return this.files[manuscriptSourceFileIndex]
  }
 ...
}
```

see https://vincit.github.io/objection.js/#virtualattributes

### Question points
- We haven't used `virtualAttributes` with `objection.js` models before so it may need to be investigated  how creating a virtual attribute based on a related entities field holds together. Hopefully it's seamless and can be done the same as the example.

## Clarification needed and assumptions

Remember to add in a unit test for this new attribute

**Comment by hem-brahmbhatt** [comment]
Related to https://github.com/elifesciences/elife-xpub/issues/1469. When this gets picked up, you may find that the first use case for virtual attributes is there.
