### ISSUE TITLE
Move existing controller code to legacy directory

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1603]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) the old controller code should be moved to a new legacy directory. This will require all dependency import paths to be updated (most if not all will be found in the `xpub-server/entities/---/resolvers` but be sure to check elsewhere)

## Other considerations
~~We had decided to leave behind the `client` directory so that we aren't maintaining it in two places **however** the current clients `scienceBeamApi.js` and `S3Storage.js` are lacking unit test files so It may be easier to move everything to the legacy directory and raise an issue to recreate these with unit tests similar to #1590 and #1591. The lack of unit tests are likely because they're sitting in the resolver test files which is an issue in its own right.~~

We have decided to move `client` out of the controller directory completely. see #1609 & #1084

**Comment by Cooryd** [comment]
Decided that a better approach to carrying out the refactor is to have everyone working on getting the refactor completed into a new controller package (`xpub-controller2`?) to save moving code around as much (makes it harder to track down historical file changes).

This can't happen until outstanding issues with `fileStatus` are addressed (#1469, #1471 ect.)

**Comment by hem-brahmbhatt** [comment]
This ticket should be closed since it's no longer relevant.

**Comment by Cooryd** [comment]
Decided to work into a new controller directory instead of moving code to legacy.

**Comment by Cooryd** [comment]
#1641 created in place of this task
