### ISSUE TITLE
Create the new directory structure and initial class files for the new refactored controllers

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1606]
**This task is dependant on #1603 & #1609**

## Problem / Motivation
As part of the refactoring of the controller (see #1587) we decided to re-write the controller into the `xpub-controller` top level directory which should be cleared as part of #1603 (create legacy controller) and #1609 (move client). It has been decided that `Manuscript` should be re-named `Submission` in this refactor. As the whole controller is being re-written this seemed like the correct time and place to do this (note: resolvers and models will continue using the name Manuscript for now, the scope of this rename will only be instances in the controller.)

## Proposed Solution

The `xpub-controller` directory should now be clear. We should create a top level `index.js` inside `xpub-controller` that imports controller classes and exports them so that resolvers may import, for example:

`const { FileUploadController, SubmissionController } = require('@elifesciences/xpub-controller')`

proposed file structure:
```
/xpub-controller
  /factory
  /notify
    index.js
  /fileUpload
    index.js
  /submission
    index.js
  index.js
```

**Comment by hem-brahmbhatt** [comment]
`/client` will be moved out as part of https://github.com/elifesciences/elife-xpub/issues/1609.

We should avoid making any folders for the individual controllers as part of this. When we do, they should follow the coding standards laid out in https://github.com/elifesciences/elife-xpub/issues/1587.

@Cooryd will update the description.

**Comment by hem-brahmbhatt** [comment]
What does everyone think about having a controller directory within?

_Proposal_
```
/xpub-controller
  /factory
  /controller
    /notify
      index.js
    /fileUpload
      index.js
    /submission
      index.js
  index.js
```

**Comment by hem-brahmbhatt** [comment]
@Cooryd It's difficult to see what the scope of this issue is and at what point it should be picked up. I suggest we make separate issues to move/recreate individual controllers within the new file structure.

**Comment by Cooryd** [comment]
I’m happy with this structure, I’m not sure `uploadFile` is the correct naming however as one of the initial functions we’ll need is `delete`. I’d prefer to stick with `/file` and the class called `FileController`. 

The scope for now would be to create a `controller` directory, creating the three top level directories for `submission`, `file` and `notify` (I think notification sounds better but it’s doesn’t really matter so I’m fine to go with the suggestion above) then creating a basic `index.js` that simply defines and exports an empty class for each. This would put us in a good starting position to carry out #1611, #1607 etc.

**Comment by Cooryd** [comment]
After call it was agreed we go with the pattern of creating controller directories per 'action' ie: `fileUpload`, `fileDelete`, this would allow us to have smaller controller classes then if everything was grouped under a `ModelController` super class. This also helps us move away from having controllers with names that match models which can be confusing.

**Comment by hem-brahmbhatt** [comment]
Closing due to https://github.com/elifesciences/elife-xpub/issues/1668
