### ISSUE TITLE
Add ADR for why we are using PubSweet

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#161]
It is still not entirely apparent what PubSweet are bringing to the table. Gather this information and add to an ADR.

**Comment by jsms90** [comment]
@diversemix Is your question in relation to any particular components/packages, or rather why we are using anything from pubsweet at all?

**Comment by diversemix** [comment]
I want to gather the information on the technical need for pubsweet ... then we can address the other question ;)

**Comment by diversemix** [comment]
Blocked on @BlueReZZ  sending some information.

**Comment by hdrury1** [comment]
Do we have an ADR for this?

**Comment by diversemix** [comment]
Ah moving this to In Progress again ... got some information from Paul - this has been delayed because of the other stuff going on. Also like to run it past Paul again - we need careful wording :)

**Comment by diversemix** [comment]
Also as a part of this I will be re-indexing which affect the workflow ADR from #152

**Comment by hdrury1** [comment]
PR: https://github.com/elifesciences/elife-xpub/pull/174
