### ISSUE TITLE
Add CodeCov

### ISSUE THREAD

**Issue by SemraSh** [elifesciences/elife-xpub#1638]
See #1479
We are seeing errors while running the code coverage in development. To see the information for every branch in ci we can add Codecov (https://codecov.io) to get a report on every branch. This will give the information of how much of the added code is tested and not tested.
See also [this](https://github.com/dwyl/repo-badges) on why codecov will be good to add.

Steps to add Codecov to the github repo:
- Login using your github account through https://codecov.io
- select elife-xpub repo from the repos
- Codecov is approved by @giorgiosironi so you should be able to see the settings where you can find the generated token.
- The token needs to be added to the ci pipeline ( this step to be defined by @giorgiosironi )
- Investigate further if the Jenkinsfile should have been updated to include the codecov configuration

[Codecov docs](https://docs.codecov.io/docs)

**Comment by SemraSh** [comment]
Adding this might close #1639 as well if local coverage report is decided to be dispensable.

**Comment by giorgiosironi** [comment]
In [this pipeline](https://github.com/elifesciences/data-pipeline-bigquery-views/blob/5e60829aa40db98188fe0ccfecad4d42787c671e/Jenkinsfile#L86-L93) we retrieve Google Cloud credentials from Vault. We'll do a similar thing here.
