### ISSUE TITLE
Create a new controller directory for this refactor work

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1641]
A new directory is needed to place the newly refactored/rearchitected code into. This should sit at the top level of `/server` next to the current `/xpub-controller`. Directory name is TBD, could be `xpub-controller2` or `xpub-controller-new`?

**Comment by hem-brahmbhatt** [comment]
Closing due to https://github.com/elifesciences/elife-xpub/issues/1668
