### ISSUE TITLE
ScienceBeam having issues

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1657]
Yesterday's logs had lots of issues @de-code 

```
49984:{"error":"Request to science beam timed out","manuscriptId":"a075bc80-8de2-42f4-b312-f282573eb9f3"
77077:{"error":"Request to science beam timed out","manuscriptId":"197117f3-7c4c-47ee-99e0-ffd471bfdeeb"
98510:{"error":"Request to science beam timed out","manuscriptId":"f30b3427-9d72-4f4f-8cc2-c64194a1bb63"
99971:{"error":"Request to science beam timed out","manuscriptId":"a57f9163-e35f-49b4-8e4b-3f7b43ec4db8"
140558:{"error":"Request to science beam timed out","manuscriptId":"81c8c2b4-9d7d-4b97-9be3-268b69c336db"
```

/cc @hdrury1

**Comment by de-code** [comment]
How do we manage those issues best? Will someone from the xPub team first look at the container health? Or should I already have a look (in which case I'd need to know the IP I should be connecting to). Does the problem still persist or was it temporary?

Just a comment: For consistent naming, it's `ScienceBeam` as a display name, or `sciencebeam` as an id (one word, I noticed it's two in the log).

**Comment by diversemix** [comment]
Thanks for the feedback - if you use `builder` you can connect to either of the servers for `elife-xpub--prod` and take a look under `/srv/elife-xpub/var/log`

**Comment by de-code** [comment]
The server had been restarted around 7 hours ago. We could maybe try the service with those manuscripts.

It might also be worth setting up Newrelic for that if we haven't already?
(we could also actively keep converting a document every hour to check the 'health')

**Comment by diversemix** [comment]
Yeah good suggestions @de-code ... I need to understand a little more of New Relic to learn how to do this.
