### ISSUE TITLE
Update stepper label in wizard

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1666]
Change the label of the "submission" step of the wizard to "details". "Submission" is misleading as it's the term we use for the overall article, metadata etc.

![image](https://user-images.githubusercontent.com/41907215/54208983-d93e3900-44d4-11e9-87d2-76e64edcd1d0.png)

**Comment by hdrury1** [comment]
This may be worth considering when we're looking at restructuring the codebase @diversemix.

**Comment by diversemix** [comment]
Yeah - thanks for highlighting... @Cooryd / @damnhipster  ... would probably be worth renaming the components and files? no?

**Comment by hem-brahmbhatt** [comment]
Yes, it's worth renaming parts of the code. We'll want to identify what the word submission is used for within the codebase. 

May be worth adding a dictionary of terms to the docs at some point.

**Comment by Cooryd** [comment]
Duplicate of #1877
