### ISSUE TITLE
Discuss and Decide a solution to the CD issue

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1672]
The pipeline for continuous deployment uses `docker-compose up --force-recreate` which tears down and rebuilds the relevant containers in the deployment. In turn, this tearing down stops any server-side running process that is currently underway. This has the side effect of potentially interrupting any of the following:
- Any file upload by a user that is in progress.
- Any task in `mecaExport`, including package, transfer to S3 and/or to SFTP

We need to discuss and decide on a solution for this. Current options are:
- Option 1: Change the pipeline and the application to graciously wait for any tasks in progress and shutdown gracefully.
- Option 2: Make the app "recoverable" by storing state in the database (not sure how this would work for file uploads in progress) so it can pick up where it left off when re-started.
- Option 3: Avoid the issue as best we can by figuring out the least busy time of day and only deploying then.
- Option 4: Re-architect so that the app has microservices that can be deployed to less frequently and also stores state as in option (2)

/cc @Cooryd @hdrury1 @giorgiosironi

**Comment by diversemix** [comment]
If any of you @damnhipster / @SemraSh  / @jyenes have any bandwidth to think/contribute that would be good too :+1:

**Comment by giorgiosironi** [comment]
Option 1 seems the most viable, but in a soft way: there must be an upper limit to how much we can wait before restarting a container (30 seconds, 5 minutes, etc). This will likely never be reached.

In this scenario the application also has to implement a draining mode in which it stops accepting new connections after receiving SIGTERM.

**Comment by diversemix** [comment]
@giorgiosironi thanks for commenting... I sort of agree option1 is the best choice with introducing massive changes. I will talk with others in this premise and see.

**Comment by diversemix** [comment]
I'm going to close this off - as contemplating the other alt options they all seem either lots of work or half-baked.
