### ISSUE TITLE
Create xpub-search service

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#169]
This service will search for submissions / manuscripts that are currently in xPub of are in eJP.

This is a separate service so that it can periodically import data from Lax/s3 buckets.

**Comment by hdrury1** [comment]
This depends on how we go about architecting xPub-eLife microservices.

**Comment by hdrury1** [comment]
I'm going to close this down for now. It's a feature that may or may not be needed but isn't in any way defined right now.
