### ISSUE TITLE
Separate our unit tests from functional tests

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1693]
When the server-side code was first written, everything was placed within resolvers. Tests were written directly against these resolvers [which still exist to this day](https://github.com/elifesciences/elife-xpub/blob/develop/server/xpub-server/entities/manuscript/resolvers/submitManuscript.test.js).

We've now started to split these resolvers up, in milestones such as the [Controller Rearchitecture](https://github.com/elifesciences/elife-xpub/milestone/13). New tests were written at the time, but the old resolver tests were kept, since they provided value in ensuring the refactoring had not caused any regression.

Our testing strategy has changed as part of [further rearchitecting work](https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md). We have more emphasis on writing pure unit tests where external factors to our functions are mocked. This is in conflict to our existing tests, such as the resolver tests mentioned above. To keep both strategies alive:

- [ ] rename resolver tests to `*.test.functional.js`
- [ ] rename any further tests where we do not use mocks to be `*.test.functional.js`
- [ ] rename other tests to be `*.test.unit.js`
- [ ] identify any tests which don't fit into either of the above, and create tickets to rewrite them
- [ ] update the docs to describe the naming patterns for our tests, including functional, browser, and unit tests.

**Comment by diversemix** [comment]
@damnhipster how about `*.test.unit.js` ? Just thinking this would force the developer to acknowledge which type of test they think they are writing  before starting out. - just a thought.

**Comment by Cooryd** [comment]
I'm for both of these suggestions. It will be a good way of keeping testing strategy consistent and encourage us to slim down the number of functional tests we have.
