### ISSUE TITLE
Add option to preview uploaded manuscript

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1695]
## Problem / Motivation
- WHO wants this? Submitters
- WHEN and WHERE do they want it? To appear in the dropzone molecule upon successful upload of a manuscript file
- WHAT do they want? A link to preview their manuscript
- WHY do they want this? Feedback from submitters suggests they have some anxiety around the files they have uploaded and that they would prefer visual feedback in order to 'prove' that the application has ingested their file correctly and that the editors will view the manuscript as the submitter intended

## Proposed solution
- Convert the manuscript file to PDF
- Add a link to the dropzone molecule for the submitter to open this PDF in their browser

## Clarification needed and assumptions
- We can reliably convert the PDF
- A user will be happy to re-upload their manuscript if the PDF conversion has failed

---

## User interface / Wireframes

![image (3)](https://user-images.githubusercontent.com/17023702/54539526-32ebab00-498e-11e9-9bae-ab4447c6823e.png)

Text should be:

Success! **Replace** your manuscript file or **preview** it.

**Comment by diversemix** [comment]
How to tackle...
1. Add `downloadLink` to the manuscript query schema
2. Populate with a signed a URL see ... http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

**Comment by diversemix** [comment]
Put back into ToDo ...

Notes:
```
var AWS = require('aws-sdk');
var s3 = new AWS.S3({accessKeyId:'XXXXXXXXXXXX', secretAccessKey:'YYYYYYYYYYYY', region:'REGION'});
 
var params = {Bucket: 'test-bucket-tutorial', Key: 'images/myimage.jpg', ContentType: 'image/jpeg'};
s3.getSignedUrl('putObject', params, function (err, url) {
    console.log('Your generated pre-signed URL is', url);
});
```
see  https://ademcan.net/blog/2017/11/24/uploaddownload-images-tofrom-aws-s3-in-react-native-a-step-by-step-guide/

**Comment by Cooryd** [comment]
TBC on @will-byrne's return
