### ISSUE TITLE
Ensure deployments only occur during certain hours

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1707]
Currently, the application has no way of gracefully shutting down so whenever we deploy problems occur in the database, MECA package etc.

As a temporary step before we are able to complete https://github.com/elifesciences/elife-xpub/milestone/15 we should ensure deployment only occurs at time when the application has the least amount of traffic.

According to GA, this is between 3 and 4 am GMT. We should schedule deployments to take place during this time.

**Comment by diversemix** [comment]
This is linked to the PR for #1676 ... #1698

**Comment by diversemix** [comment]
@giorgiosironi ... will you be able to pick this up this week?

**Comment by giorgiosironi** [comment]
This can be configured at https://alfred.elifesciences.org/job/prod-elife-xpub/configure can you access that page?
This not modelled in code, but need to uncheck `GitHub hook trigger for GITScm polling` and check `Build periodically` with a cron schedule of `30 3 * * *` which will deploy once per day at 3:30 AM.

**Comment by diversemix** [comment]
Thanks @giorgiosironi - all changed /cc @hdrury1
