### ISSUE TITLE
Manuscript title missed on the send confirmation email.

### ISSUE THREAD

**Issue by jyenes** [elifesciences/elife-xpub#1708]
@diversemix detected the bug:

> I just received a confirmation email for my submission to eLife, however, in the email the title was missing between two ditto symbols, and so I wondered if the submission has been completed correctly. (In the submission system the title appears correctly: "Shared neural underpinnings of multisensory integration and trial-by-trial perceptual recalibration")

looking at the PR: https://github.com/elifesciences/elife-xpub/pull/1674

we have introduced new variable to include the manuscript title:
https://github.com/elifesciences/elife-xpub/blob/8ffd6de8a0469467d064a5032052f522ab4c2a4c/templates/final-submission-email-html.pug#L3

we need to compile the template and send this variable

**Comment by hem-brahmbhatt** [comment]
We should add a snapshot test for the email contents. Currently we only assert on the subject and recipient address.
