### ISSUE TITLE
[WATCH] Confirm Submission hanging in Staging

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1751]
See ... https://staging--xpub.elifesciences.org/submit/771e6c21-56b2-4935-aa48-fcee2cc65a3e/disclosure

This may well be the issue we've seen in production.

/cc @hdrury1 
![Screenshot from 2019-03-22 16-25-38](https://user-images.githubusercontent.com/8524685/54837775-284b5180-4cbf-11e9-9fa9-1e988bed29fa.png)

**Comment by hem-brahmbhatt** [comment]
I'm unable to reproduce this with the link you provided.

I've noticed that nothing happens when you click Confirm when there's a file uploading, or if the file upload gets interrupted. Either case causes the `fileStatus` field on the GraphQL API to be `'CHANGING'`. When this happens, you get an error in the console each time you click Next or Confirm.

**Comment by hem-brahmbhatt** [comment]
I think it's caused by https://github.com/elifesciences/elife-xpub/issues/1378, and was exasperated by https://github.com/elifesciences/elife-xpub/pull/1669

**Comment by diversemix** [comment]
Found error in client-side console:
> 2app.ec7bcff520d90e8bcd41.js:20 Uncaught (in promise) Error: GraphQL error: Manuscript fileStatus is CHANGING

**Comment by hdrury1** [comment]
But if the file is CHANGING how has the user managed to progress all the way to this screen? They should be stuck on the file upload step surely.

**Comment by hdrury1** [comment]
See also https://elifesciences.slack.com/archives/C6MJK1RD4/p1553185088026900

**Comment by diversemix** [comment]
After some investigation we can confirm that we're at a loss on how this can happen with the current application. A few things we found out / tested:

1) The uploading of files still continues when the browser tab is closed.
2) The page a user last visited can go past the "File" page of the wizard if the user goes on after uploads are complete and then goes back and changes the files. (this cannot be reproduced).
3) "Remove All" button still operates when files are uploading. Is this a bug @hdrury1

**Comment by diversemix** [comment]
Going to move this back to do as we need to keep an eye on this.

**Comment by hdrury1** [comment]
Should be addressed with #1882 and #1875 and
