### ISSUE TITLE
Create dedicated CI node

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#177]
We were running our CI jobs with stringent resource limits to ensure they fit on the kube nodes. This resulted in jobs being killed when they exceeded those limits.

We are now setting `request` instead of `limit`, but this may result in CI pods exhausting the nodes they are running on.

For a different reason (inability to enforce resource limits on DinD) Gitlab recommends creating a dedicated node for CI: https://docs.gitlab.com/runner/executors/kubernetes.html#resource-separation. This would also allow us to return to using limits, but set a higher limit.

This would entail:

- [ ] adding and labelling the node
- [ ] telling the gitlab-runner to deploy to that node
- [ ] adjusting our other kubernetes deployment configs so that other apps are not deployed onto this node.

**Comment by diversemix** [comment]
@hdrury1 My view is this should be in the ToDo as a priority

**Comment by diversemix** [comment]
This is something we could consider if we have failures in k8s jobs again. @giorgiosironi ... its probably worth you being aware of this as well.

**Comment by giorgiosironi** [comment]
We are in the middle of a Fastly migration so it would be difficult to provide infrastructure for this from the eLife side in the short term.

**Comment by diversemix** [comment]
@giorgiosironi This was only meant to be a point of information - the actual work will get done on YLD's infrastructure.

**Comment by g-sam** [comment]
Increased `pod_timeout` from 180 to 600. May eradicate our errors.

**Comment by g-sam** [comment]
We've had an instance of 

```
ERROR: Job failed: image pull failed: rpc error: code = Canceled desc = context canceled
```

since, which is the error related to resource usage that this ticket would address.
another way of addressing it is this ticket: https://github.com/elifesciences/elife-xpub/issues/71

**Comment by hdrury1** [comment]
How much of an issue is this? Can we leave it on the back-burner until we get the form done?

**Comment by diversemix** [comment]
This is being moved to Jenkins

@giorgiosironi @damnhipster
