### ISSUE TITLE
Use ScienceBeam `include` parameter

### ISSUE THREAD

**Issue by de-code** [elifesciences/elife-xpub#1773]
## Subtasks

- [ ] `include` parameter set to `title` for ScienceBeam requests

## Assumptions and notes
- The time to extract might vary depending on what ScienceBeam is asked to extract
- For that reason the `include` parameter was introduced (https://github.com/elifesciences/sciencebeam/issues/51)
- To extract only the title, add `include=title`, e.g. `POST /api/convert?include=title&filename=file.pdf`
- The effect will be that GROBID is only executing the header model and it is also only parsing the first three pages (assuming the title is found there)
- (The file could also be reduced before sending it to ScienceBeam)

/cc @diversemix

**Comment by diversemix** [comment]
Thanks for the putting this on my radar ... I anticipate this will help us improving the user experience by making times more predictable :+1:
