### ISSUE TITLE
Fix styleguide asset ref paths

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1790]
## Background
We currently replace all asset paths within the styleguide deployed from PRs to fetch from a relative path from the `index.html` hosted in an S3 bucket instead of `/assets/` served up by the server in a full deployment. 

See : https://github.com/elifesciences/elife-xpub/blob/develop/webpack/webpack.styleguide.config.js for details.

## Issue

It looks like the recent moving of code has caused the webpacks config to no longer replace the `/assets/` reference with the relative `./assets/` path. This is causing assets not to load on styleguide. A brief investigation confirmed these assets are still being hosted within the S3 bucket collections so it should just be the reference that is causing this problem.

**Comment by erezmus** [comment]
Doesn't seem to be an issue anymore
