### ISSUE TITLE
Submission email sent too early

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1816]
see: https://elifesciences.slack.com/archives/C6MJK1RD4/p1553785394003900

/cc @hdrury1 @Susanna-eLife - feel free to add any more detail but I think the conversation captures it!

**Comment by hdrury1** [comment]
This is worth investigating ASAP.

**Comment by diversemix** [comment]
@hdrury.... I'm only sending the confirmation email out when the meca export is successful... 

So the code reads - if its successful then send confirmation email to the user ... else send error email to tech alerts
