### ISSUE TITLE
Move User resolvers into the user-model and submission component packages

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1824]
## Background

#1801 moved the User ORM files out of the top level `/server` directory and into their own `component-model-user` package.

## Task

There are still files under the `server/xpub-server/entities/user` directory that need moving to their correct context package. Some of what is in the `resolver.js` doesn't belong in the component-model-user ie: 

```
    async editors(_, { role }) {
      return elifeApi.people(role)
    },
```

should probably belong in the component-submissions package as it relates to the submission wizard form although it does use the user model.

Decided to split this into several subtasks:

- [x] move resolver for component-user (#1827)
- [x] move resolvers for component-submission (#1828)

**Comment by hdrury1** [comment]
@erezmus is this epic now done?
