### ISSUE TITLE
Stale information on 2nd Submission

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#185]
When you submit a manuscript the second time around - all the information from the first time round is present in the forms.

1. Click "Submit a Manuscript" from the hompage and go through the process till submission
2. Click "Submit a Manuscript" from the hompage a second time.
3. Observe the information is the same as the first time round

I expected these to appear as the first time round.

**Comment by tamlyn** [comment]
This is expected, pending #168 which handles the final submission and changes the stage to `QA`.

**Comment by hdrury1** [comment]
Given #168 has now been merged, can this issue be closed @diversemix?
