### ISSUE TITLE
Update links to transparent reporting form in Author Guide

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1855]
Should link to new form: 

`https://elife-cdn.s3.amazonaws.com/xpub/guides/transparent_reporting.pdf`
and
`https://elife-cdn.s3.amazonaws.com/xpub/guides/transparent_reporting.docx`

**Comment by diversemix** [comment]
@hdrury1 I believe these links are already correct ... did you want to check that the they are the same?

I checked they are both linking to one tagged as "March 2019"
