### ISSUE TITLE
Add 'publicUrl' to config

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#187]
At the moment in the configuration we only have the "baseUrl" which is the url of the local server - not the one of the public server. We need to ensure we have two configuration items as they are not always the same. I suggest we use 'publicUrl' so that whenever we render a link to the site we use the public one not the internal web server running using "baseUrl"

**Comment by tamlyn** [comment]
Shouldn't baseUrl be the URL of the public server? Why do we need to know the URL of the local server?

**Comment by diversemix** [comment]
... its mainly for the port ... the baseUrl ... has the port slapped into it which may not be correct.

**Comment by tamlyn** [comment]
In development the baseUrl defaults to localhost + the port. In production baseUrl is undefined. The expectation is that it will be set to the public base url of the website which may or may not specify a non-default port. 

Perhaps the option would benefit from being renamed but I still don't see any need for a separate option.

**Comment by diversemix** [comment]
... ah ok ... this makes sense. I was trying to serve up a local instance to Hannah using `ngrok` and this is what caused the issue. I'm happy leaving it as is if production can set the public facing url with `baseUrl` but agree with you - maybe next time we are in there we can rename it ;)

**Comment by hdrury1** [comment]
@diversemix Can this be closed down now?

**Comment by diversemix** [comment]
Closing out for now
