### ISSUE TITLE
Validate entire wizard on 'Submit' and feedback error(s) to user

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1875]
## Problem / Motivation
- WHO wants this? Submitters
- WHEN and WHERE do they want it? Upon clicking 'Submit' on the Disclosure step of the wizard, any validation error message should appear above the button
- WHAT do they want? A message to indicate that there is a problem with one or more of the wizard steps and that the user should review their input
- WHY do they want this? Currently the user is able to trigger the confirmation modal but not progress if there is any validation error within the wizard (e.g. on the files page). We do not feed this error back to the user, so the application simply appears broken.

## Proposed solution
- Validate the entire wizard when the user clicks 'Submit'
- If there are any errors, display a message to the user, e.g. _We're sorry but there appears to be one or more errors in your submission that require attention before you can submit. Please go back and review your submission before trying again._

## Clarification needed and assumptions

---

## Tasks

- [ ] A description of a task
- [ ] A description

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes

![image (4)](https://user-images.githubusercontent.com/17023702/55474659-a554c000-5609-11e9-9859-be078c7cf93c.png)

**Comment by Cooryd** [comment]
I think this can be closed as #1886 added the validation in with the list of pages that have errors.

@hdrury1 Can you have a check and confirm it looks as it should
