### ISSUE TITLE
Separate running of app from browser test startup

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#1902]
## Background
Browser tests are running quite slowly. The reason for that is that during the setup phase of each *.browser.js file, the app is being recompiled via webpack. This is due to the fact that the `startServer` function is calling the pubsweet routine to start the server and clobber the database.

The aim of this task is to get to a state where the app is built and run independently as a separate step and the browser tests are then run pointing at the instance.

## Tasks
* [ ] Get rid of the `startServer` method in `test/helpers/setup.js`
* [ ] As part of the `setup` method in the same file, add code truncate all the tables. This is needed as we won't be clobbering the db because of the previous step.

## Notes
Running the tests will therefore involve the following steps
* Serve the app in production mode with test config:
`NODE_CONFIG_ENV=test NODE_ENV=production yarn run server`
* Run the browser tests
`yarn run test:browser`

**Comment by diversemix** [comment]
Trying to get this to run locally ... need to set the port in `config/test.js` to `3000`
