### ISSUE TITLE
Create separate Dockerfile for browser tests

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#1913]
Currently, the container for browser tests uses the Dockerfile for building the image which builds the whole app for production which is not needed.

Copy and customise Dockerfile to a new one specifically for the browser test container keeping only what we need

**Comment by giorgiosironi** [comment]
Looks like this is [implemented](https://github.com/elifesciences/elife-xpub/blob/develop/Dockerfile-test_browser)?

**Comment by diversemix** [comment]
Agreed - shall we close @erezmus
