### ISSUE TITLE
Make 'Files' page instructions clearer

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1930]
Based on user feedback, they are struggling with the 'Files' page of the wizard, as they often have a pre-written cover letter they wish to upload. 

As a first step, we should separate the page subtitles to make clearer that there are two components on the page- the text box and a dropzone molecule. We should also remove the questions from the text box, and display them as instructional text on the page instead to emphasise that the text box should be filled. 

/cc @chugginselifesciences

**Comment by chris-huggins** [comment]
![image](https://user-images.githubusercontent.com/41907215/56573914-fa0caa80-65b9-11e9-9a4d-d7b6d8cba873.png)

@hdrury1 What do you think of the wording? We don't want to force people so I haven't said anything like **"...please ensure you answer the following questions..."** but not sure if **"...Your work is more likely to progress..."** is accurate?

**Comment by hdrury1** [comment]
@acollings have you any thoughts on the above wording? Perhaps something similar to what we have in the Author Guide ("To help with the initial evaluation of your submission, you should aim to answer the following questions in your cover letter:

How will your work make others in the field think differently and move the field forward?
How does your work relate to the current literature on the topic?
Who do you consider to be the most relevant audience for this work?
Have you made clear in the letter what the work has and has not achieved?

In addition, please upload any related studies that you have published recently or have under consideration elsewhere as supporting files and describe them in your cover letter.") would work?

Andy, to be clear, the longterm plan is to allow authors to upload a cover letter file... but this is an iterative first step towards that, and will help us test some assumptions we are making.

**Comment by acollings** [comment]
Thanks @hdrury1! Your wording sounds good and overall this sounds good as an interim step!
