### ISSUE TITLE
"Add more supporting files" shown on files tab in wizard before any files are uploaded

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1933]
**Describe the bug**
The wording in the link to add supporting files is not showing correctly in its initial state. The wording is `Add more supporting files (optional)` which should only be shown after one or more supporting files have been added

**Steps To Reproduce**
Start a submission and add a manuscript file. Look at the text below. 

**Expected behavior**
It should say `Add supporting files (optional)` until one or more files have been added. If all have been removed again it should revert to the original wording (i.e. lost the word "more").

@hdrury1 There's been some feedback that it's not clear what the supporting files should be... I wonder if we should take another look at this instead to be more descriptive in the link, or add some additional text on formats etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/41907215/56573605-620ec100-65b9-11e9-9821-78866a2a6961.png)

**Comment by chugginselifesciences** [comment]
![image](https://user-images.githubusercontent.com/41907215/56573914-fa0caa80-65b9-11e9-9a4d-d7b6d8cba873.png)

@hdrury1 What do you think of the wording? We don't want to force people so I haven't said anything like **"...please ensure you answer the following questions..."** but not sure if **"...Your work is more likely to progress..."** is accurate?

**Comment by chris-huggins** [comment]
@hdrury1 I'm also wondering if we need to describe what the cover letter is for... or what it should be aiming to do? At the moment we assume authors know, which is likely but perhaps not best practice.

So maybe something like "To help us evaluate your submission please paste in your cover letter or simply answer the following questions".

This should give those with no cover letter some guidance, but doesn't imply authors with an existing cover letter _need_ to update it to be considered.
