### ISSUE TITLE
Ensure 'Preview' link opens PDF in browser tab

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1965]
The 'Preview' link within the manuscript upload component currently downloads the file as uploaded by the user, but we should look to update this functionality so instead the PDF is opened in a new browser tab.

Depends on #1970

**Comment by chris-huggins** [comment]
@hdrury1 Just to check the outcome of the stakeholder meeting was to delay this and track how many people use this link before we invest the time into this ticket?

**Comment by hdrury1** [comment]
Closing this down. This is a question of browser, rather than application, functionality.
