### ISSUE TITLE
Ensure 'Preview' link saves the manuscript's file extension

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1975]
**Describe the bug**

Attempting to download/preview an uploaded manuscript file in firefox showed the below dialog, which only had the option to open with "text editor" on Mac, which opened a text file that wasn't readable. Choosing "Save file" seemed to have no result. This means in Firefox on Mac I haven't been able to preview or download the manuscript file.

![image](https://user-images.githubusercontent.com/41907215/57127433-5a54d680-6d88-11e9-8510-d84011cdec45.png)

In chrome the file downloads but is not obviously a PDF or docx file. Chrome or OSX manages to open it as a PDF however. With .docx it opens as a textfile, which removes all formatting etc. 
I don't have MS word, but "pages" usually manages to open .docx correctly, so not currently behaving as expected.

![image](https://user-images.githubusercontent.com/41907215/57128859-a3a72500-6d8c-11e9-83b3-49e7e32823c6.png)

**Expected behavior**

This may be just on Mac, I'm not sure, but I assume user expectations would be to see their file download or open in the format they uploaded it and with the same filename. Currently on Mac it's downloading as a text file.

I would say this is doing more harm than good as may lead users to believe there was an error when there is not.

**Comment by Cooryd** [comment]
This will almost certainly be to do with us not storing the extension on the file when saving it in s3

**Comment by hdrury1** [comment]
Edited the title to reflect this.
