### ISSUE TITLE
Users cannot scroll list of editors on Windows 7, Firefox 66

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#1980]
**Describe the bug**
* Login to the application
* Start a new submission and fill in details
* In the editors step you cannot scroll using the scroll bar, only with mouse or trackpad or up and down arrows

**Expected behavior**
It should scroll down the list of editors

**Screenshots**
![elife-scroll-bug-firefox](https://user-images.githubusercontent.com/2045191/57434929-03417c80-7234-11e9-8521-bad2b6a882d1.gif)

**Device, Operating System and Browser**
Windows 7, Firefox 66

**Comment by hdrury1** [comment]
This is affecting a not insignificant amount of users according to GA- around 12%. @erezmus any indication of how big a fix it is?

**Comment by erezmus** [comment]
@hdrury1 not sure but will update here as soon as I get an idea

**Comment by erezmus** [comment]
The cause of the bug was that the scrollbar of the body elements was overlayed above the modal overlay element (even though the overlay had a higher z-index). Solution is to disable scrolling of body and html elements when modal is open and re-enable it when its closed.

The best place I found to put it was in the componentDidUpdate lifecycle hook
