### ISSUE TITLE
Logged in user presented with green login screen

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1984]
**Describe the bug**
When a user is logged in via the Journal site they are presented with the green ORCiD login screen upon accessing reviewer.elifesciences.org.

**Steps To Reproduce**
1. Navigate to elifesciences.org
2. Click the 'Login with ORCiD' button and log in
3. Navigate to reviewer.elifesciences.org (via URL bar or 'Submit My Research' button
4. Observe green login screen:

<img width="1249" alt="Screenshot 2019-05-15 at 12 40 02" src="https://user-images.githubusercontent.com/17023702/57772900-997f1200-770e-11e9-95f8-e6db9aec9a16.png">

**Expected behavior**
Once logged in via the Journal site, on reaching reviewer.elifesciences.org the user should only be presented with the blue Continue screen (rather than being invited to log in again):

<img width="1261" alt="Screenshot 2019-05-15 at 12 41 32" src="https://user-images.githubusercontent.com/17023702/57772969-ccc1a100-770e-11e9-8302-69393bc9475e.png">

May be related to #1652 and #1904

**Comment by erezmus** [comment]
So after having a look on staging, it seems that the journal is redirecting to the url

https://staging--xpub.elifesciences.org/login

According to the LoginPage.js code, it looks for a token in the history.location.hash (so i'm guessing the hash of the url) in order to do the token exchange, but it seems that the hash is not passed from the reviewer.

So, bug in reviewer or am i missing somethign?

**Comment by giorgiosironi** [comment]
I think I can reproduce this, the redirect I see from `https://continuumtest--cdn-journal.elifesciences.org/submit` is:
```
HTTP/2.0 302 Found
...
location: https://staging--xpub.elifesciences.org/login
```

**Comment by thewilkybarkid** [comment]
Pretty sure we've been here before, and the cause is the old EJP logic is still present in the CDN, which doesn't take cookies into account. Removing that should cause it to work (try https://prod--journal.elifesciences.org/ directly (ie bypassing the CDN), which works as expected.

**Comment by erezmus** [comment]
ok i can confirm that using https://continuumtest--journal.elifesciences.org/ instead of https://continuumtest--cdn-journal.elifesciences.org makes the issue dissapear. How do we remove the old EJP logic from CDN?

**Comment by thewilkybarkid** [comment]
Need to remove https://github.com/elifesciences/builder/blob/master/src/buildercore/fastly/vcl/journal-submit.vcl.tpl (requires manual deployment). I'm heading home shortly, can tackle in the morning if @giorgiosironi doesn't beat me to it.

**Comment by giorgiosironi** [comment]
It's 4:40 PM so too late for today given there are also pending updates for `journal--prod` for the containers rollout. I can do it for `staging` at the moment.

**Comment by giorgiosironi** [comment]
`staging` is fixed. Tomorrow morning we apply it to the other environments.

**Comment by giorgiosironi** [comment]
Can you confirm `staging` works as expected in all cases so that we roll out to `prod`?

**Comment by erezmus** [comment]
so i can confirm that on https://continuumtest--cdn-journal.elifesciences.org if i'm logged in to orcid and click on the submit my research button, i'm no longer asked to login again in xpub

so i think its all good on `staging`

**Comment by giorgiosironi** [comment]
Applying to `end2end` and `prod`.

**Comment by hdrury1** [comment]
Good to close?

**Comment by erezmus** [comment]
@hdrury1 waiting until its done

looks like the end2end worked:
https://alfred.elifesciences.org/blue/organizations/jenkins/process%2Fprocess-clean-end2end/detail/process-clean-end2end/684/pipeline

not sure about prod

**Comment by giorgiosironi** [comment]
Tests failed in https://alfred.elifesciences.org/job/test-elife-spectrum/334/console on the xpub login, so not a good sign, they may need to be updated. Will solve that before updating `prod`.

**Comment by giorgiosironi** [comment]
So, what happens now is that after following `Submit my research` xpub asks the user to login immediately; but after login is performed, the welcome page `Before you start` is shown; end2end tests need to be updated to take into account that or they will stop there rather than going through the whole flow.

**Comment by giorgiosironi** [comment]
Tested and applied to `prod`; close upon verification it behaves the way you want it to.

**Comment by hdrury1** [comment]
Tested and working according to product reqs, so closing down.
