### ISSUE TITLE
Investigate if authsome is available with current pubsweet version

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1986]
## Background

We aren't currently on the most up to date version of `pubsweet` or `pubsweet-server` we need to investigate if this is available to us or if we will need to use the authsome library directly until we have upgraded.

**Comment by will-byrne** [comment]
We have authsome version 0.1.0 in the versions of pubsweet-client and pubsweet-server we are currently using which is the latest version that has been released. So we can use it and not have to worry when we upgrade to the latest version of pubsweet.
