### ISSUE TITLE
Investigate changes needed to data model for authorisation

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1987]
## Subtasks

Our current db schema and ORM models aren't set up to account for user authorisation. We need to investigate how some of the other pubsweet users are setting up authorisation / permission modelling and plan the migrations / ORM changes we will need.

**Comment by petereast** [comment]
Before we do this, we should probably settle on an authentication model. @hdrury1 said something about using a scheme that's similar to that used by Google groups. The way I see it, we've got a few options in how we go about doing this:
- **Copy Hindawi's use of `authsome`:** They've got a model, maybe we could just do exactly what they're doing, but we don't know how well that meets our requirements. Maybe some further investigation into how their scheme works would be a good idea.
- **Use `authsome` and develop our own polices based on our own requirements.**: We could use authsome as a wrapper to execute some our own policies - all `authsome` does is pass models into the policy handlers and select policies based .
- **Don't use `authsome`and build our own permissions system**: Authsome isn't designed for the permissions model we've come up with, so adapting our logic to use authsome might put us in a tricky position down the line and might make it harder for us to adapt. Obviously we can't tell what to do before we thouroughly gather some requirements and fully evaluate what `authsome` can and can't do.

**Comment by diversemix** [comment]
We currently have Users and User Groups (Team) in our model - we also need to add Permission and Permission Groups. Then we can do the standard set theory of mapping UserGroups to PermissionGroups. Example here: https://github.com/diversemix/xpub-skel/blob/master/src/elife-server/xpub-accesscontrol/index.js
