### ISSUE TITLE
E-mail re-tries

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#199]
# Description

We should have a number of retries for the e-mail component. If the e-mail fails to get sent, the component should try sending it a couple more times.

We can make these changes at component level in PubSweet[1], or have our own retry mechanism.

[1] - https://gitlab.coko.foundation/pubsweet/pubsweet/tree/master/packages/components/SendEmail-server

**Comment by hdrury1** [comment]
@dryhten Can you outline the pros and cons of both approaches? If the coponent already exists it makes sense to me to save ourselves the work of implementing our own.

**Comment by dryhten** [comment]
@hdrury1 
The only pro I can think of right now: if the SMTP server goes down for some reason (for a brief period of time - this can happen for various reasons but it's a rare occurrence) this will account for it.

Cons: no cons other than having to write code for it :) It's not something hard to do either.

The pubsweet component doesn't do retries at the moment. If we decided to do it at component level we would have to do a merge request to pubsweet, which might take a while (we have to discuss this with jure first and if he agrees with it then we write it and push it there waiting to be merged for probably like a week). If we come up with our own mechanism it will be faster (and maybe we write it in such a way so that we can re-use it for other components too).

**Comment by hdrury1** [comment]
@dryhten As per discussion, let's implement our own mechanism and then feed back to PubSweet.

**Comment by diversemix** [comment]
> The only pro I can think of right now: if the SMTP server goes down for some reason (for a brief period of time - this can happen for various reasons but it's a rare occurrence) this will account for it.

Network connectivity to the mail server is a lot more likely and always should be catered for. IMHO

**Comment by giorgiosironi** [comment]
> What strategy do you currently use for this?

Bear with me and have a :coffee: ...

The `localhost` Postfix + AWS SES takes care of this for other applications. Postfix has a [local queue](http://www.tech-g.com/2012/07/15/inspecting-postfixs-email-queue/) which holds mails rejected by SES. This has happened in the past when we reached our daily quota for example, we requested the increase and Postfix worked through the queue when SES stopped throttling.

In a single node environment having a off-the-shelf daemon running on `localhost` is pretty robust, you can consider it like `cron` or `sshd`. There is no network connectivity to take care of.

In a container-based environment we may have a single stateful pod containing this to centralize this queue, as that's the easiest way to check the queue's size for observability. That introduces network connectivity problems, and also doesn't provide high availability.

If you think of external operations in general (pushing some data somewhere) you may decouple from their failures by introducing a task queue in the application (e.g. RabbitMQ or similar) that can be configured with multiple replicas for high availability. That becomes the dependency you cannot isolate from (what if I can't reach the RabbitMQ servers/pods?) in addition to the database.

The most robust way to decouple from external failures would then be to commit "tasks to do" in a single transaction with the current database (Postgres) changes. A separate container(s) can pick up the tasks from a table, performing all the retries that are needed; contention of competing consumers of the tasks table is a concern for this choice. In this case, the task would simply be getting the mails to the Postfix pod. This is [astronautical](https://www.joelonsoftware.com/2001/04/21/dont-let-architecture-astronauts-scare-you/) for emails, but may emerge later if there are notifications to deliver to other, possible unreliable or far away systems e.g. EJP.

**Comment by giorgiosironi** [comment]
A few things have changed in this area: we are now using AWS SES directly through SMTP. Possible errors are lack of connectivity and quota being reached; but it's a managed service that should always be up so it's a low priority to deal with failures there.
