### ISSUE TITLE
Add an withAuthsomeMiddleware wrapper to be used at the resolver level 

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1990]
## Task

Following #1986 configure the application to use authsome and create a middleware wrapper similar (or the same 👍 ) to hindawi's https://gitlab.com/hindawi/xpub/xpub-review/blob/develop/packages/helper-service/src/withAuthsomeMiddleware.js that can be passed authorisation policies.

It might not be worth wrapping resolvers in this yet if it causes issues. Just getting the files/ config in should be fine.

**Comment by Cooryd** [comment]
I"m going to attempt to bring in the `@pubsweet/models` dependency before doing this as it'll make the process of passing data models down to the authsome policy functions easier.

see #2003

**Comment by petereast** [comment]
The Hindawi code is too horrible. If I got a PR with that in it, I would definitely not approve it, I think we should look into the functionality and rewrite it more clearly, without and nested reducer-ternary statements or any of that rubbish - this is a critical piece of glue for some equally critical business logic, it's too risky to introduce any ambiguity or unnecessary complexity here.

**Comment by petereast** [comment]
Quick question: Is adding policies part of the scope of this ticket? If not then I'm not sure what else to be doing...
