### ISSUE TITLE
Create latex conversion step for INK (in Node)

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#20]

**Comment by g-sam** [comment]
Several options discussed here: https://tex.stackexchange.com/questions/39309/convert-latex-to-html

This needs more clarification as to exact requirements.

**Comment by BlueReZZ** [comment]
We have an eLife LaTeX template that Overleaf built for us:  https://www.overleaf.com/latex/templates/elife-latex-template/csqxykvsnyxm#.WfctKmi0MuU

**Comment by g-sam** [comment]
Nice. In principle people could modify this, add their own packages, etc. Do we say we support all basic LaTeX + only the packages in the template?

**Comment by g-sam** [comment]
Following a call with @jgilbert_prod and @sian on Slack, we'll begin by supporting the eLife template only and then see if anyone complains.

**Comment by g-sam** [comment]
Basic latex to pdf conversion step complete
