### ISSUE TITLE
Track use of the 'Preview' link

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2002]
## Problem / Motivation
- WHO wants this? Product and design
- WHEN and WHERE do they want it? On the new 'Preview' link that allows a user to download the manuscript file they have uploaded
- WHAT do they want? Simple tracking so that we can identify how many users are interacting with this feature
- WHY do they want this? We'd like to know how useful this feature is for users, if it is addressing their needs and how much time we should spend iterating on it.

## Proposed solution
- Implement a GA tracking code?

---

## Tasks

- [ ] A description of a task
- [ ] A description

## Technical notes
- We could use this technology
- More notes or suggestions

**Comment by chris-huggins** [comment]
I think while we're working on this it might be worth adding tracking to the "pre-fill your details" option on the author details page - see https://github.com/elifesciences/elife-xpub/issues/2012
