### ISSUE TITLE
common conventions for writing stateful components

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#201]
See https://github.com/elifesciences/elife-xpub/pull/182#discussion_r194452326

For example, due to the use of [`transform-class-properties`](https://github.com/elifesciences/elife-xpub/blob/develop/yarn.lock#L1105), the general idea seems to be that we use es6 arrow functions & therefore there's no need to bind in the constructor.

As I understand it, this would also mean that we don't actually need to be using the constructor, super pattern?

Might be worth coming to a consensus on which conventions to use, so there is consistency throughout our project?

**Comment by g-sam** [comment]
I randomly vote for property initializers.

**Comment by diversemix** [comment]
I randomly vote for pig licences .... or is that random!? ;)

**Comment by tamlyn** [comment]
I vote for inline functions https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578

**Comment by jsms90** [comment]
Yeah I think arrow functions makes sense.

I like what @tamlyn's article is saying - not measuring your performance = you don't _know_ if it's having an impact. Data-driven decision making ftw :+1: But surely you can still reason about whether it's going to have a performance impact, just by understanding how the 2 options work internally & understanding what you're building?

I quite like [this article's performance explanation](https://medium.com/dailyjs/demystifying-memory-usage-using-es6-react-classes-d9d904bc4557). I'd say this is the main reason that we can go with arrow functions:
> There is one caveat to all of this. The memory saving only applies if you are making multiple instances of a class. A single list view in your app, for example. But for classes that you instantiate multiple times (a list item for example), you will see a memory savings.

It seems that, at least for the moment, the we're not creating enough instances of the classes that we're writing for arrow functions to have a huge performance impact. So IMO the benefits outweigh the costs.

**Comment by jsms90** [comment]
How do we feel about state outside the constructor?

The most informative thing I've seen written so far is probably [this article](https://itnext.io/property-initializers-what-why-and-how-to-use-it-5615210474a3). As far as I can tell, the choice is largely a stylistic preference & I'm not sure that I'm strongly in either camp.

I guess the reason that people are trying to get away from using the constructor is because they don't appreciate the use of a syntax which misrepresents how JS inheritance works? Guessing none of this is news to you guys, but [here's a detailed article on that concept](https://davidwalsh.name/javascript-objects-deconstruction).

The only particularly persuasive thing for me comes from the first article I linked - that staying away from the constructor might have an effect on the way you write your code. Namely, encouraging you to defining your methods as separate, pure functions outside the class, which "makes it easy to test because it has no side effects"

Thoughts?

**Comment by tamlyn** [comment]
Defining initial state as a class property is more declarative 👍

**Comment by diversemix** [comment]
@seanwiseman @davidcmoulton  .... feel free to contribute too.

**Comment by dryhten** [comment]
I vote for using `transform-class-properties`. The code looks better and it seems to make my life easier.

**Comment by tamlyn** [comment]
Just to clarify, is this discussion specifically about event handlers or is it about deciding on a style for all class methods?

If the former then I think the consensus is (correct me if I'm wrong) to use inline functions as these read best. If the latter then I don't personally feel this is a decision that needs to be made but if it is then it looks like the consensus is class properties because of their more predictable behaviour in regards to `this`.

**Comment by diversemix** [comment]
I'm unassigning myself from this @jsms90 - can this be closed?
