### ISSUE TITLE
Determine percentage of completed submissions (and those with supporting files)

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#2011]
Can we create a database query that allows us to track/review the number of submissions completed vs. started within e.g. 7 days.

It would be useful to understand how many submissions are/aren't being completed... we"re using hotjar to track drop-offs during the submission wizard but it doesn't record those that come back to finish the submission later/after exiting.

HotJar suggests (only based on a week so far) that only 28.8% of new submissions are completed but this doesn't include those coming back to finish later.

_**Is this something we can surface/add to reports in GA?**_

![image](https://user-images.githubusercontent.com/41907215/58166967-d99c4280-7c82-11e9-95d2-563f944a4bf5.png)

**Comment by chris-huggins** [comment]
I've added that it would be great to also find out what percentage of submissions have supporting files. I'm assuming we can calculate this by querying the database to see, of all completed submissions, how many have supporting files.

The alternative would be to track events on the "Add supporting files" options but authors could click multiple times so I feel this would be more conclusive.

I'm assuming these can be done as part of the same ticket?

**Comment by hdrury1** [comment]
Going to serve this one into @diversemix's court.

**Comment by diversemix** [comment]
I think we need to talk about this ... to determine if this is more part of data-hub than xpub?

/cc @BlueReZZ

**Comment by diversemix** [comment]
After conversation with @hdrury1 ... Agreed to put another section in the tech alerts

/cc @chugginselifesciences
