### ISSUE TITLE
Make submit completely async

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2035]
The user action of submitting should be asynchronous, other than validating the data the user should not need to wait for any server-side operation.

**Comment by petereast** [comment]
It's easy to make the export run asynchronously, but what's not so easy is testing that it actually runs as the tests don't have anything to wait for.
Maybe a solution to this would be for the `updateManuscript` function to return a tuple e.g. `(BrowserResult, Promise<MecaExportResult>)` which is unpacked by something in the resolver?

**Comment by petereast** [comment]
Actually, the more I think about it, the more unhappy I am with the '_fire and forget_' pattern - I think we should either:
1. Display a loading indicator to the user when the request is running. The user shouldn't mind waiting 1-3s to submit the manuscript they've spend the last 6months writing (easier, quicker)
2. Dispatch a task to a task queue, for another part of the code to pick up (more scalable, more reusable)

I think using number 2 would be better long term, but it would require deploying a new service (either RabbitMQ or Redis, or even some randomly named Amazon service), so I'd like to have a discussion about it @diversemix @erezmus @will-byrne @Cooryd

**Comment by diversemix** [comment]
The rationale for the 'fire and forget' pattern is to isolate the user from the system - they only need to know their manuscript has been submitted ... on the other hand eLife will know that it has and if there is an issue or not then we can handle it on our end rather than have the user worry about it.

/cc @hdrury1 @chugginselifesciences

**Comment by diversemix** [comment]
@petereast ... I like your idea though, so let's raise this as a separate issue (for the future). Putting this simple fix in now will benefit the exiting users, then we can consider this longer term solution when we have the infrastructure to do it :wink:  :+1:
