### ISSUE TITLE
Jenkins Dashboard for xPub does not show a failed deployment to Production or Staging

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2037]
Need to fail in some visible way - or add a new task? 

The status of this dashboard should reflect the CI/CD pipeline.

**Comment by giorgiosironi** [comment]
Referring to https://alfred.elifesciences.org/view/elife-xpub/ ? A failed deployment should show up as a big red rectangle there?

**Comment by diversemix** [comment]
I'm wracking my brain now why I raised this (pretty soon after returning from holiday) ... going to dig around and see why. Pretty sure that it was green even though it had not deployed.

**Comment by giorgiosironi** [comment]
If you had the `elife-xpub--prod` lock on, it may be in a strange state because it gets blocked immediately when it runs; but can't think of other cases.

**Comment by diversemix** [comment]
It might have been the use case when the `test-elife-xpub-source-repository` fails ... the other deployments use the older version - rather than failing themselves... although I don't see that as a big issue... I'm happy we close this and if we find a problem again I will raise a new bug with more information :)

**Comment by giorgiosironi** [comment]
:+1: for closing and reopening in case.

**Comment by diversemix** [comment]
Closing for the reasons above.
