### ISSUE TITLE
Change removeSupportingFiles resolver to not use Manuscript model

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#2039]
The `removeSupportingFiles` resolver calls the `supportingFiles.removeAll` method which in turn, does a Manuscript model save.

This can potentially cause a race condition and should remove the files independently from saving the manuscript

**Comment by Cooryd** [comment]
Possibly won't matter but See #2045 and #2047 for the use-case issues raised for this functionality.
