### ISSUE TITLE
Share a validation schema between the frontend and backend

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#206]
# Description

Right now the backend uses a Joi schema for validation (once https://github.com/elifesciences/elife-xpub/pull/168 gets merged) and the frontend uses several Yup schemas for each page. There should be a way to store the schema in one place only and slightly change it (if that's the case) for frontend/backend. There has been discussions on whether to use Yup/Joi and why here https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/11 and here https://github.com/elifesciences/elife-xpub/pull/168#discussion_r194428142.

**Possible solutions**

1. Use Yup for both frontend and backend and keep a slightly more restrictive Yup schema in one place.
2. Ignore this issue and keep using Yup for frontend and Joi for backend :)
3. Use both Yup and Joi and find a way to convert between the two (so we would keep the schema for one package only)

Other suggestions welcomed.

**Comment by g-sam** [comment]
I very mildly favour 1 over 2. 1 would be nice. 2 keeps us closer to pubsweet. I'm against 3.

**Comment by jsms90** [comment]
@g-sam why are you against 3? And why would you be in favour of 1 over 2?

**Comment by tamlyn** [comment]
I think we first need to determine whether it's possible to have a single (yup) schema that satisfies the slightly different validation requirements of the client and the server.

If it isn't then we have to go with 2. If it is then I favour 1 simply because it avoids the schemas drifting out of sync.

**Comment by devinrhode2** [comment]
Pardon my asking here. I was just searching google for this topic of sharing validations between client+server. It looks like both joi and yup are listed in the package.json of this project. I'm just curious there's any interesting insights this project/it's developers could share with the greater community :)
