### ISSUE TITLE
Change the code in SubmissionWizard to be that found in NewSubmissionWizard

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#2086]
## Task

We need to remove the `newSubmit` route and implement the code found in NewSubmissionWizard on the `submit` route. Copy code over to the SubmissionWizard file to maintain history.

**Comment by diversemix** [comment]
Part of #2064

**Comment by Cooryd** [comment]
Blocked until #2083 #2084 #2085 complete
