### ISSUE TITLE
New updates to Author Guide

### ISSUE THREAD

**Issue by Susanna-eLife** [elifesciences/elife-xpub#2100]
## Problem / Motivation
Some updates have been made to the eJP Author Guide and I would like the xPub version to match.

---

## Tasks
1) Journal Policies -> Competing Interests.
Text should be updated to:
Authors, reviewers, and editors are all required to declare any competing interests that might be perceived to interfere with the objectivity of the presentation or handling of the work. Any relevant patents, patent applications, and products in development that relate to a submission must be disclosed in full, including patent numbers and titles. For further information on competing interests, see the recommendations of the ICMJE and the guidance provided by PLOS.

2) Initial submissions -> Limited Metadata -> Subject Areas(s).
"Genetics and Genomics" URL not working. It should be https://elifesciences.org/about/people/genetics-genomics

3) Initial submissions -> Single Manuscript PDF -> Intro, Results, Discussion, Materials and methods.
Text should be updated to:
[...] On first mention, please provide details of any manufacturers in the following format: company name, city, country (or state, if based in the United States).

Any footnotes (including commentary or footnotes embedded within the reference list) should be placed inside parentheses at the appropriate place in the main text.

4) Journal policies -> Competing Interests.
Text should be updated to:
Authors, reviewers, and editors are all required to declare any competing interests that might be perceived to interfere with the objectivity of the presentation or handling of the work. Any relevant patents, patent applications, and products in development that relate to a submission must be disclosed in full, including patent numbers and titles. For further information on competing interests, see the recommendations of the ICMJE and the guidance provided by PLOS.

5) Journal metrics tab has been updated for Q1 2019. I've sent Hannah a link to the new chart.js file.

**Comment by hdrury1** [comment]
Hi @Susanna-eLife, for future reference could you add any new tickets to the xPub project board when you open them and @hdrury1 rather than assigning me? (Let me know if I can help you do this!) :)

**Comment by chris-huggins** [comment]
@hdrury1 Might be worth reviewing together alongside https://github.com/elifesciences/xPub-features-roadmap-test/issues/22 and https://github.com/elifesciences/xPub-features-roadmap-test/issues/40

**Comment by Susanna-eLife** [comment]
@hdrury1 Ooops, yes, sorry :)

**Comment by hdrury1** [comment]
@chugginselifesciences I think these changes should be merged in as soon as the pipeline is fixed. We can definitely look at use of modals at a later time though!

**Comment by chris-huggins** [comment]
> I think these changes should be merged in as soon as the pipeline is fixed. We can definitely look at use of modals at a later time though!

Regarding updates to the contact pages it doesn't look like many people at all have looked at the Editorial and Production team pages, so I think it's fair to say it's a low priority to update them.
