### ISSUE TITLE
Pre-fill my details causes validation issues

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#211]
**Describe the bug**
Validation errors
![screen shot 2018-06-15 at 14 44 43](https://user-images.githubusercontent.com/8524685/41471216-eb9c6f62-70aa-11e8-93f3-892df1f27a55.png)

**To Reproduce**
1. Go to Submit a Manuscript
2. Fill out the form on page 1
3. Click on "Pre-Fill my details" using ORCiD
3. Watch the validation errors

**Expected behavior**
The validation errors do not occur and invalid fields are blanked.

**Comment by tamlyn** [comment]
This looks like an interesting one! I cannot reproduce it on latest `develop`. 

Could you add some more details? Which version, which environment, what steps were performed prior to this, does it happen reliably or is it intermittent.

**Comment by diversemix** [comment]
Its on the demo website ... let me check the version...

**Comment by diversemix** [comment]
Looks like this was never added, unless its hidden somewhere? https://github.com/elifesciences/elife-xpub/issues/105

**Comment by jsms90** [comment]
I believe it's in the top right hand side of the screen, next to logout?

This:
![image](https://user-images.githubusercontent.com/15656538/41606499-b7033414-73db-11e8-9a2e-8d987c880666.png)

**Comment by hdrury1** [comment]
@jsms90 This is the ORCiD, not the app version.

**Comment by tamlyn** [comment]
1. Visit a production deployment such as https://xpub-elife-staging.gateway.xpub.semioticsquares.com
2. View source

You should see something like this 
```
<!--
  | Package version: 1.0.0
  | Git hash: 3ac68bab5bb8fe17530d499d2e934fe181d8dd46
  | Build time: Wed Jun 20 2018 16:17:23 GMT+0000 (UTC)
  | -->
```

Does this not satisfy the requirements of this ticket?

**Comment by tamlyn** [comment]
See https://github.com/elifesciences/elife-xpub/issues/105#issuecomment-399031151
