### ISSUE TITLE
Investigate failing browser tests when re-integrating back into pipeline tasks

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#2115]
Pipeline still fails on browser tests once thy've been re-enabled. Investigate fixes to get this working.

**Comment by erezmus** [comment]
In: https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-xpub/job/PR-2103/8/artifact/build/screenshots/2019-06-13_11-08-56/test-11/HeadlessChrome_75.0.3770_Linux_0.0.0/errors/1.png

![Screenshot 2019-06-13 at 13 33 41](https://user-images.githubusercontent.com/2045191/59432735-ede5e200-8ddf-11e9-92f3-6d56a536f630.jpg)

looks like example@example.org backwards? then hash
