### ISSUE TITLE
Premature validation on files step

### ISSUE THREAD

**Issue by petereast** [elifesciences/elife-xpub#2135]
**Describe the bug**
There's something wrong in the files step where the validation fails when the file has finished uploading. I think it's related to a race condition between the graphql mutation and the validation being checked, where the validation is running before the file upload can complete - or something like that. Needs investigation though.

We think it's some to do with https://github.com/elifesciences/elife-xpub/blob/develop/packages/component-submission/client/utils/ValidationSchemas.js#L32

**Comment by Cooryd** [comment]
This is likely caused by the issue described here: https://github.com/elifesciences/elife-xpub/issues/2091
