### ISSUE TITLE
Validation of "click to agree" box not showing

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2156]
At the end on the Disclosure page the validation message for "click to agree" does not show.

**Comment by Cooryd** [comment]
On investigating it looks like there are two issues:

- CheckBox isn't correctly setting its `touched` property when changed. This looks like it's an existing issue in prod too.

- On submitting the form from the disclosure page it's not setting any of the fields to `touched` like it is on the other pages. This is because the code :

```
                          Object.keys(errors).forEach(errorField => {
                            if (typeof errors[errorField] === 'object') {
                              const flattenedSubfields = flattenObject(
                                errors[errorField],
                              )
                              Object.keys(flattenedSubfields).forEach(
                                subField => {
                                  formikProps.setFieldTouched(
                                    `${errorField}.${subField}`,
                                    true,
                                  )
                                },
                              )
                            } else {
                              formikProps.setFieldTouched(
                                errorField,
                                true,
                                false,
                              )
                            }
                          })
```

called on 'Next' isn't ran on submit.

**Comment by Cooryd** [comment]
I've raised #2164 to address the existing production issue of the checkbox not showing validation message on change. This issue will just address the validation message not showing on submit being pressed (a regression of production)
