### ISSUE TITLE
'Submit My Research' redirects straight to ORCiD log in

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2169]
**Describe the bug**
Clicking on 'Submit My Research' from the Journal homepage takes the user to the ORCiD login screen

**Steps To Reproduce**
Navigate to Journal homepage while logged out (use incognito mode if necessary)
Click 'Submit My Research' 
Observe ORCiD login page

**Expected behavior**
The user should be redirected to Libero Reviewer's 'Welcome' screen with green login button, so they can access the author and reviewer guides without being logged in

**Comment by hdrury1** [comment]
/cc @giorgiosironi and @thewilkybarkid 

I suspect this may have been implemented alongside the single sign out?

**Comment by diversemix** [comment]
Appears as though the redirect on `/submit` is exactly the same as on `/log-in` and both are to:
```
https://api.elifesciences.org/oauth2/authorize?state=2559c75c841bbf654ad1e1c36c450adb&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Felifesciences.org%2Flog-in%2Fcheck&amp;client_id=journal--prod
```

**Comment by diversemix** [comment]
@giorgiosironi did notify of this modified behaviour - here https://github.com/elifesciences/elife-xpub/issues/1984#issuecomment-499473116

**Comment by hdrury1** [comment]
Apologies, this was completely my bad. We'll need to change and revert the e2e accordingly.

**Comment by thewilkybarkid** [comment]
Opened https://github.com/elifesciences/journal/pull/1163.

**Comment by giorgiosironi** [comment]
Does this mean the revert of https://github.com/elifesciences/elife-spectrum/pull/176 or is it a new behavior?

**Comment by hdrury1** [comment]
Not immediately clear to me I'm afraid @giorgiosironi.

**Comment by giorgiosironi** [comment]
Merged https://alfred.elifesciences.org/job/test-journal/1715/ and it's getting to `end2end`. Current end2end tests correctly fail because they don't find the login button:
```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"button[data-test-id="login"]"}
```
Will run it while `journal` is deployed and before the rollback and force a merge if passing.

**Comment by giorgiosironi** [comment]
See #xpub-tech for the latest.

**Comment by giorgiosironi** [comment]
Fix [deployed](https://alfred.elifesciences.org/job/prod-journal/870/console), confirm if it works tomorrow.

**Comment by hdrury1** [comment]
Can confirm this is working in Production. Happy to close this off. Thanks @thewilkybarkid and @giorgiosironi
