### ISSUE TITLE
Production reporting errors "Cannot query field"

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2188]
Production has started to report errors (see screenshot).
This was alerted via New Relic : https://alerts.newrelic.com/accounts/1451451/incidents/73463008/violations

![Screenshot_20190626-070411_Chrome](https://user-images.githubusercontent.com/8524685/60156862-6471df00-97e5-11e9-8e23-42099b2eca3c.jpg)

**Comment by diversemix** [comment]
Looking at this, the error is coming from both nodes. It started soon after deployment and is still occurring now. I think its because I am on production and "auto saving" ... however I cannot see any problems appearing in the console of the browser.

**Comment by erezmus** [comment]
Managed to reproduce using the following process:

1. checkout to commit just before PR #2175:`git checkout de9c46`
2. Run the app in production mode:`yarn run app:browser`
3. Start a submission and keep browser tab open
4. Stop the app and checkout latest develop: `git checkout develop`
5. Run the app again in production as in step 3
6. In the browser tab, trigger an autosave by changing some field (e.g. cover letter)

The following error message should appear:
```
error: Cannot query field "updateManuscript" on type "Mutation". Did you mean "createManuscript", "deleteManuscript", "uploadManuscript", "submitManuscript", or "updateUser"? message=Cannot query field "updateManuscript" on type "Mutation". Did you mean "createManuscript", "deleteManuscript", "uploadManuscript", "submitManuscript", or "updateUser"?, locations=[line=2, column=3]
```
