### ISSUE TITLE
Investigate withGQL wrappers causing unnecessary re-renders

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#2199]
## Background

We were noticing performance issues within the submission wizard caused by entire step component (ie: `AuthorStepPage`) re-renders on user interactions like focusing on inputs. Originally we thought it was `Formik` causing  the extra re-renders but on investigating as part of #2088 we found it was the `Apollo` HOC wrapper causing the prop changes which are triggering the re-renders.

We need to investigate and see if we can optimise this wrapper so that it only triggers the re-render when the data being fetched by it changes.

**Comment by Cooryd** [comment]
https://github.com/elifesciences/elife-xpub/issues/2088#issuecomment-506712218 details how we found the issue.

**Comment by erezmus** [comment]
Seems to be related to this issue
https://github.com/apollographql/react-apollo/issues/1777

Upgrading to latest version (2.5.8) sees to help. Still getting re render on formik's touched changes

**Comment by erezmus** [comment]
actually scratch that, didn't change anything

**Comment by erezmus** [comment]
From my investigation, issue seems to be that when a blur event happens on an input, it calls the formik's internal `handleBlur` method which updates the touched state, hence causing a re render.

closing for now
