### ISSUE TITLE
Facilitate collection of last author information

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2208]
## Problem / Motivation

- WHO wants this? Journal Development Editor and Editorial department
- WHEN and WHERE do they want it? Between the last page of the submission wizard (Discloser step) and the 'Thank you' page
- WHAT do they want? Three questions inviting the submitting author to provide additional demographic information about the last (most senior) author of the paper
- WHY do they want this? In order to be able to track any bias implicit in our current peer review process and improve engagement

## Proposed solution
- Add a page between the last step of the wizard and thank you page in order to try and encourage users to provide responses to the questions asked
- Once the content is finalised, redirect the 'Submit' button to reach this page
- Save the answers in a new table in the database
- The answers should be linked back to a manuscript ID
- (Potentially) make this page a line in config.js so it is configurable for other journals/publishers

## Clarification needed and assumptions
- Final content of page to be provided by Editorial team via @chugginselifesciences 
- We only need to store manuscript ID, country, gender, time (all as strings)
- Information is provided optionally, so `NULL` is valid
- We do not need to export this information in MECA package

---

## Tasks

Typescript:
- [ ] Backend (#2209)
- [ ] Frontend (prop type checking), [Add ticket to do later]

Implementation:
- [ ] Infrastructure #2256
- [ ] Domain #2259
- [ ] Use Cases #2257
- [ ] GraphQL #2258

## User interface / Wireframes

<img width="444" alt="Screenshot 2019-07-02 at 14 16 06" src="https://user-images.githubusercontent.com/17023702/60515658-02791400-9cd4-11e9-9647-b955786a584f.png">

**Comment by erezmus** [comment]
For the country of residence should we be providing a list of countries?

/cc @hdrury1

**Comment by hdrury1** [comment]
Intended user flow:

<img width="837" alt="Screenshot 2019-07-11 at 13 50 53" src="https://user-images.githubusercontent.com/17023702/61052316-0c40fc80-a3e3-11e9-959a-501052cec3a2.png">

**Comment by hdrury1** [comment]
Done and implemented in production.
