### ISSUE TITLE
Plan the new Component

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2241]
We need to sit down and plan how we are going to create and div-y up the work. Output should include - folder structure, technologies and repository pattern plan.

It would be good to use this opportunity to create a component in a new shared understanding of how we'd all like to develop going forward. I suggest we all come with some sort of idea on how we'd like the code to look.

**Comment by erezmus** [comment]
Typescript:
- Backend (#2209)
- Frontend (prop type checking), [Add ticket to do later]

Implementation:
- Infrastructure #2256
- Domain #2259
- Use Cases #2257
- GraphQL #2258

**Comment by hdrury1** [comment]
Closing and adding tech tickets to the Epic.
