### ISSUE TITLE
Survey Component: Infrastructure layer

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#2256]
### Survey `survey`
Schema
- id: uuid

### Questions
Hard coded but via Repository with expectation to have a real table if needed
Proposed schema:
  - id:  uuid
  - survey_id: uuid
  - question: text

### Answers
Store them in database table `survey_answers`
- id: uuid
- survey_id: uuid
- manuscript_id: uuid
- question_id: uuid
- answer: text

## Migration

We need a migration for `survey` and `survey_answers` tables

## Repositories
Add Repository class(es)
TBD

**Comment by hdrury1** [comment]
Closing as obsolete
