### ISSUE TITLE
Update Heading atom to conform to the styleguide

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#226]
The Heading atom should look like the one in the [styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985).

Right now we use [Heading](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/ui/src/atoms/Heading.js) from pubsweet. If updating that component to look like the one in the styleguide via theme variables is not possible, then we should create our own Button atom (e.g. in `app/components/ui/atoms`).

**Comment by g-sam** [comment]
depends on https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/292/diffs
