### ISSUE TITLE
Create "Person Pod" component

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#227]
## Select Button
**User Story:**

_As a submitter I want to access the people picker from the submission wizard in order to select editor suggestions._

_As an editor I want to access the people picker from the article information screen in order to view submitter suggestions and assign editors and reviewers to the submission._

**Product requirements/Acceptance criteria:**

Functional: 

- Suggestions are required, but exclusions are not and this should be reflected in the text on the button (see wireframes)
- '+' icon on the right-hand side of the button should open the people picker modal.

**Designs**
![image](https://user-images.githubusercontent.com/15656538/42771010-afeff340-891d-11e8-98a7-26452f43024d.png)

---

## Person Pod
**Product requirements/Acceptance criteria:**
- The '+' icon is the only clickable part of the pod, indicated with a pointer change on hover

- Clicking the icon adds a tick to the pod and also adds the person's name as a tag under the search box

**Design(s):**
Component in the [invision styleguide](https://invis.io/D8KXOML3C6N#/302926985_components):
![image](https://user-images.githubusercontent.com/15656538/42823444-7141fffe-89d5-11e8-9f30-57a2c9dcf91d.png)

![group](https://user-images.githubusercontent.com/17023702/42878192-12c33484-8a84-11e8-948f-d4ed62149199.png)

The width of this component is dependent on its parent

**"Chosen" version - states:**
![image](https://user-images.githubusercontent.com/15656538/42822273-8afe02ba-89d2-11e8-9052-ae52b5c1f034.png)
![image](https://user-images.githubusercontent.com/15656538/42820332-cbf4b3f4-89cd-11e8-9c06-b5f6d3af202a.png)
![image](https://user-images.githubusercontent.com/15656538/42821826-590d0888-89d1-11e8-9dac-455ba27fb48e.png)
![image](https://user-images.githubusercontent.com/15656538/42824728-54defaee-89d8-11e8-9620-4774649d4b13.png)

Future states to consider (but not necessarily build yet):
![image](https://user-images.githubusercontent.com/15656538/42824680-3558157a-89d8-11e8-9f59-6e14aff2adf3.png)
![image](https://user-images.githubusercontent.com/15656538/42825366-c6f9baa0-89d9-11e8-8d88-34fae3340ffa.png)
![image](https://user-images.githubusercontent.com/15656538/42824612-1339b868-89d8-11e8-95cb-fe4415add3bc.png)

**Comment by jsms90** [comment]
This is part of the People Picker feature & should probably wait until the associated functionality and overall product requirements have been clearly defined.

**Comment by jsms90** [comment]
Agreed by @NickDuf on comments in invision

@hdrury1 are you happy to move this to the backlog for now?

**Comment by jsms90** [comment]
Tam's latest PR will fix the clicking functionality on the RHS of the button.

But putting it into the `PeoplePicker` has raised questions about the naming of `ChoosePersonPod` & `ChosenPersonPod`.

When an author is selecting using the people picker modal to select editors, the act of clicking on the '+' icon to select a person is "choosing". So Tam was saying that he kept going to put the `ChoosePersonPod` in there, instead of the `ChosenPersonPod` with an 'add' icon.

Instead, how about we use the names @hdrury1 originally suggested when creating these github issues:
- `ChosenPersonPod` -> `PersonPod`
- `ChoosePersonPod` -> `PersonPod.SelectButton`
?

**Comment by jsms90** [comment]
Note:

Of the "future states to consider"
- disabled state has been implemented :tada: 
- "status" is currently the (hide-able) 4th line in the `PersonPod`, as per designs, but this will need to be changed in future, when we actually make use of the 4th line for availability & no. of papers assigned

Validation shown in the invision styleguide will be implemented as part of a separate issue

I didn't see the extra product requirements about missing person information. So we've raised separate tickets for those :+1:
