### ISSUE TITLE
Create feature flag for survey

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2273]
see label on tin.

**Comment by petereast** [comment]
Why is this marked as <kbd>Server-Side</kbd> and not <kbd>Client-Side</kbd>? Shouldn't the feature flag switch the display of the client side component

**Comment by diversemix** [comment]
yes ... I guess its cos config is stored on the server side :)

**Comment by petereast** [comment]
I'm not convinced it needs to be a config thing - couldn't it just be a query string that's disabled by default until it's time to switch it on? - e.g. during development we go to `https://review.elifesciences.org/?_features=submission_survey`

**Comment by diversemix** [comment]
Talked f2f ... agreed that it will be in config ... enabled for staging and disabled for prod
