### ISSUE TITLE
Create database migration

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2275]
## Survey

Table `survey_responses` columns
- response_id : uuid
- submission_id: uuid
- response : JSONB[]

Example....
{
 questions: { 1: "what is ...?", 2: "why....?" }
 answers: { 1: "this" , 2: "that" }
}

**Comment by petereast** [comment]
Should we create this in the same way as the other ORM models are added, i.e. make a `component-model-survey`, or should we add it somewhere else, like inside of `component-submission`?
