### ISSUE TITLE
Create API tests for new survey mutation

### ISSUE THREAD

**Issue by petereast** [elifesciences/elife-xpub#2279]
## Questions
- How do we check that the response has been correctly written to the database?
- Does `api-test` need to know about feature flags?

**Comment by petereast** [comment]
Blocked by unfinalised changes to the api definition

**Comment by Cooryd** [comment]
As discussed over call we'll need to change the mutation resolver name to `submitSurveyResponse` as part of this issue. Integration tests will need to be aligned with this change.
