### ISSUE TITLE
Retry failed instance starts after a timeout

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2283]
can we increase the timeout on `test-elife-xpub` ? 
```
RuntimeError: Reached timeout 120 while waiting for nodes to complete boot
```

**Comment by giorgiosironi** [comment]
Need to diagnose what's happening first (is the server not running at all, does it come up but doesn't respond, is an healthcheck failing?)

**Comment by giorgiosironi** [comment]
May be referring to https://alfred.elifesciences.org/blue/organizations/jenkins/test-elife-xpub/detail/test-elife-xpub/1037/pipeline
That is the `elife-libraries--spectrum` node not being accessible after 120 seconds from boot, it's the one holding end2end tests.

**Comment by giorgiosironi** [comment]
However, the server was reporting well since 6:22 PM (6:28 was when the build gave up). Checking some logs.
Normal syslog?
```
Jul 10 17:21:36 spectrum--libraries.elife.internal syslog-ng[1023]: syslog-ng starting up; version='3.5.6'
Jul 10 17:21:36 spectrum--libraries.elife.internal syslog-ng[1023]: Syslog connection established; fd='8', server='AF_INET(54.164.8.26:514)', local='AF_INET(0.0.0.0:0)'
...
Jul 10 17:26:28 spectrum--libraries.elife.internal kernel: IPv6: ADDRCONF(NETDEV_CHANGE): br-c67e247f251a: link becomes ready
Jul 10 17:26:43 spectrum--libraries.elife.internal kernel: br-c67e247f251a: port 1(veth0497bf6) entered forwarding state
```
Suspect a botched boot but difficult to diagnose.

**Comment by giorgiosironi** [comment]
From experience botched boots don't resolve themselves, and need a restart. We could probably automated that in the `start` builder command: upon a timeout, retry once to `stop` the instance` and `start` it again.

**Comment by giorgiosironi** [comment]
Post mortem: https://github.com/elifesciences/tech-team/pull/20

**Comment by diversemix** [comment]
@hdrury1 / @giorgiosironi ... we ok to close this now?

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder/pull/523 still open for more testing.

**Comment by giorgiosironi** [comment]
Rolled out and used in https://alfred.elifesciences.org/job/test-elife-xpub/1068/; close at the end of the day if no adverse issues (it may take more time to encounter the race condition again).
