### ISSUE TITLE
Change/create Hide/show Panels

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#229]
We need a new component for the Hide/show Panel from [styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985).

![image](https://user-images.githubusercontent.com/15656538/41656871-54a5b540-7489-11e8-9141-41f3a0b957eb.png)

I would place this one in `atoms`.

**Comment by jsms90** [comment]
If I am interpreting the invision designs correctly, the place in the designs where this component is going to be used on the 3rd page of our wizard? So this component would replace what has currently been implemented?

**Current**
![image](https://user-images.githubusercontent.com/15656538/41656820-2d13be5a-7489-11e8-8688-57a1507e1e26.png)

**New**
![image](https://user-images.githubusercontent.com/15656538/41656871-54a5b540-7489-11e8-9141-41f3a0b957eb.png)

If so, this is currently being achieved by a combination of:
- pubsweet's `Checkbox` atom
- our `TextArea` atom
- both wrapped inside our `CalloutBox` component

See comment 5 on the invision designs, which I have just posted.
> What is a "hide/show panel", without a checkbox? Is this not just a TextArea? In which case, do we need the X icon?

If I am correct in my assumptions of where the hide/show component is being used in our app, then we don't need to create any new components.

But the X icon inside the TextArea/TextField (in the invision designs), is new. Is this to be used in all 3 places within the Manuscript Metadata page? Or only for the TextArea under the first checkbox?

If it's only for the first TextArea, then we simply need to alter the existing TextArea atom, to add this functionality. If product wants to have the X icon functionality in the TextFields as well, then we will need to create a new component that wraps TextField & TextArea. @hdrury1 perhaps we should get on a hangouts call to discuss product requirements for the Manuscript Metadata page?

---

Or have I misunderstood & the hide/show component is something which is to be used elsewhere?

**Comment by jsms90** [comment]
Based on @NickDuf's comment in invision, it seems that this refers to a component/components on page 4. Waiting on access to the latest invision designs for page 4.

**Comment by jsms90** [comment]
So, the designs above actually represent 2 distinctly different components:
### 1. 1st hide/show panel
![image](https://user-images.githubusercontent.com/15656538/41721383-9e251060-755d-11e8-8e29-8dfc0edb04b0.png)

This empty box with an X icon is actually part of a more complex component, represented on the new page 4 designs:

![image](https://user-images.githubusercontent.com/15656538/41721151-14059ef4-755d-11e8-8176-68554deef752.png)

So the component on the styleguide needs to include something which _generates_ the creation of this box (i.e. the button/link saying 'suggest more editors') as well as something that removes it (the X).

Previous designs didn't contain a way of removing these boxes from the screen once they are generated. This is new functionality necessitates a signficant change to the code, including the creation of a new component, but also a refactor of the current page 4 implementation.

Let's have a new feature issue @hdrury1?

### 2. 2nd hide/show panel
![image](https://user-images.githubusercontent.com/15656538/41721608-4d345174-755e-11e8-9698-5fe4260780a3.png)

This already exists & is currently called [`CheckboxGeneratedChild` in the code for page 3](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/submission/ManuscriptMetadata/ManuscriptMetadata.js#L14-L31). It employs a combination of `CalloutBox` & sub-components, including a checkbox
![image](https://user-images.githubusercontent.com/15656538/41656820-2d13be5a-7489-11e8-8688-57a1507e1e26.png)

But this is based on the old wireframes, where the box surrounded the whole component:
![image](https://user-images.githubusercontent.com/15656538/41721121-02016cec-755d-11e8-8e99-3b2d4dc5f196.png)

Now that designs have changed, the box doesn't surround the checkbox & there are 2 children inside the box - some text with a link as well, which in turn has its own functionality:
![image](https://user-images.githubusercontent.com/15656538/41721869-f0ebfa4c-755e-11e8-92c0-975a2d8d7634.png)

This is different again from the other checkbox-generated hide/show panels on page 3, which only have a single child

![image](https://user-images.githubusercontent.com/15656538/41722306-0258f3b0-7560-11e8-908b-31ccfccb9678.png)

@hdrury1 let's have a separate feature issue for this second type of hide/show panel?
