### ISSUE TITLE
Add ORM model and GraphQL typedefs for survey response

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#2292]
Create a new folder called component-model-survey with the following structure

```
component-model-survey-response/
  entities/
    survey-response/
      index.js
  index.js
  package.json
  typeDefs.graphql
```

* The `entities/survey-response.js` file should define a SurveyResponse model derived from the pubsweet base model
* the `typeDefs.graphql` should define the graphql type for the SurveyResponse
* the top `index.js` file should export the model, model name and graphql typedefs as done in other component-model-* packages
* Add an `updated` column to the `survey_response` table and rename column `submission_id` to `manuscript_id`

**Comment by diversemix** [comment]
@Cooryd / @erezmus ... I'm closing this
