### ISSUE TITLE
Investigation: What functionality are we currently leveraging from pubsweet-server

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#2318]
## Investigate

List the current functionality provided by `pubsweet-server`

**Comment by Cooryd** [comment]
- Sets up graphql (knex queries in connectors? 🤷‍♂)
- Registers components from config. (building graphql resolvers up ect.)
- Sets up socket connections (provides pubsub pattern)

**Comment by erezmus** [comment]
some info on connectors

> Connector: a layer on top of a database/backend driver that has GraphQL-specific error handling, logging, caching and batching. Only needs to be implemented once for each backend, and can be reused in many apps

https://blog.apollographql.com/how-to-build-graphql-servers-87587591ded5
