### ISSUE TITLE
Update manuscript upload widget to reflect product requirements and styling

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#234]
**User Story:**

_As a submitter I want to upload my manuscript file to my submission in order to receive feedback from a Senior Editor._

**Product requirements/Acceptance criteria:**

Functional:

- A user should be able to upload their manuscript file to accompany their submission information.
- A user should be able to preview their manuscript as it will appear to the editors in read-only format.
- A user should be able to overwrite a previously uploaded file with another.
- The system should pre-populate the submission wizard (page 3) with the manuscript title from within the uploaded file.
- The system should indicate the upload progress.
- The system should indicate any errors encountered during the upload process.

**Relevant links to design(s):**
[Styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985)
[Hi-fi component](https://drive.google.com/drive/u/1/folders/1UKwf0YVqBCMQFrF-oFeQ8i4_JKhkTyS9)

**Related open issues:**

- [ ] [Determine how best to fetch upload progress](https://github.com/elifesciences/elife-xpub/issues/135)
- [x] [Create e2e test](https://github.com/elifesciences/elife-xpub/issues/102)

**Comment by tamlyn** [comment]
Apart from the lack of progress reporting, my untrained eye cannot spot any visual differences between the app and the designs. @hdrury1 do you agree? If not, could you specify the things that need to be changed?

**Comment by diversemix** [comment]
Yeah I thought that too!

**Comment by hdrury1** [comment]
@tamlyn Can confirm that styling looks good, but will keep this issue open until the other product requirements have been met (i.e. we can reliably return upload progress to include title extraction).

**Comment by hdrury1** [comment]
Closing this down in lieu of https://github.com/elifesciences/elife-xpub/issues/135
