### ISSUE TITLE
Update cover letter molecule to conform to style guide and product requirements

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#235]
**Product requirements**

Functional:

- Cover letter editor should allow for the following: Bold, Italic, Underline, Superscript, Subscript, ~Unordered bullets, Ordered bullets, Indent left, Indent right~
- Default state should have the following questions in the text area, which is editable (i.e. the user can delete the entire contents if they wish):

How will your work make others in the field think differently and move the field forward?
How does your work relate to the current literature on the topic?
Who do you consider to be the most relevant audience for this work?
Have you made clear in the letter what the work has and has not achieved?

- Validation should ensure the text box contains text

Non-functional:

- Cover letter should be styed to conform with the [Styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3) and latest [hi-fi wireframes](https://invis.io/TCLPA2R3JYA#/304489194_wizard-Screen-2)

**Comment by jsms90** [comment]
@hdrury1 Clicking on the last link, I get a 'You need permission' pop up

**Comment by hdrury1** [comment]
@jsms90 Description updated with new link.

**Comment by tamlyn** [comment]
> Validation should ensure the text box contains text

The cover letter starts off with the sample text so would be valid by default. Should I require a certain word count? The sample text has 56 words. Should I require 57 words? 100?

**Comment by hdrury1** [comment]
@tamlyn Good point well made. Yep, let's validate for more than the current word count and see how it goes (57 words).

**Comment by tamlyn** [comment]
OK, in that case what should the validation message be? "Please enter more than 57 words" is too weirdly specific. Plus Heinz probably have that number trademarked. Make it 60 words? Or don't specify the minimum amount in the message? "Your cover letter must be longer"?

**Comment by hdrury1** [comment]
Something like "Your cover letter should be longer" would do it, sure.

**Comment by tamlyn** [comment]
List control requirements moved to #251 (also changed "Indent right" to "Unindent")
