### ISSUE TITLE
Empty opposed Reviewer fields preventing users from submitting

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2354]
A user is able to progress past the Details page with empty opposed Reviewer fields but clicking ‘submit’ throws an error in the console. All the user sees is the submit button not working.

The opposed Reviewer fields should not throw an error if both ‘Name’ and ‘Email’ are empty... only if one or the other is missing, and this validation error should be displayed to the user when clicking ‘Next’ on the Details page.

It seems the error is most commonly occurring when a user fills out the fields for one opposed Reviewer (generating the second row) but then doesn’t add a second.

**Comment by thewilkybarkid** [comment]
Sounds like you also need to give some feedback to the user too that something's gone wrong.

**Comment by diversemix** [comment]
Yes we've been discussing this... feel free to submit a PR

**Comment by erezmus** [comment]
Ok i was initially looking at the front end validation instead of the backend one

**Comment by erezmus** [comment]
Wrote a fix for the Joi server side validation. Will add some tests (probably will copy from the client side ones) to make sure its not broken. Should probably do the same for suggested reviewers

**Comment by erezmus** [comment]
In the end it looks like the suggested reviewers are already being filtered out, so rather than fixing joi validation which proved quite cumbersome, i extended `removeOptionalBlankReviewers` method in the manuscript entity to do the same for opposed reviewers

**Comment by diversemix** [comment]
Going to push #2355 as the server side fix, but won't close this ticket until we have a client side fix too. You ok with that @erezmus ?

**Comment by diversemix** [comment]
ok - I needed to reopen this - you merged before I had chance to update the comment :stuck_out_tongue_winking_eye:

**Comment by erezmus** [comment]
@diversemix ok no worries. yeah saw that :-)

**Comment by erezmus** [comment]
I tried filtering out on the client side, but unfortunately, the logic relies on there being one empty entry for suggested and opposed reviewers, so if that gets filtered out and saved, then that part of the form doesn't get displayed.

**Comment by erezmus** [comment]
So it turns out that suggested reviewers and opposed reviewers logic is slightly different in that respect.

When creating the manuscript on the server side, the `setDefaults()` method gets called which adds a single empty entry to `suggestedReviewers` team.

For opposed reviewers, a row for the opposed reviewers is always displayed independent of whether the `opposedReviewers` array is empty or not (in EditorsStepPage.js).
