### ISSUE TITLE
Update static pages

### ISSUE THREAD

**Issue by weimunchan** [elifesciences/elife-xpub#2370]
Hello Hannah,

Would you be able to help us with updating the Libero Reviewer pages. The details are out of date:

1) Contact pages

https://reviewer.elifesciences.org/contact-us/editorial-staff

The contact pages in eJP are up to date.

https://submit.elifesciences.org/html/eLife_contact.html#

2) In the Article Types section of the author guide:
https://submit.elifesciences.org/html/elife_author_instructions.html#types

ORIGINAL TEXT in Review Article section:

Review Articles are commissioned by eLife Senior Editors. If you would like to propose a Review Article, please send an outline to the most relevant Senior Editor (please email your outline to editorial [at] elifesciences [dot] org). The outline should include: i) 50-100 words on each of the main sections of the proposed article; ii) a paragraph on why it would be timely to publish an article on this topic now; iii) a paragraph on why you are a suitable author for such an article.

PLEASE UPDATE TO THE FOLLOWING (please keep the hyperlink Senior Editor page):

Review Articles are commissioned by eLife Senior Editors. If you would like to propose a Review Article, please email your outline to editorial [at] elifesciences [dot] org. In your email please also suggest a relevant Senior Editor to assess the outline. The outline should include: i) 50-100 words on each of the main sections of the proposed article; ii) a paragraph on why it would be timely to publish an article on this topic now; iii) a paragraph on why you are a suitable author for such an article.

Let me know, thanks,
Wei Mun

Thanks,
Wei Mun

**Comment by hdrury1** [comment]
Hi @weimunchan 

Would you be able to update this ticket with all of the static page update requirements, so that I can hit them in one go? I've had different requests about, e.g. the reviewer guide and the journal metrics while I've been away and it would be good to have them all in one place rather than in disparate emails.

**Comment by weimunchan** [comment]
Hi Hannah,

I've updated the changes I requested requested, I didn't request changes to the Journal metric pages so don't have the requirements for those changes.

Thanks,
Wei Mun

**Comment by hdrury1** [comment]
**Journal Metrics**

New chart.js 
https://drive.google.com/file/d/100MDdkkNfIADRVgMkmfImkUaxVS-c2dd/view?usp=sharing

New location of raw data
https://elife-cdn.s3.amazonaws.com/eliferawdata.xlsx
