### ISSUE TITLE
Updates to author/reviewer guide

### ISSUE THREAD

**Issue by Milly-eLife** [elifesciences/elife-xpub#2387]
@hdrury1 We made some minor changes to the author/reviewer guide recently so please update Reviewer to match.

Please change the end of the Special Issues section ad described here:
https://docs.google.com/document/d/1EMU2F9aMI_6n67LFTVwfXt4W3Uy5man9ndr9gEAbRzI/edit

**Comment by diversemix** [comment]
@Milly-eLife ... I've made a copy of this (https://github.com/libero/reviewer/issues/484) so we can track this on our board https://github.com/orgs/libero/projects/4

@hdrury1 - its currently at the bottom of `Todo`
