### ISSUE TITLE
Set timeout to redirect to login when session expires

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#2389]
LoginPage.js

```
  static setToken(token) {
   // set timeout here to clear token and redirect user to /
    window.localStorage.setItem('token', token)
  }
```

Let's just grab this timeout value from config for now. The session currently has a 24 hours ttl so lets set it to that for now (86400000).

**Comment by diversemix** [comment]
Relates to #2363

**Comment by diversemix** [comment]
Blocked pending Cory's return
