### ISSUE TITLE
Prevent submission from getting stuck due to whitespace characters

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2401]
We've had a handful of submissions getting stuck in the `INITIAL` state because users have inadvertently added extra characters to reviewers email addresses, presumably when copy + pasting them into the form.

```
Uncaught (in promise) Error: GraphQL error: ValidationError: child "suggestedReviewers" fails because ["suggestedReviewers" at position 0 fails because [child "email" fails because ["email" must be a valid email]]]
    at new W (ApolloError.js:37)
    at Object.next (QueryManager.js:186)
    at y (Observable.js:130)
    at b (Observable.js:165)
    at _.value (Observable.js:219)
    at y (Observable.js:130)
    at b (Observable.js:165)
    at _.value (Observable.js:219)
    at index.js:91
    at nrWrapper (newrelic.js:1095)
```

The error is logged in the console but the user receives no visual feedback and is simply unable to proceed past the last CONFIRM/CANCEL modal.

We should look into:

1) Preventing the error by stripping erroneous whitespace from email input
2) Better handling the error by providing some visual feedback for the user

**Comment by diversemix** [comment]
Currently checking the email containing some of the chars from - https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt

**Comment by diversemix** [comment]
Ok - managed to get an error by copying and pasting from the output of this python script:
```
print("snip >me@here.com\u2000\u00A0\u200A\u2028\u2029\u202F\u205F\u3000<")
```
Into one of the "Suggested Reviewers" name/email pairs

**Comment by diversemix** [comment]
I did look at doing something with the paste event - but there are so many edge cases, e.g. like what happens if you do want to paste in a space and then you type to remove it ... the other thing it not allowing spaces in email fields? But the simplest thing / less risky thing I thought would be to clean the fields up prior to submission. 

/cc @hdrury1 - (ok to merge this now?)

**Comment by diversemix** [comment]
#2407 - Deals with the server side trimming
#2408 - Deals with the client side trimming
