### ISSUE TITLE
Create new Production environment

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#245]
**User Story:**

_As Head of Product I want a production-ready site in order to see project progression at any given time._

**Product requirements/Acceptance criteria:**

Every feature that has been made thus far, and every feature that is subsequnetly made and/or updated should be consolidated in one place, so that stakeholders have a visualisation of work that has been undertaken. 

This enviroment should simulate production and sit alongside the demo environment used for development.

**Comment by diversemix** [comment]
This has been done and its now documented in `/docs/deploying/environments.md` 

Although the environment is set up there is still a lot of work still to do. This is detailed by #254
