### ISSUE TITLE
Updates to Author/Reviewer Guide

### ISSUE THREAD

**Issue by Milly-eLife** [elifesciences/elife-xpub#2454]
Hi @hdrury1, we've made some changes to the Author and Reviewer Guides on eJP, please update Reviewer to match:

**Initial submissions (new text for Limited Metadata, point 7,):**
Reviewer Suggestions/Exclusions: Authors are encouraged to suggest potential reviewers for their work at the Initial Submission stage. Please list the names of experts who are knowledgeable in your area and could give an unbiased review of your work. To support diversity, please consider suggesting potential reviewers at an early stage of their career, women, and experts from countries other than the USA and Europe. Please do not list colleagues who are close associates, collaborators, or family members. Authors may also provide the names of reviewers or editors who they would prefer to exclude from the assessment of the article. We will make every effort to follow author requests for excluded individuals unless the editors judge that such exclusion would interfere with the rigorous assessment of the work. Requests to exclude individuals must be accompanied with a brief explanation.

**Full submissions (new text for Metadata, point 6):**
Editor and Reviewer Suggestions/Exclusions: 
Authors are required to provide suggestions for at least four potential reviewers of the work during the Full Submission. To encourage diversity, please consider specifically suggesting reviewers at an early stage of their career, women, and experts from places other than USA and Europe. Please do not list colleagues who are close associates, collaborators, or family members. Authors may also provide the names of reviewers who they would prefer to exclude from the assessment of the article. We will make every effort to follow author requests for excluded individuals unless the editors judge that such exclusion would interfere with the rigorous assessment of the work.

**Full submissions (Submission files, point 2)**
Please remove ‘Corel Draw’ from the list of allowed file types

**Revised Submissions (Figures and Figure Supplements)**
Please remove ‘Corel Draw’ from the list of allowed file types

**Reviewer Guide, “Confidentiality and co-review”,** 
Please change “reveal his or her identity” to “reveal their identity”

**Comment by norisalsaadie** [comment]
Should be closed by https://github.com/libero/reviewer-client/pull/436
