### ISSUE TITLE
Add list controls to cover letter editor

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#251]
**User Story:**

_As an author I want to include lists in my cover letter in order to list things._

**Product requirements/Acceptance criteria:**

Functional:

- Add list control buttons to cover letter editor: Unordered bullets, Ordered bullets, Indent, Unindent
- Use icons from https://material.io/tools/icons/?style=baseline

**Relevant links to design(s):**

https://projects.invisionapp.com/share/TCLPA2R3JYA#/screens/304489194_wizard-Screen-2

**Comment by jure** [comment]
For reference, some or all of this work is here: https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/325

**Comment by hdrury1** [comment]
Closing in favour of #1413
