### ISSUE TITLE
Define interface for searching for articles

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#253]
The actual searching will be conducted by the Data Mart as part of the data consolidation project. All we need to do is define how we want to query and the anatomy of the results returned. This will satisfy the need that the submitter has to be able to search for articles to include in the co-submission section.

**User Story:**

The data consolidation project needs an Interface Specification for searching for an article.

**Product requirements/Acceptance criteria:**

Functional: None

Non-functional: The data consolidation team can work to the specification

**Comment by hdrury1** [comment]
@diversemix Happy for me to de-prioritise for now? Searching for articles won't actually occur until the QC step.

**Comment by jsms90** [comment]
@hdrury1 So is this `epic 2`?

**Comment by hdrury1** [comment]
Going to close this down until we have further requirements and the data mart is a realistic solution.
