### ISSUE TITLE
Refactor Container to reduce size

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#254]
Attached example dockerfile to create smaller container.  This excludes all the unnecessary bits including the e2e test stuff:

[Dockerfile-prod.txt](https://github.com/elifesciences/elife-xpub/files/2404453/Dockerfile-prod.txt)

This work can be found on the `245-prod` branch - still to do is to create a `teste2e` container that would test the above container.

**Comment by hdrury1** [comment]
@damnhipster Has this been done/does it need to be done/can I close the ticket?

**Comment by diversemix** [comment]
@hdrury1  We can use the current container in production, I talked with Hem and although we can go with the current container ... it would be good to create something more manageable.  I wouldn't want to close this, I will rename it - but please can we keep it in the backlog as I think its something that would be beneficial in the longer term.
