### ISSUE TITLE
ManuscriptPersonMetadata warning when starting the server

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#262]
**Describe the bug**
When the app starts (e.g. `npm run server`), this warning is logged
```
Type "ManuscriptPersonMetadata" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
```

**To Reproduce**
1. start the app from develop branch (`npm run server`)

**Expected behavior**
The warning should not be there.

**Comment by diversemix** [comment]
Actually there are a number of small issues with the GraphQL. Perhaps we need to have a validation test too.

**Comment by diversemix** [comment]
This is failing on `develop` 
![image](https://user-images.githubusercontent.com/8524685/42283117-6f2cb536-7fa0-11e8-92ad-219a8abd612a.png)

**Comment by diversemix** [comment]
Closing as I re-opened in contravention of our rules
