### ISSUE TITLE
Allow submitter to resend verification email to author

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#286]
**User Story:**

_As a submitter I want to be able to resend a verification email to the corresponding author._

**Product requirements/Acceptance criteria:**

Functional:
- Add a GraphQL mutation for resending the email.
- Add a "Resend" button to the notification ribbon which resends the verification email to the author.
- Animate the ribbon, show a success ribbon, then animate it back again. See [note on Invision designs](https://projects.invisionapp.com/share/CDLI0R5KBF6#/screens/299098576/comments/98510002).

**Comment by hdrury1** [comment]
Closing as out of scope.
