### ISSUE TITLE
Allow corresponding author to log in with ORCiD

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#298]
**User Story:**

_As a corresponding author I want to log in to xPub in order to track the progress of my submission._

**Product requirements/Acceptance criteria:**

Functional:

Once the corresponding author has verified themselves via the email link (https://github.com/elifesciences/elife-xpub/pull/290) they should be presented with a 'Thank You' page and given the option to log in.

The log in button redirects them to ORCiD where they can sign in to an existing account or create a new one.

Once logged in, the user is redirected to their xPub dashboard, where the new manuscript appears as an item (to be styled).

The corresponding author will now have access to a read-only version of the manuscript alongside an author view of the correspondence tab of the submission (to be confirmed and styled).

**Relevant links to design(s):**

![image](https://user-images.githubusercontent.com/17023702/42269916-70692804-7f77-11e8-9424-6880efbb7da8.png)

**Comment by hdrury1** [comment]
@jsms90 I propose that, given we have some unanswered design questions, we put a pin in this functionality for now. This would mean removing the button from the Thank You page and slightly altering the wording so we do not give the corresponding author the option of logging in.

The user stories we collected right at the very start of this project expressed a desire to have the option of both a submitter and a corresponding author associated with the manuscript, with the corresponding author receiving an additional copy of any decision letters from the editors (but not interating directly with the application himself). Allowing said corresponding author to log in and have his own dashboard is an additional 'nice to have' feature that we can implement later down the road.

**Comment by jsms90** [comment]
Makes total sense that we treat this functionality as a "nice to have" & focus on the ability to verify their email _first_ :+1: 

However, if the ability to log in is something that we want to offer down the road, this will likely have an impact on how we want to store represent `User` & `User Alias` in the database. It is probably going to be beneficial for us to take this into consideration from the start, even if we don't implement this feature until later.

**Comment by hdrury1** [comment]
Ripe for a 'Discussion' ticket?

**Comment by hdrury1** [comment]
No longer in scope.
