### ISSUE TITLE
Associate corresponding author's details with the submission

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#299]
**User Story:**

_As a corresponding author I want to receive decision letters from the editors and be the first port of call for correspondence from staff._

**Product requirements/Acceptance criteria:**

Functional:

Once the corresponding author has verified their position via the email link (https://github.com/elifesciences/elife-xpub/pull/290), their First Name, Last Name, Institution and email address should be linked to the manuscript entity in the database.

The corresponding author should receive a copy of all decision letters from the editors for the lifetime of the submission (or until such point as they are disassociated with the submission).

The corresponding author should NOT receive other messages from the system (e.g. from staff if a submission has failed quality checks).

The corresponding author will be the contact point for staff and/or editors throughout the life of the submission if there are questions of a scientific nature to be answered.

The corresponding author will be listed as such on the published version of an article.

**Comment by jsms90** [comment]
@hdrury1 To clarify, does this issue relate to the submission wizard? Or is this an issue to be completed once we enable editors to write a decision letter?

As far as the submission wizard goes, as soon as a submitter fills in page 1, the corresponding author's details are added to the manuscript entity in the database. So the first functional requirement is already satisfied within our app :+1: 

The rest of the requirements seem to refer to future stages of our app (beyond initial submission) that have yet to be built? Should this be put into `epic 2` or possibly `epic 3`? Or is there more work that needs to be done within `epic 1` to satisfy this ticket?

**Comment by hdrury1** [comment]
@jsms90 Wunderbar. I think I was just trying to split the EPIC ticket down, but if this is already implemented I'll close 👍
