### ISSUE TITLE
Data changes

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#301]
### The problem

I add a new required field on a manuscript and update the manuscript creation code to ensure new manuscripts always have this field. You run my code but you have existing existing manuscripts in the database that don't have this field and that causes errors when encountering code that assumes the field exists. 

### Solutions

- Write data migrations to update the data in the database to conform to the new requirements.
  - Good habit to develop as we will need to do this in production 👍
  - Easily updates deployed instances 👍
  - Extra work 👎
  - Developers need to remember to run the command 👎
- Code defensively assuming that data may not be present
  - Extra work 👎
  - Extra noise in codebase dealing with situations that may no longer arise 👎
  - Need to track and eventually remove all these special case checks 👎
- Delete the database whenever the data requirements change
  - Zero effort 👍
  - Developer needs to remember to run the command 👎
  - Tricky to manage on demo deployments 👎
  - Obviously doesn't work for production! 👎

**Comment by hdrury1** [comment]
@diversemix Is this still an issue?
