### ISSUE TITLE
Production environment does not have correct config

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#306]
**User Story:**

As a developer I want the production environment to have the production configuration. 

**Product requirements/Acceptance criteria:**

You can login with ORCiD, as the configuration is there and used.

**Comment by giorgiosironi** [comment]
As far as I can tell the production environment is pointing to `orcid.org` (but you can't use it because the login flow passes through a `/submit` page disabled in `journal--prod` via feature flag).

**Comment by diversemix** [comment]
Closing - as we have now deplyed a production environment using the `prod` node config.
