### ISSUE TITLE
Article type menu allows invalid selection

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#308]
**Describe the bug**
It is possible to select an invalid value for the article type which then results in errors preventing the app from loading.

**To Reproduce**
1. Start a new submission
2. Fill in any details and proceed to page three: article metadata
3. Click on the article type field to open the drop down
4. Press tab to highlight the first option but instead it highlights something invisible between the two options
5. Press enter to select the option

<img width="584" alt="screen shot 2018-07-05 at 16 38 03" src="https://user-images.githubusercontent.com/115310/42333156-dbe44578-8071-11e8-8291-acb996e10d1f.png">

If you now reload the page the app will crash with `Uncaught TypeError: Cannot read property 'label' of undefined`. 

**Desktop (please complete the following information):**
 - Browser: Chrome (also happens in Firefox although the sequence of keys is a bit different)

**Comment by jsms90** [comment]
I can't seem to recreate this on my machine. Guessing it only happens on Mac?

**Describe the bug**
But in general, this component appears to be completely inaccessible (at least on my machine). You can't use the normal keyboard shortcuts to do most things with this menu.

**To Reproduce**
Steps to reproduce the behavior:
1. Click on, or tab into, the "Manuscript title" field
2. Press tab, to focus the Article type menu
3. Press the down arrow key - the menu does not open
4. Press enter (the menu does open)
5. Press the down arrow to go through the items in the list - focus does not move from the select field
6. Press tab once, to start going through the items in the list (works)
7. Press tab 3 more times - you are no longer scrolling through the menu. Focus scrolls through the whole form

We could:
1. Make the core pubsweet component accessible
    - likely to take a long time to add all of the correct key presses & focus management :-1: 
    - pubsweet would have its own, accessible menu component :+1: 
    - contributing to the pubsweet library - others may be using this component & could benefit form the accessibility improvements :+1: 
2. Use the `react-select` library
    - we're already using this library for the multi-select dropdown, so even though it's a 3rd party library, it shouldn't take much extra time to jump into :+1: 
   - immediately as accessible as the multi-select dropdown :+1: 
   - easier to bring these 2 menu components, that exist on the same page, into alignment styling-wise :+1: 
   - not contributing back to pubsweet (yet) :-1:

**Comment by hdrury1** [comment]
Closing as no longer an issue.
