### ISSUE TITLE
Fetch ORCID user details on login

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#309]
**User Story:**

_As an author or submitter I want my details in xpub to be up to date with my details in orcid in order that emails can be sent to me and the corresponding author check can be carried out._

**Product requirements/Acceptance criteria:**

Functional:

- When a user logs in with ORCID, perform an API request to ORCID to fetch the user's email address and save this on the xpub user object.
- Do this even when an existing xpub user is found, updating the previous value. This is because the email address may have changed since their last login.
- This data could be used for the form prefill, bypassing the current API request.

Currently this API request can be quite slow (> 5 seconds). Perhaps this is just an issue with the ORCID sandbox. If not we will need to make this request in the background to avoid slowing down the login too much.

**Comment by diversemix** [comment]
@tamlyn @hdrury1 

Just had a chat to @gmaciocci about this...

The important thing to remember is that during Initial Submission an author and a submitter only have an email address via their relationship to the manuscript. This does not get stored against their profile. Later on when the author creates an profile - we may need this (?).

We do not need this piece of work to be carried out yet. Not sure how this found its way into `In Progress`  let alone `ToDo` - I will leave this open in case I have got the wrong-end-of-the-stick on this.

**Comment by tamlyn** [comment]
I think we do need something like this now:
- The way to detect whether the submitter is different from the corresponding author (and trigger the verification logic) is to compare their email addresses. 
- We don't have a field on the form for submitter email address so I think we need to fetch this from ORCID. 
- The submitter may not use the prefill button at all so we need to fetch their email address separately.

It doesn't have to be on login. Other options:
- Fetch the email on demand each time it is required. 
  - Guaranteed up to date 👍
  - Less robust as network request may fail,  ORCID API token may have expired or been revoked 👎
  - Slows down any operation that requires an email 👎
  - Can't find DB users by email address 👎
  - More complex to implement 👎 
- Fetch on submission start 
  - Doesn't help for user types who never submit anything 👎
- Use webhooks to get notified when ORCID email changes
  - Guaranteed up to date 👍
  - Insufficient on its own so needs to be combined with a way of fetching the initial email 👎

**Comment by jsms90** [comment]
> We do not need this piece of work to be carried out yet. Not sure how this found its way into `In Progress`  let alone `ToDo`

This piece of work is implicitly necessary (for the reasons @tamlyn has stated above), if we want to create the feature where a corresponding author gets emailed on Submit. I think what this discussion is showing here, is that the ramifications of this feature have not been fully communicated.

I have attempted to outline all of the technical tasks that are involved in implementing this feature in the overall feature issue: #272 But I am concerned that this list alone is not adequate, as communication between product and devs! I strongly believe that we need to spec out this feature together & discuss all the technical implications associated with the latest product requirements before continuing. The important thing here is that we are aligned, as a team, on expectations.

For now, can we bench this conversation entirely, as we focus on tasks which we need to get done before the demo?

**Comment by hdrury1** [comment]
@diversemix can you confirm this is obsolete now we are using Journal to log in?
