### ISSUE TITLE
Email correpsonding author on 'Submit' instead of 'Next'

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#310]
**Product requirements/Acceptance criteria:**

- Given that we are now only emailing the corresponding author once the submission has been completed, there is no need for a notification ribbon to appear in the wizard.

- The ribbon should appear on the submission once the submitter has hit 'Submit', but there are currently no final designs for this view.

- For the purposes of demonstrating functionality, could we add a temporary status to the submission on the dummy dashboard view to feed back to the user that an email has been sent to the corresponding author?

**Tasks**
- [x] Remove code that adds corresponding author to the manuscript object on clicking 'Next' & move email sending into `finishSubmission` resolver
- [ ] ~Move corresponding author notification ribbon from submission wizard to dashboard~ Remove notification ribbon from submission wizard (or the codebase altogether)?

**Comment by jsms90** [comment]
@hdrury1 If the notification ribbon is going to appear on the dashboard, how does the subimitter know which manuscript this ribbon relates to?

**Comment by hdrury1** [comment]
@jsms90 Sorry, unclear. On the dummy dashboard I was envisioning some kind of status attached to a specific manuscript rather than a ribbon, perhaps alongside the 'QA' marker we currently have?

**Comment by jsms90** [comment]
Yeah that's what I was thinking too. Makes more sense :smile: 

So shall we remove the notification ribbon altogether from our codebase?

Also, it seems like designs for the dashboard are becoming increasingly important? Should we expect this to be the next body of work, after the people picker? The current table on the dashboard was just a placeholder that @tamlyn put in to help us develop.
