### ISSUE TITLE
Data model support for changing Corresponding Author from User Alias to full User

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#311]
We need to ensure that our data model accounts for [this product requirement](https://github.com/elifesciences/elife-xpub/issues/298#issuecomment-402432658):
> The user stories we collected right at the very start of this project expressed a desire to have the option of both a submitter and a corresponding author associated with the manuscript, with the corresponding author receiving an additional copy of any decision letters from the editors (but not interacting directly with the application himself). Allowing said corresponding author to log in and have his own dashboard is an additional 'nice to have' feature that we can implement later down the road.

What is our plan for reconciling a user alias & a user, or more specifically, turning a user alias into a fully fledged user?

If a corresponding author (user alias) is associated with multiple different manuscripts, how do we ensure that these different user aliases all get amalgamated into the saame user object once they do actually sign up with Orcid for the first time?

Ideally, we would take this into consideration before implementing the corresponding author email verification feature, to avoid future headaches. Or! We could implement the basic email verification feature (no option for the corresponding author to log in) without deciding this first. The downside being that we will need to implement a schema migration if/when our data model changes to support this concept & if we go into production first, then we'll need a full database migration.

**Comment by diversemix** [comment]
The idea was that the data model did account for this - did you want to chat about it?

What is supposed to happen is that the `Manuscript Person` object gets created with the `Alias` - i.e. the as yet unconfirmed details ... if they were to confirm ... then the `User` field would end up having that actual user (the field is nullable) ... see https://docs.google.com/document/d/1KU-DLMNhPxjQF2j8HVlJvenvttPLxgtbTHo8Sy_PNRc/edit#

**Comment by hdrury1** [comment]
@diversemix Let's assume I have reviewed 3 papers for eLife- is a new `Alias` created every time I review?

**Comment by diversemix** [comment]
@hdrury1 ...  what the `Alias` is in this context ... is a record of a set of details to identify you as a reviewer in the system. (a little like a set of search parameters) ... the resolution of which could be done immediately and then the alias information thrown away.  (Notice how I did not quite answer your question)

**Comment by jsms90** [comment]
> the resolution of which could be done immediately 

How could this resolution happen immediately? It would only be possible for a `User Alias` to become a `User` if/when the Corresponding Author decides to click 'Log in' from the verification email. If this never happens & they never log in to our system, then yes @hdrury1, we would have 3 different `User Alias`es in our system, because we're not checking if they're the same person.

Or we could check whether a `User Alias` already exists in our database (by checking whether a `User Alias` with the same email address already exists?) If it does already exist, we could reconcile those 2 `User Alias` objects & save multiple manuscripts against their name, in preparation for the day when they (might) become a full `User`

This is exactly the kind of discussion we probably need to have, now that we're looking at saving a submitter's info, separately from the corresponding author's info & creating a `User Alias` against the manuscript.

**Comment by tamlyn** [comment]
> If it does already exist, we could reconcile those 2 User Alias objects & save multiple manuscripts against their name
But what if the name or institution is different? Which one do we use? 

That's why the user alias exists in the first place (otherwise we could just create a placeholder user entities with no ORCID ID). In contradiction to what @diversemix said, I thought we needed to keep the user alias even if/when an author is reconciled to a full system user. The user alias is what was entered on the form and needs to be retained as it may not match the details on the user entity which are populated from ORCID.

I think the data model already enables the necessary functionality.

**Comment by hdrury1** [comment]
Closing as out of scope for the Product.
