### ISSUE TITLE
Report upload progress for manuscript

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#313]
**User Story:**

_As a submitter I want to have feedback that my manuscript is being uploaded in order that I have confidence the application is functioning correctly._

**Product requirements/Acceptance criteria:**

Depends on #312

Functional:
- Use the push functionality from #312 to send upload progress from the manuscript upload mutation back to the client. See [discussion](https://github.com/elifesciences/elife-xpub/issues/135#issuecomment-392713302). 
- Use this data on the client to animate the progress from 0-50%.

**Relevant links to design(s):**

https://drive.google.com/open?id=1SkJQr3cA4C6HL8FQ5tQ2-9U967C0H1o0

**Comment by dryhten** [comment]
This was actually done in https://github.com/elifesciences/elife-xpub/pull/368 but it's currently waiting for some changes in pubsweet to get merged here https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/337, so I consider it blocked.

I'm also attaching a GIF file with what it looks like now, in case anyone has any complains (although I would make changes to this as part of different issues).

![manuscriptupload](https://user-images.githubusercontent.com/1497469/42831824-49173f64-89e7-11e8-9b45-1cfb9009b2a5.gif)

**Comment by dryhten** [comment]
Done in https://github.com/elifesciences/elife-xpub/pull/368
