### ISSUE TITLE
Migrate from kube-lego to cert-manager

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#319]
[kube-lego](https://github.com/jetstack/kube-lego) is used to fetch certs from LetsEncrypt and use them for our staging and demo environments. It's since been deprecated, and the official successor is [cert-manager](https://github.com/jetstack/cert-manager/)

**Comment by giorgiosironi** [comment]
`staging` on the eLife side uses the eLife wildcard certificate deployed on the AWS ELB, so I think this could be closed as obsolete?
