### ISSUE TITLE
fix SubjectAreaDropdown's internal spacing & font

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#327]
- Height is currently different when there are no tags inside vs when there are tags inside
- Label fontsize is too large
- Need spacing between label & select field
- Spacing between green message & select field needs to match error validation spacing

Currently, if the user has selected 2 options, the green message appears. But if they navigate away from the page and then back again, the 2 options are still selected but the green message is no longer there. Is this an issue?

**Comment by hdrury1** [comment]
@jsms90 I think this message should remain.
