### ISSUE TITLE
change co-submission box

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#328]
**Designs**
![image](https://user-images.githubusercontent.com/15656538/42562412-92ae4dbe-84f3-11e8-8507-b3e921e49cc4.png)
https://projects.invisionapp.com/share/N3LUQ8S5ARV#/screens/304489195

**Tasks**
- Remove 2nd input field
- Add Action link & functionality which generates new input field
- Maximum of two co-submissions - when 'include' is clicked, the action text ("Would you like to include another co-submission") hides & a second "Article" input field appears
- Second co-submission field is labelled as optional

**Comment by tamlyn** [comment]
Current progress is on https://github.com/elifesciences/elife-xpub/tree/cosubmission

Still to do: 
 - [ ] update tests to use new data model
 - [ ] add the button to create the second field

**Comment by tamlyn** [comment]
Sam's suggestion for validating arrays works:

```
cosubmission: yup
      // validate the array as an object to allow different requirements at different positions
      .object({
        '0': yup.object().shape({
          title: yup.string().required('Article title is required'),
        }),
        '1': yup.object().shape({
          title: yup.string(),
        }),
      })
      // transform array to object for the purpose of validation
      .transform((_, originalValue) =>
        originalValue.reduce(
          (obj, value, index) => ({ ...obj, [index]: value }),
          {},
        ),
      ),
```

**Comment by diversemix** [comment]
Think the schema needs to be: 
```
const schema = yup.array().of(yup.object().shape({
		"title": yup.string().required('Article title is required'),
	})).max(2, "Cannot have more than 2 cosubmissions")
```
