### ISSUE TITLE
Copy xpub app and remove unneeded elements

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#33]
- [x] copy files from `xpub/xpub` into `xpub/xpub-elife` (do not preserve git history)
- [x] remove unnecessary files like `app/config/*`
- [x] make initial commit

**Comment by tamlyn** [comment]
Are those checkboxes awaiting to be checked when that subtask is completed or are they  communicating non-goals?

**Comment by g-sam** [comment]
the former!

**Comment by g-sam** [comment]
are they correct as such?
