### ISSUE TITLE
Add Process for X-Browser Testing

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#332]
**User Story:**

As a developer, I want to ensure that the UI component I have created is robust.

**Product requirements/Acceptance criteria:**

The processes should match ones used by Libero.

**Comment by diversemix** [comment]
Fixed with #329

**Comment by diversemix** [comment]
Closed by mistake

**Comment by damnhipster** [comment]
We're currently using [TestCafe](https://devexpress.github.io/testcafe/) to run our E2E tests. This is the place where we should do cross-browser testing. TestCafe supports running the tests in [different browsers](http://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html)

What's up for debate is what method we use to provide the browsers to test on. Our options are **running headless browsers** or test against **browsers running inside VMs**

###Headless Browsers
TestCafe supports running **Chrome** and **Firefox** headlessly. We can use this to run the browsers ourselves in containers. We won't be able to run tests against IE/Edge, which will have to be tested manually.

###Browsers running in VMs
TestCafe can run against all the browsers we want to supports if they're running within VMs. Running and maintaining these VMs is expensive, and I'd recommend using a service like [SaucesLabs](https://saucelabs.com/platforms) to provide our browser VM needs. This is a paid for service.

**Comment by damnhipster** [comment]
@diversemix does #344 address this issue?

**Comment by diversemix** [comment]
Wait till tomorrow to close this out.
