### ISSUE TITLE
Ensure Sciencebeam is Production Ready

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#333]
Remove the ScienceBeam API and deploy alongside the application in its own container.

**Comment by damnhipster** [comment]
This will be deployed by updating elife-xpub-formula.

Update docker-compose inside elife-xpub-deployment to include the sciencebeam docker image along with the correct version.

**Comment by damnhipster** [comment]
There's a risk of downtime/reliability issues with ScienceBeam, which we'll want to address. This is because of Gorbid.

**Comment by giorgiosironi** [comment]
I think: https://github.com/kermitt2/grobid

In alternative, we could specify a version of sciencebeam with a [SCIENCEBEAM_TAG variable in .env](https://github.com/elifesciences/elife-xpub-deployment/blob/develop/.env) but given updates to `IMAGE_TAG` are merged automatically this wouldn't be safe.

Reporting a canonical example of dependency image tag:
```
$ docker inspect elifesciences/annotations_fpm:latest | jq .[].Config.Labels
{
 "org.elifesciences.dependencies.api-dummy": "05ab239fa0eec32b3f36ca2dc8117123e2879717",
 "org.elifesciences.dependencies.hypothesis-dummy": "27fd587c07a8169d81adf9683fdf40335ab6b572"
}
```
maps to the deployment of that `annotations_fpm` image using two sidecar containers with images `api-dummy:05ab239...` and `hypothesis-dummy:27fd587...` respectively.

**Comment by diversemix** [comment]
Looking at what we need from the `docker-compose` file in the project ( see https://github.com/elifesciences/sciencebeam/blob/develop/docker-compose.yml ) ... 
- Latest IMAGE_TAG is `f05c51adbc49b47a65df1c3b7f69d25e401f5560` - so lets pin at that for now 
- And for grobid, lets pin at the image `lfoppiano/grobid:0.5.1`

**Comment by diversemix** [comment]
Talk with Daniel:
- There is a health check on the hosted service - which is deployed using this `docker-compose` ... https://github.com/elifesciences/sciencebeam-texture-formula/blob/8ce393b016fdc409ee9d5c4aa4a1fb574b32151f/salt/sciencebeam-texture/config/home-deployuser-sciencebeam-texture-docker-compose.yml#L33
- Good to use New Relic to monitor the server's memory usage
- There is a security issue. However this should not concern us as our deployment should not be publicly accessible.

**Comment by diversemix** [comment]
The preparation work and conversations should now allow #658 to be completed.
