### ISSUE TITLE
Update suggested reviewers functionality

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#336]
**User Story:**

_As a submitter, I would like to suggest appropriate reviewers to assess my submission to eLife_

**Product requirements/Acceptance criteria:**

- Three reviewer name/email rows should be listed by default
- Filling in the first two rows has no effect on the UI
- Focussing on the third row (if the first two rows are already filled) generates a new fouth row below
- Focussing on the subsequent fourth row (if the first three are already filled) generates a fifth row ...and so on, up to a maximum of six rows
- Validation should occur on the first three rows only- the rest are optional input fields
- Currently there is no affordance for deleting rows that have been generated
- Once a sixth row has been generated/filled the user cannot enter any more suggestions

**Relevant links to design(s):**

Screen 1 - two rows filled (https://invis.io/KXMHPB5YRZ8#/305858554_author-Exclusion-Set)
Screen 2 - focus on third row generates a new fourth row (https://invis.io/4GMHPDE89TR#/305873221_author-Add-More-Reviewers)

**Comment by jsms90** [comment]
@hdrury Could we separate this out from the "people picker" epic? It has a fair bit of complexity in it & it's a pretty separate body of work from the people picker modal (even though it exists on the same page of the wizard).

**Comment by hdrury1** [comment]
Done.

**Comment by diversemix** [comment]
@hdrury1 ... for the moment I am not going to do it on focus but when there is data in the field ... There are some horrendous issues with the focus event at the moment.

**Comment by diversemix** [comment]
Requirements have changed for the optional reviewers:
> Morning all. Any queries awaiting me from Friday? peter and tamlyn at a glance, the answer is yes, we should require name+email for the optional reviewer fields. so it’s all or nothing.

https://elifesciences.slack.com/archives/C6LKMFK5Z/p1532939698000180

**Comment by diversemix** [comment]
Further relevant background: 

Tam said:
> There is still *some* validation as we check that any email entered is valid. And I think we said (a long time ago) that it should check that the same email is not entered twice.

https://elifesciences.slack.com/archives/C6LKMFK5Z/p1532940135000069?thread_ts=1532939783.000057&cid=C6LKMFK5Z

GM said:
> Also worth noting that Invalid optional fields should only stop progress to the next stage of a wizard if they’re at least partially filled. If they’re blanked again, they are ignored.

https://elifesciences.slack.com/archives/C6LKMFK5Z/p1532940764000173?thread_ts=1532939783.000057&cid=C6LKMFK5Z
