### ISSUE TITLE
Progress indicator tick not appearing in Firefox

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#338]
**Describe the bug**

Tick icon does not appear in the progress indicator when using Firefox browser (either Mac or PC). May be related to https://github.com/elifesciences/elife-xpub/issues/329

**To Reproduce**
1. Go to 'https://demo--xpub.elifesciences.org/submit/'
2. Click through wizard
3. Notice error

**Expected behavior**
Tick should appear

**Screenshots**
<img width="501" alt="screen shot 2018-07-11 at 12 19 56" src="https://user-images.githubusercontent.com/17023702/42568466-271714e8-8505-11e8-94a6-3bbb26ddffd7.png">

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser Firefox
 - Version 60.0.2

**Comment by diversemix** [comment]
Fixed with #329
