### ISSUE TITLE
Update panel for excluding editors

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#342]
**User Story**

_As a submitter I want to request that certain editors are excluded from assessing my work if I feel they are conflicted._

**Product requirements:**

- The panels for allowing a submitter to request editors be excluded from the review process should be updated to reflect new designs
- The exclusion panel should contain a select button component
- The user should be able to select exclusions from the people picker modal
- Upon clicking the 'choose editor' select button, the people picker modal should open
- ~~Within the modal, the search box should be empty by default, and the results returned should be every user within the context of the selection (i.e. all Senior -Editors when selecting Senior Editors to exclude, all Reviewing editors when selecting Reviewing editors to exclude)~~ search functionality removed from epic scope
- Selecting an editor (or more) and clicking the 'Add' button returns the user to the submission wizard and replaces the select button component with the selected person pod(s)
- User can select up to 1 Senior editor to exclude and up to 2 Reviewing editors to exclude
- Spare exclusion slots in the submission wizard should be occupied by a select button (use case: A submitter has selected one reviewing editor to exclude and returned to the submission wizard. They should see the person pod for the editor they have excluded along with a select button to choose a second editor to exclude if they wish)
- The user has the option to delete this person pod using the trash can icon, at which point it is replaced with the select button component once more
- The user can close the exclusion panel without making a selection by using the 'X' icon in the right-hand corner
- ~~If a person pod(s) is added to the exclusion panel, the user must give reasons for this exclusion(s) in the text box. This should be validated for text entry~~ see #405 

**Relevant Designs:**

Screen 1 (https://invis.io/QXMHH5SSARJ#/305823522_author-Suggestions-Change)
Screen 2 - After choosing 'exclude reviewing editor' (https://invis.io/2VMHHBPJYDT#/305823523_author-Exclusion)
Screen 3 - After selecting reviewing editor to exclude (https://invis.io/NJMHHDX8C6V#/305858554_author-Exclusion-Set)

**Comment by jsms90** [comment]
@hdrury1 Am I right in thinking this same pattern will be reused in 2 places in our designs?
- excluding Senior Editors
- excluding Reviewing Editors

If so, what's the limit on the number of senior editors & reviewing editors that can be excluded? At our last meeting, I believe you said that senior editors = max 2 & reviewing editors max = either 2 or 3?

**Comment by hdrury1** [comment]
@jsms90 Yes, the same pattern can be used in both instances. Users can exclude up to a maximum 2 Senior Editors and 2 Reviewing Editors.

**Comment by tamlyn** [comment]
The new design with a single reason for exclusion doesn't fit with our data model which has a reason per excluded person. I guess we need to update the data model?

**Comment by hdrury1** [comment]
@tamlyn A single array... @diversemix I'll open a new issue.

**Comment by hdrury1** [comment]
@tamlyn Scratch that. I think it makes sense for you to update the schema as part of this work, so unless you want me to I'll avoid raising a separate issue.

**Comment by tamlyn** [comment]
If a user clicks to show the box to [exclude a reviewing editor](https://projects.invisionapp.com/share/QXMHH5SSARJ#/screens/305823523) but then doesn't select anyone or type a reason, is the form still valid? Or do they have to close the box to continue without selecting someone?
