### ISSUE TITLE
Impose filtering rules for people picker

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#348]
**User Story**

_As a submitter/editor I want to be able to filter the list of people in order to identify those best to assign to a submission._

**Product requirements**

- User should be able to use the search box to filter results by name, keywords or institution

- The search box should offer suggestions based on character input (see related ticket)

- Results should be ordered by relevance

- If more than one MSA is entered in the search box, comma separated, results are presented alphabetically by first name regardless of MSA

- Any results that have also been suggested by the authors should appear first

- Any results excluded by the authors should appear at 50% opacity, with status set to 'Excluded by the authors'. These should be selectable by staff only

**Comment by dryhten** [comment]
> Results should be presented in alphabetical order by first name

Does this mean that the person pods should be ordered in the first place, when the people picker is loaded? If not, we shouldn't allow for empty string searches, it's inconsistent (e.g. just hitting enter on the search box will reorder the list of people alphabetically)

**Comment by hdrury1** [comment]
@dryhten I've updated the description to reflect the brief discussion we had this morning- results should be ordered by relevance.

Expected behaviour when search box is empty: top results should be those already selected, followed by a full unfiltered list, ordered alphabetically.

**Comment by hdrury1** [comment]
Closing this down due to updated feature requirements.
