### ISSUE TITLE
Search box offers suggestions

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#349]
**User Story**

_As an editor/staff I would like to be offered search suggestions to save me time in typing._

**Product Requirements**

- Search box should offer suggestions based on input

- These suggestions can be MSAs, keywords, institution or names already associated with users in the system

- Suggestions should refine as more characters are entered

- Suggestions should be ordered alphabetically by first letter, with names appearing first

- Number of suggestions appearing should be limited based on screen size, with the remainder of the list being scrollable

**Designs**

https://invis.io/FUMJS349R2E#/305823534_staff-Picker-Reviewers-Search

**Comment by dryhten** [comment]
This was done as part of this other issue (they are more or less the same, having a search box with basic functionality) https://github.com/elifesciences/elife-xpub/issues/347
