### ISSUE TITLE
Connect people picker modal to app

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#351]
**User Stories:**

_As a submitter I want to see a list of editors, their institutions and their subject area(s) in order to choose the most appropriate people to oversee the review of my work or to exclude those who may have a COI._

_As a Deputy/Senior editor, I want to see a list of Senior/Reviewing editors alongside their current availability, expertise and the authors' suggestions in order to assign the most appropriate team to the paper._

_As a Reviewing Editor, I want to see the authors' suggested reviewers to help me decide on who to invite to review._

_As a RE, I want to see how long a reviewer usually takes to write a review as this may impact whether or not I invite them to review a particular paper._

_As an author, I'd like the system to offer me a browsable list of editors I can select from, e.g., by key words, major subject area_

**Product requirements/Acceptance criteria:**

- When a selection has been made, the person pod should replace the Select Button component within the submission form.

- ~~The person pod should be populated with data from eLife API `/people` endpoint.~~ see #401 

- The amount of data displayed in each pod depends on the privileges of the user selecting the person(s):

- _Submitter should see_

First Name, Last Name
Institution
Keywords

_Editor/Staff should see_

First Name, Last Name
Institution
Keywords
Status (see separate ticket)

- ~~If any information is missing, the line should be left blank but not omitted (i.e. overall size of the pod would not be affected)~~ see #404 

- ~~If institution is missing, the line should be replaced with email address (e.g. a reviewer suggested by the submitter that is not a user in the database)~~ see #403 

- Clicking `+` on select pod should bring up people picker
- 'Cancel' button should close the people picker modal with no updates to the Submission wizard/Assignment Tab
- 'Add' should only become active and clickable once the required number of selections has been made
- Clicking 'Add' closes the modal and replaces the previously clicked selection button component with the chosen person pod(s)
- ~~Navigating back in the browser should be the same as clicking 'Cancel'~~ see #402 

**Relevant links to design(s):**

[Invision Prototype](https://invis.io/Z9MDY2CPXE6)

**Comment by jsms90** [comment]
@hdrury1 I've changed the name of this issue because the product requirements describe how the person pod component will interact with the page. This is separate from the creation of the Person Pod atom in the first place. For that work, see issue #227
