### ISSUE TITLE
Create some test people data for the application 

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#353]
**Product Requirements**

- Data pertaining to editors and reviewers currently within the eJP database should be imported.

**Comment by diversemix** [comment]
@hdrury1 - not convienced we need this yet - we may use the data from the `/people` endpoint... need to talk with the team here.

**Comment by hdrury1** [comment]
@diversemix Happy to let you guys fight about implementation amongst yourselves. What is the alternative? To hard code the list for now?

**Comment by diversemix** [comment]
We've agreed the data source for the author's view should be taken from : https://api.elifesciences.org/people

**Comment by diversemix** [comment]
We need to be aware that the `people` entity is a completely separate one to `profile` - at the minute there is no way to reconcile these - apart from maybe with ORCiD.

For example, looking at Huda Zoghbi .... https://api.elifesciences.org/profiles/h7n71e36 ... also has a people id of https://api.elifesciences.org/people/1e9e661f

**Comment by diversemix** [comment]
Let's change the title of this to reflect the fact that this is a demo and we need some test data.

**Comment by diversemix** [comment]
@hdrury1 ... if its okay with you after the meeting we have just had, I suggest we close this as we are going to use the `/people` endpoint ( https://api.elifesciences.org/people ) as the data source for the people picker.

**Comment by hdrury1** [comment]
@diversemix Is there any work involved in this implementation? If so we should probably keep this open as a record that that work still needs to be done.

**Comment by diversemix** [comment]
So I will close this off now, this ticket was to provide / make accessible the data for testing - Which it is on the above endpoint. There is work in the implementation,  but this should be covered on the other tickets. What is emerging as another potential piece of work is the introduction of the DAL/ORM - if this does arise then we need to raise another ticket methinks :tickets:
