### ISSUE TITLE
Impose limit on number of person selections and display feedback

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#355]
**Product requirements**

- There is a maximum number of selections that can be made:

2 x suggested Senior editors
2 x excluded Senior editors
2 x suggested Reviewing editors
2 x excluded Reviewing editors

- Feedback should be given to the user (2 more suggestions required, 1 more suggestion required, Maximum 2 choices)
- When the maximum is reached the feedback is shown in success colour
- For exclusions, no 'required' message is displayed, but when the maximum is reached a 'Maximum 2 choices' message is displayed in success colour

**Designs**

[Suggestions required](https://invis.io/9HLUEH9AXRF#/305823519_picker-Author)
[Maximum reached](https://invis.io/9HLUEH9AXRF#/305823520_picker-Author-Selection)

**Comment by tamlyn** [comment]
Can I suggest a wording change to "2 __more__ suggestions required"? Otherwise if you have selected one person and it says "1 suggestion required" but it doesn't let you submit, that's potentially confusing.

**Comment by hdrury1** [comment]
@tamlyn Good shout.
