### ISSUE TITLE
Create Cancel/Add bar

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#356]
**Product requirements/Acceptance criteria:**

- Bar is fixed to the bottom of the screen and content scrolls behind it

- ~~'Cancel' button should close the people picker modal with no updates to the Submission wizard/Assignment Tab~~ see #385

- ~~'Add' should only become active and clickable once the required number of selections has been made~~ see #385

- ~~Clicking 'Add' closes the modal and replaces the previously clicked selection button component with the chosen person pod(s)~~ see #385

**Relevant links to design(s):**

Screen 1 - Add bar inactive (https://invis.io/QWMEPDWCZ83#/305823519_picker-Author)
Screen 2 - Add bar active (https://invis.io/DAMEPJN937M#/305823520_picker-Author-Selection)
Screen 3 - Selection button replaced with 2 people pods (https://invis.io/83MEPMCTR7W#/305823521_author-Suggestions-Set)

**Comment by tamlyn** [comment]
A question that came up this morning is what should happen if the user clicks the browser back button when on the people picker modal. Should it have the same effect as clicking 'Cancel'?

**Comment by hdrury1** [comment]
Yes @tamlyn.
