### ISSUE TITLE
Add review app urls to PRs

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#357]
**User Story:**

As a developer, I want to see review app urls in Github PRs

**Notes**

Here is a peudo bash script if anyone wants to implement this. It's accurate except the variables are not properly inserted:

```
curl \
 -H 'Content-Type: application/json' \
 -H 'Authorization: token ${GITHUB_ACCESS_TOKEN}' \
 -H 'Accept: application/vnd.github.ant-man-preview+json' \
 -X POST \
 --data '{"ref":"${CI_COMMIT_REF}","environment":"${CI_ENVIRONMENT_SLUG","transient_environment":true}' \
 https://api.github.com/repos/elifesciences/elife-xpub/deployments
```

pipe to `jq -r '.id'` and save as `GITHUB_DEPLOYMENT_ID`, then:

```
curl \
 -H 'Content-Type: application/json' \
 -H 'Authorization: token ${GITHUB_ACCESS_TOKEN}' \
 -H 'Accept: application/vnd.github.ant-man-preview+json' \
 -X POST \
 --data '{"state": "success", "environment_url": "${CI_ENVIRONMENT_URL}"}' \
 https://api.github.com/repos/elifesciences/elife-xpub/deployments/${GITHUB_DEPLOYMENT_ID}/statuses
```

I would put these in a script in pubsweet/deployer and run it in the review app deployment job after deployment.

**Comment by diversemix** [comment]
Superseded by current changes to build pipelines - moving to Jenkins 

@giorgiosironi if there is a specific issue please tag it :+1:

**Comment by giorgiosironi** [comment]
Now in the checklist of https://github.com/elifesciences/elife-xpub/issues/938
