### ISSUE TITLE
Ensure error messages are converted into something user-friendly

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#363]
**User Story:**

_As a non-technical user I want to be presented with user-friendly error messages so that I am not confused by technical jargon._

**Product requirements**

Errors on the server or client side should be presented to the user in non-technical language.

**Relevant tickets**

#144

**Comment by diversemix** [comment]
@hdrury1 you may want to check this again - it might have been fixed as we did some work to fix the creation of invalid data - which was generating some obscure messages

**Comment by hdrury1** [comment]
@diversemix Will put a pin in this for the moment and add any examples as I come across them today. If I don't come across any I'll close it down.

**Comment by hdrury1** [comment]
e.g.

![screen shot 2018-07-18 at 12 05 30](https://user-images.githubusercontent.com/17023702/42877831-dcfe893a-8a82-11e8-8aba-7958dd95a55b.png)

**Comment by hdrury1** [comment]
Closing due to better define issue #625
