### ISSUE TITLE
Make the dropzone animation a little smoother

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#375]
**User Story:**

_As a user I don't want to see the upload progress circle jumping from percentage to percentage. I would like to get a smoother experience of the values changing._

This can be done via CSS transitions and there is already code for that inside Upload icon that it's not currently being used. One possible solution would be to get the new progress and animate from the old one to the new one in a certain amount of time (e.g. 1 second).

**Comment by hdrury1** [comment]
Closing as now obsolete.
