### ISSUE TITLE
Add 10MB+ file warning message to upload dialogue box

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#396]
**User Story:**

_As an editor I want to warn users that files larger than 10MB may incur a delay in review in order to temper their expectations._

**Product requirements/Acceptance criteria:**

Functional:

- A message should be added to the Upload manuscript dialogue box to indicate that files over a certain size may mean an extended review time.

**Relevant links to design(s):**

https://invis.io/X9LHWJ3BHMY#/304489194_wizard-Screen-2

**Comment by dryhten** [comment]
Isn't this issue solved?

**Comment by hdrury1** [comment]
Yes.
