### ISSUE TITLE
PersonPod Icons should darken on hover

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#397]
The icons on a PersonPod should darken when the mouse hovers over them. There should be no darkening on the background of the pod - just the button.

I realise this is a little vague - but its here as this is a visual that needs to be specified further, is difficult to explain and is non-obvious from the wireframes.... i.e. don't shoot the messenger!

**Designs**
![group](https://user-images.githubusercontent.com/17023702/42878192-12c33484-8a84-11e8-948f-d4ed62149199.png)

**Comment by diversemix** [comment]
So ... the 48px from rhs is still the button.. hovering over here darkens only the icon.

**Comment by hdrury1** [comment]
@diversemix is correct. Let's shoot for 50% darker icon on hover.

**Comment by hdrury1** [comment]
@jsms90 Pointer should change to a hand on hover too.
