### ISSUE TITLE
Browser Testing - Grab screenshots

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#399]
**User Story:**

As a developer I want to ensure I know how the site gets rendered on different browsers in different environments. (see #344 )

**Product requirements/Acceptance criteria:**

Use TestCafe & Browser stack to work some magic in CI

**Comment by damnhipster** [comment]
Here's my notes so far:


### Spike/Questions

#### Does Browserstack support the browsers we want?
Yes

#### Can TestCafe execute tests on Browserstack?


#### Can TestCafe take screenshots? Can they be taken manually?


#### How do artifacts work on Gitlab CI?


#### Can/Should we use node-replay on Browserstack?


### BrowserStack
https://live.browserstack.com/dashboard
- [x] get access to browserstack
- [x] run test on browserstack
    - [x] exclude browserstack from node-replay
    - [x] fix https error
- [ ] find browsers to use
- [ ] run on multiple browsers
    - [x] browserstack:chrome@67.0:Windows 10
    - [ ] browserstack:safari@11.1:OS X High Sierra
    - [ ] browserstack:edge@17.0:Windows 10
    - [ ] browserstack:firefox@61.0:Windows 10

### TestCafe
- [x] execute test cafe locally
- [ ] speed up the tests
    - [ ] on safari - 8 minutes
    - [ ] on chrome - 3 minutes
    - [ ] on firefox - 6 minutes
    - [ ] on edge
- [x] add browserstack plugin
- [ ] run on multiple browsers
    - [ ] safari
    - [ ] edge
    - [ ] firefox
    - [ ] chrome

### Screenshots
- [ ] take screenshots using testcafe
- [ ] take screenshots on browserstack
- [ ] save screenshots locally
    - [ ] folder doesn’t exist
    - [ ] folder already exists
    - [ ] file already exists
- [ ] mark screenshot folder as artifact
    - [ ] move screenshot folder to jobs directory
