### ISSUE TITLE
Handle editors with no institution

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#403]
**Product requirements/Acceptance criteria:**

Functional:
- If institution is missing, the line should be replaced with email address (e.g. a reviewer suggested by the submitter that is not a user in the database)

**Comment by tamlyn** [comment]
It seems that some editors in `/people` have no institution and no email address (e.g. the first one returned: Huda Zoghbi). What should happen for these?

**Comment by hdrury1** [comment]
Gah. `/people/` doesn't return either for anyone.

**Comment by tamlyn** [comment]
It does return `affiliation` for some people which I guess is the same as institution?

**Comment by jsms90** [comment]
@hdrury1 I think `/people` does return institution - its called "affiliation"

**Comment by hdrury1** [comment]
And "expertises"

**Comment by hdrury1** [comment]
Sorry folks, closed in error!

**Comment by tamlyn** [comment]
Looks like all reviewing editors have an affiliation but none of the senior editors do. Also `affiliations` is an array in the API data though I haven't seen any examples with more than one. Currently just displaying the first item.

**Comment by hdrury1** [comment]
Thanks @tamlyn for the update. I think you already identified, but just to confirm `expertises` are the MSAs (Major subject areas) while `focuses` are keywords. Is it possible to combine both of these to appear in the Keywords line of the PersonPod? I'm just imagining a use case where you have searched for people with `expertises` Neuroscience but then you receive no visual feedback within the Pod to show why the returned results are as they are.

**Comment by hdrury1** [comment]
@tamlyn Let's leave for now and think about raising another ticket for this functionality once we've got visual designs for the tooltip.

We will need to convert the case to something sensible, yes ;)
