### ISSUE TITLE
Add Styleguide deployment into CI

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#408]
**User Story:**

As a developer I want to see the latest styleguide for elife-xpub

**Product requirements/Acceptance criteria:**

At the moment Tam has manually posted up the following guide:
https://tamlyn.s3.amazonaws.com/elife-styleguide/index.html

This should be done as part of CI - https://alfred.elifesciences.org/job/test-elife-xpub/

**Comment by giorgiosironi** [comment]
Confirm me this spec and I create the resources, along with credentials to used on Gitlab CI to be able to write these files.

**Comment by diversemix** [comment]
I am happy with this spec and Tam is currently working on doing just that in Gitlab CI ... so it seems we are on the same page.

@tamlyn / @damnhipster / @jyenes  ... are we happy with this https://github.com/elifesciences/elife-xpub/issues/408#issuecomment-432998142

**Comment by diversemix** [comment]
NOTE: 
* Giorgio has completed work for this in https://github.com/elifesciences/builder/pull/415/files
* Tam has completed work to host for the time being: https://elifesciences.gitlab.io/elife-xpub/

I am going to put this back into the backlog for now @hdrury1
