### ISSUE TITLE
Add styleguidist build to Gitlab CI for branches

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#409]
**User Story:**

_As a project member I want to see proposed changes to components before they are merged in order to better review PRs and keep up to date with development._

**Product requirements/Acceptance criteria:**

- Run a `styleguidist build` on CI and upload the results somewhere (e.g. S3) in a folder per branch (e.g. using `CI_COMMIT_REF_SLUG`)
- Post the resulting URL somewhere accessible (e.g. on the Gitlab pipeline page/Github PR/Slack channel...)

This is distinct from #408 which is to deploy the current `develop` styleguide using Jenkins.

**Comment by damnhipster** [comment]
#945
