### ISSUE TITLE
Create customised drop zone molecule (wireframe 003)

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#41]

**Comment by g-sam** [comment]
@NickDuf reports the behaviour around accessing the preview is about to change to holding off on implementing the finer details of this component for now

**Comment by NickDuf** [comment]
@g-sam hi-fidelity designs are ready. Quick question for general component styling. Do you need these details now to unblock this work? Personally I would like to hand over these details when I supply the hi-fi form comps next week as a component list.

**Screen A:** Default state. Drag and drop a single file onto the drop zone or click upload text link to open the browser file picker. When file is over the drop zone the border changes colour to brand blue (primary color). 

**Screen B:** Processing state. Outer circle displays percent of file conversion. Highlighted number updates at the same time to show percent complete.

**Screen C:** Success state. Outer circle is 100% complete and arrow icon is replaced with tick icon. Text is updates to display preview and replace links.

**Screen D:** Error state. Outer circle upon error changes to Red and and arrow icon is replaced with cross icon. Text updates to Error message and upload option.

[file-picker.pdf](https://github.com/elifesciences/elife-xpub/files/1987724/file-picker.pdf)
[icons.zip](https://github.com/elifesciences/elife-xpub/files/1987725/icons.zip)

**Comment by dryhten** [comment]
@NickDuf I think I can work with what you uploaded here (file-picker, icons) for now. If I have other questions I will get back to you. I would prefer to start working on this now, but I can wait until next week if there's something you still want to add to these.

**Comment by NickDuf** [comment]
@dryhten no problem. Totally fine for you to start work on the component.

**Comment by dryhten** [comment]
@NickDuf the svg icons in icons.zip don't have the circle from file-picker.pdf (e.g. Success, Error). Do you want to it yourself or should I do it? Not sure where my responsibilities as a dev end :)

**Comment by NickDuf** [comment]
@dryhten :D I imagined that the hoop/progress bar would be achieved using a css type of technique and imagine the progress indicator to be as smooth as possible. More than happy to do a call if you need more clarity

**Comment by dryhten** [comment]
@NickDuf I would have to add the circle first just like you would and then change the color using some CSS trick. I can add it using some free svg editor like inkscape or by hand (though I would remove some of the groups sketch made automatically to make my life easier) since I don't have sketch.

I was thinking of having the static svg images like this: the upload one with a gray circle around it, the success with a blue circle and the failure with a red circle (these two don't really change).

**Comment by dryhten** [comment]
@NickDuf thanks, they look good!
