### ISSUE TITLE
Create an eLife UI package

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#412]
**User Story:**

As a developer the relative import paths make me want to vomit.

**Product requirements/Acceptance criteria:**

See https://github.com/elifesciences/elife-xpub/pull/406#pullrequestreview-141507585

**Comment by diversemix** [comment]
@Cooryd ... use this one

**Comment by jsms90** [comment]
Begs the question whether we want to keep this particular code structure?

I'm not really convinced that we should be keeping as many of our components inside the `atoms` & `molecules` folders as we currently do. Feels quite hard to figure out where to find things.

I would envisage the absolute lowest level things (e.g. Button, Link, Paragraph) staying in `atoms` & potentially the patterns commonly re-used across multiple different pages (e.g. ModalOverlay). But it seems a little pointless having things that are as page-specific as `DashboardListItem` inside that folder?

Of course, this is just a suggestion. Maybe it's not the best idea?

But if we were to do this, would it still be worth publishing a package that contained just a few basic components? Especially when many of our simplest components actually live in pubsweet?
