### ISSUE TITLE
Increase number of editors displayed in People Picker

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#419]
**User Story:**

_As an author or editor I want to be able to scroll through a long list of people in order to find the person I want._

**Product requirements/Acceptance criteria:**

Functional:
- Currently the people picker gets quite slow so an artificial limit of 30 results has been imposed
- Remove this limit and ensure rendering stays acceptable with a long (>300) list of people 
- This may just be a case of optimising the rendering or implementing a virtual scrolling behaviour

**Comment by tamlyn** [comment]
Did a bit of profiling and couldn't see any obvious performance problems in the components. Each person pod takes a few milliseconds to render but when you render 300 of them it all adds up. 

![image](https://user-images.githubusercontent.com/115310/43525597-2e655dcc-959a-11e8-854b-e281de99d7bd.png)

You can optimise them to only re-render when needed (e.g. with [onlyUpdateForKeys](https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforkeys) which helps but initial render is still slow.

Next avenue of exploration should probably be [react-virtualized](https://github.com/bvaughn/react-virtualized).

**Comment by diversemix** [comment]
I know this is not about rendering - but I noticed the people picker makes two graphql queries one with role `senior-editor` and the other with `reviewing-editor` - these requests are made on the page regardless of how you have arrived (via wanting to select senior or reviewing). Is this an oversight? ... @tamlyn

**Comment by tamlyn** [comment]
No, that's as designed. It simplifies the structure of the page and was deemed to be a small cost. But we could change it to load the data only when the modal is shown.

**Comment by hdrury1** [comment]
Can someone confirm if this is still a to-do?

**Comment by tamlyn** [comment]
Yes, this is still to do in order to remove the 30 pod display limit (and even that will be slow on older devices).

**Comment by damnhipster** [comment]
### Background 

Off the back of #419, we decided to put `react-window` in place to improve the performance of the people picker when you have 

### Behaviour of `react-window`
`react-window` doesn't give us flexibility to use window scrolling to control rendering, and instead creates a new scrollable component. It also doesn't allow you to add a header or footer onto the scrollable component, so it's not ideal to render large lists which are part of a page.

You can see it in action here:

![react-window-demo](https://user-images.githubusercontent.com/2573277/49735741-084bd100-fc80-11e8-9dda-3b6548fd1061.gif)

Another issue is that we lose the responsive functionality of the people picker.

### Solution
[`react-virtualized`](https://github.com/bvaughn/react-virtualized) helps solve the above issues:
- Use the [window scroller](https://bvaughn.github.io/react-virtualized/#/components/WindowScroller) feature to keep the existing behaviour, by rendering pods in view based on the window scroll
- Use the [autosizer](https://bvaughn.github.io/react-virtualized/#/components/AutoSizer) feature to keep the responsive behaviour
- If autosizer doesn't work, we can use [columnsizer](https://bvaughn.github.io/react-virtualized/#/components/ColumnSizer) instead

**Comment by damnhipster** [comment]
Performance is abysmal when running locally, but when building and running the app in production mode, the performance is better.

We've deemed that the performance is adequate. Further performance enhancements will be done in #1225. Our findings will be captured there.
