### ISSUE TITLE
Use validationColor from ui-toolkit

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#430]
Right now we use several functions similar to [validationColor](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/release/packages/ui-toolkit/src/themeHelper.js#L19) from pubsweet. For example

1. [Subject Area Dropdown](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/pages/SubmissionWizard/steps/Submission/SubjectAreaDropdown.js#L75)
2. [NotificationRibbon](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/NotificationRibbon.js#L4)
3. [TextField](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/elements/ui/TextField.js#L14)
4. [TextArea](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/Textarea.js#L13)

We should figure a way to reuse the same function to avoid duplicated code. If re-using `validationColor` is too difficult, we could try to make it more generic.

**Comment by hdrury1** [comment]
Closing as obsolete.
