### ISSUE TITLE
Use styled components instead of CSS modules to style the SearchBox

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#437]
Right now the SearchBox component is styled using CSS modules: [SearchBox.local.css](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/molecules/SearchBox.local.css). It would be better to use styled components instead: first for consistency since we already use styled modules everywhere in the code, and second to be able to use theme variables. Right now everything is hardcoded in the CSS file so if the theme changes we have to manually make these changes ourselves for the SearchBox.

The reason we went for CSS modules is that they are already supported in react-autosuggest (what we used for the search box) while styled components are not. It might be tricky to use styled components since we have to target individual components from the autosuggest (like the input field or the list of suggestions).

**Comment by dryhten** [comment]
Just leaving this here in case someone wants to pick on this issue: micropubs uses react-autosuggest styled with style components and it looks pretty straightforward to replace the CSS module we have with styled components.

https://gitlab.coko.foundation/micropubs/wormbase/blob/author-submits-article/app/components/formElements/AutoComplete.js#L13

**Comment by jsms90** [comment]
`react-autosuggest` isn't written to support `styled-components` (https://github.com/moroshko/react-autosuggest#themeProp):
> Autosuggest comes with no styles.
>
> It uses react-themeable that allows you to style your Autosuggest component **using CSS Modules, Radium, Aphrodite, JSS, Inline styles, and global CSS**.

Specifically, react-autosuggest doesn't use the `className` prop. See an issue that was already raised about this: https://github.com/moroshko/react-autosuggest/issues/535

This is not only in the render function within `react-autosuggest`: https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L698-L716, but also throughout the code in `react-whatever` that autosuggest relies upon: https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js

Seems like they got around this in wormbase by assuming the exact structure of the HTML & deeply nesting their CSS with styled-components
https://gitlab.coko.foundation/micropubs/wormbase/blob/1af4f5bde1e5ee0b8a3176802ed1705ae1964b51/app/components/formElements/AutoComplete.js#L13-54

**Comment by dryhten** [comment]
The class names for react autosuggest are documented here https://github.com/moroshko/react-autosuggest#theme-optional

Since it worked for micropubs I would try that as well and if it works I would stick with it (not sure you need to specify the entire path to the component, just the class name itself, e.g. `react-autosuggest__input`)

**Comment by jsms90** [comment]
Yeah thanks @dryhten :+1: I'm unsure whether I've misunderstood something, or just not explained myself very well?

Those hard coded class names are the way that you access these components with CSS modules. Since wormbase/micropubs are using styled-components, as you say, the only way they can access the sub-components is by using these hard-coded class names. To be more specific, they have used styled-components on a wrapper div (since the `className` prop isn't passed down in `react-autosuggest`) & then accessed the sub-components via deeply nested CSS on that wrapper.

As I said, I am intending to do the same thing that wormbase/micropubs has done it, at least for now (possibly/probably long-term). Such is the way, when using 3rd-party components :grin:

**Comment by dryhten** [comment]
I was just saying that I would investigate this:

Do you have to use the entire path in the CSS selector (e.g. `div[role='combobox'] { ... div.react-autosuggest__input { ... }`) or just the class name for the react autosuggest component? (e.g. `react-autosuggest__input`) If the latter, then it's not really hardcoding, since those class names are documented. If the former, then it feels like hardcoding and I'm not sure I would like this solution. It will probably be hard to feed the component back to pubsweet too, since page hierarchy will be different in most cases (like styleguide etc)
