### ISSUE TITLE
Improve search/filtering functionality for the People Picker

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#443]
The list of suggestions displayed in the search box should be improved. The matching should happen at the beginning of words and the list should be sorted by relevancy.

**Comment by dryhten** [comment]
Updated issue to reflect the discussion we had at the standup.

**Comment by hdrury1** [comment]
@dryhten Consensus from Product is that the items should be listed by order of relevancy. I know we spoke about this over a call but wanted to record it here too.

**Comment by dryhten** [comment]
@hdrury1 should they be sorted alphabetically too? (e.g. if nothing is typed in the search box)

**Comment by dryhten** [comment]
https://github.com/elifesciences/elife-xpub/issues/467

**Comment by hdrury1** [comment]
If nothing is typed in the box, they should be sorted alphabetically with already selected persons first.

**Comment by dryhten** [comment]
Even if the keywords with the selected people are right under the search box? I was playing with this and it can lead to weird behavior/inconsistencies. What happens if you select something from a page? Should it move to the top right away or when should it move to the top? If you refresh the page/modal with the current implementation you lose all the selections so the only behavior that wouldn't scare the user would be to move them to the top only on new searches which seems a little tedious right now (I would make a new issue for it)

**Comment by hdrury1** [comment]
Let's just have the full list for now and see how that goes down in testing. If we need to tweak the behaviour after this we can do.

**Comment by dryhten** [comment]
Done, right now the matches only happen at the beginning of the words for single word inputs. For inputs containing multiple words it's basically a substring search. The results are sorted by where the match happened (e.g. first word, second word etc).

**Comment by diversemix** [comment]
@hdrury1 Something tells me we should actually document (somewhere) how this search functionality behaves - otherwise we might be in for repeating ourselves :)
