### ISSUE TITLE
Submission page loses responsiveness

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#446]
**Describe the bug**

After selecting "Suggest Reviewing Editors" on the submission page the page loses responsiveness

**Expected behavior**
The page should remain responsive.

**Screenshots**
Attached
![without-selected](https://user-images.githubusercontent.com/8524685/43827466-cddef3f2-9af1-11e8-9ff3-00da4f012b57.png)
![with-selected](https://user-images.githubusercontent.com/8524685/43827467-cdf68a08-9af1-11e8-9119-2fd563d12ff1.png)

**Comment by tamlyn** [comment]
Good spot. This is caused by https://css-tricks.com/flexbox-truncated-text/

**Comment by hdrury1** [comment]
@diversemix Can you confirm this is still an issue? I can't re-create.

**Comment by tamlyn** [comment]
Yes, this is still an issue. It depends on which editors have been selected. Choose the ones in the screenshots, for example, or any where the list of keywords is truncated.
