### ISSUE TITLE
People Picker position of information text

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#448]
**Describe the bug**
The people picker has the information text on the same level as the blue "tags" - the information should be beneath these

**Screenshots**
In this case "Maximum 2 choices" should be beneath the blue people at the top.
 
![pp-wrapping](https://user-images.githubusercontent.com/8524685/43831833-54bc7e48-9afd-11e8-8d82-46653b8f5f19.png)

**Comment by tamlyn** [comment]
Is this only at the smallest (single column) breakpoint? And with a standard 24px margin above and below?

**Comment by hdrury1** [comment]
Closing due to duplicated ticket
