### ISSUE TITLE
Add list of subject areas to Search Box

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#450]
Right now the Search Box on the People Picker Modal only shows people as suggestions in the dropdown list. Subject areas should be added to the list too. Also, we should make sure that the mechanism for filtering out People Pods takes this into account too.

There is currently no way that I know of to retrieve the list of subject areas from an eLife API. The only eLife API I know of is documented at [1], and the only query that returns subject areas is the `/people` one (as `research.expertises.name` from `items`) so we could go through the list of people and record all unique subject areas.

[1] - https://api.elifesciences.org/documentation/

**Comment by hdrury1** [comment]
Closing this down due to updated feature requirements.
