### ISSUE TITLE
Add list of institutions to Search Box

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#451]
Right now the Search Box on the People Picker Modal only shows people as suggestions in the dropdown list. Institutions should be added to the list too. Also, we should make sure that the mechanism for filtering out People Pods takes this into account too.

There is currently no way that I know of to retrieve the list of institutions from an eLife API. The only eLife API I know of is documented at [1], and the only query that returns institutions is the /people one (as `affiliations.name` from `items` or `person.aff` in our converted object) so we could go through the list of people and record all unique institutions.

**Comment by hdrury1** [comment]
Closing this down due to updated feature requirements.
