### ISSUE TITLE
Enter key behavior on Search Box

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#452]
When you hit the enter key in the Search Box the list of Person Pods will get updated to match your query. However, if you navigate in the dropdown list of suggestions (e.g. using the arrow keys) and hit enter again to select a suggestion, this key is recorded inside the Search Box as well so the list of Person Pods will get updated to match the suggestion you just selected.

While as an user I like this behavior (just talking personally here), this is not the desired functionality for the Search Box. The requirements are to hit enter twice, first to select the suggestion and second to filter the results/person pods. This might be a little tricky to implement.

**Comment by gmaciocci** [comment]
I tend to agree with @hdrury here

**Comment by dryhten** [comment]
Ok, closing this issue then.
