### ISSUE TITLE
Resize icons on PersonPod

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#458]
Currently, the plus and rubbish icons are 24x24px within the PersonPod component. They should be 14x14.

<img width="319" alt="screen shot 2018-08-09 at 07 48 52" src="https://user-images.githubusercontent.com/17023702/43882729-b46cf1d2-9ba8-11e8-8910-cc151121f110.png">

**Comment by jsms90** [comment]
@hdrury1 I was going by the invision styleguide, which says "context icons: 36px x 36px"

![image](https://user-images.githubusercontent.com/15656538/43910424-b4933580-9bf4-11e8-8e57-969f9744b853.png)

I'm pretty sure it used to say that the other icons (plus and rubbish bin) were 24px and only the selected tick was 36px. Is 14 x14 a new requirement? And does the selected icon size need to change?

**Comment by hdrury1** [comment]
@jsms90 I believe 36x36px is the size of the whole area... i.e. the space that PersonPod should leave for the icon regardless of what that icon is. The selected icon looks good to me- it visually matches the style guide. Within the icon area, the plus and rubbish icons should be smaller, i.e. 14x14px. It's something that's been picked up on in visual testing.

**Comment by jsms90** [comment]
Fixed automatically by switching to Material icons :smile:
