### ISSUE TITLE
Submitter not stored in database

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#477]
Currently only the 'author' role is stored in the database, allowing for one (corresponding) author. However, we need to store also the details of the currently logged in user (the submitter) to account for cases when the two are different. This is of high priority as the information is needed to create the same MECA file.

**Comment by jsms90** [comment]
@diversemix and I discussed this at standup - this may go into the db under the `createdBy`. Moving this into the backlog, as this can't/shouldn't be picked up until #473 is finished.

Also, in terms of our roadmap, this probably falls under the "MECA export" epic? And we've still got plenty of other epics in progress atm.
