### ISSUE TITLE
Corresponding author status not recorded in database

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#478]
Currently we do not record when the `<role>author</role>` is corresponding. We should add a boolean value to account for future instances when more than one author is linked to a manuscript.  This is of high priority as the information is needed for the sample MECA file.

**Comment by tamlyn** [comment]
Agreed that we need this in future but since we only record a single author at this time, can we not infer that this is the corresponding author?

**Comment by hdrury1** [comment]
I'm keen to ensure the XML we send to eJP is as clear as possible so nothing has to be inferred.
