### ISSUE TITLE
Create data disclosure page

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#489]
- There should be an additional page added to the wizard to allow the submitter to confirm they are happy with our data disclosure agreement

- The page should pull in the article title, current date and corresponding author's name captured in Steps 1 and 2 of wizard.

- 'Privacy policy' should link to https://elifesciences.org/privacy-notice

- The user should not be able to proceed past this page without ticking the box and entering a value in the name input

- Validation message for the tick box should be 'We are unable to proceed without your consent.'

- An extra step should be added to the progress indicator to account for the extra page.

**Designs**

![wizard-screen-5 2x](https://user-images.githubusercontent.com/17023702/44259837-96500780-a20a-11e8-95bc-d3f36fb55a67.png)

<img width="553" alt="screen_shot_2018-08-13_at_16 36 39" src="https://user-images.githubusercontent.com/17023702/44264085-43ca1780-a219-11e8-8413-689f2a75bef7.png">

**Comment by jsms90** [comment]
#### Manuscript author names
In this wireframe, it lists "Natasa Savic" & "Sara Marinelli" as authors, but there is nowhere in our wizard where they would enter the names of other authors. Are we intending on pulling this info out from the manuscript with sciencebeam during the file upload step of the wizard?

At the moment, if ScienceBeam can't fetch the manuscript title from the file upload step (for whatever reason), the submitter can still enter the title themselves during step 3 of our wizard :+1: So if we were to de-scope wizard step 2 (so that it's only a file upload rather than extracting info as well) then we would need to get all the manuscript info that we need from step 2.

#### Pulling info
> The page should pull in the article title, current date, submitter's name and corresponding author's name captured on page 1 (if different)

I don't see the submitter's name anywhere in the copy. Do we need to pull in this info for anything? The submitter just needs to add their own name to the acknowledge box, right?

#### Validation
Presumably there is validation on the name input field, but only that it be non-empty?

**Comment by jsms90** [comment]
Might it be a good idea to call this step "Disclosure" in the progress bar, rather than "Data"?

**Comment by hdrury1** [comment]
@jsms90 Name should be collected from Step 2 of the wizard. Pulling other names out using ScienceBeam is probably outside the scope of this issue and potentially outside the scope of first release. In reality, there will only be one name listed here. Updated top description accordingly.

Title should also be pulled from Step 2... whether it's got there via ScienceBeam or manual input.

Yes, validation for non-empty only.

**Comment by hdrury1** [comment]
I've had similar comments regarding title of this step from internal feedback too, so let's go with 'Disclosure'.

**Comment by diversemix** [comment]
@hdrury1 I guess I have the same question as @jsms90  ... where do we get the author list of names from to show on this page?

**Comment by diversemix** [comment]
![image](https://user-images.githubusercontent.com/8524685/44266024-e33ed880-a220-11e8-95bb-bc6254987f09.png)

There are two names in the example, but  if there are 10 authors do we need to display them all here? @hdrury1

**Comment by hdrury1** [comment]
I think the design is confusing matters. In reality, there will only be one name listed here- that captures in Step 1.

**Comment by jsms90** [comment]
All good. Thanks for the clarification @hdrury1. I trust that you're more likely to know than me, whether it's ok for first release to only show the corresponding author and not the other authors' names.

Do you happen to know the sizing for all the headings/paragraphs on this page?

**Comment by hdrury1** [comment]
Body + name = fontSizeBase
Article type + date = fontSizeBaseSmall
Header = h2 (match other pages)
Title = h3

Let's see what that looks like.

**Comment by jsms90** [comment]
So we've talked about the "Manuscript author names" part of [my comment above](https://github.com/elifesciences/elife-xpub/issues/489#issuecomment-413829883). Any thoughts on this @hdrury1?
> I don't see the submitter's name anywhere in the copy. Do we need to pull in this info for anything? The submitter just needs to add their own name to the acknowledge box, right?

In the requirements, you specify that the _submitter_'s name should also be pulled in. But I don't see anything on the page where we use this.

Do you intend for us to pre-populate the "acknowledge" input field with the submitter's name or something?

**Comment by hdrury1** [comment]
Not sure I understand what the outstanding question is. One name (first and last) should appear on this page below the title. This will be the name entered in Step 1 of the wizard. I updated the top description to remove 'submitter's name'.

The acknowledge field will not be pre-populated. The user enters their own name manually, and it is stored against the manuscript as `dataAcknowledgementName` or similar.

**Comment by jsms90** [comment]
Oh right, I didn't see that you'd edited the requirements to now be:
> The page should pull in the article title, current date and corresponding author's name captured in Steps 1 and 2 of wizard.author's name captured on page 1 (if different)

where it used to say
> The page should pull in the article title, current date **submitter's name** and corresponding author's name captured on page 1 (if different)

My bad. No outstanding questions :grin:

**Comment by jsms90** [comment]
Just to update on progress beyond what's in the PR, I'm battling console errors that are thrown whenever I interact with the form fields on the disclosure page:
![image](https://user-images.githubusercontent.com/15656538/44460644-d39b0780-a605-11e8-887d-ace43b62b7c5.png)

Unsure whether my misunderstanding is with yup, formik or generally how our submission wizard is connected. But I know that one way or another, I've not connected this new page correctly.

**Comment by diversemix** [comment]
I don't mind taking a look @jsms90  ... are your current changes pushed onto the branch?

**Comment by diversemix** [comment]
@jsms90 ... found it! Its in `schema.js` ... change: ```
  disclosureConsent: yup.bool().required,
``` to ```
  disclosureConsent: yup.bool().required(),
```
