### ISSUE TITLE
Fix resolvers 'extracts title from PDF' test

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#493]
Right now this test is skipped. It was supposed to be done as part of https://github.com/elifesciences/elife-xpub/pull/368 but it's not something fast to be fixed and the PR had to be merged for various reasons. Before `uploadManuscript` is called a `Subscribe.uploadProgress` subscription should be done.

**Comment by diversemix** [comment]
The upload test is being removed as part of #497  ... this will need to be re-added.

**Comment by tamlyn** [comment]
Done some time ago.
