### ISSUE TITLE
Remove upload progress message in dropzone molecule when file finishes uploading

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#495]
Right now when you upload a file with the dropzone molecule the message under the arrow icon will stay at "Manuscript is uploading 100%" even after the file finished uploading (e.g. while it's being converted by ScienceBeam). We should replace this text with something else (e.g. "Manuscript is being converted %" or "Upload finished").

**Comment by hdrury1** [comment]
Closing, as should be considered when working on #839
