### ISSUE TITLE
Write documentation for People Picker Search

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#498]
The people picker search functionality is quite complex and involved. We need to write some more extensive tests and some documentation to go with it.

Maybe this should be done after being reviewed by product? @hdrury1 

**Related**  #476

**Comment by hdrury1** [comment]
Now we've got first cut functionality in, I'm happy to document how it works (I think this will benefit us when we come to iterate/build on it). Not sure where the best place for this to live might be.

**Comment by jsms90** [comment]
At standup yesterday, I think we agreed that this needed to be split in 2? Since @hdrury1 is assigned to this, I'm gonna make this one "documentation" and raise another for writing tests
