### ISSUE TITLE
Validate article IDs for related work (considered previously & co-submissions) based on query to eLife API

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#50]
- ~(1) Retrieve subject areas and article types from elife API~ - moved to issue #42 
- (2) Validate related work against existing article ids

Use case:
A paper has been previously rejected and the authors go away, revise and resubmit. The paper needs to be seen by the same editors and reviewers, who will need easy access to the previous submission so they can re-familiarise themselves with the original issues and evaluate if the authors have adequately addressed them.

**Comment by jsms90** [comment]
(1) - Work is blocked behind #42 

(2) How would the validation of related work be displayed on the page?

Most recent designs:
![metadata-page-checked](https://user-images.githubusercontent.com/15656538/39184199-71091fc0-47ba-11e8-9ac4-260b7782d189.png)

Current state of application (includes both input fields underneath the final checkbox):
![article-references](https://user-images.githubusercontent.com/15656538/39582106-19ac25d8-4ee5-11e8-95ff-9358b3d4528f.png)

### Considered previously
Validating a manuscript that has been considered previously, we can definitely retrieve the info from the eLife API.

Therefore, the suggestion from the YLD devs (original posed [here](https://github.com/elifesciences/elife-xpub/issues/45#issuecomment-384231976)) is to create/use an autocomplete dropdown component:
> So would you like something like [this](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=autosuggest&full=0&addons=1&stories=1&panelRight=0)? With each of the items in the dropdown being something like:
>
>  - 14107 Molecular basis for multimerization in the activation of the epidermal growth factor
>  - [ref no/article id] [article title]

Validation = user must choose one of dropdown menu

### Cosubmission
When we're validating a cosubmission, the article may not have been submitted yet. In that case, it would not yet be in the list given by the eLife API.

From @NickDuf 
> We could probably have the checkbox 3 input validate if an article is in the system or otherwise leaving it as free text if not giving us only one input.

Validation = user may choose from dropdown menu, but can also submit their own text

**Comment by jsms90** [comment]
Currently blocked by:
- Clarity on designs - are we definitely displaying a dropdown based on what the user is typing, which updates as they're typing it?
- Ability to query for the right data via eLife's API

See [this Slack thread](https://elifesciences.slack.com/archives/C6LKMFK5Z/p1525419788000331) for the most up-to-date convo

**Comment by NickDuf** [comment]
Clarity on designs - are we definitely displaying a dropdown based on what the user is typing, which updates as they're typing it? - Yes that is correct.

This manuscript is a co-submission' input
- Suggestions to be based on either 'article ref no' or 'title' if the article is in the system. If a selection is made only the title is added and displayed in the text field
- No need for the additional ref number input

**Comment by NickDuf** [comment]
Don't action the above comment now. After discussing the control internally I need to share additional designs.

**Comment by hdrury1** [comment]
Closing this down due to lack of hi-fi design and requirements.
