### ISSUE TITLE
Update AppBar component to include mobile layout

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#503]
**Product requirements**
- If not logged in, the user should have a 'Login' link on the right-hand side (colorPrimary)
- If logged in, the user should have a user icon (24px x 24px) and dropdown (4px to the right of the icon)
- On mobile, the links should be replaced with a burger menu

**Designs**
[Invision prototype](https://invis.io/FDOIB61EKV5)

![screen shot 2018-10-11 at 12 51 29](https://user-images.githubusercontent.com/17023702/46802134-69285d00-cd54-11e8-868f-a8e981b35879.png)
![image](https://user-images.githubusercontent.com/41907215/46817671-6b4fe300-cd77-11e8-8135-5af6218a4f72.png)

**Comment by tamlyn** [comment]
> Inactive links are colorBorder

The invision designs seem to show this as `colorTextSecondary` instead. `colorBorder` on white background would be very low contrast.

**Comment by hdrury1** [comment]
Thanks @tamlyn good spot (updating description)

**Comment by Cooryd** [comment]
See #871 for details on the menu component to use.
