### ISSUE TITLE
Pre-populate form fields using Orcid data 

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#51]

**Comment by tamlyn** [comment]
The OAuth credentials are saved on the user object at logon and can then be used to access the [ORCID API](https://api.sandbox.orcid.org/v2.0/#/Member_API_v2.1). Institution will be filled in from the `employments` endpoint.

**Comment by thewilkybarkid** [comment]
Don't know if you're using the JSON version of the ORCID API or XML, but might be useful to look at a few of the bugs/misunderstandings we've dealt with when putting together our Profiles service:

- https://github.com/elifesciences/profiles/pull/42
- https://github.com/elifesciences/profiles/pull/47
- https://github.com/elifesciences/profiles/pull/57
- https://github.com/elifesciences/profiles/pull/60
- https://github.com/elifesciences/profiles/pull/65

**Comment by diversemix** [comment]
I've been looking into ORCID and GDPR and it seems as though they have made a few changes we should be aware of. The fact that it is possible for a user to set their privacy settings to prevent this:

https://github.com/ORCID/ORCID-Source/pull/4476/files

**Comment by jsms90** [comment]
Blocked by Orcid login not working - to be fixed with issue #106

**Comment by jsms90** [comment]
MR open: https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/56
