### ISSUE TITLE
Create 'Thank You' page

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#512]
**User Story:**

_As a submitter I want feedback that my submission has been received._

**Product requirements/Acceptance criteria:**

Functional:

- User should be redirected to the page after hitting 'Continue' on the previous modal (see #511 )

- The title and author name and email address should be pulled in from previous steps in the wizard.

- 'Finish' redirects the user to their dashboard

- The browser's back button should be disabled

**Design:**

![wizard-finish-screen-edit 2x](https://user-images.githubusercontent.com/17023702/44398216-ff9d8680-a53a-11e8-82dc-0f43bb88237b.png)

**Comment by jsms90** [comment]
@hdrury1 shall we close this now that #736 is in?

**Comment by hdrury1** [comment]
Yes.
