### ISSUE TITLE
add date to disclosure page

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#519]
Product requirements:
- Show author the date based on their timezone

Designs:
![wizard-screen-5 2x](https://user-images.githubusercontent.com/17023702/44259837-96500780-a20a-11e8-95bc-d3f36fb55a67.png)

Current:
![image](https://user-images.githubusercontent.com/15656538/44478633-30161b00-a636-11e8-9cbe-ba30dcf7413c.png)

Potential options:
- https://date-fns.org/
- https://github.com/iamkun/dayjs
- Pubsweet currently depends on Moment.js already

**Comment by jsms90** [comment]
We had a discussion at standup about the product requirements for this. Showing the date based on the user's timezone seems to be a best guess for now. But we're aware that the journal only shows GMT publication dates, so there was a questions around whether we would want to show a different date to the author within the wizard.

The suggestion here is to add a date library to the project & go with author's timezone for now, with the understanding that product requirements may change.

**Comment by hdrury1** [comment]
> Especially if we don't end up showing the author the date based on their own timezone, date-fns is looking pretty good.

Product requirements are that any user-facing feature displays date/time in user's zone.
