### ISSUE TITLE
Store Manuscript uploads into S3

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#520]
@hdrury1 - Not sure if this is required for release - but I'm raising this as I think it would be diligent to ensure that xpub keeps a copy of what was submitted - as well as exporting to eJP.

**Comment by jsms90** [comment]
Going to move this into Backlog, as the top comment indicates that we're not sure where this does/would fit into the product roadmap? So I'm not sure this ticket is ready to be picked up yet

**Comment by hdrury1** [comment]
Can stay in the Backlog for now, but definitely a first release feature (see [this card in 'Next'](https://trello.com/c/kkbNPtVA/38-file-upload))
