### ISSUE TITLE
consistent naming of wizard steps across application

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#523]
During the frontend refactor, where the `pages` folder was added & we classified the submission wizard pages under `pages/SubmissionWizard/steps`, we also renamed the files/variables relating to each wizard step (with the new names being based on the progress bar in the UI :+1:)

But in many places in our codebase, we still use the old names for these steps. Namely:
- [x] the URLs associated with each step
- [x] in our tests
- [x] import/export names of files
- [x] docs (i.e. styleguidist)

The rename went like this:
- Step 1: `AuthorDetails` -> `Author`
- Step 2: `FileUploads` -> `Files`
- Step 3: `ManuscriptMetadata` -> `Submission`
- Step 4: `ReviewerSuggestions` -> `Editors`

If we still have renaming to do across the app, now might be a good time to ask whether "Submission" & "Editors" are the most intuitive names for these sections?

"Editors" feels less problematic. But the original name of "reviewer(suggestions)" might better encapsulate all the things that an author fills in on this page? After all the reviewers are not editors, but all of the editors are "reviewing" the submission.

But the main one that seems strange is "Submission". Every time I see this, I think this is the page where you upload the manuscript to the system.

**Comment by jsms90** [comment]
@hdrury1 I've changed the URL so that it is in line with the naming on the progress bar, since everything user-facing should be the same :+1: So it is now `localhost:3000/submit/submission` instead of `localhost:3000/submit/metadata`.

But I still think that it will cause unnecessary confusion for developers if we use this word elsewhere in the codebase. If I see a file called `submission.test.js`, for example, I would assume that it's testing the act of submission itself, rather than testing the ability to enter a manuscript title, subject area, etc.

**Comment by damnhipster** [comment]
#367

**Comment by damnhipster** [comment]
This was a good time to address this. I wasn't able to do this earlier as part of #367 because we had too many open PRs and there was a definite risk of conflicts arising.
