### ISSUE TITLE
Write tests for PeoplePicker (integration of the search functionality)

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#527]
> The people picker search functionality is quite complex and involved. We need to write some more extensive tests

**Comment by jsms90** [comment]
Just to clarify @diversemix, are you talking about tests for [the `SearchBox` component](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/molecules/SearchBox.js)? Because most of the complexity exists in `react-autosuggest` itself, or in this component.

Or are you talking about the integration between the search box itself & the people picker - i.e. testing the `PeoplePickerModal` which integrates the search box and the people picker?

Or do you mean both? i.e. separate tickets?

**Comment by diversemix** [comment]
Well I don't know if @hdrury1 finished the documentation about the search component. But if/when its finished to test against that would make sense. 

My idea is that a day or two are spend bolstering the tests around the People Picker.

**Comment by jsms90** [comment]
:thinking: Mihail has already opened an issue for testing the SearchBox itself. But perhaps this goes further than just the search box in isolation? Perhaps we should keep this ticket open for testing the integration between the `PeoplePicker` itself & the `SearchBox`? Changing the title to reflect that
