### ISSUE TITLE
Send email to author on form submission

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#53]

**Comment by diversemix** [comment]
Questions around this issue before taking... There are currently no workflow components integrated - I'm assuming this is best done by a server-side component listening to the submission request? Also, how is the email to be sent, will we need a service for message delivery? Copying to discussion in Slack - #xpub

**Comment by dryhten** [comment]
@diversemix not sure if your question was answered or not. We will probably end up using a pubsweet component for sending e-mails https://gitlab.coko.foundation/pubsweet/pubsweet/tree/master/packages/components/SendEmail-server

This component would get called in the GraphQL resolver for the submission mutation, on the server side. There is no listening for events as far as I'm aware.

**Comment by tamlyn** [comment]
At the last Coko meet in February there were some initial discussions about a "PubSweet event subsystem" which would handle all email sending. It would be something like RabbitMQ plus some recipes to hook event sources (user actions, scheduled tasks, file conversion...) to actions (send an email, run a report, send a browser notification...). Not too dissimilar to Airflow. 

As such, I've been viewing the existing `SendEmail` component as a stopgap. But three months later the gap is still there and there doesn't appear to be any effort underway to close it.

**Comment by dryhten** [comment]
Currently blocked by #156

**Comment by dryhten** [comment]
@hdrury1 Another thing we need to discuss here is what the e-mail should look like. Is there a template out there for this?

**Comment by hdrury1** [comment]
@dryhten No template as yet, but this is something we should ask the Editorial team to draft.

**Comment by diversemix** [comment]
@hdrury1 My view is this should be closed out, and we raise a ticket for the Editorial Team words.

@dryhten As long as there is a template for email and this has been tested with a mail server this ticket should be closed, as we have raised one for the email server.
