### ISSUE TITLE
Deploy mirroring job to Kubernetes

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#530]
### Background

Deploy work done in #481 to Kubernetes, and add deployment templates to codebase

- [ ] create deployment template and add it to the codebase
- [ ] create configmap template to mount ssh key, and add it to the codebase
- [ ] add ssh key as a secret
- [ ] replace existing deployment, which has been manually deployed to cluster

**Comment by giorgiosironi** [comment]
I think this could be closed as we are retiring Kubernetes usage on Gitlab CI for eLife?

**Comment by diversemix** [comment]
Agreed
