### ISSUE TITLE
Suggested Reviewers fields are slow

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#541]
**Describe the bug**
When you navigate to the Editors step in the Submission Wizard and you try to type something fast in the Suggested Reviewers fields it takes a while for the characters to be displayed. This creates a bad/slow feedback for the users.

**To Reproduce**
1. Go to Editors step in the Submission Wizard (tested on version 52fafe3 on develop)
2. Start typing fast in the Suggested Reviewers fields

**Expected behavior**
The feedback you get from the input field should be smoother.

**Comment by hdrury1** [comment]
Closing down as I'm not convinced this is an issue.
