### ISSUE TITLE
Cursor jumps to beginning of e-mail field when deleting a space in Suggested Reviewers

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#542]
**Describe the bug**
If you type a bunch of words separated by whitespace in the Reviewer e-mail field from Suggested Reviewers and then backspace to delete them, when you reach a space the cursor will jump back to the beginning of the field.

**To Reproduce**
1. Go to Editors step of Submission Wizard (tested on version 52fafe3 from develop)
2. Start typing something with whitespaces in any e-mail field from Suggested Reviewers (e.g. in `Reviewer 1 email` type `this is a test`)
3. Hold backspace to delete what you just typed in the field
4. You should see the word `test` being deleted and the cursor jumping to the beginning of the field (right before `this`) after that

**Expected behavior**
The cursor shouldn't jump to the beginning of the field.

**Comment by hdrury1** [comment]
Closing down as no longer an issue.
