### ISSUE TITLE
Prevent the server from sending all push back messages at once

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#546]
**Describe the bug**
When you try to upload a file with the dropzone molecule, the websocket server will send progress messages at once, so it stays at 0% and then it suddenly jumps to 100%.

**To Reproduce**
1. Go to Files page (assuming connection to websocket was OK)
2. Upload a (larger) manuscript
3. See that after 0% it jumps really fast to 100%

**Expected behavior**
The server should send back each individual message when it's published, instead of sending them all at once.

**Comment by diversemix** [comment]
I suggest we see if we can turn on `TCP_NODELAY` ... which effectively turns off Nagle's algorithm.

http://nginx.org/en/docs/http/ngx_http_core_module.html#tcp_nodelay

**Comment by dryhten** [comment]
Can you test this fast enough? If this solves the issue there is no need to hide upload progress.

**Comment by diversemix** [comment]
Ah! The default is `on`  ... so maybe this is not the issue. Just going to check on the actual server.

**Comment by dryhten** [comment]
We tested this without nginx and the behavior was weirder: a random number of messages were sent initially, then nothing for a while and finally all the remaining messages were sent at once. I had 1-2 tries where this was working perfectly which makes it even weirder.

Another idea we had is that maybe the messages are sent too fast (5-10ms apart), so spreading them to at least 500ms apart might work. The PR for this is here https://github.com/elifesciences/elife-xpub/pull/645

**Comment by dryhten** [comment]
Just tested https://github.com/elifesciences/elife-xpub/pull/645 on [kubernetes](http://review-add-delay-399fcd.gateway.xpub.elifesciences.yld.io) and it doesn't seem to solve the problem. Now the browser only receives the last message with 100%.

**Comment by dryhten** [comment]
We finally got the hang of this. It turns out that the file was first uploaded to nginx and while this was happening the docker process running node.js was not receiving anything. Only after the entire file was uploaded to nginx it was passed to the docker process, resulting in the upload progress going from 0 to 100% really fast. To enable streaming `proxy_request_buffering` had to be turned off for nginx, which was done here https://github.com/elifesciences/elife-xpub-formula/pull/33/.

**Comment by dryhten** [comment]
@giorgiosironi should this be reverted? https://github.com/elifesciences/elife-xpub-formula/pull/28

**Comment by giorgiosironi** [comment]
It is a different option. It makes sense for me to put it there because it's a long-running connection and we don't want messages being stuck in a not-yet-full buffer, but if you find out it's overridden by other options than it can go.
