### ISSUE TITLE
Add and connect app-bar molecule

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#55]
pubsweet molecule may require modification

**Comment by dryhten** [comment]
I connected the AppBar as part of #59. Does this issue include styling and data as well? Right now there is no data (e.g. username) to add to the navbar so it only shows Dashboard, Dummy User and Logout which does nothing. Regarding the styling, it uses the default-theme for now (I'll change to elife-theme), and there needs to be done something about brand name (the wireframes had none).
