### ISSUE TITLE
Update limit of editor suggestions

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#557]
- When suggesting _either_ Senior Editors or Reviewing Editors, the user should be able to make a maximum of 6 choices

- The behaviour when deleting a selection from `submit/editors` should remain the same

- The minimum of 2 suggestions should remain the same

- The validation message `Maximum two choices` should be updated to `Maximum six choices`

**Comment by jsms90** [comment]
How does this affect the designs?

Do you want the page to look something like this?
![image](https://user-images.githubusercontent.com/15656538/45483566-384f0b00-b749-11e8-811a-6b63a5da61ba.png)
![image](https://user-images.githubusercontent.com/15656538/45483621-5caae780-b749-11e8-9ee8-e66a85149c18.png)
![image](https://user-images.githubusercontent.com/15656538/45483623-5d437e00-b749-11e8-8a8d-239fe9ed8c7b.png)
![image](https://user-images.githubusercontent.com/15656538/45483792-e1960100-b749-11e8-9b37-ba11442eca07.png)
![image](https://user-images.githubusercontent.com/15656538/45483634-6cc2c700-b749-11e8-8110-afd56e5be708.png)
![image](https://user-images.githubusercontent.com/15656538/45483590-48ff8100-b749-11e8-874d-8c5aa9df7616.png)
![image](https://user-images.githubusercontent.com/15656538/45483623-5d437e00-b749-11e8-8a8d-239fe9ed8c7b.png)
![image](https://user-images.githubusercontent.com/15656538/45483623-5d437e00-b749-11e8-8a8d-239fe9ed8c7b.png)
![image](https://user-images.githubusercontent.com/15656538/45483623-5d437e00-b749-11e8-8a8d-239fe9ed8c7b.png)
![image](https://user-images.githubusercontent.com/15656538/45483841-0ab69180-b74a-11e8-859a-8428bf32c26b.png)

![image](https://user-images.githubusercontent.com/15656538/45483740-bca18e00-b749-11e8-9330-c4957713077c.png)

**Comment by jsms90** [comment]
If the user:
- has already selected 6 senior editors from the People Picker
- comes back to this page from the picker
- clicks the trash icon on one pod

I assume it should look like this?
![image](https://user-images.githubusercontent.com/15656538/45483566-384f0b00-b749-11e8-811a-6b63a5da61ba.png)
![image](https://user-images.githubusercontent.com/15656538/45483623-5d437e00-b749-11e8-8a8d-239fe9ed8c7b.png)
![image](https://user-images.githubusercontent.com/15656538/45483944-5d904900-b74a-11e8-92c7-a7c7ee46710f.png)
![image](https://user-images.githubusercontent.com/15656538/45483590-48ff8100-b749-11e8-874d-8c5aa9df7616.png)

If the user then:
- clicks the trash icon on another pod

Should it look like this?
![image](https://user-images.githubusercontent.com/15656538/45483566-384f0b00-b749-11e8-811a-6b63a5da61ba.png)
![image](https://user-images.githubusercontent.com/15656538/45483623-5d437e00-b749-11e8-8a8d-239fe9ed8c7b.png)
![image](https://user-images.githubusercontent.com/15656538/45484052-c4adfd80-b74a-11e8-8fd9-2a05dfbbdc8f.png)

**Comment by jsms90** [comment]
How does this affect the tags on the People Picker? The `maximum choice` message currently sits to the right of the tags.

More specifically, when there are 6 tags instead of 2, when should the tags break onto the next line?

It currently looks like this on desktop:
![image](https://user-images.githubusercontent.com/15656538/45484347-b7ddd980-b74b-11e8-99c7-61a39de7b82e.png)



and this on mobile:
![image](https://user-images.githubusercontent.com/15656538/45484339-a8f72700-b74b-11e8-810d-b1221e4f0fb8.png)

**Comment by hdrury1** [comment]
@jsms90 No, this only applies to suggested editors so:

Suggested Senior editors: Min 2, max 6
Suggested Reviewing editors: Min 2, max 6
Excluded SEs: No min, max 2
Excluded REs: No min, max 2

Any pods past the minimum 2 should be labelled (optional)... i.e. if the user selects 6 and trashes one, the replacement pod should be Choose editor (optional) and if the user then trashes a second pod, again the replacement pod would be Choose editor (optional)

The 'Maximum 2 choices' message should be replaced with 'Maximum 6 choices' and sit below the tags (rather than to the right as it currently does- see https://github.com/elifesciences/elife-xpub/issues/448)

Determining where the tags should break may require some trial and error and depend on screensize. 

In order to figure out where this sits priority wise it would be useful to get a better idea of how much dev work is involved.
