### ISSUE TITLE
Update dropzone molecule to match wireframe and remove preview link

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#560]
- An additional instruction should be added to the default state of the molecule (i.e. what the user sees when first loading the page)

- We should remove the link to 'preview' the manuscript until we have determined the product requirements of this feature.

**Design**

![screen shot 2018-09-06 at 12 54 49](https://user-images.githubusercontent.com/17023702/45155803-13e8b100-b1d4-11e8-8e8a-796c8783d1b4.png)

**Comment by jsms90** [comment]
@hdrury1 How would you like the success view to be changed?

Currently:
![image](https://user-images.githubusercontent.com/15656538/45438549-5bc57780-b6af-11e8-9877-aea13c59ee24.png)

Just have "Success!" on one line, then "Replace your manuscript" on a second line?

**Comment by hdrury1** [comment]
Hi @jsms90, yes that would be great.
