### ISSUE TITLE
Generate article.xml for MECA

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#562]
**Product requirements/Acceptance criteria:**

Functional:
- Generate a JATS XML file like https://github.com/elifesciences/elife-xpub-meca/blob/master/examples/alpha/article.xml

**Comment by tamlyn** [comment]
Questions:
- are all the empty tags required?
- what are article-type and article-type-id?
- how do we map from single reviewer name field in the form to `surname` and `givenNames` in the XML?
- reviewers have no affiliation so do we omit the `xref` tag for them?

**Comment by hdrury1** [comment]
Hi @tamlyn:

1) Presumably so. We've directly copied eJP's example so I would guess these are required for a valid import, even if empty.
2) Article-type and article-type ID are related. One is the user friendly name, one is the corresponding eJP ID.
3) I need to get back to Clara on this. Our thoughts are that we store reviewers as an electronic note so we don't need to worry about disseminating.
4) See above. Is there anther option? Can we keep the tag empty?

**Comment by hdrury1** [comment]
@tamlyn I've heard back from eJP and `<authentication-code>` is currently not used, so fine for us to leave empty/remove. Worth leaving empty in case we need to use it at a later time?
