### ISSUE TITLE
Delete demo and staging environments on kubernetes

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#577]
#### Background
We are hosting our environments on elife's infrastructure, and there's no reason to maintain the equivalent environments on the kubernetes infrastructure anymore. The kubernetes infrastructure should be used for review environments only.

The corresponding databases should be deleted as well, as they're not being used by anything other than the environments to be deleted.

#### Environments to delete
https://xpub-elife-staging.gateway.xpub.elifesciences.yld.io/
https://xpub-elife-demo.gateway.xpub.elifesciences.yld.io/

**Comment by giorgiosironi** [comment]
Looking at https://github.com/elifesciences/elife-xpub/blob/develop/.gitlab-ci.yml#L12-L16 I think this can be closed as done.

**Comment by damnhipster** [comment]
It still exists on the cluster, even though it hasn't been deployed to. Will delete it now.
