### ISSUE TITLE
Submission form: keywords

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#58]

**Comment by g-sam** [comment]
@sianroderick Do you know what this is?

**Comment by sianroderick** [comment]
Hmm - was that from one of the orange post-its (I'm not in the office today, so can I check tomorrow)?  I think any requirement for keywords was dropped for the wireframes Nick presented (we collect "keywords" for articles currently, but these are free text that the author types in).

**Comment by NickDuffield** [comment]
@g-sam I would hold fire on the use of the keywords pattern for now. I think the particular use on the form screen needs revisiting.
