### ISSUE TITLE
Write tests for Search Box icons

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#587]
Currently we don't have any test for the Search Box icons. There is an X icon which should clear everything you typed in the box, and a search icon that updates the list of person pods in the people picker (similar to hitting enter).

- [x] Write tests for the X icon
- [x] Write tests for the search icon

**Comment by dryhten** [comment]
Blocked by https://github.com/elifesciences/elife-xpub/issues/547

**Comment by hdrury1** [comment]
Is this unblocked now?

**Comment by jsms90** [comment]
Yup
