### ISSUE TITLE
Database migrations are not run for the demo website

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#608]
When the database structure changes there is nothing to automatically change it for the demo website as well https://demo--xpub.elifesciences.org (e.g. migrations are not run there automatically).

**Comment by damnhipster** [comment]
Database migrations are expected to be run manually. They can cause data loss to occur, so it isn't something that is usually done in production in a continuous automated fashion.

We should document the steps to run the migrations somewhere and it's why I'm keen to create a runbook for production.

**Comment by tamlyn** [comment]
But deployment to the demo website is automated. If the migrations are manual then the site will break every time a migration is added.

**Comment by damnhipster** [comment]
Automating it in demo is a good shout, but it depends if we'll want demo as an environment which is the same as production, i.e. the same deployment steps. 

We'll need somewhere to test out the manual migration steps.

**Comment by damnhipster** [comment]
No longer needed as demo no longer exists.
