### ISSUE TITLE
Demo site broken

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#613]
After cleaning up the images on the demo instance. The jenkins job still fails to run.

**Comment by diversemix** [comment]
Important to note - this was actually the CI instance... need to make sure we ssh into both the `demo--` and the `ci--` and clean up docker now and again. 

FYI: @damnhipster

**Comment by damnhipster** [comment]
Did docker run out of space on the CI instance? Is there something we can do to automate this?

**Comment by diversemix** [comment]
@damnhipster  Yes ... it runs out of `inodes` .... we could automate this ... @giorgiosironi pointed me at `docker system prune` which we could use as part of the deployment script?

**Comment by damnhipster** [comment]
This sounds like a step that could be added to Jenkins.

**Comment by giorgiosironi** [comment]
Not `docker system prune` but the eLife wrapper: https://github.com/elifesciences/builder-base-formula/blob/master/elife/docker-scripts/docker-prune
