### ISSUE TITLE
Tweak appearance of search box

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#614]
- Search button should only have border radius on the top right and bottom right corners (so the whole component has one single border radius, rather than one on the text input and one on the button)
- 'X' should be 12px from the left-hand side of the button
- Search button should be a square

Current:

![screen shot 2018-09-18 at 12 47 38](https://user-images.githubusercontent.com/17023702/45685371-0ff84f80-bb41-11e8-9376-8812a5850aef.png)

Expected:

![screen shot 2018-09-18 at 12 44 58](https://user-images.githubusercontent.com/17023702/45685408-29999700-bb41-11e8-9d7f-9e1fbe23ed4d.png)

Also, for reference, the journal site search box:

![screen shot 2018-09-18 at 12 50 26](https://user-images.githubusercontent.com/17023702/45685523-72e9e680-bb41-11e8-962d-9e19420af3e4.png)

**Comment by chugginselifesciences** [comment]
This is based on the close icon centred vertically and at 14px x 14px

**Comment by chugginselifesciences** [comment]
Apologies - please swap the 16px and 14px above and below the search icon. I got them the wrong way round. Should be 16px above and 14 below!
