### ISSUE TITLE
add xpub to eLife playbook

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#617]
xPub has been developed by a team outside of eLife, and a runbook is necessary for eLife to continue supporting this application once it is being used in production. 

The following should be added to the ["continuum playbook"](https://github.com/elifesciences/continuum-playbook) (perhaps now the "eLife playbook"?):
- [ ] add deployment steps, and rollback steps
- [x] #743 add migration steps for the database
- [x] add steps to backup and restore database
- [x] add contact details for relevant parties
- [ ] add links and details on support tools and processes for the application, e.g. new relic, loggly
- [x] link back to the elife-xpub docs wherever appropriate

**Comment by damnhipster** [comment]
@giorgiosironi Can you provide existing playbooks that eLife has for other applications?

**Comment by giorgiosironi** [comment]
@YLD invited to https://github.com/elifesciences/continuum-playbook

**Comment by diversemix** [comment]
@giorgiosironi ... I get a 404 trying to access the playbook

**Comment by giorgiosironi** [comment]
Added @elifesciences/tech with `Write` permissions. @yld has `Read` permissions but you should still be able to fork and propose PRs.

**Comment by damnhipster** [comment]
Should we create a new repository called xpub-playbook?

**Comment by giorgiosironi** [comment]
If we can keep everything in the same playbook it's easier for operations people like me and @lsh-0 to dig up when anything goes wrong. We can rename the repository if someone has a better name.

**Comment by tamlyn** [comment]
@damnhipster does "architecture summary" refer to infrastructure or app architecture?

**Comment by damnhipster** [comment]
> @damnhipster does "architecture summary" refer to infrastructure or app architecture?

Infrastructure architecture, including application dependencies including third-party apps, APIs and databases.

**Comment by jsms90** [comment]
@damnhipster We've added a CI pipeline explanation to the playbook. What you're describing sounds like the architecture of our application. So we'll pop that in this repo's docs rather than the playbook, as you were saying on Slack :+1:

**Comment by jsms90** [comment]
> Added @elifesciences/tech with Write permissions. @yld has Read permissions but you should still be able to fork and propose PRs.

FYI @giorgiosironi, I don't think that YLD link is related to https://github.com/yldio/, although I do love the adorable picture of gismo :wink:

**Comment by jsms90** [comment]
@damnhipster So the ticked items on this last have a PR in `elife-xpub-deployment`: https://github.com/elifesciences/continuum-playbook/pull/6.

As for the "architectural summary and details", we've made a start with in-app docs via PR #663 Probably more needed here for that to be ticked.

We were wondering whether you wanted to do this rest of this, as I don't think @tamlyn and I are familiar enough to complete the others on this list?

**Comment by giorgiosironi** [comment]
> I don't think that YLD link is related to https://github.com/yldio/,

Sorry, I meant to tag @elifesciences/yld which is the team of YLD folks inside this organization

**Comment by damnhipster** [comment]
Looks like config is quite convoluted and is worth mentioning in the runbook. You can find details as to how it works [here](https://github.com/lorenwest/node-config/wiki/Configuration-Files)

**Comment by lsh-0** [comment]
> File Load Order
Files in the config directory are loaded in the following order:
>
> default.EXT
default-{instance}.EXT
{deployment}.EXT
{deployment}-{instance}.EXT
{short_hostname}.EXT
{short_hostname}-{instance}.EXT
{short_hostname}-{deployment}.EXT
{short_hostname}-{deployment}-{instance}.EXT
{full_hostname}.EXT
{full_hostname}-{instance}.EXT
{full_hostname}-{deployment}.EXT
{full_hostname}-{deployment}-{instance}.EXT
local.EXT
local-{instance}.EXT
local-{deployment}.EXT
local-{deployment}-{instance}.EXT
(Finally, custom environment variables can override all files)
Where
> 
> EXT can be .yml, .yaml, .xml, .coffee, .cson, .properties, .json, .json5, .hjson, .ts or .js depending on the format you prefer (see below)

*wow* :scream_cat:

**Comment by jsms90** [comment]
Ok, separated in-app docs into a different ticket. So that the scope of this ticket is purely about [continuum playbook](https://github.com/elifesciences/continuum-playbook) docs :+1:

**Comment by diversemix** [comment]
@hdrury1 .... I think it would be diligent for me and @giorgiosironi to add the following before release (and also share with the team):
- Database recovery
- How to find and investigate a submission

**Comment by giorgiosironi** [comment]
Database recovery has been added, "how to find and investigate a submission" is not something I can do except in providing SSH/SQL access?
The original checklist needs to be updated?

**Comment by hem-brahmbhatt** [comment]
> Database recovery has been added, "how to find and investigate a submission" is not something I can do except in providing SSH/SQL access?
> The original checklist needs to be updated?

Has been updated.
