### ISSUE TITLE
Configure logging

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#618]
- [x] write logs to a folder, which is mounted
- [x] log requests and responses to third-party APIs
- [x] log requests and responses to xpub
- [x] log errors
  - database errors
  - API errors
  - server errors, such as uploads, malformed requests, etc.
- [ ] integrating the logs with loggly
  - [x] write logs as JSON objects

**Comment by damnhipster** [comment]
@giorgiosironi

**Comment by giorgiosironi** [comment]
Specification: we should mount a `/srv/elife-xpub/var/logs` folder somewhere inside the container. Files can then be created there, and our `syslog-ng` implementation will upload them to Loggly (besides them always being accessible on the persistent volume of the node the container runs on).

**Comment by damnhipster** [comment]
![light bulb gif](https://i.imgur.com/t0XHtgJ.gif)

**Comment by diversemix** [comment]
@damnhipster ... should we open a separate issue to configure loggly

**Comment by diversemix** [comment]
Raised #692
