### ISSUE TITLE
Create S3 buckets

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#622]
- [x] setup buckets in demo and production accounts
- [x] setup correct permission for xpub to push and pull objects from buckets

**Comment by giorgiosironi** [comment]
Ok, can see the credentials in the right place:
```
elife@demo--xpub:~$ docker exec -it xpub_app_1 /bin/bash                             
root@b5273b60fd8c:~# ls -l /root/.aws/credentials                                    
-rw-r--r-- 1 1001 1001 135 Sep 20 10:15 /root/.aws/credentials
root@b5273b60fd8c:~# cat /root/.aws/credentials 
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
region = us-east-1
```

**Comment by giorgiosironi** [comment]
@damnhipster @diversemix close if satisfied.

**Comment by diversemix** [comment]
@damnhipster I tempted to leave this open until #520 is completed.

**Comment by damnhipster** [comment]
> @damnhipster I tempted to leave this open until #520 is completed.

I'll test out the bucket using the MECA zip file upload, after which we can close this. I can't see a reason to keep it open if tests pass.

**Comment by diversemix** [comment]
Agreed... maybe we can then find some time to show/demo to @BlueReZZ  - as Paul would like to demo this too next week :+1:

**Comment by damnhipster** [comment]
Moving this to #616
