### ISSUE TITLE
Setup database in Production

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#623]
Use AWS Aurora, a managed RDS service. A single master and slave should suffice. Storage will grow as necessary.

- [x] setup postgres for production
        * same subnet as xPub
        * persistant hostname
        * enable backups
        * consider enabling encryption

**Comment by giorgiosironi** [comment]
- Initial instance size? Default is `db.t2.small`
- Initial disk size? Default is 5 GB
- Multi-az by default
- Postgres version? Default is `9.4` so a newer one probably
- Storage type: `gp2` or the older magnetic? I'd default to `gp2`
- Backup retention: 28 days for production, 2 days everywhere else
- Encryption: not supported at the moment, will see what we can develop to add it in the CloudFormation templates.
- Subnets: uses the internal subnets of our VPC, not reachable from the public but reachable from the applications inside the VPC.

**Comment by diversemix** [comment]
All sounds good to me. We currently use pg 10

**Comment by giorgiosironi** [comment]
On encryption: would be two configuration fields in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html as suggested (enabling plus the key). Key can be created at https://console.aws.amazon.com/iam/home#/encryptionKeys/us-east-1 just to have one specific to `elife-xpub` (cross-environment as for everything else) rather than using a default one.

**Comment by giorgiosironi** [comment]
Last task, encryption: https://github.com/elifesciences/builder/pull/395

**Comment by giorgiosironi** [comment]
Only `elife-xpub--prod` has RDS at the moment, https://github.com/elifesciences/elife-xpub/issues/648 will put it also on `elife-xpub--end2end` when creating it.

**Comment by giorgiosironi** [comment]
Actual usage by the application will be covered by https://github.com/elifesciences/elife-xpub/issues/620

**Comment by damnhipster** [comment]
It's tricky to test in it's current state. Let's export connection details to the app environments so we can test out the database using our migrations.

**Comment by giorgiosironi** [comment]
Run https://alfred.elifesciences.org/job/prod-elife-xpub/ when ready to deploy to `prod`.

**Comment by damnhipster** [comment]
Production database is working fine 👍 
What environment is the last stage of deployment before production? Would that be Demo? If so, I'd expect it to be using a real database.

**Comment by diversemix** [comment]
Yeah - from recollection did we agree that `demo` would become `staging` ?

**Comment by giorgiosironi** [comment]
Spawned https://github.com/elifesciences/elife-xpub/issues/688 then

**Comment by giorgiosironi** [comment]
Given the split I'd close this to start the next task?

**Comment by hdrury1** [comment]
@giorgiosironi is 'setup postgres for staging' captured in the work for #688? If so I think this can indeed be closed down.

**Comment by giorgiosironi** [comment]
Yes, see https://github.com/elifesciences/builder/pull/401/files#diff-b455e3195287afd72391b19ec4bc7ffaR1982

**Comment by hdrury1** [comment]
Updated title and description- closing this down as work completed.
