### ISSUE TITLE
differentiate between different types of file upload error & update UI

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#625]
**Product requirements/Acceptance criteria:**

- Error message should change depending on nature and origin of error (user or server)

- User should use the 'try again' link to open their native file browser, or else be able to drag and drop onto the molecule to replace the file

a) User error type = incorrect format/too big

**Design**

<img width="853" alt="screen shot 2018-10-04 at 14 49 11" src="https://user-images.githubusercontent.com/17023702/46478434-e0a23d80-c7e4-11e8-87f9-35330c26fd52.png">

b) Server error

**Design**

<img width="855" alt="screen shot 2018-10-04 at 14 51 37" src="https://user-images.githubusercontent.com/17023702/46478508-0b8c9180-c7e5-11e8-892f-bab8a9d8694c.png">

Note that 'Contact Us' should lead to the corresponding page in xPub

c) User error type = no manuscript uploaded

**Comment by jsms90** [comment]
Note that the way errors are current handled produces the following problems (identified in [this PR](https://github.com/elifesciences/elife-xpub/pull/594#issuecomment-421392135):
> There's a little bit of weirdness in using `setFieldError` in that the message disappears on the next form validation (e.g. when blurring the cover letter editor). Another issue is that it favours `conversion.error` (i.e. server errors) over form errors. That means if you upload a valid file and it fails on the server, then you try to upload an invalid file and it fails on the client, the server error continues to be displayed rather than the new form error.
>
> I think these are acceptable edge case bugs for now but happy to be convinced otherwise. The alternative is to create a stateful component which tracks errors from various sources and can choose to show the most recent error, for example.

**Comment by jsms90** [comment]
I've captured the bugs in another ticket about refactoring into a stateful component. Going to tackle that issue before this one, so moving this back into To Do

**Comment by jsms90** [comment]
@hdrury1 Now that we have many different types of error state, should we perhaps visually differentiate between these, in a way that's more obvious to the user if/when they change?

The suggestion during demo was to highlight these in red:
- That file is not supported.
- Your file is too large.
- Unable to upload your file.

Just to attract the eye to what the problem is, rather than just the "Oops!"

But I'm unsure whether that really solves the situation in which this component changes from one type of error to another :woman_shrugging: 

Either way, just wanted to record the question, so we don't forget.

**Comment by jsms90** [comment]
Also, question from a product perspective around whether we should differentiate between different types of server-side error:
- science beam conversion failure (from my understanding we don't want to show this for some reason)
- error from storing file in a different place (s3?)
- database errors (generic errors would be fine here, such as 'upload failure...')

But if I understand correctly, we're not going to differentiate right now? Only if/when we introduce multiple file uploads?

**Comment by hdrury1** [comment]
Given that we're expecting changes to the UI to implement multiple file upload I'm going to move this into the backlog for now.

**Comment by chugginselifesciences** [comment]
Addressed by #986
