### ISSUE TITLE
Discussion: using profiles service instead of users table

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#636]
There are a few issues that need to be worked out before this work can be specced.

1. The SQL schema expects user IDs to be UUIDs but eLife profile IDs are 8 character (base 36?) strings.
   - We could change the SQL schema to `TEXT` instead of `UUID`?
   - Or convert the eLife IDs into UUID format (e.g. convert to base 16 then pad with zeros)?
   - Or keep a local users table which just maps UUID to elife ID?

2. How will this work in development?
   - Is there a staging profiles service environment which we could each have API keys for?
   - How will developers log in to xpub? Is there a staging journal server connected to the staging profiles service?

**Comment by diversemix** [comment]
I'm liking the third option of (1) ... to map a UUID to an eLife ID ... reason being is that its quite flexible we could support other system's ids for users. The other two options feel like "here be dragons" :)

**Comment by diversemix** [comment]
@giorgiosironi / @thewilkybarkid (point 2) Could you give us API keys for profile service in the staging environment?

**Comment by diversemix** [comment]
My reply to point (2) is... could we mock out the profiles service (do we already have a mock for it) ... for devs?

**Comment by giorgiosironi** [comment]
Staging is implemented by an environment called `continuumtest`:
- https://continuumtest--journal.elifesciences.org/
- https://continuumtest--profiles.elifesciences.org/ping
They will use the ORCID sandbox, which is what https://demo--xpub.elifesciences.org/ uses.

If you want to stub the `profiles` service, [`api-dummy` can be used](https://github.com/elifesciences/api-dummy/blob/develop/test/OAuth2Test.php). It's so limited (only one user, no HTML pages) that it should only be used in development and/or for running automated tests.

**Comment by giorgiosironi** [comment]
The API keys for `profiles` will be the same across environments, changing only the URL to use. Should be [added to the formula](https://github.com/elifesciences/elife-xpub-formula/blob/master/salt/elife-xpub/init.sls#L28-L30) with fake pillar values, then they can be populated with real one.

**Comment by giorgiosironi** [comment]
Reference from `journal`: https://github.com/elifesciences/journal-formula/blob/master/salt/pillar/journal.sls#L31-L32 two values, id and secret. Let's do this together tomorrow.

**Comment by tamlyn** [comment]
> I'm liking the third option of (1) ... to map a UUID to an eLife ID ... reason being is that its quite flexible we could support other system's ids for users. The other two options feel like "here be dragons" :)

@diversemix Yes it does seem like the more correct approach but it also raises further questions:
- if the JWT only contains the eLife profile ID then every request will first need to query the database to convert that to a user UUID (not the end of the world)
- if this is the first time a user has logged in then they won't have a user record so xpub will need to create one

I'm wondering if the login should happen in two steps on the xpub side:
1. Journal redirects to xpub with a JWT containing the eLife profile ID
2. xPub loads or creates a local user record then redirects to xPub client side app with a new JWT containing the UUID

In development we can short circuit the first step and use the second step to generate a valid JWT for any elife profile ID. It does mean adding one more redirect to the already long list.

> According to #637 xPub won't be using Profiles Oauth?

@thewilkybarkid That's right.

> The API keys for profiles will be the same across environments, changing only the URL to use. 

@giorgiosironi Would it be possible to have different API keys? We need some kind of access to a version of the profiles service in local development and I feel more comfortable if I can't accidentally affect production services.

**Comment by giorgiosironi** [comment]
> Would it be possible to have different API keys? 

We should be able to create more API clients, only added to specific environments

**Comment by diversemix** [comment]
@tamlyn ... you do have a good point, I've been pondering (and still am) ....

**Comment by hdrury1** [comment]
What was the reasoning behind eLife profile IDs not being UUIDs?

**Comment by diversemix** [comment]
... I bet the answer is something with "eJP" in there!!! @giorgiosironi / @thewilkybarkid  ?

**Comment by giorgiosironi** [comment]
Product decided, here you go:
https://github.com/elifesciences/issues/issues/3406
https://docs.google.com/document/d/1FMM-R7pIqCW_dSGyOll5NO_U1GZouRALULNanrQ-t74/edit#heading=h.tmgm3q465b91

**Comment by hdrury1** [comment]
Is there a downside to option a of 1)? Other than for reasons of reusability? Could another system extend/alter this if needs be?

**Comment by thewilkybarkid** [comment]
Note Profile IDs are like in that our other IDs in that they're just `^[a-z0-9-]+$` (informally 8 characters). If we reach 8<sup>37</sup> profiles we'll need to increase the length. 😉

**Comment by diversemix** [comment]
@tamlyn ...I'm thinking that the extra redirect would be the best solution, as not using an id of type `UUID` will mean we drift too far from xPub for my liking. The only alternative solution (without the redirect) I can come up with is if we were to cache the currently active sessions to prevent the extra query for every request?

**Comment by diversemix** [comment]
@hdrury1 ... I think the downside of (1) is that we would diverge from the pubsweet shared data model. Option (2) is kind of a neat solution, but it sort of leaves me worried that we are not using the standard algorithm for generating UUIDs so could end up with collisions (although highly unlikely)

**Comment by tamlyn** [comment]
🚨late entry into the solution soup 🚨 

We could use [UUID v3 or v5](https://en.wikipedia.org/wiki/Universally_unique_identifier#Versions_3_and_5_(namespace_name-based)) to legitimately convert eLife profile IDs into UUIDs. This is essentially (2) from above but blessed by standards.

See https://runkit.com/tamlyn/uuid-v5

**Comment by giorgiosironi** [comment]
> Update: This is no good as we need to be able to get the profile ID from the UUID and this uses SHA1.

Good opportunity to put that Bitcoin miner in the budget

**Comment by diversemix** [comment]
Talked with Paul and he would like to preserve as much compatibility with Pubsweet rather than become more like profiles. I think the signs pointing towards using a local cache of mappings `eLifeID <=> Pubsweet UUID`

**Comment by diversemix** [comment]
Discussed IRL ... Not going to use an in-memory cache as its probably premature optimisation. Tam is going to raise the tickets necessary for this work. So closing this down.

**Comment by tamlyn** [comment]
> I'm wondering if the login should happen in two steps on the xpub side:
> 1. Journal redirects to xpub with a JWT containing the eLife profile ID
> 2. xPub loads or creates a local user record then redirects to xPub client side app with a new JWT containing the UUID

Actually this doesn't work because Journal has no safe way to pass the token back to the xpub server. Options:
1. Stick to original plan with single step login and use Journal JWT as the xPub token. Automatically create a user whenever the app tries to access one that doesn't exist.
2. Pass the JWT in the hash as planned and use the client side app to do the token exchange. This is not ideal because the app has to load in a logged out state, then do the token exchange then re-render in a logged in state.
3. Have Journal do a server-to-server request to xPub. xPub creates the user if necessary and returns the final token (with UUID), then Journal redirects with this in the hash.

**Comment by giorgiosironi** [comment]
I think 3 runs the risk of creating a mutual dependency between `elife-xpub` and `journal`, whereas originally (in the plan?) it was only from `elife-xpub` to `journal`.

**Comment by tamlyn** [comment]
We're going with (1) for now. Can revisit later. 

That means we expect Journal to deliver a JWT with an `id` property set to the eLife profile ID.
