### ISSUE TITLE
user journey: replacement file upload failure - currently not handled visually

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#638]
Visually-speaking, we're not handling the following user journey for uploading a file:

initial (i.e. nothing uploaded yet) **->** in progress **->** success **->** replace **->** failure (i.e. error)

**Describe the bug**
If an author chooses to 'replace' their manuscript but there is an error with the 2nd upload, it is not obvious for the user that the initially uploaded manuscript is still saved 

**To Reproduce**

### Step 1: upload file successfully (file 1)
![image](https://user-images.githubusercontent.com/15656538/45819796-21765e80-bcdd-11e8-8456-9416bbde4e7b.png)

### Step 2: click 'replace' & choose new file (file 2)
![image](https://user-images.githubusercontent.com/15656538/45819707-eaa04880-bcdc-11e8-9cfa-9aaa1eedcead.png)

### Error occurs during upload process
![image](https://user-images.githubusercontent.com/15656538/45819860-4ec30c80-bcdd-11e8-8a58-e0f57a2260b4.png)

At this point, the error with file 2 is shown :+1: But it is not obvious for the user that file 1 is still saved :-1:

**Expected behavior**
TBC - no designs yet

But it would be good to differentiate between the 2 different pieces of state:
- whether a file has been uploaded (true/false) & which one is saved (name)
- the progress of the current upload (initial / in progress / error / success)

I believe EPMC has a nice solution to this, where they show the name of the file that has been added, just above the dropzone. This solution would play well with the idea of multiple files being uploaded.

**Comment by hdrury1** [comment]
Note to self - multiple file upload should show the filenames uploaded

**Comment by hdrury1** [comment]
Will be sorted in #988
