### ISSUE TITLE
MECA - reviewers 'name' needs splicing to get lastname

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#643]
See Clara's comment... 
> If you can parse the information into first name, last name, and email, then yes, we can attempt to reconcile the suggested/opposed reviewers, as well as create new accounts when matching fails. (And I assume you meant to say that the information will appear in article.xml, not the manifest.) This should be provided in the same format as the other author suggestions, i.e.:
```
    <contrib contrib-type="suggested_reviewer">
        <name>
            <surname>Allmother</surname>
            <given-names>Frigga</given-names>
        </name>
        <email>everyoneandtheirmother@asgard.com</email>
    </contrib>
```

**Comment by diversemix** [comment]
My suggested solution here is to use a "hints" table .... so the pseudo code would go:
- Check the hints for the name to see if it is an exception - return the actual "surname"
- If not in the hints then split on the first space.

**Comment by hdrury1** [comment]
Further to Peter's comment, preliminary research suggests splitting on the first space will **not** result in a match in 2% of cases- approximately 1500 users. The 'hints' table would contain these 1500 users.
