### ISSUE TITLE
Fix border color when reuploading manuscript

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#646]
Right now if the manuscript upload fails the border of the dropzone will turn red. If you try to upload a manuscript again, while the text "Manuscript is uploading" is displayed the border will remain red. This doesn't look like something we would like and the color should change back to gray/text-placeholder while the manuscript is uploading.

![manuscript-uploading](https://user-images.githubusercontent.com/1497469/45881395-efc7cb00-bda2-11e8-8d46-2e516ed42866.png)

**Comment by hdrury1** [comment]
Update: This red border seems to appear regardless of whether you are replacing a manuscript or are uploading one for the first time.
