### ISSUE TITLE
Create elife-xpub--end2end

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#648]
**User Story:**

_As a developer&tester I want to run automated end2end tests between elife-xpub and journal in order to gain confidence on their user login integration._

**Product requirements/Acceptance criteria:**

Non-functional:
- [x] there is an application running at `end2end--xpub.elifesciences.org`
- [x] this application is configured to talk with `end2end--journal.elifesciences.org`
- [x] move `elife-spectrum` to a separate Jenkins node to be able to run Docker&Selenium
- [x] setup of Selenium container in formula
- [x] a test in [elife-spectrum](https://github.com/elifesciences/elife-spectrum) simulates the user logging in as much as possible
- [x] `elifeEnd2endStacks` Jenkins step
- [ ] run tests in `end2end` stage of `test-elife-xpub`
- [x] implement rollback on `approved`
- [ ] expand test to cover return of user to logged in page

**Comment by giorgiosironi** [comment]
Stack exists now, working on [tests](https://github.com/elifesciences/elife-spectrum/pull/140).

**Comment by giorgiosironi** [comment]
Need to run this on a separate node though. Don't want to add weight to the Jenkins master with Docker and Selenium.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-spectrum/pull/140 is ready as the first iteration.

**Comment by diversemix** [comment]
Created #856 to create more tests

**Comment by diversemix** [comment]
@giorgiosironi Can we close this one out now? - after creating a new ticket for expanding the tests (which I see as separate from creating the e2e test env)

**Comment by giorgiosironi** [comment]
Yes, let's split.
