### ISSUE TITLE
Decide for a minimum time delay between upload progress messages

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#650]
When an user uploads a manuscript we send back the upload progress via websockets. If we send back the progress every time we receive a chunk of data (roughly 64K) then we end up sending a message every 5-10ms which seems like a waste of resources. Right now we have a minimum delay of 500ms between 2 consecutive messages. We have to decide if we need this delay or what its value should be.

Just a side note: no matter what we decide to do there is still some work here to be done e.g. the minimum delay should be stored somewhere in config and not hardcoded in the resolver.

**Comment by diversemix** [comment]
Based on a TV framerate of 50fps ... this is 20ms ... I would say it should not be less than that. I am happy with 500ms.

**Comment by diversemix** [comment]
Closing as this we have decided on 200ms and all has been fine.
