### ISSUE TITLE
Upload Progress does not resume after navigating away

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#653]
If you begin to upload a file (the bigger the better) then navigate back.... then forward again ... you have the option to replace (as the component is unaware of the upload progress still in play - this can be seen from the ws-frames). 

You can begin to upload a second one and then the upload progress flicks between the two upload percentages ... rather fun ... but not desired :)

**Comment by chugginselifesciences** [comment]
Dependant on #639

**Comment by Cooryd** [comment]
@hdrury1 - #1044 solves this with some caveats:

- The user can only navigate between submission steps and still return to see the progress. Returning to the dashboard page and then back to the wizard will lose the connection so progress tracking gets lost (the upload process should continue in the background however).

- This only currently works if the progress isn't 100%, so if the upload has happened but the file is still being processed by ScienceBeam and you navigate away this will still be an issue (maybe should have left this open for now). This will be resolved when we fix #839
