### ISSUE TITLE
Configure SFTP for EJP integration

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#672]
**User Story:**

_As a Developer I want xPub to integrate with EJP's SFTP server in production so that submissions can be uploaded to them._

**Product requirements/Acceptance criteria:**

Functional:

- MECA exports should successfully be uploaded to EJP's SFTP server.
- SFTP uploading should be enabled on Staging and Production

**Comment by diversemix** [comment]
Blocked on `staging` environment being available.
