### ISSUE TITLE
Configure Mailer for failure alerts/notifications

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#673]
**User Story:**

_As a DevOps engineer I want to be notified of failures in Production in order to avoid downtime on the xPub submission system._

**Product requirements/Acceptance criteria:**

Functional:
- Successfully send emails in Production when there are failures on upload/export

**Comment by dryhten** [comment]
Just to make sure, this is about both configuring `nodemailer` to use the right smtp server and sending the actual mails when the log level is greater than warning for example?

**Comment by damnhipster** [comment]
Mailer is only used when we have export failures, which is when we'll want to send the mail out.

**Comment by diversemix** [comment]
I'd like to understand how this will be configured in `prod` and `staging` before we consider the issue "closed" 

I don't think should prevent us from merging this - as `localhost` seems sensible for now, but currently I don't have a clear idea on how we expect this to work. I don't think we deploy any SMTP container (e.g. `namshi/smtp`). Again maybe @giorgiosironi  could help us :grin:

**Comment by dryhten** [comment]
Ok, then there is nothing else to do other than configuring the mailer to use the right smtp. The code that sends the e-mail on export failure is already in develop https://github.com/elifesciences/elife-xpub/blob/develop/server/xpub/entities/manuscript/resolvers.js#L118.

I guess there is no point in addressing the question "Should we send an e-mail to DevOps every time we log something of a particular level? (e.g. log level less than 1 which is warn & error)" right now.

@diversemix I would assume the production vm will have postfix running as well but maybe @giorgiosironi is better to answer this.

**Comment by giorgiosironi** [comment]
We usually go for:

- `end2end`: configure the application to talk to a fake mail server that captures emails and allow end2end tests to check them.
- `staging`: talk to Postfix, mails end up in https://mailtrap.io/ or similar
- `prod`: talk to Postfix, mails are delivered for real with AWS SES

**Comment by dryhten** [comment]
This was done in https://github.com/elifesciences/elife-xpub/pull/694 but it was never tested on the demo environment because it was not straightforward to do. The consensus was that if it doesn't after it gets deployed we will open a new issue.
