### ISSUE TITLE
Consolidate elife-xpub PR builds onto eLife infrastructure

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#675]
**User Story:**

_As a infrastructure engineer I want builds to consistently run in eLife's AWS account in order to control costs, give more resources to builds in need, and be able to support on breakages._

**Product requirements/Acceptance criteria:**

Non-functional:

- PR builds appear in https://alfred.elifesciences.org/job/pull-requests-projects/
- PR builds do not depend on YLD (cloud provider) accounts
- PR builds do not depend on Gitlab or Gitlab CI

**Relevant links to design(s):**

- [mirror of `elife-xpub` on gitlab.com](https://gitlab.com/elifesciences/elife-xpub)
- [pipeline that builds Docker images](https://github.com/elifesciences/elife-xpub/blob/develop/.gitlab-ci.yml#L20)
- [underlying Kubernetes cluster](https://gitlab.coko.foundation/pubsweet/infra) will be implemented with EKS in eLife
- [Kubernetes resources](https://gitlab.coko.foundation/xpub/deployment-config) would be forked and portable as-is, in a perfect world (which this isn't)

**Comment by giorgiosironi** [comment]
Good overview of the existing Gitlab CI at s3://dev-elife-xpub/screencast/CI\ walkthrough.mov

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-xpub/pull/887 ports the first 5 steps, including building the image, on our infrastructure. They are the easy ones as they don't require Kubernetes.

**Comment by diversemix** [comment]
@hdrury1  ... FYI

**Comment by giorgiosironi** [comment]
First step with Kubernetes, with the goal to create review/demo environments:

- created a EKS cluster with Terraform (will have to be integrated into `builder`)
- running a simple deployment and service on top of it http://35.172.178.78:30000/login

**Comment by giorgiosironi** [comment]
About to split this as it's too big.

**Comment by giorgiosironi** [comment]
Sample Helm deployment at http://35.172.178.78:30705/ with only the node container and no database (`/login` loads successfully however).
It's using a chart repository hosted at s3://demo-elife-kubernetes-helm and that I will post in the formula.
I can now split the remaining parts of this.

**Comment by giorgiosironi** [comment]
Can see the splitted issues in the references above this comment. Some of them are generic to eLife's infrastructure, some specific to `elife-xpub`. Can now close this.
