### ISSUE TITLE
Create local S3 server

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#677]
**User Story:**

_As a Developer I want a local S3 server so I can run the app locally without needing credentials for AWS_

**Product requirements/Acceptance criteria:**

Functional:
- Use `docker-compose` to create a local S3 server to use when running locally
- Configure the app using `config/development.js` to use the local S3 server

**Comment by diversemix** [comment]
@damnhipster ... I think we can close this off if we put @tamlyn 's code in the repo '/docs` ?

**Comment by damnhipster** [comment]
It's something we should start as part of `yarn start:services`.

**Comment by damnhipster** [comment]
Addressed by #713
