### ISSUE TITLE
display error to author if/when journal->xpub token exchange fails

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#682]
Currently, [we redirect to the login page with an error object, but don't show anything to the user based on that error](https://github.com/elifesciences/elife-xpub/blob/abe818cd28c55650214578df87c04317b89a9ca5/app/components/pages/Login/index.test.js#L37-L47)

**User Story:**

_As an author, I want to know why I have been redirected to the login page (if/when the token exchange fails), so that I know what's gone wrong and how I might gain access to the xpub app._

**Product requirements/Acceptance criteria:**

?

**Relevant links to design(s):**

?

**Comment by hdrury1** [comment]
Closing as obsolete.
