### ISSUE TITLE
Heading font-family errors (probably noto sans semibold)

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#687]
**Describe the bug**
Some headings appear to be displayed in Arial instead of Noto Sans. In chrome there are "Failed to decode downloaded font" errors. 

**To Reproduce**
1. go to https://demo--xpub.elifesciences.org/submit/editors
2. Look at h3 "Suggest Senior Editors" 
3. in chrome developer tools check errors

**Expected behavior**
Noto Sans semibold should be displayed. 

**Screenshots**
Below it looks like the 2 screenshots in the middle look more like the Arial Bold version above (probably with added font-weight), than the Noto Sans Semibold version below.
![xpub-font-issue](https://user-images.githubusercontent.com/41907215/46220355-c3332680-c341-11e8-80ee-b60cb022fbab.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome & Firefox
 - Version: 69.0.3497, 61.0.1

**Additional context**
Google fonts does not have Noto Sans Semibold listed as an available 'style'. Maybe this has something to do with it?

**Comment by chugginselifesciences** [comment]
It looks like we're using Noto Sans and font-weight: 700 on the journal site instead of noto sans semibold. Is that something we can try first?

**Comment by chugginselifesciences** [comment]
I'm getting these errors in XPub (in chrome)

![image](https://user-images.githubusercontent.com/41907215/46279492-218a2000-c561-11e8-9181-f7e162c98be4.png)

But these in the journal

![image](https://user-images.githubusercontent.com/41907215/46279519-31a1ff80-c561-11e8-88b8-443932e1ee3d.png)

**Comment by chugginselifesciences** [comment]
Maybe this sheds some light on the problem? https://stackoverflow.com/questions/22001035/font-weight-ignored-in-chrome 

This seems to be specific to XPub, and seems to only really be a problem in Chrome. Note how at font-weight: 700 it looks significantly "lighter" than in Firefox and Safari

![image](https://user-images.githubusercontent.com/41907215/46615291-c1bae880-cb0f-11e8-8d5a-4e2490c0801a.png)

**Comment by diversemix** [comment]
Nice summary :+1:  ... the SO article suggests adding `* {-webkit-font-smoothing: antialiased;}` - have we tried this @dryhten ?

**Comment by chugginselifesciences** [comment]
If we are having issues with chrome rendering an increased font-weight for "noto sans" then perhaps we should just stick with "noto sans semibold" and font-weight:400. It looks ok in Chrome and Firefox. For some reason currently in Safari it looks very heavy and inspecting shows "font-weight:bold" - if we can change it to 400, then it seems to be resolved. 

I originally raised the issue because Noto Sans Semibold was not shown and Arial was shown instead. Noto Sans and font-weight:700 seemed a solution because we do it on the journal, but I think this is now fixed, so we should go with "Noto Sans Semibold" and font-weight: 400 *if* we can fix the bold font in safari.

**Comment by chugginselifesciences** [comment]
![image](https://user-images.githubusercontent.com/41907215/46616139-c8e2f600-cb11-11e8-8e56-81d4f2c06893.png)

**Comment by chugginselifesciences** [comment]
Above is a quick test - please ignore the blue box - I suggest we go with semibold @ 400

**Comment by dryhten** [comment]
The font path is all wrong, it shouldn't be `/submit/assets/...` but `/assets/...`. I changed to absolute path in https://github.com/elifesciences/elife-xpub/pull/748

**Comment by dryhten** [comment]
I just saw the comments above, we don't use a weight to make the font semibold, we just use a different font file that should take care of it @diversemix @chugginselifesciences.

**Comment by diversemix** [comment]
@chugginselifesciences ... I'm happy you call this one :+1:

**Comment by chugginselifesciences** [comment]
I would like to continue using "Noto Sans Semibold" now that it was fixed in #748. 

However, font-weight:bold is causing it to be far too heavy in Safari, and I'm not sure where that's coming from. Otherwise it's ok in Chrome and Firefox if we use Noto Sans Semibold at font-weight: 400.

**Comment by dryhten** [comment]
I just realized I forgot to test the fonts on IE 11, but I imagine they won't work since we don't provide the woff files as well. I'll talk with @tamlyn about the browser stack credentials or I could spin a VM with windows myself :)

**Comment by hdrury1** [comment]
Closing this down now. xPub will align with Journal and not provide woff files.
