### ISSUE TITLE
Add commitizen to elife-xpub

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#70]
Should we use [commitizen](https://github.com/commitizen/cz-cli) for conventional commits on elife-xpub?

**Comment by g-sam** [comment]
Yep, important if we ever move anything to pubsweet

**Comment by dryhten** [comment]
Implemented in https://gitlab.coko.foundation/xpub/xpub-elife/commit/32ba6aa81fdb45af2835d6bee850e0e463d7f5ff

Now you can run `npm run cz` to get the commit wizard.
