### ISSUE TITLE
Enable encryption on S3

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#704]
**User Story:**

_As a Product Manager I want manuscripts to be stored securely in order to mitigate the risk of a data breach._

**Product requirements/Acceptance criteria:**

Functional:
- Enable encryption on S3

**Tasks:**

- [x] `builder` support
- [x] creation of separate KMS
- [x] rollout to various environments

**Comment by giorgiosironi** [comment]
Interesting, which of these two options are we looking at:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingEncryption.html

**Comment by giorgiosironi** [comment]
I think only the first one can be done with JavaScript (and will use KMS like for RDS).

**Comment by damnhipster** [comment]
> Interesting, which of these two options are we looking at:
> https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingEncryption.html

The first option.



> I think only the first one can be done with JavaScript (and will use KMS like for RDS).

My thoughts is that this would be done via builder.

**Comment by giorgiosironi** [comment]
According to [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-bucketencryption), update of `BucketEncryption` requires `No interruption` which should make rollout easy.

**Comment by giorgiosironi** [comment]
Applied to relevant buckets:
https://console.aws.amazon.com/s3/buckets/staging-elife-xpub/?region=us-east-1&tab=properties
https://console.aws.amazon.com/s3/buckets/prod-elife-xpub/?region=us-east-1&tab=properties
Will sort out the `builder` changes, which are in review.

**Comment by giorgiosironi** [comment]
`builder` support and rollout completed, so I'll close this.

**Comment by damnhipster** [comment]
@giorgiosironi When I try to view whether encryption has been enabled on the AWS console, I get the following error:

<img width="555" alt="screen shot 2018-10-09 at 14 03 56" src="https://user-images.githubusercontent.com/2573277/46798193-2d3bca80-cd49-11e8-904d-d2da3a6b2fbe.png">

**Comment by giorgiosironi** [comment]
Weird console behavior, but it's in line with the permissions for the `elife-xpub` IAM user and the human users that are in the same group: no KMS access. Do you need some specific permissions here to whitelist, or should we bar access at all? Some reading side actions could be fine, as [these metadata are not sensitive](https://github.com/elifesciences/builder/blob/master/projects/elife.yaml#L1982) anyway.

**Comment by damnhipster** [comment]
It's worth whitelisting the `kms:ListAliases` action, so I can demo/test the encryption.

**Comment by giorgiosironi** [comment]
Attached a new `AmazonKMSXpubMinimalUserAccess` policy to the `Xpub` group. Let me know if that action is enough or if we need to add further ones.

**Comment by damnhipster** [comment]
I'm now seeing that the bucket has encryption enabled.

It's worth going through the steps outlined on the [AWS Bucket Encryption docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html#bucket-encryption-how-to-set-up) to address the following:
- Some of the existing objects were uploaded before encryption was enabled, and these are still unencrypted
- Are the files on S3 encrypted when downloaded using the console? Can they be decrypted when you have the key?

**Comment by giorgiosironi** [comment]
> Some of the existing objects were uploaded before encryption was enabled

Seems to be the expected behavior (that's why it was so fast to change as a setting), we can either delete them or get and put them if they aren't just testing data.

> Are the files on S3 encrypted when downloaded using the console? Can they be decrypted when you have the key?

As far as I understand this is encryption at rest, so they are decrypted before being sent back to the client.

**Comment by giorgiosironi** [comment]
Current default decryption information:
```
$ aws s3api get-bucket-encryption --bucket prod-elife-xpub
^[[A{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "KMSMasterKeyID": "arn:aws:kms:us-east-1:512686554592:key/b6f44e77-46d8-41bb-a2e5-75c0588a2b20",
                    "SSEAlgorithm": "aws:kms"
                }
            }
        ]
    }
}
$ aws s3api get-bucket-encryption --bucket staging-elife-xpub
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "aws:kms",
                    "KMSMasterKeyID": "arn:aws:kms:us-east-1:512686554592:key/b6f44e77-46d8-41bb-a2e5-75c0588a2b20"
                }
            }
        ]
    }
}
$ aws s3api get-bucket-encryption --bucket end2end-elife-xpub
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "KMSMasterKeyID": "arn:aws:kms:us-east-1:512686554592:key/b6f44e77-46d8-41bb-a2e5-75c0588a2b20",
                    "SSEAlgorithm": "aws:kms"
                }
            }
        ]
    }
}
```

**Comment by giorgiosironi** [comment]
Only two files I could find were:
```
$ aws s3 ls prod-elife-xpub
                           PRE meca-archive/
2018-10-16 15:40:54       4464 593fc9e2-2dce-4b52-a9a0-d200a8003b08
2018-10-16 15:40:42       4498 9fc9a12a-2ca0-4e46-a83b-d3a7fe9d2cff
```
(first is an empty "folder")

I have downloaded them and re-uploaded them, they now show
```
Server-side encryption
AWS-KMS
KMS key ID
arn:aws:kms:us-east-1:512686554592:key/b6f44e77-46d8-41bb-a2e5-75c0588a2b20
```
in the [console](https://console.aws.amazon.com/s3/object/prod-elife-xpub/593fc9e2-2dce-4b52-a9a0-d200a8003b08?region=us-east-1&tab=overview).

**Comment by damnhipster** [comment]
LGTM
