### ISSUE TITLE
Styleguide fails locally

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#709]
**Steps to reproduce**:

- Run the styleguide locally, using `yarn styleguide`.
- Navigate to http://localhost:6060/
- Browser throws the following error:
```
 FAIL  Failed to compile

./app/components/ui/molecules/FileUpload.js
Module not found: Can't resolve 'config' in '/home/xpub/app/components/ui/molecules'
```

**Comment by diversemix** [comment]
@damnhipster Thanks, I thought this was me / something I forgot to do.

**Comment by dryhten** [comment]
This is what I previously mentioned on slack, you don't have access to `node-config` on frontend, so I did the same trick we used in webpack for the app and that is to use a resolver in the styleguide which knows about `config` imports. I used the same one (`common-resolve`) from webpack so maybe we should move it outside webpack directory?

**Comment by dryhten** [comment]
Also, just a note here, there are a lot of warnings/errors in the styleguide if you open up the browser console, we might want to check if we already have issues for these and if not open them.

**Comment by diversemix** [comment]
Works on `develop`
