### ISSUE TITLE
Make components AA accessible (352)

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#72]
eLife is committed to the AA standard and my guess is (?) Coko will be too. We should probably start to build this in even when we touch components for other purposes.

What is AA? Each of the requirements listed in https://www.w3.org/TR/WCAG20/ is labelled A, AA or AAA - so it’s all the A and AA ones.

However, the standard is about to be updated with this: https://www.w3.org/TR/WCAG21/.

Tracking: https://gitlab.coko.foundation/pubsweet/pubsweet/issues/352

**Comment by NickDuffield** [comment]
Thanks @g-sam. So would I be correct in thinking that we will meeting all of the A and AA items from the list?

**Comment by g-sam** [comment]
Yep
