### ISSUE TITLE
Update `builder-private` to set `iss` to `journal`

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#721]
As per comment:  https://github.com/elifesciences/journal/pull/1073#discussion_r222668727

Please change the `iss` to `journal` in https://github.com/elifesciences/builder-private/pull/251/files

**Comment by thewilkybarkid** [comment]
Always `journal`? https://github.com/elifesciences/builder-private/pull/252 will make it `journal--{{environment}}`.

**Comment by giorgiosironi** [comment]
Approved the PR, assuming the value is good for the Xpub side.

**Comment by giorgiosironi** [comment]
(@diversemix please confirm of course)

**Comment by thewilkybarkid** [comment]
\*Drumroll*

**Comment by diversemix** [comment]
:) I cannot see `builder-private` :(

**Comment by thewilkybarkid** [comment]
Redeploying now.
