### ISSUE TITLE
Investigate: Fix people picker layout in IE 11

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#724]
Currently, the people picker is unusable in IE 11 due to layout issues.

![screenshot from 2018-11-30 12-54-24](https://user-images.githubusercontent.com/8524685/49290541-24d95380-f49f-11e8-93ae-45ec23bbd0a3.png)

**Comment by diversemix** [comment]
After adding the screenshot ... I had a bit of a gander and found that there is a `width: 100%` style that is making this effect. Seems that the 100% in this case is taken as the size of the screen!

**Comment by SemraSh** [comment]
First discovery : 
The issue is with CSS, I've been looking to @rebass/grid if there are css tags used and not supported by IE11, some of the flex properties seem to have issues with IE11 previously.
The shorthand versions of flex definitions seems to have issues with IE11
```
shorthand :
flex: 0 0 35%;

longhand :
flex-grow: 0;
flex-shrink: 0;
flex-basis: 35%;
```
