### ISSUE TITLE
Use test config for CI

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#731]
eLife has an environment called CI. This is currently loading it's own CI config file from xpub. This should instead be changed to use config from the test config file.

This can be achieved using one of the following methods:

- have `config/ci.js` inherit config values from `config/test.js`
- add the following code to [builder-configuration](https://github.com/elifesciences/builder-configuration/blob/master/pillar/environment-ci-public.sls)
```
     elife_xpub:
       deployment_target: test
```
- rename `config/test.js` to `config/ci.js`

**Comment by hdrury1** [comment]
Closing for now as unconvinced this is a necessary approach.
