### ISSUE TITLE
Link to last viewed wizard step

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#732]
**User Story:**

_As a submitter I want to be able to re-access and in progress submission in order to continue where I left off._

**Product requirements/Acceptance criteria:**

Functional:
- When a manuscript is in the `INITIAL` state, users should be able to click on the row in the Dashboard to continue with the submission.
- When clicking on the row, the user should be taken to the last step that they were viewing.
- This last viewed step needs to be stored somewhere (probably in the `manuscript.formState` database column).

**Relevant links to design(s):**
[Invision Prototype](https://projects.invisionapp.com/share/NEOA2G14KDH#/screens/322134918)

**Comment by hdrury1** [comment]
As per yesterday's discussion, the 'Continue Submission' link should redirect to the page containing the most recently edited field.

**Comment by jsms90** [comment]
It was our understanding of yesterday's discussion that the entire row was going to be clickable, rather than any of the words within it. Hence the way that we've defined ticket #734. Is that wrong?
