### ISSUE TITLE
Dashboard component

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#734]
- Assemble from Tabs and DashboardListItem components
  - List items ordered by status update time descending
- The 'Archive' tab will be clickable but show only a static message (to be defined)
- The active tab should be indicated by an underline (colorPrimary) and colorText
- Before the user has begun any new submissions, the dashboard should be presented in an empty state
- The user should be able to access eJP from their xPub dashboard in case they cannot find their submission(s)
  - This message is pushed down by a container with min-height
- Each entry in the dashboard should show its current status, title and date status was last updated
- Move new submission button to the right
- List items may be clickable (depending on status) 
  - "Continue submission" links to the wizard
  - "Invited to submission" links to eJP
  - Other statuses not clickable
- A submission should appear on this dashboard with this status from the moment a user has clicked 'New Submission'

**Designs**

[Invision Prototype](https://invis.io/NEOA2G14KDH)

![image](https://user-images.githubusercontent.com/115310/46798399-b81cc500-cd49-11e8-8901-010c01bf543a.png)

![image](https://user-images.githubusercontent.com/115310/46798441-d7b3ed80-cd49-11e8-9368-090dc222173a.png)

**Comment by diversemix** [comment]
Done.
