### ISSUE TITLE
Update login screen depending on SSO state

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#735]
- The user should see a different login screen depending on if they are already logged in via the `profiles` service or not
- The user should be given contextual information about the new submission system in both cases
- If the user is logged in, they should see the 'Continue' button [see here](https://projects.invisionapp.com/share/NEOA2G14KDH#/screens/322120296)
- If the user is not logged in, they should see the 'Login with ORCiD' button [see here](https://projects.invisionapp.com/share/NEOA2G14KDH#/screens/322127272)

**Comment by tamlyn** [comment]
This changes [the current login flow](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpMIGFzIGpvdXJuYWwtbG9naW5cbiAgICBwYXJ0aWNpcGFudCBKUyBhcyBqb3VybmFsLXN1Ym1pdFxuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5TUiAtPj4gSlM6IDxqb3VybmFsPi9zdWJtaXRcblxuZW5kXG5cbm9wdCBOb3QgTG9nZ2VkIEluXG5TUiAtPj4gWEw6IDx4cHViPi9sb2dpblxuWEwgLT4-IEpTOiBjbGljayBsb2dpblxuXG5KUyAtPj4gSkw6IHJlZGlyZWN0XG5KTCAtPj4gSkw6IEF1dGggd2l0aCBPUkNJRFxuSkwgLT4-IEpTOiByZWRpcmVjdFxuZW5kXG5KUyAtPj4gSlM6IENyZWF0ZSBKV1RcbkpTIC0-PiBYRDogcmVkaXJlY3RcblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0) to [something like this](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpMIGFzIGpvdXJuYWwtbG9naW5cbiAgICBwYXJ0aWNpcGFudCBKUyBhcyBqb3VybmFsLXN1Ym1pdFxuICAgIHBhcnRpY2lwYW50IFhJIGFzIHhwdWItaW5mb1xuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5TUiAtPj4gSlM6IGNsaWNrIFN1Ym1pdCBteSByZXNlYXJjaFxuSlMgLT4-IEpTOiBDcmVhdGUgSldUXG5KUyAtPj4gWEk6IHJlZGlyZWN0XG5YSSAtPj4gWEQ6IGNsaWNrIGNvbnRpbnVlXG5lbmRcblxub3B0IE5vdCBMb2dnZWQgSW5cblNSIC0-PiBYTDogY2xpY2sgU3VibWl0IG15IHJlc2VhcmNoXG5YTCAtPj4gSlM6IGNsaWNrIGxvZ2luXG5KUyAtPj4gSkw6IHJlZGlyZWN0XG5KTCAtPj4gSkw6IEF1dGggd2l0aCBPUkNJRFxuSkwgLT4-IEpTOiByZWRpcmVjdFxuSlMgLT4-IEpTOiBDcmVhdGUgSldUXG5KUyAtPj4gWEQ6IHJlZGlyZWN0XG5lbmRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19). 

xPub currently has no way of knowing if the user was previously logged in to Journal so it doesn't know whether to show the "Continue" interstitial. Would it be possible for Journal to supply this information in the JWT @thewilkybarkid?

**Comment by thewilkybarkid** [comment]
So being not logged into Journal and clicking 'Submit my research' will take you directly to xPub rather than logging you in to Journal first. xPub then sends you back to `/submit` on Journal, which logs you in then sends you back to xPub with some extra detail? If we undo https://github.com/elifesciences/journal/pull/1080 could include the `Referer` header, which would be Journal if were logged in, xPub if not, potentially blank/something else (in edge cases, eg going to `/submit` directly).

**Comment by hdrury1** [comment]
As I understand it, at the moment we don't have an xPub login screen right? 'Submit my research' should take you to a login screen, which updates depending on if you are already logged into Journal or not.

**Comment by thewilkybarkid** [comment]
I was imaging sending you the referrer value so you can see if it's xPub, but should be able to see if the session was triggered by being on `/submit`. Preference for the format? `true`/`false` in a `new-session` property?

**Comment by thewilkybarkid** [comment]
First pass as the Journal work in https://github.com/elifesciences/journal/pull/1081.

**Comment by tamlyn** [comment]
Looks good, thanks.

**Comment by diversemix** [comment]
Talking with @hdrury1 we've [clarified the flow a little](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpMIGFzIGpvdXJuYWwtbG9naW5cbiAgICBwYXJ0aWNpcGFudCBKUyBhcyBqb3VybmFsLXN1Ym1pdFxuICAgIHBhcnRpY2lwYW50IFhJIGFzIHhwdWItaW5mb1xuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5BY3RpdmF0ZSBTUlxuTm90ZSByaWdodCBvZiBTUjogSG9tZSBwYWdlXG5TUiAtPj4gSlM6IGNsaWNrIFN1Ym1pdCBteSByZXNlYXJjaFxuZGVhY3RpdmF0ZSBTUlxuSlMgLT4-IEpTOiBDcmVhdGUgSldUXG5KUyAtPj4gWEk6IHJlZGlyZWN0XG5hY3RpdmF0ZSBYSVxubm90ZSByaWdodCBvZiBYSTogQmx1ZSBjb250aW51ZSBidXR0b25cblhJIC0-PiBYRDogY2xpY2sgY29udGludWVcbmRlYWN0aXZhdGUgWElcbmVuZFxuXG5vcHQgTm90IExvZ2dlZCBJblxuQWN0aXZhdGUgU1Jcbk5vdGUgcmlnaHQgb2YgU1I6IEhvbWUgcGFnZVxuU1IgLT4-IFhMOiBjbGljayBTdWJtaXQgbXkgcmVzZWFyY2hcbmRlYWN0aXZhdGUgU1JcbmFjdGl2YXRlIFhMXG5ub3RlIHJpZ2h0IG9mIFhMOiBHcmVlbiBPUkNpRCBidXR0b25cblhMIC0-PiBKUzogY2xpY2sgbG9naW5cbmRlYWN0aXZhdGUgWExcbkpTIC0-PiBKTDogcmVkaXJlY3RcbkpMIC0-PiBKTDogQXV0aCB3aXRoIE9SQ0lEXG5KTCAtPj4gSlM6IHJlZGlyZWN0XG5KUyAtPj4gSlM6IENyZWF0ZSBKV1RcbkpTIC0-PiBYRDogcmVkaXJlY3RcbmVuZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

**Comment by thewilkybarkid** [comment]
Not sure what the difference between `xpub-info` and `xpub-dash` is, but Journal will only be redirecting to one URI (with different data).

**Comment by tamlyn** [comment]
Yeah, sorry `xpub-info` was a bit confusing. I've [updated it again](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgSkwgYXMgam91cm5hbC1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpTIGFzIGpvdXJuYWwtc3VibWl0XG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5BY3RpdmF0ZSBTUlxuTm90ZSByaWdodCBvZiBTUjogSG9tZSBwYWdlXG5TUiAtPj4gSlM6IGNsaWNrIFN1Ym1pdCBteSByZXNlYXJjaFxuZGVhY3RpdmF0ZSBTUlxuSlMgLT4-IEpTOiBDcmVhdGUgSldUXG5KUyAtPj4gWEw6IHJlZGlyZWN0XG5hY3RpdmF0ZSBYTFxubm90ZSByaWdodCBvZiBYTDogQmx1ZSBjb250aW51ZSBidXR0b25cblhMIC0-PiBYRDogY2xpY2sgY29udGludWVcbmRlYWN0aXZhdGUgWExcbmVuZFxuXG5vcHQgTm90IExvZ2dlZCBJblxuQWN0aXZhdGUgU1Jcbk5vdGUgcmlnaHQgb2YgU1I6IEhvbWUgcGFnZVxuU1IgLT4-IFhMOiBjbGljayBTdWJtaXQgbXkgcmVzZWFyY2hcbmRlYWN0aXZhdGUgU1JcbmFjdGl2YXRlIFhMXG5ub3RlIHJpZ2h0IG9mIFhMOiBHcmVlbiBPUkNpRCBidXR0b25cblhMIC0-PiBKUzogY2xpY2sgbG9naW5cbmRlYWN0aXZhdGUgWExcbkpTIC0-PiBKTDogcmVkaXJlY3RcbkpMIC0-PiBKTDogQXV0aCB3aXRoIE9SQ0lEXG5KTCAtPj4gSlM6IHJlZGlyZWN0XG5KUyAtPj4gSlM6IENyZWF0ZSBKV1RcbkpTIC0-PiBYTDogcmVkaXJlY3RcblhMIC0-PiBYRDogcmVkaXJlY3RcbmVuZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0) to more accurately reflect the flow on the xPub side.

**Comment by diversemix** [comment]
Much better @tamlyn THANKS!

**Comment by giorgiosironi** [comment]
It seems `journal` has become a single sign on portal, having this kind of customized user journeys on the `elife-xpub` side should make them easier to maintain.
