### ISSUE TITLE
Test and Document Database migration

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#743]
- [ ] update migration docs to include both up and down migration scripts
- [x] test out a migration in staging
- [ ] test rolling back a migration

**Comment by damnhipster** [comment]
Currently exists in https://github.com/elifesciences/continuum-playbook/pull/6

This should be moved to app documentation within `elife-xpub`

**Comment by damnhipster** [comment]
Unblocked by #741

**Comment by giorgiosironi** [comment]
Note: we will run this automatically inside `elife-xpub-formula`, never to deploy without the corresponding (if there is one) migration.

**Comment by giorgiosironi** [comment]
Since we are now running migrations on all eLife environments, I'll mark some of the checkbox as done (but not the documentation/rollback part).
