### ISSUE TITLE
Allow user to delete an in-progress submission

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#745]
**User Story:**

_As an author I want to delete a submission that I have not completed because I know longer wish to submit to eLife._

_As an author I want to delete a submission that I have not completed because I want to tidy up my dashboard._

**Product requirements/Acceptance criteria:**

Functional:

- Clicking on a trash can should remove that entry from a user's dashboard
- Entries below the deleted entry move up one space in the list
- A user should only be able to delete a submission with the 'in progress' status
- Below the 768px breakpoint dashboard list items should not contain the trash can icon
- A user should not have the option to delete a submission in a viewport of 768px and below

**Designs**

Above 768px:

<img width="927" alt="screen shot 2018-11-07 at 16 06 21" src="https://user-images.githubusercontent.com/17023702/48143741-5e0b1300-e2a7-11e8-929c-105356da3206.png">

<img width="910" alt="screen shot 2018-11-07 at 16 08 07" src="https://user-images.githubusercontent.com/17023702/48143754-63685d80-e2a7-11e8-99f0-38101b567069.png">

768px and below (same design as currently):

<img width="393" alt="screen shot 2018-11-07 at 16 09 56" src="https://user-images.githubusercontent.com/17023702/48143850-9ad70a00-e2a7-11e8-96b4-4bb2f9c63ed0.png">

**Comment by jsms90** [comment]
Just to make sure we're on the same page, "In progress" = "Continue submission" now, right?
