### ISSUE TITLE
Discussion: How do we delete database entities?

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#746]
My preference is to take the Hindawi approach and to just flag things as deleted (by adding a `deleted_on` column). This would mean all `data-access.js` queries would need updating to filter out deleted entities. This issue has been raised as a way to discuss other potential options and there benefits.

Input also appreciated from: @BlueReZZ @thewilkybarkid @giorgiosironi

**Comment by thewilkybarkid** [comment]
Soft deletes do create complexity. What's the use case(s) for being able to delete stuff?

**Comment by diversemix** [comment]
At the moment - this will be needed for a user to delete "unsubmitted" / "half-completed" / "abandoned" submissions. Once the submission has been submitted, then this won't be an option. Maybe I'm stuck-in-my-ways, but I've never worked on a production system that actually does a delete on the database. But am open to be convinced to go on this ride :-)

**Comment by thewilkybarkid** [comment]
Sounds like a product question. Is there a case for being able to restore/retaining _any_ information about those cases?

**Comment by diversemix** [comment]
Hannah is of the opinion that whatever we decide should be implemented for all entities. That although there is no real case atm to restore/retain things, in the future for full submission this will be the case. (One example is deleting review comments)... However, let's keep the conversation going @hdrury1

**Comment by diversemix** [comment]
Thanks! Yeah @hdrury1 and I did have a discussion about this. We would expect such requests to be carried out by an administrator - so more at the database level. 

Seems there is no strong argument against a soft deletion - other than it being more work. I expect this is something we can discuss on Wed when we talk about the Dashboard - it maybe Hannah we don't do this for first release, but we need to be clear of the implications if we don't.

**Comment by thewilkybarkid** [comment]
> That although there is no real case atm to restore/retain things, in the future for full submission this will be the case.  (One example is deleting review comments)

Does that mean the user will need to be able to 'delete' comments and restore them later?

**Comment by diversemix** [comment]
I'm thinking if a user deletes an offensive comment and we need an audit that is not deleted.

**Comment by thewilkybarkid** [comment]
Auditing can be different to soft deletes, and is less dangerous (can't actually make queries including 'deleted' things).

**Comment by diversemix** [comment]
I've talked with @hdrury1 ... I suggest we complete this discussion at a f2f tomorrow when the team meet. @thewilkybarkid and @giorgiosironi
