### ISSUE TITLE
Button size tweaks needed

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#749]
## Fix
- [x] Refactor the way buttons are styled to make this easier
- [x] Change the styles to conform to the design below ...

## The bug
Buttons are not quite the same in size and appearance as the design files, and need slight changes to be closer to intended design. 

The main problem is the height of each buttons is 50px instead of 48px and the cause seems to mostly be the 1px border - I have suggested changes below that should help but may require interpretation to apply correctly in react etc. 

Below shows the current implementation (appears the same in chrome, firefox and safari (IE/edge not tested). Next to it is the screenshot from design files, and next to that my attempts to get as close as possible to the intended designs by editing CSS in browser developer tools. I am not sure if this helps achieve the intended results in the XPub font-end code.

I have also made suggestions to increase the minimum width to 120px, and increased the side padding to give buttons more emphasis. The font should also be set to Noto Sans Semibold if font rendering issues are resolved.

**Screenshots**
![image](https://user-images.githubusercontent.com/41907215/46621160-ab685900-cb1e-11e8-93fe-be84b54fd029.png)

![image](https://user-images.githubusercontent.com/41907215/46621176-b28f6700-cb1e-11e8-8110-acabccb83c61.png)

![image](https://user-images.githubusercontent.com/41907215/46621189-bb803880-cb1e-11e8-89c7-0f2916e85121.png)

 
In addition to above:

- [x] The SUBMIT button should look the same as the NEXT and BACK buttons.
- [x] The NEW SUBMISSION button needs to be centered as the above and needs more padding to the sides.

**Comment by chugginselifesciences** [comment]
In addition to this, we are seeing buttons off the screen on mobile. Therefore the following min-widths should be applied:

"Large buttons (i.e. default size)" - min-width = 120px, height = 48px
"small buttons" - min-width = 96px, height = 36px

**Comment by diversemix** [comment]
Isn't closed yet

**Comment by SemraSh** [comment]
In addition to above:
- [ ] The `SUBMIT` button should look the same as the `NEXT` and `BACK` buttons. 
- [ ] The `NEW SUBMISSION` button needs to be centered as the above and needs more padding to the sides.
