### ISSUE TITLE
Subject Picker control size tweaks

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#751]
**Describe the bug**
Similar to generic buttons, the subject picker control could do with some tweaks to be closer to intended designs.

**To Reproduce**
As seen in staging--xpub.elifesciences.org in chrome on OSX - go to the "submission" step of the initial submission process. 

**Screenshots**

In the current implementation the control is slightly taller than other inputs and the text label is too large. 

![image](https://user-images.githubusercontent.com/41907215/46621913-be7c2880-cb20-11e8-81ae-c068c7ade490.png)

See below for intended sizes, fonts etc. Please note the keyword atom should also be 16px regular font, not semibold.

![image](https://user-images.githubusercontent.com/41907215/46621889-a3111d80-cb20-11e8-947c-53bb72fbc3c2.png)

**Comment by hdrury1** [comment]
Closing as fixed in #1333
