### ISSUE TITLE
Chrome button focus stroke/outline

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#752]
Can/should we remove the fuzzy looking focus outline/border on buttons in chrome? It appears whenever pressing a button. If needed for the sake of keyboard focus or accessibility can we style it?

![image](https://user-images.githubusercontent.com/41907215/46622143-68f44b80-cb21-11e8-8245-23d817dae271.png)

**Comment by hdrury1** [comment]
Hi Chris, this was always intended to be styled but was a task sent way down the priority list.

We don’t have any designs for custom focus rings right now- do feel free to add them to this issue!

**Comment by chugginselifesciences** [comment]
We should make sure we keep it to show keyboard focus. But for some reason in Chrome we see the outline when pressing on a button with the mouse, which doesn't happen in other places and feels like a bug to me. It doesn't happen in firefox either. I would like to fix this, but keep the outline to show keyboard focus if possible.

If we can't fix it without removing it entirely (i.e. we lose keyboard focus feedback) then I think for accessibility reasons we should keep it.

**Comment by jsms90** [comment]
@chugginselifesciences please see https://gitlab.coko.foundation/pubsweet/design/issues/11 It could be worthwhile discussing this with the design working group on MatterMost?

**Comment by chugginselifesciences** [comment]
> @chugginselifesciences please see https://gitlab.coko.foundation/pubsweet/design/issues/11 It could be worthwhile discussing this with the design working group on MatterMost?

Thanks Jen. I hadn't thought about the conflict with the validation states on inputs. The suggestions made in that conversation make sense so I'll add a new ticket with more specific actions.
