### ISSUE TITLE
Mac OS font-smoothing. Should we use it?

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#753]
Can/should we use -webkit-font-smoothing: antialiased & -moz-osx-font-smoothing: grayscale to improve rendering of text on Mac? Currently the blue looks more purple than intended and text is a little blurry (on Mac) and this could be a solution. 

However there are issues around supported browsers, accessibility etc. 

Is this something we should do for XPub?

![image](https://user-images.githubusercontent.com/41907215/46622343-267f3e80-cb22-11e8-94d6-57c562557988.png)

 
vs. 

![image](https://user-images.githubusercontent.com/41907215/46622336-1b2c1300-cb22-11e8-9b34-a856bf2f3ec6.png)

**Comment by hdrury1** [comment]
I would like @davidcmoulton input on this from an accessibility point of view.

**Comment by chugginselifesciences** [comment]
@davidcmoulton after some quick reading it seems readability of text can be negatively affected, so to be safe let's not do it.
