### ISSUE TITLE
Tabs component

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#775]
Create reusable tabs component for use on the Dashboard

- Lays out tabs and content on the page
- Keeps state of the selected tab
- Shows content only of selected tab
- On mobile, tabs should be compressed into a dropdown menu

**Comment by tamlyn** [comment]
@chugginselifesciences is there any hover style on the tabs? And what kind of mouse cursor should show?

**Comment by jsms90** [comment]
@chugginselifesciences What does clicking the down arrow on the mobile version do? And how come there's no archive tab?

**Comment by chugginselifesciences** [comment]
@tamlyn Sorry, this still needs to be added to the style guide. On hover the text label would go to colorPrimary. Pointer makes sense to me.

**Comment by chugginselifesciences** [comment]
@jsms90 it's a dropdown. Let me send you a screenshot. We should have gone through the differences on mobile screens. Although the dropdown menu hasn't been added yet, there's some mobile screens in https://invis.io/FDOIB61EKV5

**Comment by jsms90** [comment]
Omg sorry. What a stupid question :rofl:

**Comment by chugginselifesciences** [comment]
I'm sure it would have helped if we'd actually shown you design work!

There's still details to work out, but the idea being that a "press" anywhere on the bar (apart from some space reserved for multi-select when added) would open the menu. Press again to close it or select an option to do the same as selecting a tab.

There's still details to work out for when it switches to a dropdown.

![image](https://user-images.githubusercontent.com/41907215/46821528-d520ba80-cd80-11e8-96f9-0570c65926f5.png)

**Comment by jsms90** [comment]
No worries @chugginselifesciences 

I've just opened a new issue for the mobile version, since what you're talking about here is actually a completely different component. On mobile, we don't have the concept of "tabs" at all.
