### ISSUE TITLE
App bar component (desktop view)

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#777]
Product requirements

- The links for the reviewer guide, author guide and contact us pages should appear even when the user is not logged in
- The active link is colorText
- Inactive links are colorBorder
- If not logged in, the user should have a 'Login' link on the right-hand side (colorPrimary)

![app bar](https://user-images.githubusercontent.com/115310/46800889-f10c6800-cd50-11e8-9cd1-0bbe66e58eef.png)

- If logged in, the user should have a user icon (24px x 24px) and dropdown (4px to the right of the icon)

![app bar](https://user-images.githubusercontent.com/115310/46800982-40529880-cd51-11e8-8da8-e7cc38b4bd0d.png)

**Comment by chugginselifesciences** [comment]
On mobile this menu should "collapse" into a side menu. Assumed ideal behaviour would be when the screen width reaches a point that the required menu items do not all fit on screen.

![image](https://user-images.githubusercontent.com/41907215/46816571-317ddd00-cd75-11e8-9614-bfffcfc92c06.png)

When opened

**Comment by chugginselifesciences** [comment]
(Sorry I didn't mean to close this issue - was trying to add some more info - see below)

On mobile, the items in the app bar should "collapse" into a side menu. Needs testing but assuming for now it would make sense to show the side menu when there isn't space for all menu items (not including the user icon/login button).

![image](https://user-images.githubusercontent.com/41907215/46817660-612de480-cd77-11e8-9e84-4229c72e89d7.png)


Press the menu icon to show the side menu

![image](https://user-images.githubusercontent.com/41907215/46817671-6b4fe300-cd77-11e8-8135-5af6218a4f72.png)


Note - there is a lot of advice out there not to use hamburger menus or "slide out" menus as they're not as intuitive as would be ideal, however we're not using them for primary navigation so should be ok.

**Comment by jsms90** [comment]
@chugginselifesciences I think you're looking for issue #503. I'll add the extra design pic to that issue :+1:

**Comment by chugginselifesciences** [comment]
@jsms90 Oops. Thanks!

**Comment by tamlyn** [comment]
@hdrury1 @chugginselifesciences Questions:
- Does the logo link anywhere?
- Do the nav menu items (Dashboard, etc.) have a hover state?
- Do the nav menu items have a larger clickable area than just the text?

**Comment by chugginselifesciences** [comment]
1) should be https://elifesciences.org/ 

2) Default = color-secondary-text, Selected = color-text, Hover = also color-text

3) Clickable area should be entire menu item (padding is 24px top/bottom and 12px either side)
