### ISSUE TITLE
App bar user menu

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#778]
- If logged in, the user should have a user icon (24px x 24px) and dropdown (4px to the right of the icon)
- The dropdown should have a header (the user's name) and divider
- Beneath the divider, the dropdown should have the option to sign out (there will be more options in the future)
- Hover and active states should match the current dropdown component

**Designs**
[Invision prototype](https://projects.invisionapp.com/share/NEOA2G14KDH#/screens/322127272)

<img width="386" alt="screen shot 2018-10-08 at 12 03 44" src="https://user-images.githubusercontent.com/17023702/46605883-ea80b500-caf2-11e8-8813-019da41ba964.png">

**Comment by chugginselifesciences** [comment]
Updated screenshots from upcoming style guide updates:

For MVP we will only need the user name and "Log out" option. The menu width is defined by the width of the 'longest' menu item label + padding.

![image](https://user-images.githubusercontent.com/41907215/46939943-75b3fa80-d05f-11e8-875f-21690ff9f705.png)

Hover state

![image](https://user-images.githubusercontent.com/41907215/46939964-7ea4cc00-d05f-11e8-9f8e-4a7ada5a39a5.png)

**Comment by chugginselifesciences** [comment]
Please note we appear to truncate long user names on the journal site by using a max-width of 200px on the user name menu item. Screenshot taken from journal site pattern library.

![image](https://user-images.githubusercontent.com/41907215/46940424-97fa4800-d060-11e8-85c9-ed570509e8aa.png)
