### ISSUE TITLE
Update DashboardListItem Component with responsive layout

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#780]
![screen shot 2018-10-11 at 13 05 34](https://user-images.githubusercontent.com/17023702/46802814-64fd3f00-cd56-11e8-96f8-9f96c665c938.png)

**Comment by tamlyn** [comment]
At what break point should it switch to this view?

**Comment by diversemix** [comment]
@chugginselifesciences says "480" .. but he's just sticking it in the designs as we speak
