### ISSUE TITLE
Add fixed new submission button to bottom of mobile dashboard

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#781]
![screen shot 2018-10-11 at 13 10 03](https://user-images.githubusercontent.com/17023702/46803022-fec4ec00-cd56-11e8-827d-af4ebbe0b2c0.png)

- Bar should be fixed to bottom of screen
- Dashboard scrolls behind it

[Invision prototype](https://projects.invisionapp.com/share/FDOIB61EKV5#/screens/322899361)

**Comment by jsms90** [comment]
Solutions we discussed for moving the 'New Submission' button from above the tabs in desktop view & below the tabs in mobile view:
- 2 buttons in the HTML + show/hide each one based on a media query (CSS)
- use React library to insert correct button depending on screen size (something like https://github.com/contra/react-responsive ?)
- move the same button around (using CSS)

Probably going with first option. CSS will be more performant than JS option. Considering the fact that this mobile version isn't just moved to the bottom of the page but is also on a sticky footer, showing/hiding 1 of 2 buttons may be easier.

To be investigated further if/when necessary, by whoever picks this up.
