### ISSUE TITLE
Sticky footer component

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#782]
We have a repeated pattern of a white "footer" that sticks to the bottom of the page, which has a button / multiple buttons inside.

This has already been implemented once in the People Picker modal (with buttons on the left):
![image](https://user-images.githubusercontent.com/15656538/46808507-6df50d00-cd64-11e8-82a9-20b374055a8c.png)

We now have another one in issue #781 (with button on the right):
![screen shot 2018-10-11 at 13 10 03](https://user-images.githubusercontent.com/17023702/46803022-fec4ec00-cd56-11e8-827d-af4ebbe0b2c0.png)

We also have designs for a future feature (multi-selection in the dashboard) with a delete button in the footer (right hand side):
![image](https://user-images.githubusercontent.com/15656538/46808783-055a6000-cd65-11e8-9d48-4cb4ede62390.png)

@chugginselifesciences Should the height of the dashboard footer be the same as whatever we chose for the People Picker modal last time?

**Comment by chugginselifesciences** [comment]
Yes the intention is that the same footer would be used for multi-select, and anywhere else we may use it in future, which should be 132px tall including 1px border

"On mobile" (or before the breakpoint where we go from 1 to 2 columns) the plan would be for the fixed footer to be 73px tall including the 1px border.

I'll test the people picker modal when staging is up and running again.

**Comment by chugginselifesciences** [comment]
Good point as long as it's referred to. I'll speak to Hannah about it in the morning. There's probably a sensible way to keep adding to it and linking to the tickets or adding more detail if needed etc.
