### ISSUE TITLE
Create submission/archive dropdown menu ("tabs" for mobile version)

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#786]
**Product requirements/Acceptance criteria:**

Functional:
- "Submissions" selected by default
- When a user clicks on the down arrow a menu appears, containing "Submissions" & "Archive"
- When a user selects an alternative from the menu, the list of manuscripts below updates (in the same way that they would be clicking a tab on the desktop view)

**Relevant links to design(s):**
[Mobile invision prototype](https://projects.invisionapp.com/share/FDOIB61EKV5#/screens/322899359)
![image](https://user-images.githubusercontent.com/41907215/46821528-d520ba80-cd80-11e8-96f9-0570c65926f5.png)

**Comment by jsms90** [comment]
Sounds like, in this case, the switch between desktop and mobile actually changes which component we render altogether, this might be a candidate for the library that @tamlyn was talking about - https://github.com/elifesciences/elife-xpub/issues/781#issuecomment-428960111

**Comment by tamlyn** [comment]
@hdrury1 Would it make sense to deprioritise this mobile view since we only have two tabs and they fit OK side by side on a mobile screen?

**Comment by hdrury1** [comment]
@tamlyn Can we take a look at what the mobile rendering is like once the desktop version has been completed? Definitely worth getting that right first. I'll rearrange the tickets in To Do accordingly.

**Comment by Cooryd** [comment]
The side tabs on #505 will be styled in a similar way on mobile. Would be useful for this component to be abstract enough to be used there as well.
