### ISSUE TITLE
Login link fails on staging

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#787]
The login URL on staging and production is incorrect. This is because the URL is configured at build time, so it's not picking up what environment it's on.

This should be changed to a solution where the URL can be configured at run time by the server.

- [x] Load a config file onto the page using `<script src="/config.js" />`, which sets config on the `window`
- [ ] Make a change in pubsweet to allow server-side templating within html responses, and embed the config on the page within `<script></script>` tags.

**Steps to reproduce**

Go to https://staging--xpub.elifesciences.org/login
Click login
Doesn't log you in

**Comment by hdrury1** [comment]
Is this actually closed @damnhipster? Looks like we're missing the second checkbox.

**Comment by damnhipster** [comment]
@hdrury1 Updated the issue.
