### ISSUE TITLE
Use custom profile icon for user menu button

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#795]
The [material profile icon](https://material.io/tools/icons/?search=ide&icon=perm_identity&style=baseline) is not quite the same as [the designs](https://projects.invisionapp.com/share/NEOA2G14KDH#/screens/322127539). Get custom icon and replace it.

**Comment by hdrury1** [comment]
Icon is https://material.io/tools/icons/?icon=account_box&style=baseline
