### ISSUE TITLE
Disallow updating submitted manuscript

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#800]
The `updateManuscript` and `submitManuscript` resolvers should only operate on manuscripts with status `INITIAL`.

**Comment by diversemix** [comment]
... just thinking ... could we introduce a framework like `authsome` for users - but something for manuscripts so that we have a central place to handle the state management / checks ? (feel free to ignore if you think its a crazy idea or too much work at this point)

**Comment by tamlyn** [comment]
Yes, we certainly could. I was avoiding the issue for now as I think it requires a bit of a broader discussion about how we want to do authorization.

**Comment by diversemix** [comment]
@tamlyn Thanks. I've added it onto our handover chat
