### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#815]
**Relevant links to design(s):**
![image](https://user-images.githubusercontent.com/15656538/47147706-ba8d9a80-d2c6-11e8-9f46-f6e27bb53e79.png)

**Comment by jsms90** [comment]
Any more ideas on the mobile view of this @chugginselifesciences ?

**Comment by chugginselifesciences** [comment]
We have tables all over the journal, and basically all you can do is make them scroll horizontally. Please take a look at https://elifesciences.org/articles/39518/figures for an example
