### ISSUE TITLE
Create dropdown component for mobile version of static pages

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#820]
**Product requirements/Acceptance criteria:**

Depends on #821 

Functional:
- The words in the top button of the dropdown should show the words associated with the current page
- The list below should contain all of the sub-pages that a user can navigate to within the Author Guide/Reviewer Guide/Contact Us page that they are on
- When a user clicks on .... (which part of this component? just the words? just the down chevron? both? the whole bar?)
  - the dropdown should appear
  - the down chevron should turn into an up chevron
- When a user clicks on one of the items in the dropdown menu
  - the user should be navigated to the chosen sub-page  

**Relevant links to design(s):**
![image](https://user-images.githubusercontent.com/15656538/47155987-f97b1a80-d2dd-11e8-9e7a-111a87d7556b.png)
![image](https://user-images.githubusercontent.com/15656538/47155953-e405f080-d2dd-11e8-84ad-89d64ebc13b6.png)

**Comment by damnhipster** [comment]
Depends on #821
