### ISSUE TITLE
Create generic dropdown menu component

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#821]
Needs a better name than "dropdown" to differentiate between:
- this component
- the user menu component (which is also a dropdown)
- the Article Type dropdwown component on step 3 of the wizard (currently using pubsweet's "Menu" component, which needs to be replaced - see #326)

**Product requirements/Acceptance criteria:**
Generic component for use in mobile version of static pages #820 & mobile version of dashboard #786 

**Relevant links to design(s):**
Used in at least 2 places in the app:
![image](https://user-images.githubusercontent.com/15656538/47155953-e405f080-d2dd-11e8-84ad-89d64ebc13b6.png)

![image](https://user-images.githubusercontent.com/41907215/46821528-d520ba80-cd80-11e8-96f9-0570c65926f5.png)

**Comment by tamlyn** [comment]
@chugginselifesciences is the menu open/close meant to be animated at all?

**Comment by chugginselifesciences** [comment]
@tamlyn it's not something that I thought would be realistic or really necessary for MVP, but if you're able to animate it in quickly from the top then maybe it's worth a try and we can then iterate/refine from there.

It's low priority at the moment so I wouldn't recommend spending much time on it.

**Comment by jsms90** [comment]
@chugginselifesciences
Would you like the hover styling of this component to be more similar to the user menu/subject area dropdown (blue background)?

![image](https://user-images.githubusercontent.com/15656538/47579591-5c0a9100-d944-11e8-870f-d8bf5211ef5c.png)
![image](https://user-images.githubusercontent.com/15656538/47579676-91af7a00-d944-11e8-901c-b2d999021459.png)

Or the hamburger menu (links turn from grey to black)?
![image](https://user-images.githubusercontent.com/15656538/47579714-a7bd3a80-d944-11e8-9c1d-df59a9849190.png)


---

It's worth noting now that we have multiple different dropdown menu components in our app now:
- SubjectAreaDropdown - multi-select based on `react-select`
- Menu component from pubsweet (used for Article Types menu - needs to be replaced)
- ~Search in PeoplePicker~ - dropdown has been removed (for now)
- Hamburger menu
- UserMenu
- this one (`NavDropdown` perhaps)

**Comment by jsms90** [comment]
Now, having begun to build this generic dropdown, I'm starting to wonder whether #820 & #786 should actually be the same component?

In the case of the static pages, when a menu item is selected, the user will be linked to a new page (with a new URL). So the menu item which is 'selected' (i.e. at the top of this dropdown component) is not going to be based on the state of the component, but rather the URL....or how else could we persist which menu item had been chosen?

In the case of the mobile version of tabs, we are not redirecting the user to a new page at all. So the functionality associated with selecting a menu from the dropdown is different. Instead, the state of the dropdown should decide which `Submission` is rendered below it.

So in the second situation, we need to create a dropdown+DashboardList combo, which share state (like `Tabs` does on the desktop version).

I guess what I'm saying is, just because the styling is the same, doesn't necessarily mean that it's the same component. Not if the functionality is so significantly different. Any thoughts?

**Comment by chugginselifesciences** [comment]
> @chugginselifesciences
> Would you like the hover styling of this component to be more similar to the user menu/subject area dropdown (blue background)?

@jsms90 good point but I think we should keep consistency with the elife journal site for the side menu, where there is no blue hover state.

I think the hover state is a bit of an edge case given that the menu is intended on smaller device widths (generally touch devices), so not worth worrying about at the moment. The other dropdowns examples are available on all device widths.

On a related note, after having another look at the elife journal site I think the grey state for list items should be changed to black - so all menu items are black text at all times. In changing all menu items to black we'll lose the ability to show the "current page" but having tested it I think the grey text can look inactive, which is worse. Plus all black links is more consistent with the journal.

@hdrury1 what do you think? We don't have the grey links on the journal site mobile menu so I think we should change them all to black.

**Comment by hdrury1** [comment]
Agree with @chugginselifesciences. I will raise an issue to change the colour of links in the mobile nav bar.

**Comment by jsms90** [comment]
@chugginselifesciences since we're no longer distinguishing between the current page & other pages, do we still want to show the current page within the dropdown list?

Here are the designs:
![image](https://user-images.githubusercontent.com/15656538/47786077-7f498d80-dd02-11e8-867d-9683320df28d.png)

So now, we'll have the duplication of 'Editorial process', but without the colour distinction.

What do you think of removing the current page (e.g. 'Editorial process') from the dropdown list & leaving it at the top, selected position in the dropdown?

**Comment by chugginselifesciences** [comment]
@jsms90 that's a good point. I agree that would be weird, but I don't want to over complicate things by removing items.

After mocking up a few options I think we should stick with the grey for default, black for current in the dropdown menu as shown in the screenshot you posted (it's consistent with the tabs). The side/hamburger menu (i.e. the app bar on mobile) is a bit different, so black for all items makes more sense there.

I think that would work going forward and will aim to test with users at some point to see if inconsistencies cause confusion.

**Comment by jsms90** [comment]
Okie doke. So, just to be clear, with respect to #820 (static page navigation):
- clicking on the greyed-out links will navigate the user to another page
- clicking on the black link will redirect them to the same page that they're on

**Comment by chugginselifesciences** [comment]
> Okie doke. So, just to be clear, with respect to #820 (static page navigation):
> 
> * clicking on the greyed-out links will navigate the user to another page
> * clicking on the black link will redirect them to the same page that they're on

Yes please. And pressing on the top section (current page name with down pointing arrow) will close the menu

**Comment by jsms90** [comment]
@chugginselifesciences do you want the options reshuffled so that the current page is at the top? Or have them in the same order every time & leave the colour-ing to explain which is the current page?

**Comment by chugginselifesciences** [comment]
Same order every time makes sense I think. Thanks
