### ISSUE TITLE
Build "Editorial Staff" & "Production staff" content components

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#825]
Depends on #824 & #814 

**Product requirements/Acceptance criteria:**
Copy eJP's [Editorial Staff & Production staff pages](https://submit.elifesciences.org/html/contact.html#)

Final content still TBC but use what's in eJP for now

**Relevant links to design(s):**
![image](https://user-images.githubusercontent.com/15656538/47161565-32b98780-d2ea-11e8-9e7e-e0369e8dafa3.png)

![image](https://user-images.githubusercontent.com/15656538/47161584-3cdb8600-d2ea-11e8-9f40-73311514b044.png)

**Comment by jyenes** [comment]
possible duplicated with #814

**Comment by diversemix** [comment]
Ok ... there is a bug on the eJP side ... the "CONTACT" link differs from the login page: 
* https://submit.elifesciences.org/html/eLife_contact.html# 
to
* https://submit.elifesciences.org/html/contact.html#

On all the other pages... @hdrury1 / @BlueReZZ ... we should raise this with eJP

**Comment by diversemix** [comment]
![image](https://user-images.githubusercontent.com/8524685/47496520-e670c900-d84e-11e8-9aa7-23f85793ec1d.png)
