### ISSUE TITLE
Create layout component that encapsulates static page layout (switching between mobile & desktop)

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#835]
Create `StaticPageLayout` component (maybe a different name) which encapsulates the switch between desktop #813 & mobile layouts #834

**Comment by jsms90** [comment]
@chugginselifesciences which breakpoints would you like to use? 

At `768px` on eJP it still looks good:
![image](https://user-images.githubusercontent.com/15656538/47166418-0efb3f00-d2f4-11e8-81a7-11fe3cc85667.png)

But I'm not quite sure which view is best in this range: `480px`-`768px`

**Comment by chugginselifesciences** [comment]
Sorry for the delay. I'm just working on it now. It's tricky getting everything to work within the grid columns without the situation shown in your screenshot in EJP where the menu items wrap onto a second line. It's something i'd like to avoid without it overlapping the main text

**Comment by chugginselifesciences** [comment]
I've put together something in InVision to explain how I would like to change the layout at different breakpoints https://invis.io/GPONO4HMFVX - cycle through screens using arrow keys and read explanations. The basics of it are below. I'm not trying to change the grid behaviour and have based this on David's prototype from ages ago. There may not be consistencies so perhaps we should have a conversation about it if it's not clear or doesn't match up with current breakpoints.

Screen widths of **767px and below**:
Show mobile menu and stretch content to all 12 columns (grid should have 24px side margins)

**768px up to 999px:**
Show side menu in columns 2 & 3, content in columns 5 to 11 (7 columns wide)

**1000px up to 1319px**
_There may be some confusion here about the 1320px breakpoint (based on max grid width of 1272px_)
side menu in columns 2 & 3
content in columns 4 to 10 (7 columns wide)

**1320px and up (grid width is at fixed max-width)**
side menu in columns 2 & 3
content in columns 4 to 9 (6 columns wide)

This is probably going to seem over complex but I think it's important to get right if we can. Plase let me know if you have any questions. I expect the main issue will be around the 1272px breakpoint/max grid width, but I can't test current XPub implementation easily.

**Comment by chugginselifesciences** [comment]
I've done some more exploration into the differences between XPub grid and the prototype now that staging is back up and running. It seems the way we max out the grid is slightly different, which means the breakpoint works out at 1272px screen width and not 1320px. I'll update the InVision mockups accordingly and amend the above rules. Note in the images below that the grid maxes out at 1272px in Xpub but 1320px in the prototype. I'm not suggesting we change anything - I'll update the InVision work.

![image](https://user-images.githubusercontent.com/41907215/47169455-82ed1580-d2fb-11e8-8d55-1d0f0161ce16.png)
![image](https://user-images.githubusercontent.com/41907215/47169478-900a0480-d2fb-11e8-92f5-65f927730cc4.png)
![image](https://user-images.githubusercontent.com/41907215/47169488-98623f80-d2fb-11e8-8b97-1057236302f5.png)
![image](https://user-images.githubusercontent.com/41907215/47169497-9d26f380-d2fb-11e8-883d-2a7a51b5fc1b.png)

**Comment by chugginselifesciences** [comment]
@hdrury1 just to let you know this may be something we need to change in future (i.e. increase the 1272 breakpoint to 1320px) as the design work before I was involved was based on a 1272px grid and currently in XPub it looks like margins mean we're effectively working to a 1224px grid. It's probably not causing any issues but might be a sensible post-MVP tweak.

**Comment by chugginselifesciences** [comment]
@jsms90 I've updated the InVision pages to reflect the current XPub grid. Breakpoints should be:

**Screen widths of 767px and below:**
Show mobile menu and stretch content to all 12 columns (grid should have 24px side margins)

**768px up to 999px:**
Show side menu in columns 2 & 3, content in columns 5 to 11 (7 columns wide)

**1000px up to 1271px**
side menu in columns 2 & 3
content in columns 4 to 10 (7 columns wide)

**1272px and up (grid width is at fixed max-width)**
side menu in columns 2 & 3
content in columns 4 to 9 (6 columns wide)

**Comment by chugginselifesciences** [comment]
Please check https://invis.io/GPONO4HMFVX

It shows layout at:
320px
480px
767px (before breakpoint)
768px (after breakpoint)
999px (before breakpoint)
1000px (after breakpoint)
1271px (before breakpoint)
1272px (after breakpoint)
1440px (grid centered)
1920px (grid centered)
