### ISSUE TITLE
Extend ScienceBeam extraction timeout and fold feedback into manuscript upload

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#839]
See [this Slack thread](https://elifesciences.slack.com/archives/C6LKMFK5Z/p1539268174000100) for context.

- We should extend the timeout of extraction to 6 seconds, as currently many manuscripts are displaying a 'Successful' upload without extracting the title
- We should try and embed extraction into the file upload progress: up to 50% for manuscript upload, 50%-100% for ScienceBeam extraction.
- We should avoid displaying the 100% upload for an extended period of time, as this will confuse users
- 'Success' should only display when 1) the manuscript has uploaded and 2) extraction has occurred OR when 1) the manuscript has uploaded and 2) ScienceBeam has timed out.

**Comment by chugginselifesciences** [comment]
See @diversemix for details

**Comment by diversemix** [comment]
- We have found that the main time is spent in the S3 upload.
- Measured >32seconds for a 20Mb manuscript.
- Analysed file size distribution for initial submissisons:
![image](https://user-images.githubusercontent.com/8524685/49219954-b4fa9880-f3cc-11e8-8bda-b99aeb9c7ff4.png)

**Comment by diversemix** [comment]
Based on this distribution we are going to measure time taken for the full upload to see if we can predict the time taken. If so, we will progress based on time given the file size rather than actual functional progress.

**Comment by diversemix** [comment]
@jyenes and I did some tests ....

![image](https://user-images.githubusercontent.com/8524685/49222689-6f41ce00-f3d4-11e8-9124-c66f89d97c19.png)


So we are going to predict the time-taken to upload a manuscript with the formula:
```
tt = 5 + 4.67e-6 * (filesize)
```
