### ISSUE TITLE
fix spacing between dashboard items & text below

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#854]
Linux OS

Firefox:
![image](https://user-images.githubusercontent.com/15656538/47306004-1fc4f100-d623-11e8-95a8-341d9681ab97.png)

Chrome:
![image](https://user-images.githubusercontent.com/15656538/47306050-3e2aec80-d623-11e8-80a6-8fd899979d3b.png)

**Comment by jyenes** [comment]
not able to reproduce the issue @jsms90 in both browsers look good to me

**Comment by Cooryd** [comment]
<img width="1043" alt="screenshot 2018-10-26 at 14 43 24" src="https://user-images.githubusercontent.com/22455561/47570265-a59bb180-d92d-11e8-89fa-f4d0d3e36c35.png">

This is on osx in chrome. I think it has something to do with having multi-lined title dashboard item.

## To recreate
Create a submission with title 'Shearing in flow environment promotes evolution behaviour in microbial populations'. Then create 3 new submissions with no title
