### ISSUE TITLE
Complete end2end journal login integration with profile menu check

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#856]
@giorgiosironi says (see #648)
> Only extension of the tests to perform more checks on the xpub page (Continue vs other pages) is missing.

**Comment by giorgiosironi** [comment]
Notice `elife-spectrum` is the very top of the [pyramid](https://martinfowler.com/articles/practical-test-pyramid.html#TheTestPyramid), so don't expect very precise checks.

The current test clicks on `Login` but doesn't check where it ends up, I would like to add a check on which page is shown as a successful login but nothing more at that level.

**Comment by giorgiosironi** [comment]
Check `data-test-id="profile-menu"` after coming back to xpub, which means you are logged in.

**Comment by giorgiosironi** [comment]
Closing once PR is merged.
