### ISSUE TITLE
Journal-submit to determine if user is logged in to Journal

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#859]
## Problem
In order to allow the ELB to send users to xPub or eJP, we need a common URL for both. This means we can't have the 'Submit my research' button link directly to xPub login. 

## Suggestion
'Submit my research' always points to the ELB split page and if a user is selected for xPub, they are then directed to Journal-submit. Journal-submit should determine if the user is logged in, then re-direct to either xPub login (Green ORCiD button) or xPub login (Blue Continue button).

Simplified ELB flow:

<img width="644" alt="screen shot 2018-10-23 at 14 31 40" src="https://user-images.githubusercontent.com/17023702/47364179-8bb16300-d6d0-11e8-8d53-9c3c27e8f83f.png">

See new [proposed login flow](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgSlMgYXMgam91cm5hbC1zdWJtaXRcbiAgICBwYXJ0aWNpcGFudCBKTCBhcyBqb3VybmFsLWxvZ2luXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5BY3RpdmF0ZSBTUlxuTm90ZSByaWdodCBvZiBTUjogSG9tZSBwYWdlXG5TUiAtPj4gSlM6IGNsaWNrIFN1Ym1pdCBteSByZXNlYXJjaFxuZGVhY3RpdmF0ZSBTUlxuXG5vcHQgTG9nZ2VkIEluXG5KUyAtPj4gSlM6IENyZWF0ZSBKV1RcbkpTIC0-PiBYTDogcmVkaXJlY3Qgd2l0aCBKV1RcbmFjdGl2YXRlIFhMXG5ub3RlIHJpZ2h0IG9mIFhMOiBCbHVlIGNvbnRpbnVlIGJ1dHRvblxuWEwgLT4-IFhEOiBjbGljayBjb250aW51ZVxuZGVhY3RpdmF0ZSBYTFxuZW5kXG5cbm9wdCBOb3QgTG9nZ2VkIEluXG5KUyAtPj4gWEw6IHJlZGlyZWN0XG5hY3RpdmF0ZSBYTFxubm90ZSByaWdodCBvZiBYTDogR3JlZW4gT1JDaUQgYnV0dG9uXG5YTCAtPj4gSlM6IGNsaWNrIGxvZ2luXG5kZWFjdGl2YXRlIFhMXG5KUyAtPj4gSkw6IHJlZGlyZWN0XG5KTCAtPj4gSkw6IEF1dGggd2l0aCBPUkNJRFxuSkwgLT4-IEpTOiByZWRpcmVjdFxuSlMgLT4-IEpTOiBDcmVhdGUgSldUXG5KUyAtPj4gWEw6IHJlZGlyZWN0IHdpdGggSldUIChuZXcgc2Vzc2lvbilcblhMIC0-PiBYRDogcmVkaXJlY3RcbmVuZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0).

Journal-submit then needs some way to distinguish between a click on 'Submit my research' and a click xPub's 'Login with Orcid' button. Could either add a query parameter to one or both, or use HTTP referrer. See #860

**Comment by thewilkybarkid** [comment]
This is what `new-session` is for? To allow xPub to distinguish between the two?

**Comment by diversemix** [comment]
I believe there will be some amibuity now as to how `journal-submit` is called - highlighted on the sequence diagram below... maybe the referred is sufficient?  Tam raised this as a potential issue - if its not feel free to ignore!

![seq-snip](https://user-images.githubusercontent.com/8524685/48829872-3cac2b80-ed6b-11e8-9d06-13685948cb3a.png)

**Comment by thewilkybarkid** [comment]
Seems to be confusion between the button and the `/submit` path. If you're not logged in to Journal the button goes straight to xPub, the button on xPub goes to `/submit`, which logs you in and sends you back to xPub with `new-session: true`. If you are logged in to Journal the button goes to `/submit`, which redirects you to xPub with `new-session: false`.

Unless the requirements have changed again, what's currently there is as expected?

**Comment by diversemix** [comment]
So the requirement now with the "filtering" happening on `/submit` ... there is no chance the filter would happen twice? (Selected for xPub on the first time and then after logging in to the site being taken away to eJP) ... Maybe I am misunderstanding. Should we update the diagram further to show where/when the filtering is happening?
/cc @hdrury1

**Comment by thewilkybarkid** [comment]
Ah, the Journal button will need changing to go to `/submit` so the filter happens rather than always going to xPub first...

The filter will need to check if the referrer is xPub though to avoid the double filter (from xPub to `/submit` will need to always go through.).

**Comment by diversemix** [comment]
If you are happy @thewilkybarkid I'll close this
