### ISSUE TITLE
Configure user filter to 0% in Production before release

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#862]
~ELB in AWS~ A user filter (to be implemented somewhere) should direct 10% of users of submit.elifesciences.org to xPub and 90% of users to eJP

Dependent on https://github.com/elifesciences/journal/pull/1101/files

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder-configuration/pull/20 is ready for this whenever it needs to be done.

**Comment by diversemix** [comment]
@giorgiosironi   ... can we kick this off ASAP please

/cc @hdrury1 @BlueReZZ @Maelplaine

**Comment by giorgiosironi** [comment]
Ok, after staff meeting I will merge and deploy. Nothing should change.

**Comment by giorgiosironi** [comment]
Deploying in https://alfred.elifesciences.org/job/prod-journal/819/

**Comment by giorgiosironi** [comment]
https://prod--journal.elifesciences.org/submit is going to ORCID which is not a good sign. Have to check what happens with the CDN on top but there may be some caches.

**Comment by giorgiosironi** [comment]
Purged `/about` and the link on https://elifesciences.org/about is sending to EJP as expected. More testing required but it seems safe for the time being.

**Comment by giorgiosironi** [comment]
The login from Xpub does redirect back to xpub, while https://elifesciences.org/submit continues to safely go to EJP. Please try to break it if you have obscure cases (but it will be fully operational only after all caches have expired).

**Comment by diversemix** [comment]
I've tested this all out too and am happy :+1: 

/cc @hdrury1
