### ISSUE TITLE
Add files to S3 that are currently hosted on eJP

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#872]
Many of the static pages have links to various PDFs, docx & xlsx files. See PR https://github.com/elifesciences/elife-xpub/pull/849

- [x] give access to the `Xpub` IAM group to a prefix in `elife-cdn`
- [x] populate the `elife-cdn` S3 Bucket with the files into a prefix like `/xpub/...`
- [x] change the static links referenced in the above PR

**Comment by jsms90** [comment]
@diversemix I'm not sure what's involved in this work, so I wasn't really sure how to write the top comment. Please add anything you feel might be more helpful.

**Comment by giorgiosironi** [comment]
We have the `elife-cdn` bucket for miscellaneous static files, which is hosted with a Fastly CDN (`generic-cdn--prod` project):
https://cdn.elifesciences.org/author-guide/elifechart2%20Sheet1.pdf

This should be used, with a prefix for the files like `/xpub/...` or similar.

**Comment by giorgiosironi** [comment]
Edited the description's checklist to reflect this plan.

**Comment by giorgiosironi** [comment]
Testing the [IAM policy](https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::512686554592:policy/AmazonS3GenericCDNBucketXpubAccess) that should give access to the application and the human users (the application doesn't really need it but being a "subfolder" it's easier to keep permissions consistent for everyone.)

**Comment by giorgiosironi** [comment]
```
elife@staging--xpub:~$ aws s3 cp hello-world.txt s3://elife-cdn/xpub/hello-world.txt
upload: ./hello-world.txt to s3://elife-cdn/xpub/hello-world.txt
```
Appears at https://cdn.elifesciences.org/xpub/hello-world.txt

There is no staging version of the bucket (there is of the CDN): this CDN is used read-only from application from multiple environments so can probably hardcode links to `cdn.elifesciences.org` where needed.

**Comment by giorgiosironi** [comment]
Caveat: this is a CDN so updates of existing files take [several minutes to be propagated](https://github.com/elifesciences/builder/pull/406)

**Comment by diversemix** [comment]
All files are now here:
```
aws s3 ls s3://elife-cdn/xpub/guides/
```

**Comment by diversemix** [comment]
Also added the photos:
```
aws s3 ls s3://elife-cdn/xpub/images/
```
