### ISSUE TITLE
Check how editorial plan to update journal metrics

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#874]
In eJP charts on https://submit.elifesciences.org/html/elife_author_instructions.html#metrics are generated from data in [this file](https://submit.elifesciences.org/html/chart.js). That same file is also stored in Google Drive. I do not know the process for updating the chart data.

In xPub, the chart data is stored in this repository. The process as it currently stands would be to modify the file (e.g. via the GitHub web interface) then commit, create a PR, merge and redeploy xPub.

**Comment by hdrury1** [comment]
Currently the editorial team send that .JS to eJP who add it to their CDN. The editorial team then upload the corresponding .CSV files to the eLife CDN (where xPub is calling them from)

Is there a better way of doing this than commiting, merging and redeploying? What if we uploaded the .JS to the eLife CDN and had xPub call it from there?

**Comment by diversemix** [comment]
@hdrury1 ... would the meeting tomorrow be appropriate to discuss this?

**Comment by hdrury1** [comment]
Closing down for now. Metrics are only updated every quarter and it makes sense to do this manually for the moment.
