### ISSUE TITLE
Implement REST endpoint /ping

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#877]
Need to implement this endpoint on GET `/ping` for the health check to `return 200 "pong"`  ... when everything is healthy.

Also need to remove its implementation here: `elife-xpub-formula/salt/elife-xpub/config/etc-nginx-sites-enabled-xpub.conf`

**Comment by diversemix** [comment]
@giorgiosironi  FYI ... @hdrury1 This really needs to go in ASAP

**Comment by giorgiosironi** [comment]
The formula implementation is a stop gap, as it allows a server to be used as long as nginx is running. An implementation in the app will be more precise as it will make sure the container is running, and probably try to connect to the database. By the way this won't block the multiple servers expansion.
