### ISSUE TITLE
Change the emails on the Contact Page

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#878]
See: https://elifesciences.gitlab.io/elife-xpub/#contactelife

Should be:

![image](https://user-images.githubusercontent.com/8524685/47504424-23938600-d864-11e8-9d11-646fc95dbff1.png)

@hdrury1 - can you confirm we need to do this?

**Comment by hdrury1** [comment]
This would be something to do with avoiding spambots I'd presume.

**Comment by jsms90** [comment]
See https://github.com/elifesciences/elife-xpub/pull/849#discussion_r227861936

**Comment by diversemix** [comment]
I'm not convinced see: https://api.elifesciences.org/people?type=executive&per-page=100

**Comment by giorgiosironi** [comment]
This may be how the data is stored or is imported into the `journal-cms` tables backing `/people`? Only @nlisgo knows.

**Comment by thewilkybarkid** [comment]
It's how the data's stored. I wish it wasn't stored like this, but depends on https://github.com/elifesciences/issues/issues/4180 to obfuscate when presenting (plain text is fine, already existing `<a href="mailto:...">` links are harder though).

**Comment by giorgiosironi** [comment]
If it's stored like this, at least it means all front ends that use the API will be consistent with each other (for now)?

**Comment by diversemix** [comment]
Agreed - I think the problem is this its hardcoded at the moment https://github.com/elifesciences/elife-xpub/blob/3411b2ae625ba0faf87bb0d139f42902b15dbfca/app/components/pages/StaticPages/ContactUs/ContactELife.js#L21

**Comment by jsms90** [comment]
@diversemix what would you like us to do here?

Just change the copy to `[at]` instead of `@`?
Or change it from hard-coded to something else?

**Comment by diversemix** [comment]
Good question - for the group emails (like on this page) I believe these are hard coded. Could you confirm @davidcmoulton  @nlisgo ?

Where as for individuals these can be retrieved from the API, for example `https://api.elifesciences.org/people/1e9b5347` (see `profile.text` ) - however I don't think we should explicitly use this as its not marked up as the email. So perhaps just ensure that we use the same text (copy&paste job) for now. Feel free to pitch in @thewilkybarkid
