### ISSUE TITLE
Sort out image URLs

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#889]
see comment on #884 
@thewilkybarkid comment:

> So curl -v https://api.elifesciences.org/people/15fb82ec | jq .image.uri gives https://iiif.elifesciences.org/journal-cms/person%2F2017-07%2Fsusanna.jpg (the IIIF base URI). So https://iiif.elifesciences.org/journal-cms/person%2F2017-07%2Fsusanna.jpg/full/full/0/default.jpg is the image at full size.
>
> There's focal point information there too; Journal has to calculate the region, take a look at https://github.com/elifesciences/journal/blob/develop/src/Helper/IiifRegionCalculator.php (and the images on https://elifesciences.org/about/people/staff too, this is where the parameters for https://iiif.elifesciences.org/journal-cms/person%2F2017-07%2Fsusanna.jpg/0,53,1000,566/502,284/0/default.webp come from).

**Comment by hdrury1** [comment]
Done in #937
