### ISSUE TITLE
Set up a dedicated eLife Gitlab CI runner

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#89]

**Comment by diversemix** [comment]
Please discuss - as eLife uses Jenkins not gitlab CI

**Comment by hdrury1** [comment]
@g-sam Just to clarify, this is now outdated after the migration to GitHub?

**Comment by g-sam** [comment]
Not outdated, done!

**Comment by hdrury1** [comment]
Great- was just following up on @diversemix 's previous comment RE Jenkins- would be good to record here the outcome of that discussion when you have a chance.
