### ISSUE TITLE
Configure email for all environments.

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#890]
Product requirements in #858 

Need to configure email for prod, staging and end2end ... for the test environments this would good to use a fake SMTP service. 

- [x] `end2end`: do not deploy any mail server until required by tests (check this is the case)
- [x] `end2end`: configuration does not lead to any email server
- [x] `staging`: ~leave `mailer-fake` config~ point to AWS SES SMTP endpoint directly
- [x] `staging`: remove Postfix  as it's a man-in-the-middle
- [x] `prod`: point to AWS SES SMTP endpoint directly
- [x] `prod`: remove Postfix as it's a man-in-the-middle

Depends on #998

**Comment by giorgiosironi** [comment]
At the moment these environments have a local `postfix` on `localhost:25` that forwards to AWS SES (real emails):
```
    'elife-xpub--staging--*':
        - elife.postfix # queues then sends via AWS SES
        - elife.postfix-ses

    'elife-xpub--prod--*':
        - elife.postfix # queues then sends via AWS SES
        - elife.postfix-ses
```
We should probably switch `staging` to use Mailtrap.io or similar?
We should probably add to `ci`|`end2end` MailCatcher if we intend to send emails from automated tests (otherwise just leave it without a mail server)?

Port 25 is not open to the outside world, only to local connections. Have to find out what is the easiest way to resolve it from inside a container as `prod--xpub.elifesciences.org` goes to the ELB and doesn't cut it. Perhaps we should just configure SMTP to go directly to AWS SES host.

**Comment by diversemix** [comment]
@giorgiosironi I'm happy for you to pick up these tasks - maybe a good idea to update the description

**Comment by giorgiosironi** [comment]
Updated the description, I don't have a recipe for these tasks so we (or someone and me) should pair on them.

**Comment by damnhipster** [comment]
Depends on #998

**Comment by diversemix** [comment]
@giorgiosironi ... I've put in PR (https://github.com/elifesciences/elife-xpub/pull/1167/files ) that will see email being configured with the following env vars:
```
MAILER_FROM_ADDRESS
MAILER_HOST
MAILER_PORT
```

**Comment by giorgiosironi** [comment]
Confirmed that `end2end` does not have a Postfix deployed. Need to check that the configuration of the application matches, not sending emails anywhere.

**Comment by giorgiosironi** [comment]
Configuration is by default `localhost:25`, which will break on `end2end` if you try to send an email; this is not perfect but safe enough.

**Comment by giorgiosironi** [comment]
Leaving `staging` with a real email server to aid testing, Product can decide later to switch to a fake one.

**Comment by giorgiosironi** [comment]
Waiting on https://github.com/elifesciences/elife-xpub/issues/1192 for the switch from Postfix+SES to just SES through SMTP.

**Comment by giorgiosironi** [comment]
Everything is in place, how do we test the application sending an email?

**Comment by giorgiosironi** [comment]
Finally tested this in [`staging`](https://staging--xpub.elifesciences.org/submit/7a3ca5a2-c9c9-423a-a19b-35eae6df1ceb/submission); got sent too many emails but the setup is definitely working.

**Comment by giorgiosironi** [comment]
Text of the email:
```

editorial@elifesciences.org | editorial@elifesciences.org | 5:29 PM (4 minutes ago)
-- | -- | --
editorial@elifesciences.org

Dear G,

You have been randomly selected to be part of the initial group of authors given access to our brand new submission interface. Our aim is to create an application that makes the process of submitting your work to eLife as intuitive as possible and your feedback is invaluable in helping us to achieve this. Please use the link below to access your new dashboard at any time and complete your initial submission:
http://localhost:3000

Best wishes,

Susanna

Susanna Richmond

Senior Editorial Assistant, eLife eLife Sciences Publications, Ltd is a limited liability non-profit non-stock corporation incorporated in the State of Delaware, USA, with company number 5030732, and is registered in the UK with company number FC030576 and branch number BR015634 at the address, Westbrook Centre, Milton Road, Cambridge CB4 1YG.
```

That `localhost` may need some update.

**Comment by giorgiosironi** [comment]
Had to disable this because https://github.com/elifesciences/elife-xpub/issues/1207 is sending dozens of emails per submission.
