### ISSUE TITLE
Delete old review environments automatically

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#903]
When pull requests get closed, the review environment keeps running. 

Eventually, as more pull requests get created and closed, we run out of resources to create new review environments. We also run out of resources to run any builds.

We should delete review environments whenever the relevant pull request gets closed. This process should already exist, but there seems to be a bug with the Github --> Gitlab mirroring which means branch deletions don't get mirrored.

**Comment by damnhipster** [comment]
This issue has become more prominent now that we have a higher throughput with the new team members that have joined recently.

**Comment by damnhipster** [comment]
We could use [Github Webhooks](https://developer.github.com/webhooks/) to notify us when PRs get closed.

> Could we run a task when something is merged to `develop`?

Some PRs will get closed before they get merged. And querying for all the closed PRs and mapping them to running review environments sounds like there would be several edge cases to address.

**Comment by giorgiosironi** [comment]
> We could use Github Webhooks to notify us when PRs get closed.

Seems the sanest thing to do, it is what Jenkins use in general, but just ignores the events related to closing PRs.

**Comment by damnhipster** [comment]
@giorgiosironi Can this be closed?

**Comment by giorgiosironi** [comment]
Jenkins does this in https://alfred.elifesciences.org/job/process/job/process-clean-xpub-environments/ whereas Gitlab is being retired. Let's close.
