### ISSUE TITLE
Change colour of links in mobile nav bar

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#906]
To maintain consistency with the eLife journal site, the links in the nav bar on mobile should be colorText. Screengrab from Journal site for reference:

![screen shot 2018-10-29 at 14 15 52](https://user-images.githubusercontent.com/17023702/47655592-37512c00-db85-11e8-8b08-53ec173a5fab.png)

Note that this means we will lose the 'active item' state.

**Comment by Cooryd** [comment]
@chugginselifesciences The eLife journal site also uses textColor for the top bar nav links of desktop. 
<img width="668" alt="screenshot 2018-10-30 at 09 45 18" src="https://user-images.githubusercontent.com/22455561/47709651-9d42bf80-dc28-11e8-8757-c5eddd506847.png">

It's only the eJP hosted submission pages that have the secondaryTextColor links.

<img width="401" alt="screenshot 2018-10-30 at 09 45 38" src="https://user-images.githubusercontent.com/22455561/47709659-a2a00a00-dc28-11e8-9afb-9da2281e4be1.png">

**Comment by chugginselifesciences** [comment]
> @chugginselifesciences The eLife journal site also uses textColor for the top bar nav links of desktop.
> <img alt="screenshot 2018-10-30 at 09 45 18" width="668" src="https://user-images.githubusercontent.com/22455561/47709651-9d42bf80-dc28-11e8-8757-c5eddd506847.png">
> 
> It's only the eJP hosted submission pages that have the secondaryTextColor links.
> 
> <img alt="screenshot 2018-10-30 at 09 45 38" width="401" src="https://user-images.githubusercontent.com/22455561/47709659-a2a00a00-dc28-11e8-9afb-9da2281e4be1.png">

@Cooryd sorry for getting back to you late on this one. It's a good point, but I think I'd like to keep it as is for now. I think making them all black would put too much emphasis on them visually. 

On the journal site the menu is smaller so it's less of a problem.

If we have implementation problems with showing the "current" item I would suggest we go to all grey on the bar, and all black in the menu. I realise this is inconsistent but all black menu items on the bar are too prominent.
