### ISSUE TITLE
Fonts often too heavy or too light

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#915]
In various places fonts are either too heavy or too light, depending on browser/device etc.

Usually buttons are too light (at least in chrome on Mac - Mojave renders even lighter but not the only cause)
![image](https://user-images.githubusercontent.com/41907215/47710029-9d8f8a80-dc29-11e8-9a57-990bdb9920f1.png)

And headings can often be too heavy, especially in Safari and Firefox
![image](https://user-images.githubusercontent.com/41907215/47710089-c4e65780-dc29-11e8-8faa-00236e880fe7.png)

Have we decided/confirmed how we are intending to achieve the required Noto Sans Semibold? 

https://github.com/elifesciences/elife-xpub/issues/687 doesn't appear to have solved the issue.

It looks like we're using combinations of noto sans, noto sans semibold, and font-weight of 700. In places we have semi bold at 700 which gives extra heavy and blurry headings. And then we aren't using semibold in places we should be. And in some places we use "noto sans" (not semi bold) but use font-weight 700 to "fake" the semi bold weight, but it's blurry.

Where possible we should be using "Noto Sans Semibold" at 400 if this renders correctly. 

Apparently on the journal site it looks like we're achieving semibold by using noto sans and font-weight 700, but apparently where this exists it's actually being switched out with noto sans semibold at 400. I'm not sure how, but gives the results we want. Should we be doing the same in XPub?

I'm happy to investigate when and where it's not displayed correctly, but think we need to decide "how" we're going to apply it properly and then just use it everywhere we want to use semibold.

**Comment by jsms90** [comment]
I thought that these were the definitions?
- Normal font weight = 400
- Semibold = 600
- Bold = 700

So I'm not sure what you mean by
> Where possible we should be using "Noto Sans Semibold" at 400 if this renders correctly.

Is this a mistake? Did you mean "Noto Sans Semibold" at 600?

**Comment by jsms90** [comment]
Ohhhh no, I see.

The concept of "semi bold" corresponds to font-weight 600, when applied to a "regular" font (for want of a better word). But when the font itself is a semibold font (e.g. Noto Sans Semibold`), the font itself is thicker by default. So programmatically `font-weight: 400` (it's default)  _looks_ just like `font-family: Noto Sans` + `font-weight: 600`. Got it!!

I see the confusion now!!



Ok, so just to explain. A developer has these choices when trying to achieve boldness:
- `font-family: Noto Sans` + `font-weight: bold` ([bold is automatically interpreted as 700 by all broswers](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Values))
- `font-family: Noto Sans` + `font-weight: 700` (identical as font-weight: bold)
- `font-family: Noto Sans` + `font-weight: 600` (definition of semi-bold  
BUT: different browsers may or may not be able to find a "semi-bold" version & if it can't, [it will default to a different weight that it can find](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Fallback_weights) - Chrome can understand Noto Sans + 600, Firefox can't
- `font-family: Noto Sans Semibold` :+1: :+1: :+1: (default font-weight: 400 looks exactly like Noto Sans + font-weight 600 :tada:)

So @chugginselifesciences, I would say apply 'Noto Sans Semibold' wherever you want semibold (as opposed to bold)

**Comment by jsms90** [comment]
So then the question becomes: what are the most up-to-date specs for all our components? i.e. which aspects of the styleguide(s) should we be following?

For example, our `Button` component was built from the Invision specs, which don't mention bold or semibold at all:
![image](https://user-images.githubusercontent.com/15656538/47911270-f01cb100-de8c-11e8-8601-f463715f6b1f.png)

The CSS in Zeplin says Noto Sans + 600:
![image](https://user-images.githubusercontent.com/15656538/47912553-f6ad2780-de90-11e8-8220-5156f29ee102.png)

But just above the CSS panel:
![image](https://user-images.githubusercontent.com/15656538/47912578-12b0c900-de91-11e8-80b6-9cfac5e0d2d2.png)

1. In general, should we be assuming that the invision styleguide is out of date & be going by Zeplin?
2. I'm guessing we should favour what the typeface panel says vs the CSS panel?
3. I haven't done a once over of all the existing components that we built before moving to Zeplin, so I'm not sure if there are any other changes but would be happy to help with an audit?

**Comment by chugginselifesciences** [comment]
@jsms90 Yes the issue is that we are using "Noto Sans Semibold" in places, but with font-weight 700 (or maybe 600) which is making fonts very heavy. Generally where we're using "Noto Sans" and using the font-weight to make it look like Noto Sans Semibold, it isn't rendered as sharply as we would like.

In short, where the style guide says to use semibold, we should be using `font-family: Noto Sans Semibold` instead of using font-weight and the regular font. 

It's confusing because in the journal when inspecting it often looks like it's using the Noto Sans font and font-weight 700, but apparently there's some sort of switching going on. 

I wouldn't trust what Zeplin is saying in the CSS panel. I'll update the styleguide to reflect that the buttons should be using semibold. But InVision should show the latest style guide, which I'm then putting in Zeplin for spacing, sizes etc.

**Comment by jsms90** [comment]
Yeah. Different browsers seem to render Noto Sans SemiBold with different font-weights by default. With Chrome it's automatically 400, with the others it's not. The only way I can see us fixing this is to remember to add `font-weight: 400` to each component that needs `font-family: Noto Sans SemiBold`.

Unless I'm mistaken, this appears to be a cross-browser problem with the font :disappointed: 
About to push this up. See what you think :smiley_cat:
