### ISSUE TITLE
Use PubSweet BaseModel

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#917]
Refactor `@elifesciences/xpub-model` to use `@pubsweet/base-model` (and therefore Objection.js ORM).

**Comment by diversemix** [comment]
Raised #989 as per our discussion yesterday

**Comment by diversemix** [comment]
@damnhipster / @Cooryd - can we add a `md` file into `docs/developing` to record some of the idiosyncrasies of using `knex` and `objective` we discussed yesterday. This this may prove useful in sharing knowledge and for others especially as we come up to speed with this ORM? thoughts?

**Comment by damnhipster** [comment]
#984 overrides the default `save` operation. We should look at removing this due to the danger introduced of deleting related entities.

**Comment by damnhipster** [comment]
Raised #1006 to address the `save` operation
