### ISSUE TITLE
Use H1 component on Editorial and Production Staff components

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#922]
~The H1s on both the Editorial and Production staff pages are missing a class so the font is too large:~

The font is incorrect on these two components:

![screen shot 2018-10-30 at 11 06 17](https://user-images.githubusercontent.com/17023702/47714107-da607f00-dc33-11e8-9e3a-914b5de0edd0.png)

![screen shot 2018-10-30 at 11 06 37](https://user-images.githubusercontent.com/17023702/47714124-e77d6e00-dc33-11e8-811e-7c78c34eb758.png)

This is because we are using the generic `<h1>` HTML element, instead of [our `<H1>` **component**](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/elements/ui/Heading.js):
https://github.com/elifesciences/elife-xpub/blob/e1d61c45e811e8a1e267c24a8ff510ea68023a60/app/components/pages/StaticPages/ContactUs/EditorialStaff.js#L8

https://github.com/elifesciences/elife-xpub/blob/e1d61c45e811e8a1e267c24a8ff510ea68023a60/app/components/pages/StaticPages/ContactUs/ProductionStaff.js#L7

See the other content components for the static pages, for an example of where to import this from:
https://github.com/elifesciences/elife-xpub/blob/e1d61c45e811e8a1e267c24a8ff510ea68023a60/app/components/pages/StaticPages/ContactUs/ContactELife.js#L2-L9

**Comment by jsms90** [comment]
@hdrury1 what do you mean by "missing a class"?

Should this be an `h2` instead?

**Comment by chugginselifesciences** [comment]
H1 is fine. Sorry if I was confusing things by saying "class" if it's not relevant to react (Hannah based this on my comments). What I mean is the majority of the h1s are being set to 30px, but for some reason the production staff and Editorial staff h1s are 32px. Inspecting in Chrome shows the following:

Most H1s in static pages are set to 30px - 

![image](https://user-images.githubusercontent.com/41907215/47736697-27117d80-dc67-11e8-8311-99582dd32e69.png)

The two that aren't working (i.e. 'something' used to set font-size to 30px on other h1s is not happening here).

![image](https://user-images.githubusercontent.com/41907215/47736720-32fd3f80-dc67-11e8-8bdc-70ba56d58c03.png)

**Comment by jsms90** [comment]
Ah, I see what you meant. Thanks @chugginselifesciences :smile: 

I've updated the title of this issue & the top comment to reflect what needs to be done :+1: 

---

As an aside, about the application of classes, I think the confusion comes down to component-based approach (which we happen to be implementing with React, Styled Components, etc) vs non-component-based.

In a non-component based approach, you might have a bunch of classes, one of which is a class called `large-font` that's responsible for making the font size 30px. You might then apply the `"large-font"` class to anything on the page that you like - an h1, a p tag, the text inside a particular div.

Whereas, in a component-based approach, each component (i.e. `H1`, `DashboardListItem`, etc.) is built with its own HTML, CSS & JS all wrapped up together - the combination of all of these is what defines that component as being an `H1` or `DashboardListItem`, etc. So, in a component-based approach, we're not applying generic classes to any elements. Instead, each component has it's own personal CSS.

So! Our `H1` component is deffined as having font-size: 30px. That means it should have this, no matter where you put it on the page, which page you put it on, etc. That same concept/definition of what an H1 _is_, can be re-used anywhere.

Hope that helps to clarify what we're doing?

**Comment by chugginselifesciences** [comment]
Ok, makes sense. Thanks for the info.
