### ISSUE TITLE
Heading on login screen overlaps appbar on mobile

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#926]
1. Go to https://staging--xpub.elifesciences.org/login while on mobile
2. See header overlapping the app bar

![screen shot 2018-10-30 at 14 16 28](https://user-images.githubusercontent.com/17023702/47724527-c5451980-dc4e-11e8-9774-77e4f603196b.png)

**Comment by jsms90** [comment]
FYI this is happening because of the somewhat hacky way we tried to get this into the center of the screen (vertically)

https://github.com/elifesciences/elife-xpub/blob/3411b2ae625ba0faf87bb0d139f42902b15dbfca/app/components/pages/Login/index.js#L78-L79
