### ISSUE TITLE
Investigate using Mattermost for comms module

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#930]
This spike needs to be done to allow @chugginselifesciences to continue on his current path with design work.

We need to investigate if using mattermost as a chat client is (1) possible and (2) how much we can customise the appearance.

If the investigation finds that mattermost is not suitable, then look for other alternatives.

**Comment by hdrury1** [comment]
Closing down as this is part of a much wider product/design question ahead of any tickets.
