### ISSUE TITLE
End2end testing of submission up to people picker

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#932]
**User Story:**

_As a developer/tester I want to check the correct integration between `elife-xpub` and `api-gateway`/`journal-cms` (people API) across environments in order to avoid live broken or empty pages._

**Product requirements/Acceptance criteria:**

Non-functional:
- [x] some fixture is provisioned into `journal-cms--end2end` to add `senior-editor` items to the API /cc @nlisgo 
- [x] a Selenium-based end2end test runs, starting a new submission
- [x] it goes through page 1
- [x] it goes through page 2
- [x] it goes through page 3
- [x] it exercises enough of page 4 that the people picker is used
- [x] some knowledge sharing/demo
- ~check `X-Consumer-Groups` can't be passed directly to `journal-cms` bypassing `api-gateway`~ https://github.com/elifesciences/issues/issues/4625

/cc @diversemix as per our previous plans

**Comment by diversemix** [comment]
@giorgiosironi and @diversemix to pair
Depends on data being in end2end ...

**Comment by giorgiosironi** [comment]
Depends on https://github.com/elifesciences/journal-cms-formula/pull/48

**Comment by giorgiosironi** [comment]
Renaming this, because it's not a static page we have to look at, but a people picker deep in the initial submission flow.

**Comment by giorgiosironi** [comment]
First page implemented at https://github.com/elifesciences/elife-spectrum/pull/146

**Comment by giorgiosironi** [comment]
Second page implemented at https://github.com/elifesciences/elife-spectrum/pull/148

**Comment by giorgiosironi** [comment]
On the third page ~~of Christmas~~ of the wizard https://github.com/elifesciences/elife-xpub/issues/1041 needs to be worked around; the trade-off will be less robust CSS selectors.

**Comment by diversemix** [comment]
:christmas_tree: :santa: :gift:  :mrs_claus: :christmas_tree:
~~~ Keep up the good work ~~~

**Comment by giorgiosironi** [comment]
A rough page 3 and part of page 4 are in https://github.com/elifesciences/elife-spectrum/pull/149 but need to debug what's happening on page 4 (empty menus) with someone on the xpub side, possibly adding more fixtures.

**Comment by giorgiosironi** [comment]
Tried to debug that but I can see one `reviewing-editor` is correctly coming back from `api-gateway`; the picker remains empty.

**Comment by diversemix** [comment]
... this may well be related to #991 .and/or #1001

**Comment by giorgiosironi** [comment]
It's possible. Is there an environment variable to increase logging level, I think it's `info` on `end2end` and doesn't seem enough to understand what it's doing.

**Comment by giorgiosironi** [comment]
Finally zoomed in on the `research.expertise` being missing:
```
app_1          | debug: Fetching editors from /people role=reviewing-editor
app_1          | error: Cannot read property 'expertises' of undefined message=Cannot read property 'expertises' of undefined, locations=[line=2, column=3], path=[editors]
app_1          | info: ::ffff:172.18.0.1 [19/Nov/2018:15:49:16 +0000] POST /graphql 200 EditorList 152 83.093 ms
```
It seems the field is mandatory when `research` is defined, but that is an optional field. What should happen if a `senior-editor` or `reviewing-editor` has (even temporarily) no `research` defined?

For comparison, this is how it looks like in general:
```
      "research": {
        "focuses": [
          "computational neuroscience",
          "systems neuroscience",
          "decision-making",
          "perception",
          "arousal",
          "learning",
          "electrophysiology"
        ],
        "expertises": [
          {
            "id": "neuroscience",
            "name": "Neuroscience"
          }
        ]
      },
```

/cc @hdrury1 for specifying behavior
/cc @nlisgo in case we need to add `research` through `drush create-person`

**Comment by giorgiosironi** [comment]
For the record, in `prod` at the moment only `executive` and `director` people do not have a `research` field.

**Comment by diversemix** [comment]
Yeah ... I've had to fix this in #991

**Comment by giorgiosironi** [comment]
So should these editors appear _no matter their `research` field_ once your changes for #991 are in?

**Comment by diversemix** [comment]
@giorgiosironi ... I believe so - but would be worth checking as I'm not sure that the `type` filtering is correctly working.

**Comment by giorgiosironi** [comment]
I now see the `reviewing-editor`:
![screenshot_2018-11-22 xpub](https://user-images.githubusercontent.com/160299/48896021-7dc14000-ee3e-11e8-88a1-775f4eb27353.png)
So it should be a matter of adding more data now.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-spectrum/pull/149 is now ready for review.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder-base-formula/pull/194 paves the way for better validation of the authentication on `journal-cms`, which was in the checklist.

**Comment by giorgiosironi** [comment]
Split out the `journal-cms` hardening. Only thing remaining is knowledge sharing/demo, @diversemix what would you like to do and when?

**Comment by giorgiosironi** [comment]
Knowledge sharing scheduled for Monday, as part of a wider update on CI/CD, so closing.
