### ISSUE TITLE
Release 0.1 of data model 

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#94]
- Come to common understanding of the domain & workflow
- Propose data model for eLife's needs (taking what we know from Coko into account)
- Communicate this proposal to Jure & get confirmation

**Comment by jsms90** [comment]
Blocked pending whole team meeting on Wednesday 23rd to continue [the discussion that was started on Tuesday 15th](https://docs.google.com/document/d/13UD_geO3f_7gfRdYtxW9zNt0XhqW_WrqsTNgl4T0Euc/edit#)

**Comment by tamlyn** [comment]
Please review and comment https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/66/diffs?view=inline

**Comment by hdrury1** [comment]
Now here https://github.com/elifesciences/elife-xpub/pull/170
