### ISSUE TITLE
In all environments use the internal URLs for server-side calls

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#948]
When we are in production we can access the endpoints of journal internally by using `elife.internal` - for example `http://prod--gateway.elife.internal`

Ref: https://github.com/elifesciences/builder-configuration/blob/master/pillar/environment-prod-public.sls#L12

I'm anticipating that this is only a change to the config for the API url... but its worth checking. Contact @diversemix or @giorgiosironi  if you have any questions.

**Comment by giorgiosironi** [comment]
About the server side vs. client side using these URLs:
- `*.elife.internal` will only work from the server side
- `*.elifesciences.org` is the equivalent, no-CDN version, to be used from the client side for each of the hostnames
- the `/people` API has a secret `Authorization` header to use so its calls have to be done from the server side

**Comment by damnhipster** [comment]
We're storing the URLs in our config files. The [config block containing the URL is public](https://github.com/elifesciences/elife-xpub/blob/develop/config/default.js#L45-L49) and made available client-side.

There's no need for the URL itself to be made public, just the surrounding config. We should add support placing the `isPublic` property within nested config, and [update the tests](https://github.com/elifesciences/elife-xpub/blob/develop/server/client-config/routes.test.js).

**Comment by diversemix** [comment]
Doing this ticket as its a pre-requisite to #991

**Comment by diversemix** [comment]
Tests failing as http-mocks now using the wrong URLs. Need to re-record
