### ISSUE TITLE
Waiver anchor link in author guide not working

### ISSUE THREAD

**Issue by gmaciocci** [elifesciences/elife-xpub#955]
**Describe the bug**
Waiver anchor link in author guide not working

**To Reproduce**
1. Go to https://staging--xpub.elifesciences.org/author-guide/fees
2. Click on "waiver" in part 2

**Expected behavior**
waiver policy should be displayed

**Comment by hdrury1** [comment]
Thanks @gmaciocci. PR going in today that should allow internal linking. I'm going to work through the rest of the static pages and collate all instances of these.

**Comment by diversemix** [comment]
I've had a quick look, and it appears this is the only place in the static pages we use an `a name` tag.

**Comment by hdrury1** [comment]
Okay, looks like this is the only other instance of linking to an anchor within the same sub-page.

**Comment by diversemix** [comment]
This will be fixed with a change in #954 - it was done on this branch as this renames how links work on thst static pages.
