### ISSUE TITLE
Populate Senior Editor profiles with affiliations and missing email addresses in Journal CMS

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#958]
We have a list of affiliations that will need to be added manually to the Senior editor profiles in Journal CMS so that they appear in the People Picker.

**Comment by hdrury1** [comment]
Done. Note continuumtest will need to be updated with data from Journal CMS in order for information to appear in xPub staging environment.

**Comment by diversemix** [comment]
@hdrury1 ... Let's talk with @giorgiosironi or @thewilkybarkid to ask if they can update `continuumtest` with the live data again. I don't know if there is a procedure / we need to make an announcement we are doing this - or if we can pair - so we can do it another time?
