### ISSUE TITLE
Line lengths of some js files are getting a little big.

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#970]
We should look at breaking out some of these where possible...

```
319,app/components/pages/StaticPages/AuthorGuide/EditorialProcess.js
350,app/components/pages/SubmissionWizard/steps/Editors/EditorsPage.js
378,server/xpub-server/entities/manuscript/resolvers.js
384,app/components/pages/StaticPages/AuthorGuide/Initial.js
440,app/components/pages/StaticPages/AuthorGuide/Full.js
520,server/xpub-server/entities/manuscript/resolvers.test.js
748,static/newrelic.js
972,app/components/pages/StaticPages/AuthorGuide/JournalPolicies.js
```

- [ ] Split files out as appropriate
- [ ] Add linting rules as per @damnhipster 's suggestion

**Comment by damnhipster** [comment]
We should enable linting for line lengths as part of this, to stop it happening again.

**Comment by diversemix** [comment]
Great idea! Putting it into the description...

**Comment by diversemix** [comment]
@Cooryd / @damnhipster - do we want to do this as part of #1587 too?

**Comment by hdrury1** [comment]
@diversemix and @Cooryd worth looking at again for Refactor Round 2?
