### ISSUE TITLE
Reduce space between logo and screen edge in app bar for widths above 768px

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#972]
**Describe the bug**
The space between screen edge and eLife logo is too large.

**To Reproduce**
Go to any XPub page in staging.

**Expected behavior**
Should be 24px to the visible edge of the logo. Pressable area should not be re is currently fine, 
**Screenshots**
![image](https://user-images.githubusercontent.com/41907215/47993530-9cf26a80-e0e7-11e8-8ec3-aa370c4a7e3a.png)
Top shows screenshot on chrome, below shows design files.

**Desktop (please complete the following information):**
Chrome on Mac (mojave)

**Smartphone (please complete the following information):**
MacBook Pro, OSX Mojave, Chrome 70.0.3538

**Additional context**

**Comment by hdrury1** [comment]
Closing down as we will be replacing the app bar shortly.
