### ISSUE TITLE
Multiple menu items shown in "current/selected" state.

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#975]
**Describe the bug**
On the Author/reviewer guide static pages, the dashboard menu item shows a selected state when it should not.

**To Reproduce**
Go to https://staging--xpub.elifesciences.org/author-guide/editorial-process - the app bar should show 2 items in black text. It should only be the current page.

**Expected behavior**
Only the current 'page' (i.e. the dashboard, author guide, reviewer guide or contact us) should be in a selected state (black text). All others should be grey.

**Screenshots**
![image](https://user-images.githubusercontent.com/41907215/47994921-b4335700-e0eb-11e8-8749-08e56eb4822e.png)

**Desktop (please complete the following information):**
Chrome 70.0.3538 on Mac OSX Mojave.

**Comment by diversemix** [comment]
Reproduced

**Comment by hdrury1** [comment]
Closing as we will be replacing the app bar shortly.
