### ISSUE TITLE
Change sans-serif to serif font for "No ORCID" text on login page.

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#977]
**Describe the bug**
The "No ORCID? Sign up now" text/link on the login page should be in Noto Serif to match the other text on the page.

Note that the screenshot says "ORCID" while the designs show "ORCiD". We should stick with the full capitalised version we have now, so only the font-family needs changing. 

**To Reproduce**
https://staging--xpub.elifesciences.org/login

**Screenshots**

![image](https://user-images.githubusercontent.com/41907215/47996103-54d74600-e0ef-11e8-8173-ac4d8f979bee.png)

**Desktop (please complete the following information):**
Chrome 70.0.3538 on MacOS Mojave

**Comment by diversemix** [comment]
Possibly depending on #1122

**Comment by hem-brahmbhatt** [comment]
Resolved by #1122
