### ISSUE TITLE
'Action' component should be Noto Sans 400/regular, not semibold

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#979]
**Describe the bug**
The font-family of the "Pre-fill my details" link on page 1 of the submission wizard is `Noto Sans Semi-bold` but should be regular (400 weight) `Noto Sans`

**To Reproduce**
Go to https://staging--xpub.elifesciences.org/ and create a new submission. Check the text above the First Name input of the form. 

**Expected behavior**
Regular font for the blue link

**Screenshots**
![image](https://user-images.githubusercontent.com/41907215/48000117-7ee33500-e0fc-11e8-8530-add989d34531.png)

**Desktop (please complete the following information):**
Chrome  70.0.3538 on Mac OS Mojave

**Smartphone (please complete the following information):**
Also seen in Chrome on iPhone 6

**Additional context**
This relates to #915 where @jsms90 worked on changes to the regular `button` style, which affected the `link` style. It appears to have been corrected in other instances (e.g. on the login page) but the `link` in the wizard is still semibold

**Comment by jsms90** [comment]
See comment in PR https://github.com/elifesciences/elife-xpub/pull/959#discussion_r230432913 for why this is happening and how to fix it

**Comment by hdrury1** [comment]
We'll need to create our own override for this PubSweet component to ensure it uses Noto Sans, font weight 400 in every instance.
