### ISSUE TITLE
Sign In page not completely responsive

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#980]
**Describe the bug**
The sign-in page centres its content relative to the view height for desktop views. This works fine for normal browser use, however if the user reduces the height of their browser on desktop the content of the page can overflow into the `AppBar`

**To Reproduce**
1. Go to /login without an active session
2. Reduce the height of the browser window to < 400px while keeping its width > 748px

**Expected behavior**
Content shouldn't overflow into the `AppBar`

**Screenshots**
<img width="1232" alt="screenshot 2018-11-05 at 13 13 21" src="https://user-images.githubusercontent.com/22455561/48000611-e64db480-e0fd-11e8-8078-081586b34ecc.png">

**Desktop (please complete the following information):**
 - OSX Chrome

**Additional context**

Probably could do with a `@media(min-height: ... )` on this element but could do with re-looking at how we're vertically aligning content here.

**Comment by diversemix** [comment]
@jyenes ... is this a duplicate? If so we should close it.
