### ISSUE TITLE
Display the name of the uploading/uploaded file

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#988]
**User Story**

As an author I would like to see the name of the manuscript file I have uploaded so that I can double check it is the one I intended and replace if not.

**Product Requirements**

- When a file has been dragged into the dropzone (or added via file manager), the name and file extension should appear below the progress upload indicator.
- If successful, the file name and extension should remain below the 'Success' indicator
- Because it would not make sense to include the filename in one of the component's error states (when user attempts to upload multiple files) and for reasons of limited space on mobile, the filename should NOT be included if the upload is unsuccessful for any reason.

**Screenshots**

**Uploading (desktop)**

<img width="773" alt="screen shot 2018-11-07 at 11 50 15" src="https://user-images.githubusercontent.com/17023702/48130075-53d71d80-e283-11e8-92c6-ebe6156dcb67.png">

**Successful**

<img width="759" alt="screen shot 2018-11-07 at 11 50 42" src="https://user-images.githubusercontent.com/17023702/48130100-63eefd00-e283-11e8-87bf-010a18f02eda.png">

**Uploading (mobile)**

<img width="348" alt="screen shot 2018-11-07 at 11 51 28" src="https://user-images.githubusercontent.com/17023702/48130163-a57fa800-e283-11e8-997d-07bc23faeec3.png">

**Successful**

<img width="350" alt="screen shot 2018-11-07 at 11 53 01" src="https://user-images.githubusercontent.com/17023702/48130182-b3cdc400-e283-11e8-9153-d696554161fd.png">

**Comment by jyenes** [comment]
@hdrury1 and @chugginselifesciences which is the font-size for the file name? 
I've tested with font-size12px

**Comment by chugginselifesciences** [comment]
@jyenes We should use 14px if possible. I think 12px may be a little small. Thanks.
