### ISSUE TITLE
Editors Test data for staging

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#993]
see #545 

We need to ensure that we have representative test data so we can test our integration with the Prolfiles service in staging. This could mean loading of some real data.

/see @giorgiosironi , @diversemix

**Comment by giorgiosironi** [comment]
Services involved:
- `profiles`: uses the ORCID sandbox, data gets imported from there upon login
- `journal-cms`: we could restore a `prod` backup in `staging`, something we have wanted to do for a while with @nlisgo 
- `journal`: no permanent data, sessions are created when logging in

**Comment by damnhipster** [comment]
Depends on #1003

**Comment by diversemix** [comment]
@giorgiosironi / @damnhipster Can we close this now?
